objects/Account_Products__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Product</relationshipLabel>
        <relationshipName>Account_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Contracts__c</fullName>
        <label>Active Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active_Members__c</fullName>
        <label>Active Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product2</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Account Product</relationshipLabel>
        <relationshipName>Account_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Product</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account Products Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity_Product__c.object
<CustomObject>
    <description>Products related to the opportunity - acting as a junction object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Winning Carrier / Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Competitor Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Opportunity Name related to the Product</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Projected_Contracts__c</fullName>
        <label>Expected Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Members__c</fullName>
        <description>Projected number of members on the opportunity product</description>
        <label>Expected Members</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{000}</displayFormat>
        <label>OP #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OppRenewalProdLoadInvocableTest.cls
@isTest
public class OppRenewalProdLoadInvocableTest {
    
    public static testmethod void Test0001(){
        
        /* create Account */
        Account anAccount = TestClassUtiltity.createAccountWithRecType('The Big Account',Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId());
        System.debug('anAccount: ' + anAccount.Id);
        
        /* create Renewal Opportunity */
        Opportunity anOpportunity = TestClassUtiltity.newOpportunity(anAccount.Id,'The Big Opportunity');
        anOpportunity.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        insert anOpportunity;        
        System.debug('anOpportunity: ' + anOpportunity.Id);
        
        /* create Products */
        List<Product2> theProducts = TestClassUtiltity.createProducts();        
        insert theProducts;
        System.debug('theProducts: ' + theProducts);
        
        List<Account_Products__c> theAccountProducts = new List<Account_Products__c>();
        
        Integer Counter = 0;
        
        for(Product2 aProduct : theProducts){           
            
            Account_Products__c anAccountProduct = new Account_Products__c();
            
            System.debug('in Loop > anAccount: '+ anAccount.Id);            
            anAccountProduct.Account__c = anAccount.Id;
            
            System.debug('in Loop > aProduct: '+ anAccount.Id);
            anAccountProduct.Product2__c = aProduct.Id;
            
            anAccountProduct.Active_Contracts__c = 100;
            
            anAccountProduct.Active_Members__c = 1000;
            
            if(Counter == 0){
                Date todaysDate = System.today();
                anAccountProduct.Effective_End_Date__c = todaysDate;
            }
            
            theAccountProducts.add(anAccountProduct);
            
            Counter = Counter + 1;
        }
        insert theAccountProducts;
        System.debug('theAccountProducts: ' + theAccountProducts);
        
        
        Test.startTest();
        
        List<Opportunity> passToMethod = [SELECT Id, Name FROM Opportunity LIMIT 1]; 
        
        OppRenewalProdLoadInvocable.OppRenewalProductsLoad(passToMethod);        
        
        Test.stopTest();
        
        /* There were 3 Account Products created.  1 should not pass the SELECT in the Class.  Only 2 */
        /* should be loaded as part of processing.                                                    */
        List<Opportunity_Product__c> postTestOpportunityProducts = new List<Opportunity_Product__c>();
        postTestOpportunityProducts = [SELECT Id, Projected_Contracts__c, Projected_Members__c FROM Opportunity_Product__c WHERE Opportunity_Name__c = :anOpportunity.Id];        
        System.assertEquals(2, postTestOpportunityProducts.size(),'There should only be 2 Opportunity Products Loaded.');
        System.assert(postTestOpportunityProducts[0].Projected_Contracts__c == 100,'The Active Contracts did not load properly');
        System.assert(postTestOpportunityProducts[0].Projected_Members__c == 1000,'The Active Members did not load properly');
    }
    
}