objects/Account_Team_Non_SF__c.object
<CustomObject>
    <description>Contains the account team members who do not use Salesforce</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>Account Name the Non Salesforce User is related</description>
        <label>Account Name</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Group Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Prospect</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Prospect (Non BlueSTAR)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Group Account (Non BlueSTAR)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Team (Non-Salesforce.com Users)</relationshipLabel>
        <relationshipName>Account_Team_Non_SF</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member_Role__c</fullName>
        <description>Role of the Team member</description>
        <label>Member Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accountant</fullName>
                </value>
                <value>
                    <fullName>Account Executive</fullName>
                </value>
                <value>
                    <fullName>Account Management Support</fullName>
                </value>
                <value>
                    <fullName>Account Manager</fullName>
                </value>
                <value>
                    <fullName>Account Specialist</fullName>
                </value>
                <value>
                    <fullName>Accounts Receivable</fullName>
                </value>
                <value>
                    <fullName>AEP Processor</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health CAC</fullName>
                </value>
                <value>
                    <fullName>Benefit Coder</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Client Consulting Contact</fullName>
                </value>
                <value>
                    <fullName>Clinical Account Consultant</fullName>
                </value>
                <value>
                    <fullName>Cobra</fullName>
                </value>
                <value>
                    <fullName>Dearborn Sales Executive</fullName>
                </value>
                <value>
                    <fullName>Director Account Management</fullName>
                </value>
                <value>
                    <fullName>Director Sales</fullName>
                </value>
                <value>
                    <fullName>DVP Account Management</fullName>
                </value>
                <value>
                    <fullName>DVP Sales</fullName>
                </value>
                <value>
                    <fullName>EHCM Presenter</fullName>
                </value>
                <value>
                    <fullName>EHCM RFP SME</fullName>
                </value>
                <value>
                    <fullName>Electronic Eligibility Specialist</fullName>
                </value>
                <value>
                    <fullName>ENA Strategic Account Executive</fullName>
                </value>
                <value>
                    <fullName>Full Service Unit</fullName>
                </value>
                <value>
                    <fullName>GPD Director</fullName>
                </value>
                <value>
                    <fullName>GPD Group Benefit Specialist</fullName>
                </value>
                <value>
                    <fullName>GPD Marketing Service Representative</fullName>
                </value>
                <value>
                    <fullName>GPD Sales Executive/AE</fullName>
                </value>
                <value>
                    <fullName>Group Benefit Specialist</fullName>
                </value>
                <value>
                    <fullName>Implementation Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Team member of Account that doesnt have access to salesforce</description>
        <label>Team Member Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Contact</value>
            </filterItems>
            <filterItems>
                <field>Contact.In_Active__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Team Non SF</relationshipLabel>
        <relationshipName>Account_Team_Non_SF</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Team (Non-Salesforce.com User)</label>
    <nameField>
        <displayFormat>AT-{000}</displayFormat>
        <label>AT #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Teams (Non-Salesforce.com User)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Member_360Views__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>team member roles which needs to be shown on the 360 views of account and opportunity</description>
    <fields>
        <fullName>Account_Record_Types__c</fullName>
        <description>Enter account record type developer names comma Separated like Group_Account,Group_Prospect_Account</description>
        <inlineHelpText>Enter account record type developer names comma Separated like Group_Account,Group_Prospect_Account</inlineHelpText>
        <label>Account Record Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team_Role_Name__c</fullName>
        <label>Team Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Team_Member_360Views</label>
</CustomObject>

classes/LGNA_KeyContactController_Lex.cls
/********************************************************************************************
* Apex Class Name     : KeyContactController
* Version             : 1.0
* Function            : This is a Controller class for Key Contacts Lightning Component. 
* Created Date        : 08/30/2017
* Modification Log    :
*-------------------------------------------------------------------------------------------
********************************************************************************************/
public class LGNA_KeyContactController_Lex{
    public List<AccountContactRole> accountContactRoleList {get; set;}
    public list<TeamMemberWrapper> teamMembersList{get;set;}
    public List<AccountTeamMember> accountTeamMemberList {get; set;}
    public List<Account_Team_Non_SF__c> accountTeamMemberNonSFList {get; set;}
    public List<AccountContactRole> primaryContactList{get; set;}
    public Id accountId {get; set;}
    
    // Standard cController
    public LGNA_KeyContactController_Lex(ApexPages.standardController stdController) {
        try{
            accountTeamMemberList = new list<AccountTeamMember>();
            accountTeamMemberNonSFList = new list<Account_Team_Non_SF__c>();
            accountId = ApexPages.currentPage().getParameters().get('id');
             system.debug('accid'+accountId);
            accountContactRoleList = new List<AccountContactRole>();
            
            accountContactRoleList = [SELECT Contact.Email, Contact.Phone, Contact.Name, Role, Contact.PhotoUrl, AccountId FROM AccountContactRole WHERE AccountId =:accountId];
            primaryContactList = [SELECT Contact.Email, Contact.Phone, Contact.Name, Role, Contact.PhotoUrl, AccountId FROM AccountContactRole WHERE AccountId =:accountId and IsPrimary=true];
            teamMembersList = new list<TeamMemberWrapper>();
            
            list<AccountTeamMember> tempList1 = [SELECT TeamMemberRole, UserId, User.Name FROM AccountTeamMember WHERE AccountId=:accountId ];
            list<Account_Team_Non_SF__c> tempList2 = [SELECT Member_Role__c, Account_Name__c, Team_Member_Name__c, Team_Member_Name__r.Name FROM Account_Team_Non_SF__c WHERE Account_Name__c =:accountId];
           // system.debug('team role'+tempList1);
            for(Team_Member_360Views__c atm : [select Team_Role_Name__c,Sort_Order__c from Team_Member_360Views__c 
                                                where Account_Record_Types__c = 'Group_Account' 
                                                order By Sort_Order__c]){
                for(AccountTeamMember temp : tempList1){
                    //system.debug('team role'+atm.Team_Role_Name__c);
                    //  system.debug('team'+temp.TeamMemberRole);
                    if(atm.Team_Role_Name__c == temp.TeamMemberRole){
                        accountTeamMemberList.add(temp);
                        teamMembersList.add(new TeamMemberWrapper(atm.Team_Role_Name__c,temp.User.Name,temp.UserId));
                    }
              }
              // system.debug('team role'+tempList2);
                for(Account_Team_Non_SF__c temp : tempList2){
                    //system.debug('team role'+atm.Team_Role_Name__c);
                   // system.debug('team'+temp.Member_Role__c);
                    if(atm.Team_Role_Name__c == temp.Member_Role__c){
                        accountTeamMemberNonSFList.add(temp);
                        teamMembersList.add(new TeamMemberWrapper(atm.Team_Role_Name__c,temp.Team_Member_Name__r.Name,temp.Team_Member_Name__c));
                    }
                }
            }
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
            ApexPages.addMessage(myMsg);
            System.debug( 'Exception : ' +e.getMessage() ); 
        }
    
    }
    
    public class TeamMemberWrapper{
        public string teamRoleName{get;set;}
        public string teamMemberName{get;set;}
        public string teamMemberId{get;set;}
        public TeamMemberWrapper(string teamRole,String memberName,String memberId){
            teamRoleName        = teamRole;
            teamMemberName      = memberName;
            teamMemberId        = memberId;
        }
    }
    
  }