objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Audits</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Billing Explained</fullName>
                </value>
                <value>
                    <fullName>Case Management and Wellness</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>CMS Demand Letters</fullName>
                </value>
                <value>
                    <fullName>Contract Administration</fullName>
                </value>
                <value>
                    <fullName>General Inquiry</fullName>
                </value>
                <value>
                    <fullName>Group Exception</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Real Time Benefits</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>Service Center</fullName>
                </value>
                <value>
                    <fullName>Subrogation</fullName>
                </value>
                <value>
                    <fullName>Vendor Type</fullName>
                </value>
                <value>
                    <fullName>Care Management and Wellness</fullName>
                    <isActive>false</isActive>
                    <label>Care Management and Wellness</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party Disease Management</fullName>
                </value>
                <value>
                    <fullName>ABS/Matrix Updates</fullName>
                </value>
                <value>
                    <fullName>ACA</fullName>
                </value>
                <value>
                    <fullName>Accums Inquiry</fullName>
                </value>
                <value>
                    <fullName>Additional Information Request</fullName>
                </value>
                <value>
                    <fullName>Add Member</fullName>
                </value>
                <value>
                    <fullName>Adjustment Request</fullName>
                </value>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Alt Net Related Issue</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>BAE Portal</fullName>
                </value>
                <value>
                    <fullName>BAM PortaL</fullName>
                </value>
                <value>
                    <fullName>Benefit Booklet</fullName>
                </value>
                <value>
                    <fullName>Benefit Inquiry</fullName>
                </value>
                <value>
                    <fullName>Benefit Interpretation</fullName>
                </value>
                <value>
                    <fullName>Benefit Overview/Clarification</fullName>
                </value>
                <value>
                    <fullName>Benefits Exception</fullName>
                </value>
                <value>
                    <fullName>Benefit Value Advisor</fullName>
                </value>
                <value>
                    <fullName>Blue Care Connection/Blue Elite</fullName>
                </value>
                <value>
                    <fullName>Call Routing</fullName>
                </value>
                <value>
                    <fullName>Cancel Member</fullName>
                </value>
                <value>
                    <fullName>Case Management</fullName>
                </value>
                <value>
                    <fullName>Claim Denial</fullName>
                </value>
                <value>
                    <fullName>Claim Detail/Status Request</fullName>
                </value>
                <value>
                    <fullName>Claim Detail Request</fullName>
                </value>
                <value>
                    <fullName>Claim Exception</fullName>
                </value>
                <value>
                    <fullName>Claim Impact Reports</fullName>
                </value>
                <value>
                    <fullName>Claim in Process</fullName>
                </value>
                <value>
                    <fullName>Claim Not on File</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProspectingAppActivitiesListCtrlTest.cls
@isTest
private class ProspectingAppActivitiesListCtrlTest {
    @testSetup 
    static void setupData() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
        Note testNote = new Note();
        testNote.Body = 'Test Body';
        testNote.Title = 'ProspectingAppNewNote';
        testNote.ParentId = testAccount.Id;
        insert testNote;
        
        Task testTask = new Task();
        
        /* had to updated Field Security to allow System Admin to View in order to access */
        /* the Category__c and Sub_Category__c custom Activity Fields.  Without the       */
        /* change the Error 'INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, bad value for       */
        /* restricted picklist field' was encountered.  Also had to update the  Field     */
        /* dependency for Sub_Category__c to allow for Category = "Other" to map to       */
        /* Sub Category = "Other".                                                        */
        
        testTask.Category__c = 'Other';
        testTask.Sub_Category__c = 'Other';
        
        testTask.Type = 'Account';       
        testTask.Priority = 'High';
        testTask.Status = 'Completed';
        testTask.Subject = 'ProspectingAppNewTask';
        testTask.OwnerId = UserInfo.getUserId();
        testTask.WhatId = testAccount.Id;
        insert testTask;
        
    }
    
    static testMethod void validateQueryAccountNotes() {
        Account testAccount = [SELECT Id FROM Account WHERE Name='Test Account'];
        
        List<Note> notes = ProspectingAppActivitiesListController.queryAccountNotes(testAccount);
        System.assert(notes.size()==1);
    }
    
    
    static testMethod void validateQueryAccounTasks() {
        Account testAccount = [SELECT Id FROM Account WHERE Name='Test Account'];
        
        List<Task> tasks = ProspectingAppActivitiesListController.queryAccountTasks(testAccount);
        System.assert(tasks.size()==1);
    }
    
}