objects/Benefit_Agreement__c.object
<CustomObject>
    <description>Benefit Agreement information offered to the employees for the Group Account will be stored using this object</description>
    <fields>
        <fullName>Benefit_Agreement_Number__c</fullName>
        <description>This field is used to capture the number of the Benefit Agreement as listed in BlueStar</description>
        <label>Benefit Agreement Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Account__c</fullName>
        <description>This field is used to capture the Group Account associated to the Benefit Agreement</description>
        <label>Group Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Agreements</relationshipLabel>
        <relationshipName>Benefit_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Benefit Agreement</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Benefit Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To retrieve days to submit for each division for calcuating Submit_Date__c on opportunity</description>
    <label>SGR Days to Submit</label>
</CustomObject>

objects/SGR_Opportunity_Benefit_Agreement__c.object
<CustomObject>
    <description>This object is connected to Opportunity object using a look up field (Opportunity).</description>
    <fields>
        <fullName>Benefit_Agreement_Number__c</fullName>
        <label>Benefit Agreement Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Benefit Agreements</relationshipLabel>
        <relationshipName>Opportunity_Benefit_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Benefit Agreement</label>
    <nameField>
        <label>Opportunity Benefit Agreement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Benefit Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SGR_RefreshController.cls
public class SGR_RefreshController {
    
    Public  list<String> initiaterefresh(List<SGR_Opportunity_Benefit_Agreement__c> obfaList)
        
    {
        List<String> Successmsg = new List<String>();
        /*set<ID> tempid= new set<ID>();
        tempid=obfid;
       List<String > s = new list<String>();
       String oppId;
       String AccId;
       //List<SGR_Opportunity_Benefit_Agreement__c> oppid= new List<SGR_Opportunity_Benefit_Agreement__c>();
       //List<SGR_Opportunity_Benefit_Agreement__c>  Accid= new List<SGR_Opportunity_Benefit_Agreement__c>();
       oppId = [select Opportunity__c from SGR_Opportunity_Benefit_Agreement__c where ID IN :tempid Limit 1].Opportunity__c;
        //oppid= [select Opportunity__r.id from SGR_Opportunity_Benefit_Agreement__c where ID IN :tempid];
        //Accid=[select Opportunity__r.AccountID  from SGR_Opportunity_Benefit_Agreement__c where ID IN :tempid]; 
         AccId= [select Opportunity__r.AccountID  from SGR_Opportunity_Benefit_Agreement__c where ID IN :tempid Limit 1].Opportunity__r.AccountID;
    List<SGR_Opportunity_Benefit_Agreement__c> oppbfa = [Select id,name from SGR_Opportunity_Benefit_Agreement__c  where ID =:oppId];
     List<Benefit_Agreement__c> accbfa = [select id,name from Benefit_Agreement__c where ID =:AccId];
       for(Benefit_Agreement__c bps: accbfa)
       {
            if(bps.Benefit_Agreement_Number__c==bps.Group_Account__c)
               {
                   
                   
               }
               else{
                   
                   
               }
           
           }
           
           
      */
       
     return Successmsg;   

    }

    
}