objects/Business_Rule_Validation_Log__c.object
<CustomObject>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpportunityId</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>BusinessRuleValidationLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SGR_caseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Business Rule Validation Logs</relationshipLabel>
        <relationshipName>Business_Rule_Validation_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Rule Validation Log</label>
    <nameField>
        <displayFormat>BRV-{0000}</displayFormat>
        <label>Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Rule Validation Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assigned_UW__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned UW</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SGR_Workflow_Activity__c</fullName>
        <label>Workflow Activity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
                <value>
                    <fullName>UW Review - Validation Errors</fullName>
                </value>
                <value>
                    <fullName>Actuarial Gate</fullName>
                </value>
                <value>
                    <fullName>Awaiting BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>Plan Change in Progress</fullName>
                </value>
                <value>
                    <fullName>Pend in Progress</fullName>
                </value>
                <value>
                    <fullName>Not Eligible to be Transferred</fullName>
                </value>
                <value>
                    <fullName>UW Review</fullName>
                </value>
                <value>
                    <fullName>IT Review - Rating Failed</fullName>
                </value>
                <value>
                    <fullName>Underwriting Review</fullName>
                </value>
                <value>
                    <fullName>Actuarial Release</fullName>
                </value>
                <value>
                    <fullName>Ready for Distribution</fullName>
                </value>
                <value>
                    <fullName>Group Verifier Review - BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>BlueStar Transfer Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SGR_BRVFalloutCaseForUW_Impl_Test.cls
@isTest
public  class SGR_BRVFalloutCaseForUW_Impl_Test{
	
 	@isTest static void testCreateCases(){
        try{
        List<Opportunity> opp = new List<Opportunity>();
        
        Opportunity opp1 = new Opportunity();
        
       opp1.StageName='Triggered';
        opp1.SGR_Workflow_Activity__c='UW Review - Validation Errors';
       opp1.CloseDate=date.today();
       opp1.Assigned_UW__c = Userinfo.getUserId();   
        opp1.Name='Test VSR 9/9/2020 Analytical';
        opp1.recordTypeId=SGR_BRVFalloutCaseForUW_Impl_Test.getOpptyRecordTypeIds('Opportunity','SGR Analytical Opportunity');
        //opp1.Assigned_UW__c='0054D000001FFfi';
        opp.add(opp1);
        insert opp;
        system.debug(opp);
       Business_Rule_Validation_Log__c br = new Business_Rule_Validation_Log__c();
        br.OpportunityId__c=opp1.id;
        br.Status__c='Failed';
        
        //br.SGR_caseId__c='';
        insert br;
            
            case c = new case();
            c.Opportunity_Name__c=opp1.id;
            c.OwnerId=opp1.Assigned_UW__c;
            insert c;
       SGR_BRValidationFalloutCaseForUW_Impl sr = new SGR_BRValidationFalloutCaseForUW_Impl();
        
       
           sr.createCases(opp);
           //sr.GetCaseDefaultsByOpportunity(opp1);
        }
        catch(Exception e){}
        
}

public Static String getOpptyRecordTypeIds(String ObjectName,String recTypeName){
         Map<String, Schema.SObjectType> mapSchemaobject = Schema.getGlobalDescribe() ;
        Schema.SObjectType SchemaObject = mapSchemaobject.get(ObjectName) ;
        Schema.DescribeSObjectResult getDescribeSchema = SchemaObject.getDescribe() ;
        Map<String,Schema.RecordTypeInfo> RecordTypeInfo = getDescribeSchema.getRecordTypeInfosByName();
        String recordTypeId = RecordTypeInfo.get(recTypeName).getRecordTypeId();
        System.debug(':::RECTYPE:::'+recordTypeId);
        return recordTypeId;
       
    }

}