objects/Case__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Maintanance Related picklist values</description>
    <label>Maintanance Type</label>
</CustomObject>

objects/GEMS_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Attachment__c</fullName>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>GEMS  Attachments</relationshipLabel>
        <relationshipName>GEMS_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABS</fullName>
                </value>
                <value>
                    <fullName>ACA CALCULATORS</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT CHANGE REQUEST FORM</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT STRUCTURE</fullName>
                </value>
                <value>
                    <fullName>ACH/WIRE FORM</fullName>
                </value>
                <value>
                    <fullName>ADDENDUM TO BPA FOR AFFILIATES</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRATIVE SERVICE AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO BENEFIT PROG APP (BPA)</fullName>
                </value>
                <value>
                    <fullName>ASO MANDATE CHECKLIST</fullName>
                </value>
                <value>
                    <fullName>BENEFIT ADHOC MEETING MINUTES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT BOOKLETS / CERTIFICATES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT EDIT TOOL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT MATRIX</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROG DESCRIPTION-DENTAL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROGRAM DESCRIPTION-BPD</fullName>
                </value>
                <value>
                    <fullName>BENEFIT WALLET DISCOVERY FORM</fullName>
                </value>
                <value>
                    <fullName>BINDER CHECK</fullName>
                </value>
                <value>
                    <fullName>BPA - ASO SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - ASO UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - DENTAL SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - DENTAL UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HCA SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HCA UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HEALTH SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HEALTH UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>BROKER TRANS/AOR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <formula>IF( ISBLANK(Attachment__c) , HYPERLINK(AttachmentUrl__c,&quot;View&quot;) , HYPERLINK (&quot;/servlet/servlet.FileDownload?file=&quot;+Attachment__c,&quot;View&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>View</label>
        <type>Text</type>
    </fields>
    <label>GEMS Attachments</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS  Attachments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GEMS_ReviewDocuments.cls
public with sharing class GEMS_ReviewDocuments 
{
    public Case cases{get;set;}
    public Case caseRecord{get;set;}
    public List<GEMS_Attachment__c> documentsList{get;set;}
    
    public GEMS_ReviewDocuments(ApexPages.StandardController controller) 
    {
        try {
        cases = (case)controller.getRecord();
        caseRecord = [Select ID, GEMS_Return_Check__c, GEMS_ReviewDocuments__c, GEMS_Approve__c,GEMS_Return__c,GEMS_Routed_In_Error__c, Status, GEMS_Account_Submission_Info__c,RecordType.name from Case where ID =: cases.ID];
        documentsList = [Select ID, name, Attachment__c, Case__c, Description__c, Type__c, View__c, CreatedBy.name, createdDate from GEMS_Attachment__c where Case__c =: caserecord.GEMS_Account_Submission_Info__c ];
        }
        catch(Exception ex){
        System.debug('======Exception==========='+ex.getMessage());
        }
    }

}