objects/Case__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Maintanance Related picklist values</description>
    <label>Maintanance Type</label>
</CustomObject>

objects/GEMS_Characteristic__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Characteristics</relationshipLabel>
        <relationshipName>GEMS_Characteristics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsUpdated</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS Characteristic</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Characteristic No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GEMS Characteristics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GEMS_Characteristic_Value__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>GEMS Characteristic Values</relationshipLabel>
        <relationshipName>GEMS_Characteristic_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Characteristic__c</fullName>
        <label>Characteristic</label>
        <referenceTo>GEMS_Characteristic__c</referenceTo>
        <relationshipLabel>GEMS Characteristic Values</relationshipLabel>
        <relationshipName>GEMS_Characteristic_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUpdated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsUpdated</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS Characteristic Value</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Characteristic Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GEMS_CharValTriggerHandler.cls
/**************************************************************************************
//Apex Class Name     : GEMS_CharacteristicValueTriggerHandler
//Version             : 1.0
//Modification Log    :
//Developer                   Date                   Description
//----------------------------------------------------------------------------------                 
//5/10/2018   Gokul Bharati   SFDC-4912 GEMS: BlueSTAR - Transfer Updated Characteristic Value Descriptions from GEMS to B* 
*************************************************************************************/ 
public class GEMS_CharValTriggerHandler{

public static Boolean recursiveCheck = true;

/**************************************************************************************
Method Name : AfterInsert
Description : Set the Char isUpdated flag to true after Creation of New Char Value for Renewal and Off Cycle Cases.
Parameters  : AfterInsert(Map<Id,sObject> TriggernewMap,Map<Id,sObject> TriggerOldMap)
ReturnType  : Void
**************************************************************************************/
    public static void AfterInsert(Map<Id,sObject> TriggernewMap,Map<Id,sObject> TriggerOldMap){
    
    List<GEMS_Characteristic_Value__c> charValues = (List<GEMS_Characteristic_Value__c>)TriggernewMap.values();
    set<Id> chaValueIds = new set<Id>();
    for(GEMS_Characteristic_Value__c charValue : charValues){
            chaValueIds.add(charValue.Characteristic__c);
    }
        
    List<GEMS_Characteristic__c> charsToUpdate = new list<GEMS_Characteristic__c>();        
    charsToUpdate = [SELECT Id, Case__c, IsUpdated__c FROM GEMS_Characteristic__c WHERE Id IN : chaValueIds AND IsUpdated__c = false];
    
    for(GEMS_Characteristic__c charToUpdate : charsToUpdate){
        charToUpdate.IsUpdated__c = true;
    }
    
    if(charsToUpdate != null)
       update charsToUpdate;
    
    }
    
/**************************************************************************************
Method Name : BeforeUpdate
Description : Set the Char isUpdated flag to true after updating Char Value Description for Renewal and Off Cycle Cases.
Parameters  : BeforeUpdate(List<sObject> TriggerNew,List<sObject> TriggerOld,Map<Id,sObject> TriggernewMap,Map<Id,sObject> TriggerOldMap){
ReturnType  : Void
**************************************************************************************/    
    public static void BeforeUpdate(List<sObject> TriggerNew,List<sObject> TriggerOld,Map<Id,sObject> TriggernewMap,Map<Id,sObject> TriggerOldMap){
        
    set<Id> chaValueIds = new set<Id>();
        
        for(GEMS_Characteristic_Value__c cha:(List<GEMS_Characteristic_Value__c>)TriggernewMap.values()){
        
            GEMS_Characteristic_Value__c oldRec = (GEMS_Characteristic_Value__c)TriggerOldMap.get(cha.Id);
            GEMS_Characteristic_Value__c newRec = (GEMS_Characteristic_Value__c)TriggernewMap.get(cha.Id);
            
            if(!String.isBlank(cha.Name) && oldRec.Name != newRec.Name && newRec.isNew__c == false && oldRec.IsUpdated__c == false){  
              cha.IsUpdated__c = true;
              chaValueIds.add(cha.Characteristic__c);
            }
        }
                        
        List<GEMS_Characteristic__c> charsToUpdate = new list<GEMS_Characteristic__c>();                      
        charsToUpdate = [SELECT Id, Case__c, IsUpdated__c FROM GEMS_Characteristic__c WHERE Id IN : chaValueIds AND IsUpdated__c = false AND isNew__c = false];       
        for(GEMS_Characteristic__c charToUpdate : charsToUpdate){
            charToUpdate.IsUpdated__c = true;
        }
        
        if(charsToUpdate != null)
           update charsToUpdate;
    
    }
}