objects/Case__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Maintanance Related picklist values</description>
    <label>Maintanance Type</label>
</CustomObject>

objects/GEMS_BA_Category_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GEMS BA Category Assignments</relationshipLabel>
        <relationshipName>GEMS_BA_Category_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>BA Category Assignments</relationshipLabel>
        <relationshipName>BA_Category_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS BA Category Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS BA Category Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Benefit_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Agreements</relationshipLabel>
        <relationshipName>GEMS_Benefit_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS Benefit Agreement</label>
    <nameField>
        <label>BA No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Benefit Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Cat_Char_Value_Association__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GEMS_Category_Characteristic_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>GEMS_Category_Characteristic_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS Cat Char Value Association</label>
    <nameField>
        <label>Category Characteristic Association</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Cat Char Value Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Category__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>GEMS_Categories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Description__c</fullName>
        <label>Category Description</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Usage_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Usage - Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Usage_Reporting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Usage - Reporting</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS Category</label>
    <nameField>
        <label>Category No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Category_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Category_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Group Section - Category Associations</relationshipLabel>
        <relationshipName>Category_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS GroupSection Category Association</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS GroupSection Category Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Characteristic__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GEMS_Characteristics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Characteristics</relationshipLabel>
        <relationshipName>GEMS_Characteristics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Usage__c</fullName>
        <label>Usage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
                <value>
                    <fullName>Mailing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Billing/Product</fullName>
                </value>
                <value>
                    <fullName>Billing/Reporting</fullName>
                </value>
                <value>
                    <fullName>Billing/Mailing</fullName>
                </value>
                <value>
                    <fullName>Billing/Product/Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GEMS Characteristic</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Characteristic No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GEMS Characteristics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GEMS_Characteristic_Value__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>GEMS Characteristic Values</relationshipLabel>
        <relationshipName>GEMS_Characteristic_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS Characteristic Value</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Characteristic Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Group_Section__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>GEMS Group Sections</relationshipLabel>
        <relationshipName>GEMS_Group_Sections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Group Sections</relationshipLabel>
        <relationshipName>Group_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_No__c</fullName>
        <label>Group No.</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsNew__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsNew</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS Group Section</label>
    <nameField>
        <label>Group Section No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Group Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Captures product category</description>
        <inlineHelpText>required field for plans to flow correctly on BA to BlueSTAR</inlineHelpText>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BCC</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Disease Management</fullName>
                </value>
                <value>
                    <fullName>EPO</fullName>
                </value>
                <value>
                    <fullName>Group Govt</fullName>
                </value>
                <value>
                    <fullName>HCA</fullName>
                </value>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>IHI</fullName>
                </value>
                <value>
                    <fullName>Nurseline</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
                <value>
                    <fullName>Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Dearborn</fullName>
                </value>
                <value>
                    <fullName>Health Advocacy Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GEMSBACatAssignController_TEST.cls
/**************************************************************************************
  Apex Class Name     : GEMSBACatAssignController_TEST
  Version             : 1.0
  Function            : This class serves as Unit Test Class for GEMSBACatAssignController.
  Modification Log    :
* Developer           :    Date                   Description
* ----------------------------------------------------------------------------                 
* Siva Thimmannagari        07/19/2016                Original Version
*************************************************************************************/
@isTest 
public class GEMSBACatAssignController_TEST{
    public static testMethod void GEMSBACatAssignController_TEST1()
    {
        Profile profileRec = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User testUser = GEMS_UtilityClassTest.CreateUserRecord(profileRec.Id, 'test1@user11.com', 'testUser1', 'test1@user.com');
        insert testuser;

        Account acc = GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        System.assertEquals('BenefitAgreementControllerTest',acc.Name);

        Product2 product2Rec=GEMS_UtilityClassTest.insertionProduct();
        product2Rec.Product_Category__c='EPO;PPO;Dental';
        insert product2Rec;

        Opportunity opp = GEMS_UtilityClassTest.insertionOpp(acc.id);
        insert opp;

        Case subRec= GEMS_UtilityClassTest.insertionCase('GEMS Account Submission');
        subRec.status = 'In Progress';
        subRec.Funding_Type_Multiselect__c = 'ACAP';
        subRec.GEMS_AEP_Account__c= true;
        insert subRec;

        Id subCaserecordTypeId= Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS Account Submission').getRecordTypeId();
        Case subCaseRec = [Select id, recordtype.id from case where recordtypeid=:subCaserecordTypeId];
        System.assertEquals(subCaserecordTypeId,subCaseRec.recordtype.id);

        CaseTeamMember caseTeamAccSpecMem = GEMS_UtilityClassTest.insertionCaseTeam(subCaseRec.Id,'Account Specialist');
        insert caseTeamAccSpecMem;
        System.assertEquals(subCaseRec.Id,caseTeamAccSpecMem.ParentId );

        Case caseObj= GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        caseObj.GEMS_Account_Submission_Info__c  = subCaseRec.Id;
        caseObj.accountId = acc.Id;
        caseObj.Status = 'Design In Progress';
        insert caseObj;

        Id accStrRecordTypeId= Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS Account Structure').getRecordTypeId();
        Case strCaseRec=[SELECT Id, GEMS_Account_Submission_Info__c, status, RecordTypeId from Case 
        where RecordTypeId=:accStrRecordTypeId and GEMS_Account_Submission_Info__c =: subCaseRec.Id ];
        System.assertEquals('Design In Progress',strCaseRec.status);

        List<GEMS_Category__c> catList = new List<GEMS_Category__c>();
        GEMS_Category__c gemscat1 = GEMS_UtilityClassTest.insertiongemscat1(acc.ID,caseObj.Id);
        gemscat1.Usage_Billing__c = true;
        gemscat1.Usage_Reporting__c = true;
      
        GEMS_Category__c gemscat2 = GEMS_UtilityClassTest.insertiongemscat2(acc.ID,caseObj.Id);
        gemscat2.Usage_Billing__c = true;
        catList.add(gemscat1);
        catList.add(gemscat2);
        insert catList;
        System.assertEquals('1234',catList[0].Name);
        gemscat1.Category_Description__c ='Changed';
        gemscat1.IsNew__c= False;
        Update gemscat1;
        List<GEMS_Group_Section__c> groupSectionList = new List<GEMS_Group_Section__c>();
        GEMS_Group_Section__c gemsGroupObj = GEMS_UtilityClassTest.insertionGroup(acc.ID,caseObj.Id);
        insert gemsGroupObj;
        groupSectionList.add(gemsGroupObj);
        GEMS_Group_Section__c  grpquery =[select id,Group_No__c from GEMS_Group_Section__c where account__c=:acc.ID and case__c= :caseObj.Id];
        System.assertEquals('TeSt02',grpquery.Group_No__c);

        GEMS_Category_Assignment__c gemsCatAsgmnt = GEMS_UtilityClassTest.insertionCategoryAssign(acc.ID,caseObj.Id,catList[0].Id,gemsGroupObj.Id);
        insert gemsCatAsgmnt;

        GEMS_Characteristic__c gemsCaract = GEMS_UtilityClassTest.insertionCharacteristic(acc.ID,caseObj.Id);
        insert gemsCaract ;
        System.assertEquals('ABS',gemsCaract.Usage__c );
        List<GEMS_Benefit_Agreement__c> baList = new List<GEMS_Benefit_Agreement__c>();
        GEMS_Benefit_Agreement__c gemsbenefit = GEMS_UtilityClassTest.insertionBenefit(acc.ID,caseObj.Id,product2Rec.id);
        baList.add(gemsbenefit);
        insert baList;
        System.assertEquals('1234',gemsbenefit.Name);
        GEMS_BA_Category_Assignment__c catass = GEMS_UtilityClassTest.insertionBACategory(acc.ID,caseObj.Id,baList[0].id,catList[0].Id);
        insert catass;
/*
        GEMS_Characteristic_Value__c charval = GEMS_UtilityClassTest.insertionCharacValue(gemsCaract.id,caseObj.Id);
        insert charval;
        GEMS_Cat_Char_Value_Association__c charass = GEMS_UtilityClassTest.insertionAssociate(caseObj.Id,acc.ID,charval.id,catList[0].Id);
        insert charass ;
        */
        PageReference pageRef = Page.GEMSBACatAssign;
        String strlist = baList[0].id;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('recs',strlist);
        ApexPages.currentPage().getParameters().put('RN','1234');
        ApexPages.currentPage().getParameters().put('RecordCan',CaseObj.id);
        ApexPages.currentPage().getParameters().put('dDate','07/05/16');
        Apexpages.StandardSetController stdControllerr = new Apexpages.StandardSetController(groupSectionList);
        GEMSBACatAssignController gm = new GEMSBACatAssignController (stdControllerr);
        List<Id> idlist=null;
        list < Id > newList ;
        list<list < Id >> newListList ;
        List<GEMSBACatAssignController.CatWrapper> wrapList = new List<GEMSBACatAssignController.CatWrapper>();
        GEMSBACatAssignController.CatWrapper catwrap = new GEMSBACatAssignController.CatWrapper();
        
        gm.getRecords();
        gm.getSize();
        catwrap.IsAssigned = true;
        wrapList.add(catwrap);
        gm.cats = wrapList;
       // gm.selectedCat = catList;
      //  gm.getTheUpdatedMembersCount();
        gm.gotoCase();
        gm.numberOfRowToRemove=1;
        gm.numberOfNewRowToRemove = 1;
      //  gm.rowCount = '2';
       // String CancelDate = '10/03/2016' ;
        gm.cancelDate = date.parse('12/27/2009'); 
        gm.recordToDelete = caseObj.ID;
        gm.NewrecordToDelete = caseObj.ID;
       // gm.updateRecord();
        gm.removeNewRow();
        gm.removeRow();
        
        gm.refresh();
        gm.offset = 0;
        gm.limitSize = 1;
        gm.pageNumber = 2;
        gm.hasPrevious = true;
        gm.hasNext = true;
        gm.first();
        gm.last();
        gm.previous();
        gm.next();
        gm.goToCharacteristics();
        gm.addCat();
        gm.addAllCats();
        GEMS_Category__c newCat1 = GEMS_UtilityClassTest.insertiongemscat3(acc.ID,caseObj.Id);
        
        gm.newCats.add(newCat1) ;
        
        gm.saveCat();
       // gm.assignCat();
        gm.gotoCreateAccountStructure();
        gm.backtoBA();
        gm.cancelRecord();

        Map < Id, GEMS_Category__c > idcatmap = new Map < Id, GEMS_Category__c >();
        idcatmap.put(catList[0].id,catList[0]);
        idcatmap.put(catList[1].id,catList[1]);
       // gm.mapOfIdAndCat = idcatmap;
        ApexPages.currentPage().getParameters().put('RecordCan',catList[0].id);
        gm.cancelRecord();
      //  gm.mapOfIdAndCat = idcatmap;
        gm.recordToDelete = catList[0].id;
       // gm.selectedIda='ABS';
      //  gm.recordToCancel=caseObj.id;

        
        }
      
  /*public static testMethod void GEMSBACatAssignController_TEST2()
    {
        
        Profile profileRec = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User testUser = GEMS_UtilityClassTest.CreateUserRecord(profileRec.Id, 'test1@user11.com', 'testUser1', 'test1@user.com');
        insert testuser;
        Account acc = GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        System.assertEquals('BenefitAgreementControllerTest',acc.Name);

        case caseObj = GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        caseObj .GEMS_Submission_Type__c = 'Renewal';
        caseObj .GEMS_Case_Effective_Date__c = date.today();
        caseObj.accountid= acc.id;
        caseObj.Status= 'Design In Progress';
        insert caseObj;

        GEMS_Category__c gemscat1 = GEMS_UtilityClassTest.insertionGemsCatg(acc.ID,caseObj.Id);
        insert gemscat1;
        Product2 product2Rec=GEMS_UtilityClassTest.insertionProduct();
        product2Rec.Product_Category__c='EPO;PPO;Dental';
        insert product2Rec;
        List<GEMS_Group_Section__c> groupSectionList1 = new List<GEMS_Group_Section__c>();
        GEMS_Group_Section__c gemsGroupObj1 = GEMS_UtilityClassTest.insertionGroup(acc.ID,caseObj.Id);
        insert gemsGroupObj1;
        groupSectionList1.add(gemsGroupObj1);
        GEMS_Group_Section__c  grpquery =[select id,Group_No__c from GEMS_Group_Section__c where account__c=:acc.ID and case__c= :caseObj.Id];
        System.assertEquals('TeSt02',grpquery.Group_No__c);
        List<GEMS_Benefit_Agreement__c> baList = new List<GEMS_Benefit_Agreement__c>();
        GEMS_Benefit_Agreement__c gemsbenefit = GEMS_UtilityClassTest.insertionBenefit(acc.ID,caseObj.Id,product2Rec.id);
        GEMS_Benefit_Agreement__c gemsbenefit1 = GEMS_UtilityClassTest.insertionBenefit(acc.ID,caseObj.Id,product2Rec.id);
        baList.add(gemsbenefit);
        baList.add(gemsbenefit1);
        insert baList;

        GEMS_Category_Assignment__c gemsCatAsgmnt = GEMS_UtilityClassTest.insertionCategoryAssign(acc.ID,caseObj.Id,gemsCat1.Id,gemsGroupObj1.Id);
        insert gemsCatAsgmnt;

        PageReference pageRef = Page.GEMSBACatAssign;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('recs',gemsGroupObj1.Id);
        Apexpages.StandardSetController stdControllerr = new Apexpages.StandardSetController(groupSectionList1);
        GEMSBACatAssignController gm = new GEMSBACatAssignController (stdControllerr);

        gm.getTheUpdatedMembersCount();
        gm.gotoCase();
        gm.numberOfRowToRemove=2;
        gm.rowCount = '2';
        gm.recordToDelete= caseObj.ID;
        gm.numberOfNewRowToRemove  = 1;
        gm.recordToDelete  = caseObj.ID; 
        gm.removeNewRow();
        gm.removeRow(); 
        gm.assignCat();
        gm.gotoCreateAccountStructure();

        gm.backtoBA();
        gm.saveCat();
    }

    public static testMethod void GEMSBACatAssignController_TEST3()
    {

        Profile profileRec = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User testUser = GEMS_UtilityClassTest.CreateUserRecord(profileRec.Id, 'test1@user11.com', 'testUser1', 'test1@user.com');
        insert testuser;

        Account acc = GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        System.assertEquals('BenefitAgreementControllerTest',acc.Name);

        case caseObj = GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        caseObj .GEMS_Submission_Type__c = 'Renewal';
        caseObj.accountid= acc.id;
        insert caseObj;
        Product2 product2Rec=GEMS_UtilityClassTest.insertionProduct();
        product2Rec.Product_Category__c='EPO;PPO;Dental';
        insert product2Rec;

        List<GEMS_Group_Section__c> groupSectionList = new List<GEMS_Group_Section__c>();
        GEMS_Group_Section__c gemsGroupObj = GEMS_UtilityClassTest.insertionGroup(acc.ID,caseObj.Id);
        insert gemsGroupObj;
        groupSectionList.add(gemsGroupObj);
        GEMS_Group_Section__c  grpquery =[select id,Group_No__c from GEMS_Group_Section__c where account__c=:acc.ID and case__c= :caseObj.Id];
        System.assertEquals('TeSt02',grpquery.Group_No__c);
        GEMS_Category__c gemscat1 = GEMS_UtilityClassTest.insertiongemscat1(acc.ID,caseObj.Id);

        insert gemscat1;
        List<GEMS_Benefit_Agreement__c> baList = new List<GEMS_Benefit_Agreement__c>();
        GEMS_Benefit_Agreement__c gemsbenefit = GEMS_UtilityClassTest.insertionBenefit(acc.ID,caseObj.Id,product2Rec.id);
        GEMS_Benefit_Agreement__c gemsbenefit1 = GEMS_UtilityClassTest.insertionBenefit(acc.ID,caseObj.Id,product2Rec.id);
        baList.add(gemsbenefit);
        baList.add(gemsbenefit1);
        insert baList;

        PageReference pageRef = Page.GEMSBACatAssign;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('recs',gemsGroupObj.Id);
        Apexpages.StandardSetController stdControllerr = new Apexpages.StandardSetController(groupSectionList);
        GEMSBACatAssignController gm = new GEMSBACatAssignController (stdControllerr);

        gm.getTheUpdatedMembersCount();
        gm.gotoCase();
        gm.numberOfRowToRemove=2;
        gm.rowCount = '2';

        gm.recordToDelete= caseObj.ID;
        gm.removeRow(); 
        gm.assignCat();
        gm.gotoCreateAccountStructure();
        gm.backtoBA();
        gm.saveCat();
        //List<Integer> ittt =gm.iter;
      //  List < List < SelectOption >> opplist = gm.listOfOptions;
    }    */  
}