objects/Case__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Maintanance Related picklist values</description>
    <label>Maintanance Type</label>
</CustomObject>

objects/PROPOSAL_NI_TYPE__mdt.object
<CustomObject>
    <description>This Meta Data will be used in Case Network Information Request Type functionality.</description>
    <label>PROPOSAL NI TYPE</label>
    <pluralLabel>PROPOSAL NI TYPES</pluralLabel>
</CustomObject>

objects/Request_Type__c.object
<CustomObject>
    <description>This object is used to populate Case Network Information Types and the number requested.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>Network information case.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Request Types</relationshipLabel>
        <relationshipName>Request_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Request Type</label>
    <nameField>
        <label>Request Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RequestTypeDAOTest.cls
@isTest
private class RequestTypeDAOTest {

    @isTest static void testUpsertAndDelRequestType() {
        Test.startTest();
        Case case1 = new Case();
        case1.Subject = 'Test Case';
        insert case1;
        Request_Type__c requestType = new Request_Type__c();
        requestType.Case__c = case1.id;
        RequestTypeDAO rtDao = new RequestTypeDAO();
        List<Request_Type__c> rtList = new List<Request_Type__c>();

        rtList.add(requestType);

        rtDao.upsertRequestType(rtList);


        List<Request_Type__c> soqlList = rtDao.getRequestTypes(case1.id);

        system.assertEquals(rtList.size(), soqlList.size());

       List<PROPOSAL_NI_TYPE__mdt> soqlLists = rtDao.getRequestType(case1.id);

        
        rtList.remove(0);
        rtDao.deleteRequestType(soqlList);
        soqlList = [SELECT Case__c FROM Request_Type__c WHERE case__c = : case1.id ];


        System.assertEquals(soqlList, rtList);

        Test.stopTest();
    }



}