objects/Case__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Maintanance Related picklist values</description>
    <label>Maintanance Type</label>
</CustomObject>

objects/GEMS_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Attachment__c</fullName>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BA_Info__c</fullName>
        <label>BA Info</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>GEMS  Attachments</relationshipLabel>
        <relationshipName>GEMS_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>The Level tells user whether account level or Benefit agreement level</inlineHelpText>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Submission</fullName>
                    <default>true</default>
                    <label>Account Submission</label>
                </value>
                <value>
                    <fullName>Benefit Agreement</fullName>
                </value>
                <value>
                    <fullName>--None--</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABS</fullName>
                </value>
                <value>
                    <fullName>ACA CALCULATORS</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT CHANGE REQUEST FORM</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT STRUCTURE</fullName>
                </value>
                <value>
                    <fullName>ACH/WIRE FORM</fullName>
                </value>
                <value>
                    <fullName>ADDENDUM TO BPA FOR AFFILIATES</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRATIVE SERVICE AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO BENEFIT PROG APP (BPA)</fullName>
                </value>
                <value>
                    <fullName>ASO MANDATE CHECKLIST</fullName>
                </value>
                <value>
                    <fullName>BENEFIT ADHOC MEETING MINUTES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT BOOKLETS / CERTIFICATES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT EDIT TOOL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT MATRIX</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROG DESCRIPTION-DENTAL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROGRAM DESCRIPTION-BPD</fullName>
                </value>
                <value>
                    <fullName>BENEFIT WALLET DISCOVERY FORM</fullName>
                </value>
                <value>
                    <fullName>BINDER CHECK</fullName>
                </value>
                <value>
                    <fullName>BPA - ASO SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - ASO UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - DENTAL SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - DENTAL UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HCA SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HCA UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HEALTH SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HEALTH UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>BROKER TRANS/AOR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <formula>IF( ISBLANK(Attachment__c) , HYPERLINK(AttachmentUrl__c,&quot;View&quot;) , HYPERLINK (&quot;/servlet/servlet.FileDownload?file=&quot;+Attachment__c,&quot;View&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>View</label>
        <type>Text</type>
    </fields>
    <label>GEMS Attachments</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS  Attachments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GEMS_UploadAttachmentController.cls
public class GEMS_UploadAttachmentController {
    @TestVisible public transient String description {get;set;}
     @TestVisible public transient  String selectedType {get;set;}
    @TestVisible public transient String BAInfo {get; set;}
    @TestVisible public Case case1 {get;set;}
    public String filename {get;set;}
     @TestVisible public transient  String selectedLevel {get;set;}
    @TestVisible public transient Blob fileBody {get;set;}
    @TestVisible public transient List<GEMS_Attachment__c> gemsAttachmentList {set;get;}
    public Boolean filebool {get;set;}
    public string getInfo{get;set;}
    public Boolean typebool{get;set;}
    
    public List<WrapperClass> listWrapper {get;set;}
    public Boolean allBool {get;set;}
    
    public GEMS_UploadAttachmentController (ApexPages.StandardController Controller) {
        try{
            this.case1 = (Case)controller.getRecord();
            typebool = false;
            filebool = false;
            gemsAttachmentList =[select name,description__c,type__c,CreatedBy.name,View__c,Attachment__c, level__c, BA_Info__c  from GEMS_Attachment__c where case__c = :case1.id order by createddate desc];
            listWrapper = new List<WrapperClass>();
            if(gemsAttachmentList.size() > 0) {
                for(GEMS_Attachment__c gemAtt: gemsAttachmentList) {
                    listWrapper.add(new WrapperClass(gemAtt));
                }
            }
        }
        catch(Exception ex) {
            System.debug('====Exception==============='+ex.getMessage());
        }
    }
    
    //creates a new case_attachment__c record
    
    @testVisible private Database.SaveResult saveCustomAttachment(){
        GEMS_Attachment__c obj = new GEMS_Attachment__c();
        Database.SaveResult saveResult;
        try {
            obj.case__c = case1.id;
            obj.description__c = description;
            obj.type__c = selectedType;
            obj.level__c=selectedLevel;
            obj.ba_info__c=bainfo;
            saveResult = Database.insert(obj);
        }
        catch(Exception ex) {
            GEMS_CreateExceptionLog.insertErrorLog(ex, null, null, null,'Apex Class', 'Case', null, 'GEMS_UploadAttachmentController.saveCustomAttachment()','High'); 
            return null;
        }
        return saveResult;
    }
    
          public List<SelectOption> getLevelOptions(){
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult LevelResult = GEMS_Attachment__c.Level__c.getDescribe();
        List<Schema.PicklistEntry> Ty = LevelResult.getPicklistValues();
        for( Schema.PicklistEntry f : Ty)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
        return options;
    }
    public List<SelectOption> getTypeOptions(){
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult TypeResult = GEMS_Attachment__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> Ty = TypeResult.getPicklistValues();
        for( Schema.PicklistEntry f : Ty)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
        return options;
    }
    
    
    //create an actual Attachment record with the case_attachment__c as parent
    
    @testVisible Private Database.SaveResult saveStandardAttachment(Id parentId) {
        Database.SaveResult result;
        try {
        Attachment attachment = new Attachment();
        attachment.body = this.fileBody;
        attachment.name = this.fileName;
        attachment.parentid = parentid;
        result = Database.insert(attachment);
        }
        catch(Exception ex) {
            GEMS_CreateExceptionLog.insertErrorLog(ex,null, null, null,'Apex Class', 'Case', null, 'GEMS_UploadAttachmentController.saveStandardAttachment(Id parentId)','High'); 
            return null;
        }
        //set the file for the view state
        fileBody = Blob.valueof('');
        return result;
    }
    
    
    
    //Upload process is:
    // Insert new Contact_Attachment__c record
    // Insert new attachment with the new Contact_Attachment__c record as parent
    // Updates the Contact_attachment__c record with the ID of the new attahcment
    
    Public PageReference processUpload(){
        
        Boolean docTypeCheck =false; if(selectedType != null && selectedType =='--None--') docTypeCheck =true; System.debug('====selectedType  ==='+selectedType+docTypeCheck  );

       System.debug('fileBody======>'+fileBody);
        System.debug('fileName ======>'+fileName );
        if (docTypeCheck){
            //if(docTypeCheck)
            typebool=true;
            filebool=false;
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No DocType Chosen'));
            fileName = fileName;                      
            //PageReference pageRef = new PageReference(ApexPages.currentPage().getUrl());
            //pageRef.setRedirect(true);
            return null;
        }else if (fileName == Null && fileBody == Null){
            filebool=true;
            System.debug('Testing in else if');
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No file chosen to be uploaded'));
            return null;
          }

           
        
        else{
            try {
            System.debug('Testing in  if');
                Database.SaveResult customAttachmentResult = saveCustomAttachment();
                if (customAttachmentResult == null || !customAttachmentResult.isSuccess()) {
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Could not save attachment'));
                    return null;
                }
                
                Database.SaveResult attachmentResult = saveStandardAttachment(customAttachmentResult.getId());
                if (attachmentResult == null || !attachmentResult.isSuccess()) {
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Could not save attachment'));
                    return null;
                }
                else {
                    //update the custom attachment record with some attachment info
                    GEMS_Attachment__c customAttachment = [select id from GEMS_Attachment__c where id = :customAttachmentresult.getId()];
                    customAttachment.name = this.filename;
                    customAttachment.Attachment__c = attachmentResult.getId();
                    update customAttachment;
                }
                
                gemsAttachmentList =[select name,description__c,type__c,Level__c ,ba_info__c,CreatedBy.name,Attachment__c  from GEMS_Attachment__c where case__c = :case1.id order by createddate desc];
                listWrapper.Clear();
                if(gemsAttachmentList.size() > 0) {
                    for(GEMS_Attachment__c gemAtt: gemsAttachmentList) {
                        listWrapper.add(new WrapperClass(gemAtt));
                    }
                }
                description ='';
                selectedType ='--None--';
                selectedLevel = 'Account Submission';
                bainfo = '';
                 return null;
            }
            
            catch(Exception ex){
                ApexPages.AddMessages(ex);
                GEMS_CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'Case', null, 'GEMS_UploadAttachmentController.saveStandardAttachment(Id parentId)','High'); 
                return null;
            } 
            
             
            return new PageReference('/apex/GEMSUploadAttachment1?id='+case1.id);
        }
    }
    
    
    Public PageReference back(){
        return new PageReference ('/'+case1.id);
    }
    public Integer getPageNumber()
    {
        return  1;
    }
    
    public Integer getTotalPages()
    {
        
        return 1;
        
    }
    public class WrapperClass {
        public Boolean checked {get;set;}
        public GEMS_Attachment__c gemAtt{get;set;}
        public WrapperClass(GEMS_Attachment__c gemAtt) {
            this.gemAtt= gemAtt;
        }
    }
    public void del() {
        List<GEMS_Attachment__c > listAttForDel = new List<GEMS_Attachment__c >();
        List<WrapperClass> listTempWrapper = new List<WrapperClass>();
        for(WrapperClass w : listWrapper) {
            if(w.checked) {
                listAttForDel.add(w.gemAtt);
            } else {
                listTempWrapper.add(w);
            }
        }
        if(listAttForDel.size() > 0) {
            delete listAttForDel;
            listWrapper = listTempWrapper;
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Select atleast one record to delete'));
        }
    }
    public void selectAll() {
        if(allBool) {
            for(WrapperClass w : listWrapper) {
                w.checked = true;
            }
        } else {
            for(WrapperClass w : listWrapper) {
                w.checked = false;
            }
        }
    }
    public void test()
    {
        
    }
}