objects/Case__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Maintanance Related picklist values</description>
    <label>Maintanance Type</label>
</CustomObject>

objects/Request_Type__c.object
<CustomObject>
    <description>This object is used to populate Case Network Information Types and the number requested.</description>
    <fields>
        <fullName>Case__c</fullName>
        <description>Network information case.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Request Types</relationshipLabel>
        <relationshipName>Request_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_NI_Type__c</fullName>
        <description>The Case Proposal/ NI type.</description>
        <label>Proposal/NI Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ClaimsQuest (Milliman) Repricing</fullName>
                </value>
                <value>
                    <fullName>Discounts (ClaimsQuest)</fullName>
                </value>
                <value>
                    <fullName>Discounts (Local)</fullName>
                </value>
                <value>
                    <fullName>Disruption</fullName>
                </value>
                <value>
                    <fullName>GeoAccess</fullName>
                    <label>Geo</label>
                </value>
                <value>
                    <fullName>Maps</fullName>
                </value>
                <value>
                    <fullName>MarketQuest Network Compare Analysis</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>NDAT</fullName>
                </value>
                <value>
                    <fullName>Page Calculations</fullName>
                </value>
                <value>
                    <fullName>Provider Counts</fullName>
                </value>
                <value>
                    <fullName>Radius Page</fullName>
                </value>
                <value>
                    <fullName>Service Area</fullName>
                </value>
                <value>
                    <fullName>Site Match</fullName>
                </value>
                <value>
                    <fullName>Strennus Network Comparison</fullName>
                </value>
                <value>
                    <fullName>Summary Chart</fullName>
                </value>
                <value>
                    <fullName>Toggle</fullName>
                </value>
                <value>
                    <fullName>Total Discount Measurement Analysis</fullName>
                </value>
                <value>
                    <fullName>TX Repricing</fullName>
                </value>
                <value>
                    <fullName>ValueQuest Analysis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Type</label>
    <nameField>
        <label>Request Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RequestTypeTriggerHandlerTest.cls
@isTest
private class RequestTypeTriggerHandlerTest {

	@isTest static void setCaseNITypeSelectionsTest(){
		Account acc = TestClassUtiltity.CreateAccountRecord('TestAccount');
		Id networkInformationRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(System.Label.CaseRecordTypeNetworkInformation).getRecordTypeId();

		Case networkInformationCase = new Case(AccountId = acc.Id, Provider_Groups__c = 'Test');
		networkInformationCase.RecordTypeId = networkInformationRecordTypeId;
		insert networkInformationCase;

		Request_Type__c rt = new Request_Type__c(Case__c = networkInformationCase.Id);
		rt.Proposal_NI_Type__c = 'BCBSA';
		insert rt;

		networkInformationCase = [SELECT Id, NI_Type__c FROM Case WHERE Id =: networkInformationCase.Id];
		System.assert(networkInformationCase.NI_Type__c.contains('BCBSA'));
	}
	
}