objects/Competitor_Relationship__c.object
<CustomObject>
    <description>Competitors related to a Group Account as Carriers and to an Opportunity as Incumbent/ Won / Competing</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Competitor Relationship</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Members__c</fullName>
        <description>Total number of members the competitor/vendor has for the related account</description>
        <label>Total Members</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competitors / 3rd Party Vendors</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors / 3rd Party Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProspectingAppNewCompVendModalCtrlTest.cls
@isTest
private class ProspectingAppNewCompVendModalCtrlTest {
    static testMethod void validateSaveCompVendRelationship() {
        Competitor_Relationship__c compVendRel = new Competitor_Relationship__c();
        compVendRel.Total_Members__c = 123;
        
        ProspectingAppNewCompVendModalController.saveCompVendRelationship(compVendRel);
        System.assertNotEquals(null, compVendRel.Id);
    }
    
    static testMethod void validateGetPicklistValues() {
        List<String> compVendStatusList = ProspectingAppNewCompVendModalController.getPicklistValues('Competitor_Relationship__c', 'Status__c');
        
        Set<String> compVendStatusSet = new Set<String>();
        Schema.DescribeFieldResult fieldResult = Competitor_Relationship__c.Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : ple)
        {
            compVendStatusSet.add(f.getValue());
        } 
        
        for(String status : compVendStatusList) {
            System.assertEquals(true, compVendStatusSet.contains(status));
        }
    }
}