objects/Contract_Administration__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Custom Contracts</relationshipLabel>
        <relationshipName>Contract_Administrations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complexity__c</fullName>
        <label>Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Administration</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Administrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractAdministrationDAO.cls
public class ContractAdministrationDAO implements IContractAdministrationDAO { 
	
	public Interface IContractAdministrationDAO {
		List<Contract_Administration__c> getContractAdminsByGroupAccounts(Set<Id> groupAccIds);
	}

	public List<Contract_Administration__c> getContractAdminsByGroupAccounts(Set<Id> groupAccIds) {
		return [SELECT Complexity__c, Account__c FROM Contract_Administration__c WHERE Account__c IN :groupAccIds AND Complexity__c IN :ConstantsController.complexities];
	}
}