objects/Division__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of HCSC divisions</description>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>HCSC Division</label>
</CustomObject>

objects/OAuth_Jwt_Token2__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>stored integration callout credential name/</description>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JWT_Token__c</fullName>
        <label>JWT Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Updated_Date_Time__c</fullName>
        <label>Last Updated Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <label>OAuth Jwt Token CallOut</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Comments__c</fullName>
        <description>This field is used to capture the detailed description on why an Opportunity is closed won, lost or declined.</description>
        <label>Closed Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>County_Code__c</fullName>
        <label>County Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>This field is used to capture the date when the opportunity is won or lost.</description>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <label>FIPS Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Closed_Reason__c</fullName>
        <description>This field is used to capture the primary reason why an Opportunity is won, lost or declined.</description>
        <label>Primary Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absorbed by Parent Group</fullName>
                </value>
                <value>
                    <fullName>Change of Ownership</fullName>
                </value>
                <value>
                    <fullName>Consol. Covg with 1 Carrier</fullName>
                </value>
                <value>
                    <fullName>Headquarters Relocated</fullName>
                </value>
                <value>
                    <fullName>Lack of Narrow Network</fullName>
                </value>
                <value>
                    <fullName>Market Check by Group</fullName>
                </value>
                <value>
                    <fullName>Organizational Changes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Guarantees</fullName>
                </value>
                <value>
                    <fullName>Plan Design-Other</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Purchase by Another Company</fullName>
                </value>
                <value>
                    <fullName>Rates-Aggregate Stop Loss-Claim/Attch Factor</fullName>
                </value>
                <value>
                    <fullName>Rates-Incumbent Reduced</fullName>
                </value>
                <value>
                    <fullName>Rates-Individual Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Rates-Insured</fullName>
                </value>
                <value>
                    <fullName>Repricing</fullName>
                </value>
                <value>
                    <fullName>Reputation of Selected Carrier</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Broker Relationship</fullName>
                </value>
                <value>
                    <fullName>Changed Brokers</fullName>
                </value>
                <value>
                    <fullName>Network Discounts</fullName>
                </value>
                <value>
                    <fullName>Network Disruption</fullName>
                </value>
                <value>
                    <fullName>Product Packaging</fullName>
                </value>
                <value>
                    <fullName>Did Not Want to Disrupt Ees</fullName>
                </value>
                <value>
                    <fullName>Not Enough Diff. to Change</fullName>
                </value>
                <value>
                    <fullName>PUG Did not meet participation</fullName>
                </value>
                <value>
                    <fullName>Rates-Admin. Charge too High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>changed field from number to text as suggested by cesar</inlineHelpText>
        <label>Zip Code</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Plan__c.object
<CustomObject>
    <description>To capture all the plans related to products - Loaded from BlueStar</description>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HCSC_Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Product__r.HCSC_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HCSC State</label>
        <type>Text</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SearchFIPS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <label>FIPS Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>ZipCode</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>SearchFIPS</label>
</CustomObject>

objects/SGR_Opportunity_Census__c.object
<CustomObject>
    <description>This object is used  for</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is  look up  to  Opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Census</relationshipLabel>
        <relationshipName>Opportunity_Census</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Opportunity Census</label>
    <nameField>
        <label>Opportunity Census Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Censuses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Group_Section__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Group Section</relationshipLabel>
        <relationshipName>Opportunity_Group_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Group Section</label>
    <nameField>
        <label>Opportunity Group Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Group Section</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Member_Benefits__c.object
<CustomObject>
    <description>This object acts as a junction object between the Opportunity Group Section and Opportunity Census objects</description>
    <fields>
        <fullName>Opportunity_Plan_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Plan Rate</label>
        <referenceTo>SGR_Opportunity_Plan_Rate__c</referenceTo>
        <relationshipLabel>Opportunity Member Benefits</relationshipLabel>
        <relationshipName>Opportunity_Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Member Benefits</relationshipLabel>
        <relationshipName>Opportunity_Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Member Benefits</label>
    <nameField>
        <label>Opportunity Member Benefits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Member Benefits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Plan_Rate__c.object
<CustomObject>
    <description>This object contains details about opportunity plan Rates.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Plan Rate</label>
    <nameField>
        <label>Opportunity Plan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Username_Password__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EndPoinUrl__c</fullName>
        <label>EndPoinUrl</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Username_Password</label>
</CustomObject>

globalValueSets/HCSC_Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NM</fullName>
    </customValue>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <customValue>
        <fullName>TX</fullName>
    </customValue>
    <masterLabel>HCSC Division</masterLabel>
</GlobalValueSet>

classes/SGR_URE_OpportunityRatingBatch_Test.cls
@isTest
public class SGR_URE_OpportunityRatingBatch_Test {
    
    @isTest 
    public static void testOppRating(){
        List<String> task = new List<String> ();
        task.add('RetentionTask');
        task.add('MarketingRatesGenericTask');
        Integer age= 4;
        String  rateEffectiveDate='2019-01-01';
        List<String> values = new List<String>();
         List<String> errMsgsLst = new List<String>();
        errMsgsLst.add('error');
        errMsgsLst.add('error12');
        
       
        
        
        set<string> planId = new set<string> ();
        List<string> type = new List<string>();
        type.add('TIER4');
        planId.add('SPSG10BCOSILO');
        planId.add('SPSG10PPOSILO');
        planId.add('DILLR07');
        
        
          CustomSettingDAO.ICustomSettingDAO customSettingInstance=new CustomSettingDAO();
        Username_Password__c pwd = new Username_Password__c();
        pwd.Name = 'URE_Rate_Callout';
        pwd.Integration_Name__c = 'Integration SGR';
        pwd.EndPoinUrl__c = 'https://test';
        pwd.Password__c = 'Password';
        insert pwd;
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User u =new User();
        u.FirstName = 'Integration test';
        u.LastName = 'SGR';
        u.Alias = 'ISGR';
        u.Email = 'xyz@gmail.com';
        u.Username = 'Integrationxyz@gmail.com';
        u.IsActive = true;
        u.ProfileId = profileId.id;
        u.TimeZoneSidKey = 'GMT';
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LocaleSidKey = 'en_US';
        insert u;
        
        OAuth_Jwt_Token2__c oAuth = new OAuth_Jwt_Token2__c();
        oAuth.Name = 'Integration SGR';
        //oAuth.SetupOwnerId=u.Id;
        oAuth.Password__c='xx';
     	oAuth.UserName__c = 'xs123';
     	oAuth.End_Point__c = 'https://test';
        oAuth.Last_Updated_Date_Time__c = System.now();
        oAuth.JWT_Token__c = 'xyz1234';
      
     	insert oAuth;
        
        Plan__c pl=new Plan__c();
        pl.name='SPSG10BCOSILO';
        insert pl;
        
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity op=new Opportunity();
        op.name='TestOp';
        op.StageName='Lost';
        op.CloseDate=Date.newInstance(2022, 12, 9);
        op.HCSC_Division__c ='IL';
        op.Renewal_Date__c = System.today();
        op.County_Code__c = '43243';
        op.FIPS_Code__c = '17111';
        op.Zip_Code__c = '32015';
        op.Date_Closed__c = System.today();
        op.Primary_Closed_Reason__c ='Other';
        op.Closed_Comments__c = 'xyz';
        oppList.add(op);
        
       
        Opportunity op2=new Opportunity();
        op2.name='TestOp';
        op2.StageName='Withdrawn';
        op2.CloseDate=Date.newInstance(2022, 12, 9);
        op2.HCSC_Division__c ='IL';
        op2.Renewal_Date__c = System.today();
        op2.County_Code__c = '43243';
        op2.Zip_Code__c = '32015';
        op2.Date_Closed__c = System.today();
        op2.Primary_Closed_Reason__c ='Other';
        op2.Closed_Comments__c = 'xyz';
        oppList.add(op2);
        
        Opportunity op3=new Opportunity();
        op3.name='TestOp';
        op3.StageName='Lost';
        op3.CloseDate=Date.newInstance(2022, 12, 9);
        op3.HCSC_Division__c ='IL';
        op3.Renewal_Date__c = System.today();
        op3.Zip_Code__c = '32015';
        op3.Date_Closed__c = System.today();
        op3.Primary_Closed_Reason__c ='Other';
        op3.Closed_Comments__c = 'xyz';
        oppList.add(op3);
        
        insert oppList;
        list<id> opId=new list<id>();
        for(Opportunity opp: oppList){
            opId.add(opp.id);
        }
        Division__c div = new Division__c();
        div.Name = 'IL';
        div.State_Code__c ='17';
        insert div;
        
        SearchFIPS__c fips = new SearchFIPS__c();
        fips.FIPS_Code__c = '17111';
        fips.ZipCode__c = '32015';
        fips.State__c = 'IL';
        fips.Name ='17111IL';
        insert fips;
        
        SGR_Opportunity_Plan_Rate__c opPlan=new SGR_Opportunity_Plan_Rate__c();
        opPlan.Name='PR - 0000000434';
        opPlan.Opportunity__c=op.id;
        opPlan.Plan__c=pl.id;
        opPlan.Type__c = 'Renewal';
        insert opPlan;
        
        SGR_Opportunity_Group_Section__c grp=new SGR_Opportunity_Group_Section__c();
        grp.Name='GS-976908';
        grp.Opportunity__c=op.id;
        insert grp;
        
        SGR_Opportunity_Census__c cen=new SGR_Opportunity_Census__c();
        cen.Name='860535';
        cen.Opportunity__c=op.id;
        cen.Subscriber_Number__c=860535;
        cen.Gender__c='M';
        cen.Relationship__c='Subscriber';
        cen.Relationship_Code__c='PR';
        cen.Date_of_Birth__c=Date.newInstance(1992, 12, 9);
        cen.Age_New__c=26;
        cen.Zip_Code__c='12';
        insert cen;
        list<SGR_Opportunity_Census__c> cenLst=new list<SGR_Opportunity_Census__c>();
        cenLst.add(cen);
        
        
        
        List<SGR_Opportunity_Member_Benefits__c> soc = new List<SGR_Opportunity_Member_Benefits__c>();
        SGR_Opportunity_Member_Benefits__c mbs = new SGR_Opportunity_Member_Benefits__c();
        mbs.Name='demo34Cloned';
        mbs.Opportunity_Group_Section__c=grp.id;
        mbs.Opportunity_Census__c=cen.id;
        mbs.Opportunity_Plan_Rate__c=opPlan.id;
        insert mbs;
        soc.add(mbs);
        
        SGR_URE_OpportunityRatingBatch obj=new SGR_URE_OpportunityRatingBatch(opId);
        Database.executeBatch(obj);
        
    }

}