objects/Division__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of HCSC divisions</description>
    <label>HCSC Division</label>
</CustomObject>

objects/Market_Segment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Segment Picklist values from Account</description>
    <label>Market Segment</label>
</CustomObject>

objects/SGR_Plan_FIPS_Map__c.object
<CustomObject>
    <fields>
        <fullName>Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <label>FIPS Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SGR_Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Plan FIPS Map</label>
    <nameField>
        <label>Plan FIPS Map Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan FIPS Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_URE_Age_Rate_Driver__c.object
<CustomObject>
    <fields>
        <fullName>Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <label>FIPS Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Processed Successfully</fullName>
                </value>
                <value>
                    <fullName>Processed With Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SGR_Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Age Rate Driver</label>
    <nameField>
        <label>URE_Age_Rate_Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Age Rate Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SGR_URE_GenerateAgeRateDriverBatchTest.cls
@isTest
public class SGR_URE_GenerateAgeRateDriverBatchTest {
    
 	@testSetup 
    public static void dataSetup() {
    	
    	List<SGR_Plan_FIPS_Map__c> planFipsList = new List<SGR_Plan_FIPS_Map__c>();
    	planFipsList.add(new SGR_Plan_FIPS_Map__c (
				Name = '17001-GPSG12BCESILO',
				SGR_Plan_Id__c = 'GPSG12BCESILO' ,
				FIPS_Code__c = '17001',
				Division__c = 'IL',
				Corporate_Entity_Code__c = 'IL1',
				Effective_Date__c = System.today().addYears(-3),
				Market_Segment__c = 'SG',
				Funding_Type__c = 'PREM'    	
    					));
    	planFipsList.add(new SGR_Plan_FIPS_Map__c (
				Name = '17002-GPSG12BCESOKO',
				SGR_Plan_Id__c = 'GPSG12BCESOKO' ,
				FIPS_Code__c = '17002',
				Division__c = 'OK',
				Corporate_Entity_Code__c = 'OK1',
				Effective_Date__c = System.today().addYears(-4),
				Market_Segment__c = 'SG',
				Funding_Type__c = 'PREM'    	
		));
		planFipsList.add(new SGR_Plan_FIPS_Map__c (
				Name = '17002-GPSG12BCESNMO',
				SGR_Plan_Id__c = 'GPSG12BCESNMO' ,
				FIPS_Code__c = '17002',
				Division__c = 'NM',
				Corporate_Entity_Code__c = 'NM1',
				Effective_Date__c = System.today(),
				Market_Segment__c = 'SG',
				Funding_Type__c = 'PREM'    	
		));
		
		insert planFipsList; 
        
        
        List<Division__c> divs = new List<Division__c>();
        divs.add(new Division__c(Name='IL'));
        divs.add(new Division__c(Name='OK'));
        divs.add(new Division__c(Name='NM'));
        divs.add(new Division__c(Name='TX'));
        insert divs; 
    	
    } 
    
    @isTest
    public static void testPlanFipsCreation() {
    	List<Division__c> divs = [Select Id from Division__c]; 
    	List<SGR_Plan_FIPS_Map__c> planFipsList = [Select Id from SGR_Plan_FIPS_Map__c];       
        System.assert(null != divs);
        System.assertEquals(4, divs.size());
    	System.assert(null != planFipsList);
    	System.assertEquals(3, planFipsList.size());
    	
        Test.startTest();
    		SGR_URE_GenerateAgeRateDriverBatch b = new SGR_URE_GenerateAgeRateDriverBatch(Date.today());
    		Database.executeBatch(b);        	
    	Test.stopTest(); 
        
        List<SGR_URE_Age_Rate_Driver__c> ardList = [Select Id,Processing_Status__c from SGR_URE_Age_Rate_Driver__c];
        System.assert(null != ardList);
        //PCM - 01/31/19 - Commenting Out because failing test classes 
		System.assertEquals(1, ardList.size());
		System.assertEquals('Ready', ardList[0].Processing_Status__c);
    }   
}