objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Message of the Exception</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FW_Service_Status_Log__c.object
<CustomObject>
    <label>FW Service Status Log</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Status Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SearchFIPS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <label>FIPS Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>SearchFIPS</label>
</CustomObject>

objects/SGR_Product_Group__c.object
<CustomObject>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <label>FIPS Code</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SGR_Client_ID__c</fullName>
        <label>Client ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RENEWALS</fullName>
                </value>
                <value>
                    <fullName>QUOTING</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SGR_Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SGR_Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SGR_Line_of_Business__c</fullName>
        <label>Line of Business</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SGR_Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SGR_Product_Group_Code__c</fullName>
        <label>Product Group Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SGR_Product_Group_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Product Group External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SGR_Product_Group_Type__c</fullName>
        <label>Product Group Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SGR_GSPS_GetProductGroups.cls
//*************************************************************************************
// Name             : SGR_GSPS_GetProductGroups.cls
// Description      : Callout To get Product Groups
// Created By       : Raviteja 
// Created Date     : 10/29/2018
// 
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 30/10/2018       Raviteja             SFDC 14273,14274 
// 11/20/2018       Mei Chen			Updated to call within loop of Fipscode
// ************************************************************************************
public class SGR_GSPS_GetProductGroups {
    @TestVisible private final String SGR_INTEGRATION_NAME = 'GSPS_ProductGroupCallOut';
    @TestVisible private static UserDAO.IUserDAO userDAOInstance;
    @TestVisible private static String EXCEPTION_MESSAGE = 'EndPoint not configured';

    public static String errorMessage;
    private List<FW_Service_Status_Log__c> logsList = new List<FW_Service_Status_Log__c>();
    private APICallOutRestWSUtility objUtility;
    public SGR_GSPS_GetProductGroups() {
        this.objUtility = new APICallOutRestWSUtility(SGR_INTEGRATION_NAME);

    }

    public void callGSPSProductGroupService(String clientId, Integer Version, Date effectiveDate, String state,
            String marketSegment, String fundingType) {
        List<SGR_Product_Group__c> productGroupList = new List<SGR_Product_Group__c>();
        List<FW_Service_Status_Log__c> logList = new List<FW_Service_Status_Log__c>();
        AggregateResult[] fips = [SELECT FIPS_Code__c, State__c FROM SearchFIPS__c WHERE State__c = :state GROUP BY FIPS_Code__c, State__c];
        List<String> fipsCodeList = new List<String>();
        for (AggregateResult ar : fips) {
            fipsCodeList.add(String.valueOf(ar.get('FIPS_Code__c')));
        }
        system.debug('fipscode List;:::' + fipsCodeList);
        String fipsCodeStr = String.join(fipsCodeList, ';');
        try {
            List<SGR_Product_Group__c> pgData = getGSPSProductGroup(clientId, Version, effectiveDate, state, marketSegment,
                    fundingType, fipsCodeStr);
            system.debug('size of pgData:' + pgData);

            if (pgData != null && !pgData.isEmpty()) {
                system.debug(' add new pg Data....');
                productGroupList.addAll(pgData);
            }
            List<String> errMsgsList = new List<String>();
            if (productGroupList != null && productGroupList.size() > 0) {

                system.debug('@@@@@@productGroupList:::::' + productGroupList);

                Database.UpsertResult [] results = Database.upsert(productGroupList, SGR_Product_Group__c.SGR_Product_Group_External_ID__c, false);

                system.debug('upSert result:::::' + results);

                if (results != null) {
                    for (Database.UpsertResult sv : results) {
                        if (sv != null && sv.isSuccess()) {
                            System.debug('*****Success::**' + sv.getId());
                        } else {
                            system.debug('something wrong when insert/update the product group data.' + sv.getErrors());
                            for (Database.Error err : sv.getErrors()) {
                                if (err != null) {
                                    errMsgsList.add(err.getMessage());
                                }
                            }
                            if (errMsgsList != null && !errMsgsList.isEmpty()) {
                                createErroLog(errMsgsList);
                            }
                        }

                    }
                }

            }

            if (logsList != null && !logsList.isEmpty()) {
                insert logsList;
            }

            if (objUtility != null && objUtility.newAccessToken != null) {
                objUtility.oAuthUtil.updateToken(objUtility.newAccessToken);
            }
        } catch (system.DmlException dml) {
            system.debug('insert product group exception::' + dml);
        } catch (Exception e) {
            system.debug('product group general exception:::' + e);
        }

    }
    public List<SGR_Product_Group__c> getGSPSProductGroup(String clientId, Integer Version, Date effectiveDate, String division,
            String marketSegment, String fundingType, String fipsCodes) {

        system.debug('calling callSGPS Product group Service.....fips code:.' + fipsCodes + 'state: ' + division);
        List<SGR_Product_Group__c> pgList = new List<SGR_Product_Group__c>();
        Set<Id> succPGIDS = new Set<Id>();
        try {
            SGR_GSPS_ProductGroupRequestWrapper objRequestWrapper = new SGR_GSPS_ProductGroupRequestWrapper();
            objRequestWrapper.clientId = clientId;
            objRequestWrapper.version = Version;
            objRequestWrapper.effectiveDate = effectiveDate;
            objRequestWrapper.division = division;
            objRequestWrapper.marketSegment = marketSegment;
            objRequestWrapper.fundingType = fundingType;
            objRequestWrapper.fipsCode = null ;//fipsCode;no need to pass the fipscode

            if (objRequestWrapper != null) {
                SGR_GSPS_ProductGroupResponseWrapper objResponseWrappertoProcess = objUtility.invokeProductGroupService(objRequestWrapper);

                if (objUtility.integrationStatuLog != null) {
                    logsList.add(objUtility.integrationStatuLog);
                }

                pgList = handleGSPSServiceResponse(objResponseWrappertoProcess, clientId, fipsCodes);

            }

        } catch (Exception e) {
            System.debug('OAUTH Exception:' + e.getMessage() + ' ' + e.getStackTraceString());
        }

        return pgList;
    }
    @TestVisible
    private List<SGR_Product_Group__c> handleGSPSServiceResponse(SGR_GSPS_ProductGroupResponseWrapper
            objResponseWrappertoProcess,
            String clientId, String fipsCodeStr) {
        List<SGR_Product_Group__c> pgList = new List<SGR_Product_Group__c>();
        Set<Id> succPGIDS = new Set<Id>();

        if (objResponseWrappertoProcess.responseItemsList != null) {
            system.debug('@@@@@@' + objResponseWrappertoProcess.responseItemsList + ' client Id:::' + clientId +
                    ' fipsCode....' + fipsCodeStr);
            for (SGR_GSPS_ProductGroupResponseWrapper.SGR_GSPS_ProductGroupResponseItems
            obj : objResponseWrappertoProcess.responseItemsList) {

                SGR_Product_Group__c sPG = new SGR_Product_Group__c();
                sPG.Name = obj.name;
                sPG.SGR_Product_Group_Code__c = obj.productGroupCode;
                sPG.SGR_Market_Segment__c = obj.marketSegment;
                sPG.SGR_Division__c = obj.division;
                sPG.FIPS_Code__c = fipsCodeStr;

                if (obj.effectiveDate != null) {
                    sPG.SGR_Effective_Date__c = Utility.parseDate(obj.effectiveDate);

                }
                if (obj.endDate != null) {
                    sPG.SGR_Expiry_Date__c = Utility.parseDate(obj.endDate);

                }
                sPG.SGR_Funding_Type__c = obj.fundingType;
                sPG.SGR_Line_of_Business__c = obj.lineOfBusiness;
                sPG.SGR_Product_Group_Type__c = format(obj.productGroupType);
                sPG.SGR_Product_Group_External_ID__c = convertPgExtId(obj.productGroupCode, obj.marketSegment, obj.division,
                        sPG.SGR_Effective_Date__c, sPG.SGR_Expiry_Date__c,
                        obj.lineOfBusiness);
                sPG.SGR_Client_ID__c = clientId;
                system.debug('@@@@@@' + sPG.SGR_Product_Group_External_ID__c);
                pgList.add(sPG);

            }
            system.debug('********size****' + pglist.size());
        }
        return pgList;
    }
    public static String format(List<String> values) {
        if (values == null) return null;
        return String.join(values, ';');
    }
    public static void createErroLog(List<String> errMsgsLst) {
        List<Error_Log__c> errLst = new List<Error_Log__c>();
        for (String er : errMsgsLst) {
            Error_Log__c errLog = new Error_Log__c();
            errLog.Application__c = System.Label.ErrorLog_Application_TriggerOff;
            errLog.Error_Message__c = er;
            errLst.add(errLog);
        }
        if (errLst.size() > 0) {
            insert errLst;
        }
    }

    public static String convertPgExtId(String productGroupCode, String marketSegment, String division, Date effctDate,
            Date expDate, String lineOfBusiness) {
        return productGroupCode + marketSegment + division + (effctDate == null ? '0/0/0'
                : effctDate.format()) + lineOfBusiness;
    }
}