objects/Fips_Mapping_for_Plan_Batch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>this table is used to keep track if the get plan batch has been ran the fips code.</description>
    <fields>
        <fullName>Fips_Code__c</fullName>
        <label>Fips Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCSC_State__c</fullName>
        <label>HCSC State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Fips Mapping for Plan Batch</label>
</CustomObject>

classes/SGR_GSPS_GetAvailablePlansSc_Test.cls
@isTest
public class SGR_GSPS_GetAvailablePlansSc_Test {
    static testMethod void testMethod1() {
        Fips_Mapping_for_Plan_Batch__c fip = new Fips_Mapping_for_Plan_Batch__c();
        fip.Fips_Code__c = '17003';
        fip.HCSC_State__c = 'IL';
        fip.Name = '17003';
        insert fip;

        test.startTest();
        SGR_GSPS_GetAvailablePlansSchedule sb = new SGR_GSPS_GetAvailablePlansSchedule();
        String CRON_EXP = '0 0 0 3 9 ? 2022';
        System.schedule('GSPS_Test_Schedule', CRON_EXP, sb);
        //System.schedule('Test', CRON_EXP, sb);
        test.stopTest();
    }

}