objects/GEMS_Custom_ID_Request_Form__c.object
<CustomObject>
    <fields>
        <fullName>Applicable_BAs__c</fullName>
        <label>Applicable BAs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Applicable_GSs__c</fullName>
        <label>Applicable GSs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Agreement</fullName>
                </value>
                <value>
                    <fullName>Group Section</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issuance_Type__c</fullName>
        <label>Issuance Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Issuance</fullName>
                </value>
                <value>
                    <fullName>Partial Issuance</fullName>
                </value>
                <value>
                    <fullName>Maintenance Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GEMS Custom ID Request Form</label>
    <nameField>
        <displayFormat>CIR-{00000}</displayFormat>
        <label>Custom Request Form ID#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GEMS Custom ID Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_ID_Card_Suppression__c.object
<CustomObject>
    <fields>
        <fullName>Applicable_BAs__c</fullName>
        <label>Applicable BAs</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Applicable_GSs__c</fullName>
        <label>Applicable GSs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Agreement</fullName>
                </value>
                <value>
                    <fullName>Group Section</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GEMS ID Card Suppression</label>
    <nameField>
        <displayFormat>IDS#{0000000}</displayFormat>
        <label>ID Card Suppression Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GEMS ID Card Suppressions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GEMS_Prospective_ID_Card__c.object
<CustomObject>
    <fields>
        <fullName>Applicable_BAs__c</fullName>
        <label>Applicable BAs</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Applicable_GSs__c</fullName>
        <label>Applicable GSs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Agreement</fullName>
                </value>
                <value>
                    <fullName>Group Section</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GEMS Prospective ID Card</label>
    <nameField>
        <displayFormat>PID#{0000000}</displayFormat>
        <label>Prospective ID Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GEMS Prospective ID Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GEMS_IDCardUtil_Test.cls
@isTest

public class GEMS_IDCardUtil_Test {
    
    
    private static testmethod void testGetAssignmentItems() {
        List<SelectOption> options = GEMS_IDCardUtil.getAssignmentItems();
        SelectOption option = options.get(1);
        System.assertEquals('Group Section', option.getValue());
    }
    
    private static testmethod void testCopyCustomIDFormToIDCompare() {
        List<GEMS_Custom_ID_Request_Form__c> customIDFormList = new List<GEMS_Custom_ID_Request_Form__c>(); 
        GEMS_Custom_ID_Request_Form__c cForm = new GEMS_Custom_ID_Request_Form__c();
        cForm.Applicable_BAs__c = '1111,2222';
        cForm.Applicable_GSs__c = '';
        cForm.Assignment_Type__c = 'Benefit Agreement';
        cForm.Issuance_Type__c = 'Full Issuance';
        //insert cForm;
        customIDFormList.add(cForm);
        List<GEMS_IDCompare> idCompareList = GEMS_IDCardUtil.CopyCustomIDFormToIDCompare(customIDFormList);
        GEMS_IDCompare idCompare = idCompareList.get(0);
        System.assertEquals('1111,2222', idCompare.applicableBAs);
	}
    
    private static testmethod void testCopyIDCompareToProspectiveIDForm() {
        List<GEMS_IDCompare> idcompareList = new List<GEMS_IDCompare>();
        Map<ID, GEMS_Prospective_ID_Card__c> oldMap = new Map<ID, GEMS_Prospective_ID_Card__c>();
        GEMS_IDCardUtil.copyIDCompareToProspectiveIDForm(idcompareList, oldMap);
    }
    
    
    private static testmethod void testCopyIDCompareToSuppressionIDForm() {
     	List<GEMS_IDCompare> idcompareList = new List<GEMS_IDCompare>();
        Map<ID, GEMS_ID_Card_Suppression__c> oldMap = new Map<ID, GEMS_ID_Card_Suppression__c>();
        GEMS_IDCardUtil.copyIDCompareToSuppressionIDForm(idcompareList,oldMap);
    }
    
    private static testmethod void testUpdateExistingAssignments() {
    	Id formId;
        String assignmentType = 'Benefit Agreement';
        String baCaseNums = '0001';
        String gsCaseNums = '1234-1563';
    	List<GEMS_IDCompare> idCompareList = new List<GEMS_IDCompare>();
        GEMS_CustomFormInput customFormInput = new GEMS_CustomFormInput(formId,assignmentType,baCaseNums,gsCaseNums,idCompareList);
        List<GEMS_IDCompare> idCompareListNew = GEMS_IDCardUtil.updateExistingAssignments(customFormInput);
    }
}