objects/GEMS_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Sequence__c</fullName>
        <externalId>true</externalId>
        <label>Address Sequence</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Usage__c</fullName>
        <label>Usage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Mailing</fullName>
                </value>
                <value>
                    <fullName>BAE</fullName>
                </value>
                <value>
                    <fullName>Subsidary</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>ThirdParty</fullName>
                </value>
                <value>
                    <fullName>Stlm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GEMS Address</label>
    <nameField>
        <label>Street</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GEMS_AddressTriggerHandler.cls
/**************************************************************************************
 * Apex Class Name     : GEMS_AddressTriggerHandler
 * Version             : 1.0
 * Function            : This is a handler class for Address Trigger which is used to restict user or system to create or update multiple GEMS Address Values for primary. 
 * Modification Log    :
 * Developer           :    Date                   Description
 * ----------------------------------------------------------------------------                 
 * Lakshmi Arigela       06/28/2017                Original Version,SFDC-3913 System should not send duplicate primary address values to BLUESTAR
 * Shankar				 11/08/2017				   SFDC-7238. Added a check to allow changes to existing primarya address by comparing addr seq #
 *************************************************************************************/
public  class GEMS_AddressTriggerHandler {


	/*****************************************************************
  Method: checkPrimaryAddress
  Description: checkPrimaryAddress method is to check the Account Addresses and 
                         create error message if primary address already exists
	 *******************************************************************/
	public static void checkPrimaryAddress(List<GEMS_Address__c> addresses){

		List<Id> AccountIds= new List<Id>();
		Set<Id> addresscheck = new Set<Id>();

		for(GEMS_Address__c addr : addresses){



			//Adding only the Accounts only that have Primary address.
			if(addr.Usage__c!=null && !string.isEmpty(addr.Usage__c)){
				if(addr.Usage__c.contains('Primary')){
					AccountIds.add(addr.Account__c);
					addresscheck.add(addr.Id);
				}
			}     
		}


		Map<Id,GEMS_Address__c> Account_AddressMap = new Map<Id,GEMS_Address__c>();

		// SFDC-7238. Added Address_Sequence__c to query
		for(GEMS_Address__c addrss: [Select id ,Usage__c, Address_Sequence__c, Account__c from GEMS_Address__c where Account__c in: AccountIds and Usage__c includes('Primary')]){
			if(!addresscheck.contains(addrss.id)){
				Account_AddressMap.put(addrss.Account__c,addrss);
			}
		}
		// SFDC-7238 End

		// SFDC-7238. Error out if a primary address (with a different address sequence #) is being inserted and if one exists already
		for(GEMS_Address__c addr : addresses){
			GEMS_Address__c a = Account_AddressMap.get(addr.account__c);
			if(Account_AddressMap.containskey(addr.account__c) && a.Address_Sequence__c != addr.Address_Sequence__c){
				addr.Usage__c.adderror('Primary address already exists for this account');
			}

		} 
		// SFDC-7238 End




	}
}