objects/GEMS_Return_Reason__c.object
<CustomObject>
    <fields>
        <fullName>GEMS_Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>GEMS_Sub_Type__c</fullName>
        <label>ABS/Matirx Sub Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>GEMS_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Blue Distinction</fullName>
                </value>
                <value>
                    <fullName>BVA</fullName>
                </value>
                <value>
                    <fullName>Eligibility Provisions</fullName>
                </value>
                <value>
                    <fullName>Emergency Benefits</fullName>
                </value>
                <value>
                    <fullName>Exclusions</fullName>
                </value>
                <value>
                    <fullName>Federal Mandates</fullName>
                </value>
                <value>
                    <fullName>General Information Summary</fullName>
                </value>
                <value>
                    <fullName>General Provisions</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Inpatient Hospital Benefits</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous Benefit Provisions</fullName>
                </value>
                <value>
                    <fullName>National Radiology Quality Initiative (NRQI)</fullName>
                </value>
                <value>
                    <fullName>Other Covered Services</fullName>
                </value>
                <value>
                    <fullName>Outpatient Hospital Benefits</fullName>
                </value>
                <value>
                    <fullName>Overall Program Payment Provisions</fullName>
                </value>
                <value>
                    <fullName>Prescription Drug Benefits</fullName>
                </value>
                <value>
                    <fullName>Preventive Health Benefits</fullName>
                </value>
                <value>
                    <fullName>Professional Service Benefits</fullName>
                </value>
                <value>
                    <fullName>Reference Based Pricing (RBP)</fullName>
                </value>
                <value>
                    <fullName>Substance Use Disorder</fullName>
                </value>
                <value>
                    <fullName>Utilization Management</fullName>
                </value>
                <value>
                    <fullName>VBID</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GEMS_Type__c</fullName>
        <label>Returned Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABS</fullName>
                </value>
                <value>
                    <fullName>ACA CALCULATORS</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT CHANGE REQUEST FORM</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT STRUCTURE</fullName>
                </value>
                <value>
                    <fullName>ACH/WIRE FORM</fullName>
                </value>
                <value>
                    <fullName>ADDENDUM TO BPA FOR AFFILIATES</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRATIVE SERVICE AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO BENEFIT PROG APP (BPA)</fullName>
                </value>
                <value>
                    <fullName>ASO MANDATE CHECKLIST</fullName>
                </value>
                <value>
                    <fullName>BENEFIT ADHOC MEETING MINUTES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT BOOKLETS / CERTIFICATES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT EDIT TOOL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT MATRIX</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROG DESCRIPTION-DENTAL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROGRAM DESCRIPTION-BPD</fullName>
                </value>
                <value>
                    <fullName>BENEFIT WALLET DISCOVERY FORM</fullName>
                </value>
                <value>
                    <fullName>BINDER CHECK</fullName>
                </value>
                <value>
                    <fullName>BPA - ASOSIGNED</fullName>
                    <label>BPA - ASO SIGNED</label>
                </value>
                <value>
                    <fullName>BPA - ASO UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - DENTALSIGNED</fullName>
                    <label>BPA - DENTAL SIGNED</label>
                </value>
                <value>
                    <fullName>BPA - DENTAL UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HCASIGNED</fullName>
                    <label>BPA - HCA SIGNED</label>
                </value>
                <value>
                    <fullName>BPA - HCA UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HEALTHSIGNED</fullName>
                    <label>BPA - HEALTH SIGNED</label>
                </value>
                <value>
                    <fullName>BPA - HEALTH UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>BROKER TRANS/AOR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <description>Process name that auto populates from Case object.</description>
        <label>Process Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Setup Screening</fullName>
                </value>
                <value>
                    <fullName>Benefit Coding Screening</fullName>
                </value>
                <value>
                    <fullName>CDHP Tax Screening</fullName>
                </value>
                <value>
                    <fullName>Dental Screening</fullName>
                </value>
                <value>
                    <fullName>Dental Underwriting Screening</fullName>
                </value>
                <value>
                    <fullName>EPO Screening</fullName>
                </value>
                <value>
                    <fullName>FSU Membership Screening</fullName>
                </value>
                <value>
                    <fullName>Medical Management Screening</fullName>
                </value>
                <value>
                    <fullName>Underwriting Screening</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Return_Reason__c</fullName>
        <label>Return Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Missing doc</fullName>
                </value>
                <value>
                    <fullName>Incomplete doc</fullName>
                </value>
                <value>
                    <fullName>Ambiguous/Clarification Required</fullName>
                </value>
                <value>
                    <fullName>Benefit cannot be supported</fullName>
                </value>
                <value>
                    <fullName>Benefit discrepancy</fullName>
                </value>
                <value>
                    <fullName>Rate discrepancy</fullName>
                </value>
                <value>
                    <fullName>Enrollment discrepancy</fullName>
                </value>
                <value>
                    <fullName>Benefit not compliant</fullName>
                </value>
                <value>
                    <fullName>CBSR required</fullName>
                </value>
                <value>
                    <fullName>Benefit not filed / approved by DOL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBC_BB_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SBC/BB Form</label>
        <referenceTo>GEMS_SBC_BB_Form__c</referenceTo>
        <relationshipLabel>GEMS Return Reasons</relationshipLabel>
        <relationshipName>GEMS_Return_Reasons</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GEMS Return Reason</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Return Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GEMS Return Reasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GEMS_SBC_BB_Form__c.object
<CustomObject>
    <fields>
        <fullName>Form_Status__c</fullName>
        <label>Form Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent to CBDM</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Internal Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Published to Portal</fullName>
                </value>
                <value>
                    <fullName>Sent for Translation</fullName>
                </value>
                <value>
                    <fullName>Sent for Print</fullName>
                </value>
                <value>
                    <fullName>Mailing Completed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Return</fullName>
                </value>
                <value>
                    <fullName>Revision Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Returned_User_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Returned User ID</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SBC_BB_Forms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SBC_BB_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request Form</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GEMS_ReturnStatusComponentController.cls
/**************************************************************************************
  Apex Class Name     : GEMS_ReturnStatusComponentController
  Version             : 1.0
  Function            : Utility Class to update the Return Status for the Form SBC/BB.
                      : If any other object need to use Return Reason Object please refer this class to add and one more else if in the constructor and save status method.
  Modification Log    :
* Developer           :Date              Description
* ----------------------------------------------------------------------------                 
* Gokul Bharati        08/21/2017            Original Version
*************************************************************************************/
public class GEMS_ReturnStatusComponentController
{
    public GEMS_ReturnStatusComponentController() {
        objectId=ApexPages.currentPage().getParameters().get('Id');
        objectName=string.valueOf(objectId.getsObjectType());
        if(objectName == 'GEMS_SBC_BB_Form__c'){
          recordTypeId = Schema.SObjectType.GEMS_Return_Reason__c.getRecordTypeInfosByName().get('GEMS Form Return Reason').getRecordTypeId(); 
          returnreasonRec = new GEMS_Return_Reason__c(recordTypeId =recordTypeId);
          statusPickList = getMyOptions(); 
          returnReasonList = [SELECT ID, Name,SBC_BB_Form__c,Process_Name__c, GEMS_Type__c, GEMS_Sub_Type__c, Return_Reason__c, GEMS_Comments__c FROM GEMS_Return_Reason__c where SBC_BB_Form__c=: objectId]; 
        }
    }
    
    public string recordTypeId{get;set;}
    public List<GEMS_Return_Reason__c> returnReasonList{get;set;}
    public List<SelectOption> statusPickList{get;set;}
    public GEMS_Return_Reason__c returnreasonRec{set;get;}
    public Boolean displayReturnReason{get;set;}
    public String selectedStatus{get;set;}
    public Id objectId{get;set;}
    public string objectName{get;set;}
    
    
    public List<SelectOption> getMyOptions()
    {    
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--Select--'));
        options.add(new SelectOption('Return', 'Return'));      
        return options;
    }
    
    public void addRow()
    {
        returnReasonList.add(returnreasonRec);
        if(objectName == 'GEMS_SBC_BB_Form__c'){       
           returnreasonRec = new GEMS_Return_Reason__c(SBC_BB_Form__c= objectId,recordTypeId =recordTypeId);
        }
    }
    
    public void showReturnReasonBlock()
    {
        if(selectedStatus == 'Return')
        {
            displayReturnReason = true;        
        }
        else if(selectedStatus == 'Routed In Error') 
        {
            displayReturnReason = false;
        }
        else
        {
            displayReturnReason = false;
        }     
        System.debug('-----called---');
    }
    
    public pagereference saveStatus() 
    {
        List<GEMS_Return_Reason__c> returnReasonsToBeInserted = new List<GEMS_Return_Reason__c>();
        try{
            if(objectId!= null )
            {
                for(GEMS_Return_Reason__c rejectReason : returnReasonList)
                {
                    if(rejectReason.id == null) 
                    {
                        GEMS_Return_Reason__c rrr = new GEMS_Return_Reason__c(GEMS_Sub_Type__c = rejectReason.GEMS_Sub_Type__c,Process_Name__c = rejectReason.Process_Name__c,GEMS_Type__c = rejectReason.GEMS_Type__c,Return_Reason__c = rejectReason.Return_Reason__c, SBC_BB_Form__c=objectId);    
                        returnReasonsToBeInserted .add(rrr);
                    }
                }
                
                if(returnReasonsToBeInserted .isEmpty())
                {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please add Return Reasons when Return is selected'));
                }
                
                else if(!returnReasonsToBeInserted.isEmpty()) 
                {
                    insert returnReasonsToBeInserted;
                    
                    if(objectName == 'GEMS_SBC_BB_Form__c'){
                        GEMS_SBC_BB_Form__c sbcbb= [select id,form_status__c,ownerId,Submitter__c from GEMS_SBC_BB_Form__c where id =:objectId];
                    
                        if(selectedStatus =='Return') 
                        {
                            sbcbb.form_status__c='Return';
                            sbcbb.Returned_User_ID__c=sbcbb.OwnerId;
                            sbcbb.OwnerId=sbcbb.Submitter__c;    
                            update sbcbb;
                        }
                    }
                }           
            }
        }
        catch(Exception ex){
          CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'Case', null, 'GEMS_ReturnStatusComponentController.saveStatus()','High');              
        }   
        System.debug('----End saveStatusMethod-----');
        if(returnReasonsToBeInserted.isEmpty())
        {
            return null;
        }
        else if(!returnReasonsToBeInserted.isEmpty())
        {
            return new Pagereference('/'+objectId);
        }
        return null;
    }
    
    public void setSelectedStatus() 
    {
        
    }
    
    public pagereference cancel()
    {
        return new Pagereference('/'+objectId);
    }
}