objects/Group_Section__c.object
<CustomObject>
    <description>Group Section information associated to a Group Account will be stored using this object</description>
    <fields>
        <fullName>Benefit_Agreement_Cancel_Date__c</fullName>
        <label>Benefit Agreement Cancel Date</label>
        <type>Date</type>
    </fields>
    <label>Group Section</label>
    <nameField>
        <displayFormat>GS-{000000}</displayFormat>
        <label>Group Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Group_Section__c.object
<CustomObject>
    <fields>
        <fullName>BEN_AGMT_renewal_date__c</fullName>
        <label>BEN_AGMT renewal date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Benefit_Agreement_Cancel_Date__c</fullName>
        <label>Benefit Agreement Cancel Date</label>
        <type>Date</type>
    </fields>
    <label>Opportunity Group Section</label>
    <nameField>
        <label>Opportunity Group Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Group Section</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Plan_Rate__c.object
<CustomObject>
    <description>This object contains details about opportunity plan Rates.</description>
    <fields>
        <fullName>Benefit_Agreement_Cancel_Date__c</fullName>
        <label>Benefit Agreement Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Canceled_Date_Copy__c</fullName>
        <description>Created for Audit Purposes only</description>
        <label>Canceled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Section</label>
        <referenceTo>SGR_Opportunity_Group_Section__c</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_Date_Copy__c</fullName>
        <description>Created for Audit Purposes only</description>
        <label>Sold Date</label>
        <type>Date</type>
    </fields>
    <label>Opportunity Plan Rate</label>
    <nameField>
        <label>Opportunity Plan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SGR_UpdateOpprPlnRteSldOrCanlDt_Test.cls
@isTest
public class SGR_UpdateOpprPlnRteSldOrCanlDt_Test {

    public testmethod static void updateSoldOrCancelDateTest(){
        
        list<SGR_Opportunity_Group_Section__c>  OppGSold = new list<SGR_Opportunity_Group_Section__c>();
        list<SGR_Opportunity_Group_Section__c>  OppGSnew = new list<SGR_Opportunity_Group_Section__c>();
        Test.startTest();
           SGR_Opportunity_Group_Section__c OppGS= new SGR_Opportunity_Group_Section__c();
        	OppGS.Name='GS1';
        	OppGS.Benefit_Agreement_Cancel_Date__c= System.today();
            OppGS.BEN_AGMT_renewal_date__c=system.today();
            OppGSold.add(OppGS);
        	insert OppGS;
        	
        	SGR_Opportunity_Plan_Rate__c OppPlan= new SGR_Opportunity_Plan_Rate__c();
        	OppPlan.name='OppPlan';
        	OppPlan.Group_Section__c=OppGS.Id;        	
        	Insert OppPlan;
        
        	OppGS.Benefit_Agreement_Cancel_Date__c= System.today()+1;
        	OppGS.BEN_AGMT_renewal_date__c=system.today()+1;
        	OppGSnew.add(OppGS);
        	update OppGS;
        	
        	list<SGR_Opportunity_Plan_Rate__c> OppPlanCheck=[SELECT id, Name, Canceled_Date_Copy__c, Sold_Date_Copy__c,Group_Section__c FROM SGR_Opportunity_Plan_Rate__c WHERE Group_Section__c=:OppGS.Id];
        	System.assertEquals(OppPlanCheck[0].Canceled_Date_Copy__c, system.today()+1);
        	update OppPlan;
        	
      		Delete OppGS;
        	Delete OppPlan;
        	
          	Test.stopTest();
    }
}