objects/Integration_Log_Switcher__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>turn on or off to log transaction request /response  to Fw_log_status__c ( integration log status)</description>
    <label>Integration Log Switcher</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Plan_Change_Needed__c</fullName>
        <label>Plan Change Needed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>SGR_Production_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>SGR Oppurtunity Record Type</description>
        <label>SGR Production Opportunity</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SGR_EmailDL__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>TaskName__c</fullName>
        <label>Task Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>SGR_EmailDL</label>
</CustomObject>

classes/SGR_BSTAR_OppValidatorBatch.cls
/**************************************************************************************
  Apex Class Name     : SGR_BSTAR_TransferBatch  
  Version             			: 1.0
  Function            		: This class is used to make calls to BlueSTAR transfer callout method
  Modification Log    	:
* Developer: Shankar  Date: 12/20/2018                   Initial version
* ----------------------------------------------------------------------------               
* Shankar                  09/05/2018                Original Version
*************************************************************************************/
global  class SGR_BSTAR_OppValidatorBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
	public static Integration_Log_Switcher__c bStarTransferLog = Integration_Log_Switcher__c.getInstance('BlueSTAR Transfer Service');
	Set<Id> oppIds;
	Id renBatchRecId;
	public List<String> recipientEmailAddr;
	public Set<Id> validOppIds; 
	Id sgrProdOppRecTypeId; 
	
	global SGR_BSTAR_OppValidatorBatch(Set<Id> oppIds, Id renBatchRecId) {
		this.oppIds = oppIds;
		this.renBatchRecId = renBatchRecId;
		this.sgrProdOppRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Production_Opportunity').getRecordTypeId();
		String className = 'SGR_BSTAR_TransferBatch';	
    	List<SGR_EmailDL__c> dlSettingVals = new List<SGR_EmailDL__c>();

		recipientEmailAddr = new List<String>();    	
		validOppIds = new Set<Id>();
		if (!Test.isRunningTest()) {
			dlSettingVals = SGR_EmailDL__c.getAll().values();
			if (null != dlSettingVals) {
				for (SGR_EmailDL__c dl: dlSettingVals) {
					if (dl.TaskName__c == className) {
						recipientEmailAddr.add(dl.To__c);
					}
				}
			}
		}    	
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		
		
		String query = 'Select Id ' +                        			
                      			 'FROM Opportunity ' +
                     			 'WHERE Id IN :oppIds AND Rating_Status__c = \'Sold\' AND (Plan_Change_Needed__c = \'\' OR Plan_Change_Needed__c = \'Complete\')';
		System.debug('Opp query::'+ query);                     			        
        return Database.getQueryLocator(query);        
    }
    
	global void execute(Database.BatchableContext bc, List<Opportunity> scope) {
		String body, subject;
		// Validate opportunities using eligibility rule validation helper
		SGR_BRValidationManager validator = new SGR_BRValidationManager('SGR_BlueSTAREligibilityRules');
		Set<Id> oppIds = new Set<Id>();			   
		for (Opportunity o: scope) {
			oppIds.add(o.Id);
		} 	
		if (!Test.isRunningTest()) {
			validOppIds = validator.validate(oppIds);
		}
		
		if (null == validOppIds || validOppIds.isEmpty()) {
			body = 'No valid opportunities found after validation. Check BR Validation logs.<br/>Regards,<br/>SGR BlueSTAR Transfer Batch';
			subject = 'SGR BlueSTAR Transfer Batch  job failed';
			if (!Test.isRunningTest()) {
				EmailUtility.circulateEmail(recipientEmailAddr, subject, body);
			}
			SGR_Exception ex = new SGR_Exception('No valid opportunities found after validation. Check BR Validation logs');
			CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'SGR_BSTAR_TransferBatch', null, 'SGR_BSTAR_TransferBatch.execute', 'High');
			return;
		}
	}

  	
  	global void finish(Database.BatchableContext bc) {
				String body, subject;
				/*body = 'BlueSTAR transfer batch completed. Check BR Validation Log & Error log to see if any error occured.<br/>Regards,<br/>SGR BlueSTAR Transfer Batch';
				subject = 'BlueSTAR transfer batch job completed';
				EmailUtility.circulateEmail(recipientEmailAddr, subject, body);
				*/
				if (!validOppIds.isEmpty()) {
                    System.enqueueJob(new SGR_BSTAR_TransferBatch(validOppIds));			    
				} else {

					if (!Test.isRunningTest()) {
						body = 'No valid opportunities found after validation. Check BR Validation logs.<br/>Regards,<br/>SGR BlueSTAR Transfer Batch';
						subject = 'SGR BlueSTAR Transfer Batch  job failed';
						EmailUtility.circulateEmail(recipientEmailAddr, subject, body);
					}
					SGR_Exception ex = new SGR_Exception('No valid opportunities found after validation. Check BR Validation logs');
					CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'SGR_BSTAR_TransferBatch', null, 'SGR_BSTAR_TransferBatch.execute', 'High');
				}				
  	}
  	
  	global void execute(System.SchedulableContext sc) {
		Database.executeBatch(new SGR_BSTAR_OppValidatorBatch(this.oppIds, this.renBatchRecId));
  	}
    
}