objects/items_SharePoint__x.object
<CustomObject>
    <externalDataSource>SharePoint</externalDataSource>
    <externalName>items_SharePoint</externalName>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <externalDeveloperName>SalesForceId</externalDeveloperName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SharePoint Documents</relationshipLabel>
        <relationshipName>items_Sharepoint</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <externalDeveloperName>SalesForceId</externalDeveloperName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>items_Sharepoint</relationshipLabel>
        <relationshipName>items_Sharepoint</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsFolder__c</fullName>
        <defaultValue>false</defaultValue>
        <externalDeveloperName>IsFolder</externalDeveloperName>
        <label>IsFolder</label>
        <readOnlyProxy>true</readOnlyProxy>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <externalDeveloperName>SalesForceId</externalDeveloperName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>SharePoint Documents</relationshipLabel>
        <relationshipName>items_Sharepoint</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>items_SharePoint</label>
    <pluralLabel>items_SharePoint</pluralLabel>
</CustomObject>

classes/ItemsSharePointDAO.cls
public class ItemsSharePointDAO implements IItemsSharePointDAO{
    public interface IItemsSharePointDAO{
        Integer getAccountsCountById(Id accountId);
        Integer getOpportunitiesCountById(Id oppId);
        Integer getCasesCountById(Id oppId);
        List<items_Sharepoint__x> getItemizedSharePointRecordsDynamically(String soql);
    }

    public Integer getAccountsCountById(Id accountId) {
        return [SELECT count() FROM items_Sharepoint__x WHERE AccountId__c = :accountId AND isFolder__c = false];
    }

    public Integer getOpportunitiesCountById(Id oppId){
        return [SELECT count() FROM items_Sharepoint__x WHERE OpportunityId__c = :oppId AND isFolder__c = false];
    }

    public Integer getCasesCountById(Id caseId){
        return [SELECT count() FROM items_Sharepoint__x WHERE CaseId__c = :caseId AND isFolder__c = false];
    }

    public List<items_Sharepoint__x> getItemizedSharePointRecordsDynamically(String soql){
        return Database.query(soql);
    }
}