objects/Market_Segment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Segment Picklist values from Account</description>
    <label>Market Segment</label>
</CustomObject>

objects/Plan__c.object
<CustomObject>
    <description>To capture all the plans related to products - Loaded from BlueStar</description>
    <fields>
        <fullName>Line_Of_Business__c</fullName>
        <label>Line Of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>HDL</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Plan_Number__c</fullName>
        <description>Marketing Plan number of the plan</description>
        <label>Marketing Plan Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Plan_Age_Rate_Detail__c.object
<CustomObject>
    <fields>
        <fullName>SGR_Plan_Id__c</fullName>
        <label>SGR Plan Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SGR Plan Age Rate Detail</label>
    <nameField>
        <displayFormat>ARD-{0000000}</displayFormat>
        <label>SGR Plan Rate Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SGR Plan Age Rate Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_URE_Age_Rate_Driver__c.object
<CustomObject>
    <fields>
        <fullName>Corporate_Entity_Code__c</fullName>
        <label>Corporate Entity Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <label>FIPS Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Of_Business__c</fullName>
        <label>Line Of Business</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Effective_Date__c</fullName>
        <label>Rate Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Plan_Id__c</fullName>
        <label>Plan Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Age Rate Driver</label>
    <nameField>
        <label>URE_Age_Rate_Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Age Rate Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SGR_GenerateAgeRateTablesBatchTest.cls
@isTest 
public class SGR_GenerateAgeRateTablesBatchTest
{
    @testSetUp
	static void testData(){
   	
		List<SGR_URE_Age_Rate_Driver__c> lstAgeRateDrivers= new List<SGR_URE_Age_Rate_Driver__c>();
		List<Plan__c> pList = new List<Plan__c>();
        
        for(Integer i=0 ;i <2;i++){
			Plan__c p = new Plan__c();
			p.Marketing_Plan_Number__c = 'Plan00'+i;
			if(i/2==0){
				p.Line_Of_Business__c = 'D';
			}else{
				p.Line_Of_Business__c = 'H';
			}
			pList.add(p);
		}
         insert pList;
        
        for(Integer i=0 ;i <100;i++)
        {
            SGR_URE_Age_Rate_Driver__c driver = new SGR_URE_Age_Rate_Driver__c();
            driver.Name ='Name'+i;
            Id planId = null;
            if (i/2==0) {
                planId = pList.get(0).Id;
            } else {
                planId = pList.get(1).Id;
            }
			driver.SGR_Plan_Id__c =planId;
			driver.FIPS_Code__c ='CC'+i;
			driver.Corporate_Entity_Code__c ='CEC'+i;
			driver.Rate_Effective_Date__c =System.today();
			driver.Market_Segment__c ='SG';
            lstAgeRateDrivers.add(driver);
        }
        		
        insert lstAgeRateDrivers;
		
		
	}
	static testMethod void testGenerateDentalAgeRateTables() 
    {	 
       
        Test.startTest();
            SGR_GenerateAgeRateTablesBatch obj = new SGR_GenerateAgeRateTablesBatch(System.today(),'Dental',1,'RenewalsSalesForce','SG',false);
            Database.executeBatch(obj,200);
        Test.stopTest();
                List<SGR_Plan_Age_Rate_Detail__c> ards = [Select Id from SGR_Plan_Age_Rate_Detail__c];
        System.assertNotEquals(null, ards);
    }
	static testMethod void testGenerateNonDentalAgeRateTables() 
    {	 
        Test.startTest();
            SGR_GenerateAgeRateTablesBatch obj = new SGR_GenerateAgeRateTablesBatch(System.today(),'NonDental',1,'RenewalsSalesForce','SG',false);
            Database.executeBatch(obj,200);
        Test.stopTest();
                List<SGR_Plan_Age_Rate_Detail__c> ards = [Select Id from SGR_Plan_Age_Rate_Detail__c];
        System.assertNotEquals(null, ards);
    } 
}