objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment for the opportunity</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <label>Batch ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Tier_Billing__c</fullName>
        <label>Current Tier/Billing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Age Rated</fullName>
                </value>
                <value>
                    <fullName>Composite Rated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_Notes__c</fullName>
        <formula>IF( Total_Number_of_Notes__c &gt; 0, &apos;Y&apos;, &apos;N&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notes?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Opportunity_Auto_Number__c</fullName>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Opportunity Auto Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>SGR_Workflow_Activity__c</fullName>
        <label>Workflow Activity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
                <value>
                    <fullName>UW Review - Validation Errors</fullName>
                </value>
                <value>
                    <fullName>Actuarial Gate</fullName>
                </value>
                <value>
                    <fullName>Awaiting BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>Plan Change in Progress</fullName>
                </value>
                <value>
                    <fullName>Pend in Progress</fullName>
                </value>
                <value>
                    <fullName>Not Eligible to be Transferred</fullName>
                </value>
                <value>
                    <fullName>UW Review</fullName>
                </value>
                <value>
                    <fullName>IT Review - Rating Failed</fullName>
                </value>
                <value>
                    <fullName>Underwriting Review</fullName>
                </value>
                <value>
                    <fullName>Actuarial Release</fullName>
                </value>
                <value>
                    <fullName>Ready for Distribution</fullName>
                </value>
                <value>
                    <fullName>Group Verifier Review - BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>BlueStar Transfer Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sgrAccountHoldReason__c</fullName>
        <formula>IF(INCLUDES(Account.SGR_Hold_Reason__c ,&apos;Wage &amp; Tax Audit&apos;),&apos;Wage &amp; Tax Audit; &apos;,NULL)+&apos;&apos; +
IF(INCLUDES(Account.SGR_Hold_Reason__c ,&apos;1st Year Renewal&apos;),&apos;1st Year Renewal; &apos;,NULL)+&apos;&apos;+
IF(INCLUDES(Account.SGR_Hold_Reason__c ,&apos;Block Acquisition&apos;),&apos;Block Acquisition; &apos;,NULL)+&apos;&apos;+
IF(INCLUDES(Account.SGR_Hold_Reason__c ,&apos;Special Adjustments&apos;),&apos;Special Adjustments; &apos;,NULL)+&apos;&apos; +
IF(INCLUDES(Account.SGR_Hold_Reason__c ,&apos;Miscellaneous&apos;),&apos;Miscellaneous; &apos;,NULL)+&apos;&apos; +
IF(INCLUDES(Account.SGR_Hold_Reason__c ,&apos;Market Segment Verification&apos;),&apos;Market Segment Verification; &apos;,NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Hold Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestClass.cls
public class TestClass {
    @AuraEnabled
    public static Opportunity TestClass(String oppId){
       
       List<opportunity> lstopp = [SELECT Id,AccountId,name,Rating_Status__c,sgrAccountHoldReason__c,SGR_Workflow_Activity__c,Has_Notes__c,RecordType.Name,HCSC_Division__c,Account_Market_Segment__c,External_Id__c,Current_Tier_Billing__c,SGR_Opportunity_Auto_Number__c,Renewal_Date__c,Batch_Id__c,Funding_Type__c FROM opportunity where id =:oppId];
       return lstopp[0];

}
}