objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To retrieve days to submit for each division for calcuating Submit_Date__c on opportunity</description>
    <label>SGR Days to Submit</label>
</CustomObject>

objects/Plan__c.object
<CustomObject>
    <description>To capture all the plans related to products - Loaded from BlueStar</description>
    <fields>
        <fullName>Line_Of_Business__c</fullName>
        <label>Line Of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>HDL</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Plan_Number__c</fullName>
        <description>Marketing Plan number of the plan</description>
        <label>Marketing Plan Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Premium__c</fullName>
        <formula>Value(&quot;SGR_Opportunity_Plan_Rate__r.Member_Premium__c&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Member Premium</label>
        <precision>18</precision>
        <scale>16</scale>
        <type>Currency</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Plan_Composite_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Plan_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Plan Rate</label>
        <referenceTo>SGR_Opportunity_Plan_Rate__c</referenceTo>
        <relationshipLabel>Opportunity Plan Composite Rate</relationshipLabel>
        <relationshipName>Opportunity_Plan_Composite_Rate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tier_Code__c</fullName>
        <label>Tier Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EO</fullName>
                </value>
                <value>
                    <fullName>EC</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>EF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Plan Composite Rate</label>
    <nameField>
        <label>Opportunity Plan Composite Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Composite Rate</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Plan_Rate__c.object
<CustomObject>
    <description>This object contains details about opportunity plan Rates.</description>
    <fields>
        <fullName>ACA_Fee__c</fullName>
        <label>ACA Fee</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Member_Premium__c</fullName>
        <label>Member Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type_Code__c</fullName>
        <description>STN or AGE for standard rate and age rate</description>
        <label>Rate Type Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Alternate</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                    <isActive>false</isActive>
                    <label>Alternative</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Plan Rate</label>
    <nameField>
        <label>Opportunity Plan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SGR_URE_OpptyRatingComputationBatch.cls
/*************************************************************************************************
	Class Name: SGR_URE_OpptyRatingComputationBatch.cls
	Created By: Cesar Murcia
	Description: Batch Class to process the URE Response to compute plan composite rates and 
				 member composite/age rates
**************************************************************************************************/
public class SGR_URE_OpptyRatingComputationBatch implements Database.Batchable<sObject>, Database.Stateful {

		List<Id> opportunityIds;
	    Set<String> planIds;
	    String planType;
		List<SGR_URE_GetRatingsResponse> ureResponse;
		String invalidParamName = '';

		String query = 'SELECT 	 Id, Plan__c, Plan__r.Marketing_Plan_Number__c, Plan__r.Line_Of_Business__c, Opportunity__c, Opportunity__r.HCSC_Division__c, ' + 
								' Opportunity__r.Renewal_Date__c, ACA_Fee__c, Member_Premium__c, Rate_Type_Code__c ' +
								' ,(SELECT Id, Tier_Code__c ' +
						 		' FROM Opportunity_Plan_Composite_Rate__r ' +
						 		' LIMIT 200) ' +
								' FROM 	SGR_Opportunity_Plan_Rate__c ' +
								' WHERE 	Opportunity__c IN :opportunityIds AND ' +
								' Plan__r.Marketing_Plan_Number__c IN : planIds AND ' +
								' Type__c = :planType ';

		public SGR_URE_OpptyRatingComputationBatch(List<SGR_URE_GetRatingsResponse> ureResponse, List<Id> opportunityIds, Set<String> planIds, String planType) 
		{
			if(ureResponse == null)
				{invalidParamName = 'ureResponse';}
			
			if(opportunityIds == null)
				{invalidParamName = String.IsEmpty(invalidParamName) ? 'opportunityIds' : invalidParamName + ', opportunityIds' ;}

			if(planIds == null)
				{invalidParamName = 'planIds';}

			if(planType == null)
				{invalidParamName = 'planType';}
			
			if(!String.IsEmpty(invalidParamName)) {
				NUllPointerException invalidParamEx = new NUllPointerException();
				invalidParamEx.setMessage(String.format('Parameters cannot be null : {0}', new String[] {invalidParamName}));
				throw invalidParamEx;
			}

			this.opportunityIds = opportunityIds;
			this.planIds = planIds; 
			this.planType = planType;
			this.ureResponse = ureResponse;
		}

		public Database.QueryLocator start( Database.BatchableContext bc) {  			
			return Database.getQueryLocator(this.query);
		}

		public void execute(Database.BatchableContext BC, List<SGR_Opportunity_Plan_Rate__c> scope) { 
			try {
				SGR_URE_OpptyCompAndAgeRatingUtility.OpportunityCompositeRateModel opptyRateModel = SGR_URE_OpptyCompAndAgeRatingUtility.ComputeCompositeAndAgeRates(this.ureResponse, scope, this.planType);
				System.debug('SGR_URE_OpptyRatingComputationBatch :: Inserting rates for Plan Rate Type: ' + this.planType);
				upsert opptyRateModel.opptyPlanCompositeRates;
				upsert opptyRateModel.opptyPlanRates;
				upsert opptyRateModel.memberRates;
				if(this.planType == SGR_URE_RatingOption.RENEWING_PLAN_TYPE)
					update opptyRateModel.opptyToUpdateList;
			}
			catch(Exception ex){
				CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'SGR_URE_OpptyRatingComputationBatch', 
							null, 'SGR_URE_OpptyRatingComputationBatch.execute', 'High');
			}

		}

		public void finish(Database.BatchableContext BC) { 
			/* compute Alternate plans */
			if(this.planType == SGR_URE_RatingOption.RENEWING_PLAN_TYPE) {
				SGR_URE_OpptyRatingComputationBatch opptyRatingAlternate = new SGR_URE_OpptyRatingComputationBatch(this.ureResponse, this.opportunityIds, this.planIds, SGR_URE_RatingOption.ALTERNATE_PLAN_TYPE); 
				Database.executeBatch(opptyRatingAlternate); 
			}
			/* compute Option 2, 3 for Renewal */
			if(this.planType == SGR_URE_RatingOption.ALTERNATE_PLAN_TYPE) {
				/* Compute Option Plans for renewing */ 
				SGR_URE_OppRatingOpt2And3CmptBatch opptyRatingRenewing = new SGR_URE_OppRatingOpt2And3CmptBatch(this.ureResponse, this.opportunityIds, this.planIds, SGR_URE_RatingOption.RENEWING_PLAN_TYPE);
				Database.executeBatch(opptyRatingRenewing); 
			}
		}
}