objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <label>Batch ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SGR_Business_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Proposed_wording_fail__c</fullName>
        <label>Proposed wording fail</label>
        <length>512</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Proposed_wording_pass__c</fullName>
        <label>Proposed wording pass</label>
        <length>512</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rule_Code__c</fullName>
        <label>Rule Code</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Business Rule</label>
    <nameField>
        <label>Business Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Benefit_Agreement__c.object
<CustomObject>
    <description>This object is connected to Opportunity object using a look up field (Opportunity).</description>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Benefit Agreements</relationshipLabel>
        <relationshipName>Opportunity_Benefit_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Benefit Agreement</label>
    <nameField>
        <label>Opportunity Benefit Agreement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Benefit Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Census__c.object
<CustomObject>
    <description>This object is used  for</description>
    <fields>
        <fullName>Opportunity_Group_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Group Section</label>
        <referenceTo>SGR_Opportunity_Group_Section__c</referenceTo>
        <relationshipLabel>Opportunity Censuses</relationshipLabel>
        <relationshipName>Opportunity_Censuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is  look up  to  Opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Census</relationshipLabel>
        <relationshipName>Opportunity_Census</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Census</label>
    <nameField>
        <label>Opportunity Census Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Censuses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Group_Section__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Agreement</label>
        <referenceTo>SGR_Opportunity_Benefit_Agreement__c</referenceTo>
        <relationshipLabel>Opportunity Group Section</relationshipLabel>
        <relationshipName>Opportunity_Group_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Group Section</relationshipLabel>
        <relationshipName>Opportunity_Group_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Opportunity Group Section</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Group Section</label>
    <nameField>
        <label>Opportunity Group Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Group Section</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Member_Benefits__c.object
<CustomObject>
    <description>This object acts as a junction object between the Opportunity Group Section and Opportunity Census objects</description>
    <fields>
        <fullName>Opportunity_Census__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Census</label>
        <referenceTo>SGR_Opportunity_Census__c</referenceTo>
        <relationshipLabel>Opportunity Member Benefits</relationshipLabel>
        <relationshipName>Opportunity_Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Group_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Group Section</label>
        <referenceTo>SGR_Opportunity_Group_Section__c</referenceTo>
        <relationshipLabel>Opportunity Member Benefits</relationshipLabel>
        <relationshipName>Opportunity_Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Member Benefits</relationshipLabel>
        <relationshipName>Opportunity_Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Member Benefits</label>
    <nameField>
        <label>Opportunity Member Benefits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Member Benefits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGR_Renewal_Batch_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>BatchId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BatchId</label>
        <referenceTo>SGRRenewalBatch__c</referenceTo>
        <relationshipName>SGR_Renewal_Batch_Opptys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <label>Batch ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SGR_Renewal_Batch_Opptys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal Batch Opportunity</label>
    <nameField>
        <label>SGR_Renewal Batch Oppty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Renewal Batch Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Prototype_SGR_ValidationHelper.cls
public class Prototype_SGR_ValidationHelper {
    
    private List<Prototype_OpportunityModel> opptyModelList { get; set; }
    private List<Opportunity> oppList {get; set;}
    
    public Prototype_SGR_ValidationHelper(List<Opportunity> opps, String BatchId)
    { 
        //callingMethods(opps,BatchId);
        
    }
    //Code added to Test BR Frame work
    public Prototype_SGR_ValidationHelper(List<Opportunity> opps, String BatchId, Boolean isBatch) 
    { 
        if(isBatch && String.isBlank(BatchId)) {
            // throw an error. 
        }
        
        oppList = opps;
        
        
    }
    
    public void StartValidation() {
        opptyModelList.addAll(GetOpportunityModels(oppList));
        Prototype_ValidationRuleValidator validator = new Prototype_ValidationRuleValidator(opptyModelList);
    }
    
    private void SetUpValidationHelper(List<Opportunity> opptyList) {
        opptyModelList = GetOpportunityModels(opptyList);
    }
    
    
    private List<Prototype_OpportunityModel> GetOpportunityModels(List<Opportunity> opportunities) {
        
        List<String> OpptyIdList = new List<String>(); 
        List<Prototype_OpportunityModel> OpptyModelList = new List<Prototype_OpportunityModel>();
        
        //for(String Id: )
        
        /* Child queries */
        /* Benefits aggrements */
        List<SGR_Opportunity_Benefit_Agreement__c> BAList = [SELECT Id
                                                             FROM SGR_Opportunity_Benefit_Agreement__c 
                                                             WHERE Opportunity__c IN :OpptyIdList  LIMIT 2000];
        /* Group Sections */
         List<SGR_Opportunity_Group_Section__c> GSList = [SELECT Id 
                                                          FROM SGR_Opportunity_Group_Section__c 
                                                          WHERE Opportunity__c IN :OpptyIdList LIMIT 2000];
        /* Census */
         List<SGR_Opportunity_Census__c> CensusList = [SELECT Id 
                                                       FROM SGR_Opportunity_Census__c 
                                                       WHERE Opportunity__c IN :OpptyIdList LIMIT 2000];
        /* Member Benefits */
         /*List<SGR_Opportunity_Member_Benefits__c> MBList = [SELECT Id 
                                                            FROM SGR_Opportunity_Member_Benefits__c 
                                                            WHERE Opportunity__c IN :OpptyIdList LIMIT 2000];*/
        
        
        /* Create a map Opportunity/ child ojects*/
        
        /* Create a list of opportunity models */
        
        
        return OpptyModelList;
        
    }
    

    
    public static String callingMethods1(List<Opportunity> opps, String BatchId) {
        String msg;
        system.debug('******** inside Method*****');
        map<String,SGR_Business_Rule__c> sbrmap = new  map<String,SGR_Business_Rule__c>();
        List<SGR_Business_Rule__c> br=[select id,Rule_Code__c,Proposed_wording_fail__c,Proposed_wording_pass__c from SGR_Business_Rule__c ];
        for (SGR_Business_Rule__c sa:br){
            sbrmap.put(sa.Rule_Code__c,sa);
        }
        
        map<id,List<SGR_Renewal_Batch_Oppty__c>>oppsrbop = new map<id,List<SGR_Renewal_Batch_Oppty__c>>();
        map<id,List<SGR_Opportunity_Group_Section__c>>oppsgrogs1 = new map<id,List<SGR_Opportunity_Group_Section__c>>();  
        map<id,List<SGR_Opportunity_Benefit_Agreement__c>> oppsgrobamap = new map<id,List<SGR_Opportunity_Benefit_Agreement__c>>();  
        map<id,List<SGR_Opportunity_Census__c>> oppsgrogs = new map<id,List<SGR_Opportunity_Census__c>>();
        map<Id, List<SGR_Opportunity_Member_Benefits__c>> benefits = new map<Id, List<SGR_Opportunity_Member_Benefits__c>>();
        List<SGR_Opportunity_Census__c> optyCens = new List<SGR_Opportunity_Census__c>();
        List<opportunity> lstopp = [SELECT Id, name, Batch_Id__c,Funding_Type__c, (SELECT Id, Name ,Batch_Id__c from SGR_Renewal_Batch_Opptys__r),(SELECT Id, Name,Status__c FROM Opportunity_Benefit_Agreements__r),(SELECT id,Name,Account__c,Opportunity__c,Relationship_Code__c,Member_Cancel_Date__c,Membership_Number__c,Member_Effective_Date__c,Relationship__c, Subscriber_number__c, Date_of_Birth__c FROM Opportunity_Census__r),(SELECT Id, Name,Benefit_Agreement_Cancel_Date__c FROM Opportunity_Group_Section__r) FROM opportunity where (id IN:opps AND Batch_Id__c=:BatchId)];
        
        //Keeping all the child objects related opportunity in a Map
        for(Opportunity os :lstopp) {
            
             oppsrbop.put(os.id,os.SGR_Renewal_Batch_Opptys__r);
             //SGR_Opportunity_Census__c opCen = os.Opportunity_Census__r;
             oppsgrobamap.put(os.id, os.Opportunity_Benefit_Agreements__r);
             oppsgrogs.put(os.id,os.Opportunity_Census__r);
             oppsgrogs1.put(os.id,os.Opportunity_Group_Section__r);
             optyCens = os.Opportunity_Census__r;
        }
        List<SGR_Opportunity_Census__c> memBenefits = new List<SGR_Opportunity_Census__c>();
        
        if (optyCens.size() > 0) {
            memBenefits = [Select Id, (Select Id, Name, Member_Policy_Tier__c, Subscriber_Number__c
                                                                   From Opportunity_Member_Benefits__r)
                                                       from SGR_Opportunity_Census__c where Id IN :optyCens];
            for (SGR_Opportunity_Census__c oc : memBenefits) {
                benefits.put(oc.Id, oc.Opportunity_Member_Benefits__r);
            }
        }
        
        system.debug('==========='+oppsgrobamap);
        system.debug('==========='+oppsgrogs);
        system.debug('============'+oppsgrogs1);
        
        System.debug('Opportunities: ' + opps);
        
        List<SGRRenewalBatch__c> RenewBatchId = new List<SGRRenewalBatch__c>();
        RenewBatchId=[select Id,BatchID__c from SGRRenewalBatch__c where BatchID__c =:BatchId];
        return msg;
    }   

}