objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Forecast_Segment__c</fullName>
        <description>The forecast segment value indicator. This is based off of details on the opportunity, such as District or Market Segment.</description>
        <label>Forecast Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENA</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Workflow_Activity__c</fullName>
        <label>Workflow Activity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
                <value>
                    <fullName>UW Review - Validation Errors</fullName>
                </value>
                <value>
                    <fullName>Actuarial Gate</fullName>
                </value>
                <value>
                    <fullName>Awaiting BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>Plan Change in Progress</fullName>
                </value>
                <value>
                    <fullName>Pend in Progress</fullName>
                </value>
                <value>
                    <fullName>Not Eligible to be Transferred</fullName>
                </value>
                <value>
                    <fullName>UW Review</fullName>
                </value>
                <value>
                    <fullName>IT Review - Rating Failed</fullName>
                </value>
                <value>
                    <fullName>Underwriting Review</fullName>
                </value>
                <value>
                    <fullName>Actuarial Release</fullName>
                </value>
                <value>
                    <fullName>Ready for Distribution</fullName>
                </value>
                <value>
                    <fullName>Group Verifier Review - BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>BlueStar Transfer Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workflow_System_Status__c</fullName>
        <label>Workflow System Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to Fetch Mapped Plans</fullName>
                    <default>true</default>
                    <label>Ready to Fetch Mapped Plans</label>
                </value>
                <value>
                    <fullName>Ready to Validate</fullName>
                </value>
                <value>
                    <fullName>Failed Validation</fullName>
                </value>
                <value>
                    <fullName>Ready to Rate</fullName>
                </value>
                <value>
                    <fullName>Ready For Gate Processing</fullName>
                </value>
                <value>
                    <fullName>Ready to Send to B-Engaged</fullName>
                </value>
                <value>
                    <fullName>Ready to Send to BlueSTAR</fullName>
                </value>
                <value>
                    <fullName>Not Eligible to Send to BlueSTAR</fullName>
                </value>
                <value>
                    <fullName>Workflow Completed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Review Task Completion</fullName>
                </value>
                <value>
                    <fullName>Awaiting Hold Task Completion</fullName>
                </value>
                <value>
                    <fullName>Gate Processing Completed</fullName>
                </value>
                <value>
                    <fullName>Failed Rating</fullName>
                </value>
                <value>
                    <fullName>Ready for BlueSTAR Initiation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Plan_Rate__c.object
<CustomObject>
    <description>This object contains details about opportunity plan Rates.</description>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Alternate</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                    <isActive>false</isActive>
                    <label>Alternative</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Plan Rate</label>
    <nameField>
        <label>Opportunity Plan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGRRenewalBatch__c.object
<CustomObject>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Renewals</fullName>
                    <default>true</default>
                    <label>Renewals</label>
                </value>
                <value>
                    <fullName>BlueSTAR Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FundingType__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MarketSegment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Effective_date__c</fullName>
        <label>Renewal Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Renewal Batch</label>
    <nameField>
        <label>SGRRenewalBatch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Renewal Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SGR_BlueSTAROptysPost.cls
public without Sharing class SGR_BlueSTAROptysPost {
@AuraEnabled
    public static string updateBlueSTAROptys(String division, String marketSegment, String fundingType, String renewaldate, Datetime scheduleDate){
        String value = '';
        Boolean isSuccess = false;
        List<SGRRenewalBatch__c> batchList;
        try{
            system.debug('++++String renewaldate--'+renewaldate);
            Date renewEffDate = Date.valueOf(renewaldate);
            system.debug('++++Date renewEffDate--'+renewEffDate);
            Integer renMonth = renewEffDate.month();
            Integer renYear = renewEffDate.month();
            system.debug('++++renMonth--'+renMonth);
            Datetime scheduledDate = scheduleDate;
            system.debug('++++Schduled Date---'+ scheduledDate);
            Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId(); 
            List<String> optyIds = new List<string>();
            //SFDC-16647 Added SOQL Filter on Rating_Status__c=Marketing Released and Workflow_System_Status__c = 'Ready for BlueSTAR Initiation' - Padma
            List<Opportunity> optyList = [select id, Rating_Status__c, SGR_Workflow_Activity__c from Opportunity where HCSC_Division__c = :division 
                                            AND ForeCast_Segment__c='Small Group' 
                                            AND Renewal_Date__c >=:renewEffDate AND Renewal_Date__c <:renewEffDate.addMonths(1) 
                                            AND Funding_Type__c = :fundingType AND Rating_Status__c = 'Marketing Release' AND RecordTypeId = :sgrProdOpp
                                            AND Workflow_System_Status__c =:system.label.UCR_WorkFlow_System_Status_Updated_Value
                                          //'Ready for BlueSTAR Initiation'
                                          ];
            
            system.debug('++++optylist size--'+optyList.size());
            
            if(optyList.size() > 0){
                batchList = [select id from SGRRenewalBatch__c where Renewal_Effective_date__c = :renewEffDate AND 
                                                          Action_Type__c = 'BlueSTAR Transfer' AND Division__c = :division AND FundingType__c = :fundingType AND MarketSegment__c = :marketSegment];// AND Scheduled_Date__c = :scheduleDate];
                system.debug('++++batchList.size()---'+batchList.size());
                if(batchList.size()>0){
                        value = system.label.SGR_BlueStar_Duplicate;
                }
                else{
                    //SFDC-16647 Updated workflow system status update - Padma
                    for(Opportunity opty : optyList){
                        opty.Rating_Status__c = system.label.BlueStar_Rating_Status_Update_Sold;//'Sold';
                        opty.SGR_Workflow_Activity__c = 
                            system.label.BlueStar_Workflow_Activity_Status_Awaiting_BlueSTAR_Transfer;//'Awaiting BlueSTAR Transfer';
                        opty.Workflow_System_Status__c = system.label.BlueSTAR_System_Status_Ready_to_Send_to_BlueSTAR;//'Ready to Send to BlueSTAR';
                        optyIds.add(opty.Id);
                    }
                    update optyList;
                    //SFDC-16647 Updated workflow system status update - Padma 
                    system.debug('++++Opty updated');
                    List<SGR_Opportunity_Plan_Rate__c> optyPlanRate = [select Sold_Date__c, Plan_Status__c from SGR_Opportunity_Plan_Rate__c 
                                                                       where Opportunity__c IN : optyIds 
                                                                       AND Opportunity__r.Rating_status__c = :system.label.BlueStar_Rating_Status_Update_Sold
                                                                       AND Type__c='Renewal'];
                    system.debug('++++optyPlanRate size--'+optyPlanRate.size());
                    if(optyPlanRate.size() > 0){
                        for(SGR_Opportunity_Plan_Rate__c oppPlanRate : optyPlanRate){
                            if(oppPlanRate.Plan_Status__c == 'Renewing' || oppPlanRate.Plan_Status__c == 'Mapped'){
                                oppPlanRate.Plan_Status__c = 'Sold';
                            }
                        }
                        update optyPlanRate;
                    }
                    value = system.label.SGR_BlueStar_success_message;//'Opportunities batch scheduled successfully';
                    isSuccess = true;
                    system.debug('++++isSuccess--'+isSuccess);
                    if(isSuccess){
                            SGRRenewalBatch__c optyBatch = new SGRRenewalBatch__c();
                            String bid=String.valueOf(System.currentTimeMillis());
                            optyBatch.BatchID__c = bid;
                            optyBatch.BatchType__c  = 'Batch';
                            optyBatch.Division__c = division;
                            optyBatch.RenewalType__c = 'Production';
                            optyBatch.FundingType__c = fundingType;
                            optyBatch.MarketSegment__c = marketSegment;
                            optyBatch.Renewal_Effective_date__c = renewEffDate;
                            optyBatch.Action_Type__c = 'BlueSTAR Transfer';
                            optyBatch.Scheduled_Date__c = scheduleDate;
                            insert optyBatch; 
                        SGR_BSTAR_TransferSchedulerHelper sheduleClass = new SGR_BSTAR_TransferSchedulerHelper();
                        //sheduleClass.scheduleJobs(optyBatch.Id, division, fundingType, marketSegment, renMonth, renYear, scheduleDate);
                        sheduleClass.scheduleJobs(optyBatch.Id, division, fundingType, marketSegment, renewEffDate, scheduleDate);
                    }
                }
            }
            else
                value = system.label.SGR_BlueStar_Message;//'No Opportunities found';
            system.debug('++++value--'+value); 
        }
        catch(exception e){
            CreateExceptionLog.insertErrorLog(e, null, null, null, 'Apex Class', 'SGR_BlueSTAROptysPost', null, 'SGR_BlueSTAROptysPost.updateBlueSTAROptys','Low');  
        }
        system.debug('++++value--'+value);
        return value;
    }
}