objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment for the opportunity</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Batch_Id__c</fullName>
        <label>Batch ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <label>FIPS Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To retrieve days to submit for each division for calcuating Submit_Date__c on opportunity</description>
    <label>SGR Days to Submit</label>
</CustomObject>

objects/SGR_Opportunity_Plan_Rate__c.object
<CustomObject>
    <description>This object contains details about opportunity plan Rates.</description>
    <fields>
        <fullName>Benefit_Agreement_Effective_Date__c</fullName>
        <label>Benefit Agreement Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_ID__c</fullName>
        <label>Marketing Plan ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <label>Plan Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Renewing</fullName>
                </value>
                <value>
                    <fullName>Mapped</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Alternate</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                    <isActive>false</isActive>
                    <label>Alternative</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Plan Rate</label>
    <nameField>
        <label>Opportunity Plan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SGR_GSPS_CallMappedPlans.cls
//16508 - Batch class to be called between the SGR_AccountRenewalBatch and SGR_validationCheckBatch. 
//This batch will call the BSPS service to receive the plan mapping information. The callout is made with one opportunity at a time.

global class SGR_GSPS_CallMappedPlans implements Database.Batchable
<sObject>, Database.stateful,Database.AllowsCallouts{
    String BatchId;
    
    global SGR_GSPS_CallMappedPlans(String BatchId){
        this.BatchId = BatchId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('select id,Renewal_Date__c,FIPS_Code__c,HCSC_Division__c,Funding_Type__c,Account_Market_Segment__c from Opportunity where Batch_Id__c = :BatchId');
    }
    
    global void execute(Database.BatchableContext bc, List
	<Opportunity> OppList){
        system.debug('Bharath we are inside execute method.');
        list<id> oppId = new list<id>();
        for(Opportunity opp1 : OppList){
            oppId.add(opp1.Id);
        }
        //Retrieve the Opportunity Plan rate information to be sent to the callout code. just dont have the context
        //urgent fixes offshore : added extra filter of type='Renewal' for the soql
        list<SGR_Opportunity_Plan_Rate__c> OppPlanRateList = [select id,Plan_Name__c,Marketing_Plan_ID__c,Plan_Status__c, Opportunity__c,Benefit_Agreement_Effective_Date__c from SGR_Opportunity_Plan_Rate__c where Opportunity__c in :oppId AND Type__c=:'Renewal' AND Plan_Status__c !='Cancelled' AND Benefit_Agreement_Effective_Date__c <> NULL order by Opportunity__c];
        system.debug('The size of plan rates list is ' + OppPlanRateList.size());
        //Opportunity group logic start - 
        //This branch of code will group the Opportunity Plan Rates into a map indexed by opportunity id. Each item in the map is a list of opportunity plan rate. 
        //This grouping is done since the callout code should be called for one opportunity at a time. 
        //This logic also helps with avoiding seperate query for each opportunity on the opportunity plan rate.
        List<SGR_Opportunity_Plan_Rate__c> TempOPRList = new List<SGR_Opportunity_Plan_Rate__c>();
        Id TempId;
        Map<Id,List<SGR_Opportunity_Plan_Rate__c>> OppPlanRateMap = new Map<Id,List<SGR_Opportunity_Plan_Rate__c>>();
        for(SGR_Opportunity_Plan_Rate__c SOPR : OppPlanRateList){
            system.debug('Bharath there are opportunity plan rates');
            if(TempId == null || TempId <> SOPR.Opportunity__c){
                if(TempId <> null){
                    OppPlanRateMap.put(TempId,TempOPRList);
                    system.debug('The id of first index is :' + TempId);
                }
                TempId = SOPR.Opportunity__c;
            }           
            TempOPRList.add(SOPR);
        }
        OppPlanRateMap.put(TempId,TempOPRList);
        system.debug('the id of last index is :' + TempId);
        //Opportunity group logic end.
        
        //Callout code to be called once per opportunity.
        for(Opportunity opp : OppList){
            if(OppPlanRateMap.containsKey(opp.id)){
              SGR_GSPS_GetMappedPlansServiceHandler.getMappedPlans(opp.FIPS_Code__c,'RENEWALS', opp.Renewal_Date__c, 
                                                                   opp.HCSC_Division__c, opp.Funding_Type__c, 
                                                                   opp.Account_Market_Segment__c, OppPlanRateMap.get(opp.id));
            }
        }
        
    }
    
    global void finish(Database.BatchableContext bc){
        SGR_validationCheckBatch svc = new SGR_validationCheckBatch(BatchId);
        ID batchId1 = Database.executeBatch(svc,50);
        
    }

}