objects/Plan__c.object
<CustomObject>
    <description>To capture all the plans related to products - Loaded from BlueStar</description>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>Type of plan in BlueStar.</description>
        <label>Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PDent</fullName>
                </value>
                <value>
                    <fullName>VGDent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product the Plan is related</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GEMS_AccessPlansControllerTest.cls
@isTest
public class GEMS_AccessPlansControllerTest {
private static testmethod void GEMS_AccessPlansControllerTest()
{
      test.starttest(); 
                    product2 prod = new product2();
                    prod.IsActive = True;
                    prod.name = 'Accident Insurance (Dearborn)';
                    insert prod;      
       
                    List<product2> prodRecQuery=[SELECT ID, name,IsActive FROM product2 WHERE IsActive =true];
                    System.assertEquals('Accident Insurance (Dearborn)',prodRecQuery[0].Name);
                  
           
                    Plan__c Plan = New Plan__c();            
                    Plan.Product__c =prod.Id;
                    Plan.Plan_Type__c ='PDent';
                    Plan.Name ='Insurance';
                    insert Plan;
           
                   List<Plan__c> planRecQuery=[SELECT ID, name FROM Plan__c WHERE name='Insurance'];
                   System.assertEquals('Insurance',planRecQuery[0].Name);
                   GEMS_AccessPlansController gems = new GEMS_AccessPlansController ();
                   
                   gems.getPlans();        
          
       test.stoptest();
 
 }
 }