objects/Rate__c.object
<CustomObject>
    <description>Contains the rate information pertaining to BPA</description>
    <fields>
        <fullName>Additional_Comments_Admin_Charge__c</fullName>
        <label>Additional Comments Admin Charge</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Comments_Term_Charge__c</fullName>
        <label>Additional Comments Term Charge</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Additional_provisions_Claim_Admin_Pro__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether there are additional provisions (outlined at end of BPA) for the claim admiin provider fees section of this BPA</description>
        <label>Additional provisions?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicable_Group_Number_s__c</fullName>
        <label>Applicable Group Number(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BlueCard_Program_Network_access_fees__c</fullName>
        <description>Network access fees to be paid to HCSC by the employer that this BPA relates to, for the plan that this BPA relates to</description>
        <label>BlueCard Program/Network access fees</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>The lesser of up to 10% of the discount or $2,000 per claim</fullName>
                </value>
                <value>
                    <fullName>Available on Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Name_1_Term__c</fullName>
        <label>Group Name 1 Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name_1__c</fullName>
        <label>Group Name 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name_2_Term__c</fullName>
        <label>Group Name 2 Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name_2__c</fullName>
        <label>Group Name 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name_3_Term__c</fullName>
        <label>Group Name 3 Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name_3__c</fullName>
        <label>Group Name 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name_4_Term__c</fullName>
        <label>Group Name 4 Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name_4__c</fullName>
        <label>Group Name 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number_s__c</fullName>
        <description>Group number for the group that the BPA relates to</description>
        <label>Group Number(s)</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Numbers_With_Multiple__c</fullName>
        <label>Group Numbers(s)</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCA_Account_Structure_ASO__c</fullName>
        <label>HCA Account Structure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employee and Family</fullName>
                </value>
                <value>
                    <fullName>Employee, +1 Dependent, +2 Dependents</fullName>
                </value>
                <value>
                    <fullName>Employee, + Spouse, + Child(ren)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCA_Account_Structure__c</fullName>
        <label>HCA Account Structure</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employee Only</fullName>
                </value>
                <value>
                    <fullName>Employee + Spouse</fullName>
                </value>
                <value>
                    <fullName>Employee + Child(ren)</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Employee + 1 Dependent</fullName>
                </value>
                <value>
                    <fullName>Employee + 2 or more depends</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>Captures HCSC division</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Changes_Claim_Admin_Provider_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether there are changes to the claim admin provider access fee(s) section compared to the previous BPA for the plan that the BPA relates to</description>
        <label>No Changes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Years__c</fullName>
        <label>Number of Years</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One Year</fullName>
                </value>
                <value>
                    <fullName>Two Years</fullName>
                </value>
                <value>
                    <fullName>Three Years</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Rate__c</fullName>
        <label>Other Rate</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Rate_Structure_Fully__c</fullName>
        <label>Rate Structure</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employee Only</fullName>
                </value>
                <value>
                    <fullName>Employee + Spouse</fullName>
                </value>
                <value>
                    <fullName>Employee + Child(ren)</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Employee + One Dependent</fullName>
                </value>
                <value>
                    <fullName>Employee + Two or More Dependents</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>2 Tier</fullName>
                </value>
                <value>
                    <fullName>3 Tier</fullName>
                </value>
                <value>
                    <fullName>4 Tier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secure_Information__c</fullName>
        <description>Associated benefit plan application</description>
        <label>Secure Information</label>
        <referenceTo>Secure_Information__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Group_1_Term__c</fullName>
        <label>Total Group 1 Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Group_1_Year_1__c</fullName>
        <label>Total Group 1 Year 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Group_2_Term__c</fullName>
        <label>Total Group 2 Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Group_2_Year_1__c</fullName>
        <label>Total Group 2 Year 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Group_3_Term__c</fullName>
        <label>Total Group 3 Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Group_3_Year_1__c</fullName>
        <label>Total Group 3 Year 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Group_4_Term__c</fullName>
        <label>Total Group 4 Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Group_4_Year_1__c</fullName>
        <label>Total Group 4 Year 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Monthly__c</fullName>
        <label>Total Monthly</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_One_Time__c</fullName>
        <label>Total One Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Other__c</fullName>
        <label>Total Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Yearly__c</fullName>
        <label>Total Yearly</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>of_ADP_savings_2__c</fullName>
        <description>Fee, as a % of the ADP savings, that will be paid to HCSC by the employer that the BPA relates to</description>
        <label>% of ADP savings #2 (IL only)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>of_ADP_savings__c</fullName>
        <description>Fee, as a % of the ADP savings, that will be paid to HCSC by the employer that the BPA relates to</description>
        <label>% of ADP savings</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>per_covered_employee_per_month_2__c</fullName>
        <description>Fee, in dollars, that will be paid to HCSC by the employer that the BPA relates to</description>
        <label>$ per covered employee / month (IL only)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>per_covered_employee_per_month__c</fullName>
        <description>Fee, in dollars, that will be paid to HCSC by the employer that the BPA relates to</description>
        <label>$ per covered employee per month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RateDAO.cls
/**************************************************************************************
  Apex Class Name     : RateDAO
  Version             : 1.0
  Function            : This is a DAO class for the Rate__c Object
* Developer                        Date                  
* ----------------------------------------------------------------------------                 
* Nick Serafin/Slalom             6/3/2016
*************************************************************************************/

public with sharing class RateDAO implements IRateDAO { 

  public interface IRateDAO{
        Rate__c insertRate(Rate__c rateObj);
        Rate__c updateRate(Rate__c rateObj);
        Rate__c grabRateObj(Id rateId);
        Rate__c grabASORateObj(Id rateId);
        Rate__c grabHCARateObj(Id rateId);
  }

  public Rate__c insertRate(Rate__c rateObj){
        insert rateObj;
        return rateObj;
  }

  public Rate__c updateRate(Rate__c rateObj){
        update rateObj;
        return rateObj;
  }

  public Rate__c grabRateObj(Id rateId){
        
        return [SELECT Number_of_Years__c, HCSC_Division__c, Rate_Structure_Fully__c, Other_Rate__c FROM Rate__c WHERE Id = :rateId LIMIT 1];
  }

   public Rate__c grabASORateObj(Id rateId){
        
        return [SELECT Total_One_Time__c, Secure_Information__c, Total_Monthly__c, Total_Yearly__c, Total_Other__c, Additional_Comments_Term_Charge__c, Additional_Comments_Admin_Charge__c, Total_Group_1_Year_1__c, 
                Total_Group_2_Year_1__c, Total_Group_3_Year_1__c, Total_Group_4_Year_1__c, Group_Name_1__c, 
                Group_Name_2__c, Group_Name_3__c, Group_Name_4__c, HCSC_Division__c, No_Changes_Claim_Admin_Provider_Access__c, 
                Additional_provisions_Claim_Admin_Pro__c, Group_Number_s__c, of_ADP_savings__c, per_covered_employee_per_month__c, Group_Numbers_With_Multiple__c, 
                of_ADP_savings_2__c, per_covered_employee_per_month_2__c, BlueCard_Program_Network_access_fees__c,
                Group_Name_1_Term__c, Group_Name_2_Term__c, Group_Name_3_Term__c, Group_Name_4_Term__c, Total_Group_1_Term__c,
                Total_Group_2_Term__c, Total_Group_3_Term__c, Total_Group_4_Term__c FROM Rate__c WHERE Id = :rateId LIMIT 1];
  }

  public Rate__c grabHCARateObj(Id rateId){
        
        return [SELECT HCA_Account_Structure__c, HCA_Account_Structure_ASO__c, HCSC_Division__c, Applicable_Group_Number_s__c FROM Rate__c WHERE Id = :rateId LIMIT 1];
  }

}