objects/Rate__c.object
<CustomObject>
    <description>Contains the rate information pertaining to BPA</description>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rate</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rate_Admin_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>List_Service__c</fullName>
        <label>List Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Miscellaneous__c</fullName>
        <label>Miscellaneous</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Frequency__c</fullName>
        <label>Other Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Rate Admin Charges</relationshipLabel>
        <relationshipName>Rate_Admin_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charges__c</fullName>
        <label>Service Charges</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Exchange</fullName>
                </value>
                <value>
                    <fullName>Non-Standard Services</fullName>
                </value>
                <value>
                    <fullName>Other Services</fullName>
                </value>
                <value>
                    <fullName>Product-Related Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>adminNumber__c</fullName>
        <label>adminNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Rate Admin Charge</label>
    <nameField>
        <label>Rate Admin Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Admin Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RateAdminChargeDAO.cls
/**************************************************************************************
  Apex Class Name     : RateAdminChargeDAO
  Version             : 1.0
  Function            : This is a DAO class for the Rate_Admin_Charge__c Object
* Developer                        Date                  
* ----------------------------------------------------------------------------                 
* Nick Serafin/Slalom             6/6/2016
*************************************************************************************/

public with sharing class RateAdminChargeDAO implements IRateAdminChargeDAO { 

  public interface IRateAdminChargeDAO{
        List<Rate_Admin_Charge__c> insertRateAdminCharge(List<Rate_Admin_Charge__c> rateAdminChargeObj);
        List<Rate_Admin_Charge__c> upsertRateAdminCharge(List<Rate_Admin_Charge__c> rateAdminChargeObj);
        List<Rate_Admin_Charge__c> grabRateAdminCharges(Id rateId);
  }

  public List<Rate_Admin_Charge__c> insertRateAdminCharge(List<Rate_Admin_Charge__c> rateAdminChargeObj){
        insert rateAdminChargeObj;
        return rateAdminChargeObj;
  }

  public List<Rate_Admin_Charge__c> upsertRateAdminCharge(List<Rate_Admin_Charge__c> rateAdminChargeObj){
        upsert rateAdminChargeObj;
        return rateAdminChargeObj;
  }

  public List<Rate_Admin_Charge__c> grabRateAdminCharges(Id rateId){
     
        return [SELECT adminNumber__c, List_Service__c, Miscellaneous__c, Service_Charges__c, Name, Frequency__c, Other_Frequency__c,
                  Amount__c FROM Rate_Admin_Charge__c WHERE Rate__c = :rateId];
  }

}