objects/Rate__c.object
<CustomObject>
    <description>Contains the rate information pertaining to BPA</description>
    <label>Rate</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rate_Term__c.object
<CustomObject>
    <fields>
        <fullName>Group_1_Amount__c</fullName>
        <label>Group 1 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_2_Amount__c</fullName>
        <label>Group 2 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_3_Amount__c</fullName>
        <label>Group 3 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_4_Amount__c</fullName>
        <label>Group 4 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Miscellaneous__c</fullName>
        <label>Miscellaneous</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Rate Terms</relationshipLabel>
        <relationshipName>Rate_Terms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>termNumber__c</fullName>
        <label>termNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Rate Term</label>
    <nameField>
        <label>Rate Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RateTermDAO.cls
/**************************************************************************************
  Apex Class Name     : RateTermDAO
  Version             : 1.0
  Function            : This is a DAO class for the Rate_Term__c Object
* Developer                        Date                  
* ----------------------------------------------------------------------------                 
* Nick Serafin/Slalom             8/31/2016
*************************************************************************************/

public with sharing class RateTermDAO implements IRateTermDAO {

	public interface IRateTermDAO{
		List<Rate_Term__c> insertRateTerm(List<Rate_Term__c> rateTermObj);
        List<Rate_Term__c> upsertRateTerm(List<Rate_Term__c> rateTermObj);
        List<Rate_Term__c> grabRateTerms(Id rateId);
	}

	public List<Rate_Term__c> insertRateTerm(List<Rate_Term__c> rateTermObj){
        insert rateTermObj;
        return rateTermObj;
  	}

  	public List<Rate_Term__c> upsertRateTerm(List<Rate_Term__c> rateTermObj){
        upsert rateTermObj;
        return rateTermObj;
  	}

 	public List<Rate_Term__c> grabRateTerms(Id rateId){
        	return [SELECT termNumber__c, Miscellaneous__c, Name, Group_1_Amount__c, Group_2_Amount__c, Group_3_Amount__c, Group_4_Amount__c 
        	FROM Rate_Term__c WHERE Rate__c = :rateId];
  	}
}