objects/Rate__c.object
<CustomObject>
    <description>Contains the rate information pertaining to BPA</description>
    <label>Rate</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rate_Group__c.object
<CustomObject>
    <fields>
        <fullName>Group_1_Amount__c</fullName>
        <label>Grouping 1 Amt</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_2_Amount__c</fullName>
        <label>Grouping 2 Amt</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_3_Amount__c</fullName>
        <label>Grouping 3 Amt</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_4_Amount__c</fullName>
        <label>Grouping 4 Amt</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>List_Service__c</fullName>
        <label>List Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Miscellaneous__c</fullName>
        <label>Miscellaneous</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Rate Groups</relationshipLabel>
        <relationshipName>Rate_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Category__c</fullName>
        <label>Service Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Exchange</fullName>
                </value>
                <value>
                    <fullName>Non-Standard Services</fullName>
                </value>
                <value>
                    <fullName>Other Services</fullName>
                </value>
                <value>
                    <fullName>Product-Related Services</fullName>
                </value>
                <value>
                    <fullName>Prescription Drug Administrative Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>groupNumber__c</fullName>
        <label>groupNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Rate Group</label>
    <nameField>
        <label>Rate Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RateGroupDAO.cls
/**************************************************************************************
  Apex Class Name     : RateGroupDAO
  Version             : 1.0
  Function            : This is a DAO class for the Rate_Group__c Object
* Developer                        Date                  
* ----------------------------------------------------------------------------                 
* Nick Serafin/Slalom             6/6/2016
*************************************************************************************/

public with sharing class RateGroupDAO implements IRateGroupDAO { 

  public interface IRateGroupDAO{
        List<Rate_Group__c> insertRateGroup(List<Rate_Group__c> rateGroupObj);
        List<Rate_Group__c> upsertRateGroup(List<Rate_Group__c> rateGroupObj);
        List<Rate_Group__c> grabRateGroups(Id rateId);
  }

  public List<Rate_Group__c> insertRateGroup(List<Rate_Group__c> rateGroupObj){
        insert rateGroupObj;
        return rateGroupObj;
  }

  public List<Rate_Group__c> upsertRateGroup(List<Rate_Group__c> rateGroupObj){
        upsert rateGroupObj;
        return rateGroupObj;
  }

  public List<Rate_Group__c> grabRateGroups(Id rateId){
        
        return [SELECT Miscellaneous__c, Service_Category__c, List_Service__c, Name, groupNumber__c, Group_1_Amount__c, Group_2_Amount__c, 
        Group_3_Amount__c, Group_4_Amount__c FROM Rate_Group__c WHERE Rate__c = :rateId];
  }

}