objects/Service_Request__c.object
<CustomObject>
    <description>Service Request custom object supports the Fess, VM, CBSR and Issue intake processes.</description>
    <fields>
        <fullName>Adjustment_Amount__c</fullName>
        <label>Adjustment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adjustment_Entry_Date__c</fullName>
        <label>Adjustment Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Adjustment_Process_Date__c</fullName>
        <label>Adjustment Process Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Adjustment_Request_ID__c</fullName>
        <label>Adjustment Request ID</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adjustment_Request_Link__c</fullName>
        <label>Adjustment Request Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Adjustment_Request_Type_Indicator__c</fullName>
        <label>Adjustment Request Type Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Single</fullName>
                </value>
                <value>
                    <fullName>Mass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Adjustment_Type__c</fullName>
        <label>Adjustment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BARS_Customer_Number__c</fullName>
        <label>BARS Customer Number</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Approver_Name__c</fullName>
        <label>Final Approver Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending with Accountant/Manager</fullName>
                    <label>Pending with Lead Accountant/Manager</label>
                </value>
                <value>
                    <fullName>Pending with Director</fullName>
                </value>
                <value>
                    <fullName>Pending with Manager</fullName>
                </value>
                <value>
                    <fullName>Pending with SLT</fullName>
                </value>
                <value>
                    <fullName>Pending with SVP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AS400 &amp; BlueStar Update Completed</fullName>
                </value>
                <value>
                    <fullName>AS400 &amp; BlueStar Update Pending</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned to CS</fullName>
                </value>
                <value>
                    <fullName>BlueSTAR Entry Complete</fullName>
                </value>
                <value>
                    <fullName>BlueSTAR Walkthrough Complete</fullName>
                </value>
                <value>
                    <fullName>BW Approval Pending</fullName>
                </value>
                <value>
                    <fullName>BW Approval Received</fullName>
                </value>
                <value>
                    <fullName>BW Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>CDHP Team Approval Pending</fullName>
                </value>
                <value>
                    <fullName>CDHP Team Approval Received</fullName>
                </value>
                <value>
                    <fullName>Client Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Client Approval Received</fullName>
                </value>
                <value>
                    <fullName>Client Approval Received with Changes</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#F3D904</color>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Closed (Marked for Delete)</fullName>
                </value>
                <value>
                    <fullName>Closed - No Response</fullName>
                    <color>#A53711</color>
                    <label>Closed - No Response</label>
                </value>
                <value>
                    <fullName>Completed but No Signature Required</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Deferred for Business Decision</fullName>
                </value>
                <value>
                    <fullName>Deferred to Business Decision</fullName>
                </value>
                <value>
                    <fullName>Design In Progress</fullName>
                </value>
                <value>
                    <fullName>Developing Content</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>DTU Approval Pending</fullName>
                </value>
                <value>
                    <fullName>DTU Approval Received</fullName>
                </value>
                <value>
                    <fullName>DTU Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>FEAK Approval Pendig</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending for Rejection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ServiceRequestTriggerRecordTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Service Request Record Types for use in the ServiceRequestTrigger</description>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <label>Record Type Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Request Trigger Record Types</label>
</CustomObject>

objects/Stage__c.object
<CustomObject>
    <label>Stage</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ServiceRequestTriggerTest.cls
@isTest
public class ServiceRequestTriggerTest {
    
    /* Service Requests that are Rejected */
    private static testmethod void testRejection()
    {
              
        /* Create the Custom Setting */
        ServiceRequestTriggerRecordTypes__c ACustomSetting = new ServiceRequestTriggerRecordTypes__c();
        
        ACustomSetting.Name = 'GFRA - Adjustment';
        ACustomSetting.Record_Type_Name__c = 'GFRA - Adjustment';
        
        insert ACustomSetting;        
        
        // Create a sample Service Request object and then submit it for approval.
        Service_Request__c testSR = new Service_Request__c();
        
        Id GFRARecordTypeId = Schema.SObjectType.Service_Request__c.getRecordTypeInfosByName().get('GFRA - Adjustment').getRecordTypeId();
        
        testSR.Adjustment_Type__c = 'T' + String.valueOf(DateTime.now());
        testSR.Adjustment_Request_ID__c = '123456';
        testSR.Adjustment_Amount__c = 1.00;
        testSR.Adjustment_Process_Date__c = Date.today() + 7;
        testSR.RecordTypeId = GFRARecordTypeId;
        testSR.Status__c = 'New';
        testSR.Stage__c = 'New';
        testSR.Adjustment_Request_Type_Indicator__c = 'Single';

        insert testSR;
        
        System.debug('testSR.Id: ' + testSR.Id);
        
        Approval.ProcessSubmitRequest testReq = new Approval.ProcessSubmitRequest();
        testReq.setComments('Submitting for Approval');
        testReq.setObjectId(testSR.Id);
        
        Approval.ProcessResult reqResult = Approval.process(testReq);
        
        System.assert(reqResult.isSuccess(),'Unable to submit new invoice statement record for approval');       
 
        List<Id> newWorkItemIds = reqResult.getNewWorkitemIds();
        //Id testWorkItemId = reqResult.getNewWorkitemIds()[0];        
        
        // Reject the submitted request, providing a comment.
        Approval.ProcessWorkitemRequest testRej = new Approval.ProcessWorkitemRequest();
        testRej.setComments('Rejecting request with a comment.');
        testRej.setAction  ('Reject');
        testRej.setWorkitemId(newWorkItemIds.get(0));
        
        Test.startTest();        
        // Process the rejection
        Approval.ProcessResult testRejResult =  Approval.process(testRej);
        Test.stopTest();
        
        // Verify the rejection results
        System.assert(testRejResult.isSuccess(), 'Rejections that include comments should be permitted');
        System.assertEquals('Rejected', testRejResult.getInstanceStatus(), 
                            'Rejections that include comments should be successful and instance status should be Rejected');
        
        List<Service_Request__c> AfterUpdateVerify = [SELECT Id, Rejection_Reason__c 
                                                     FROM Service_Request__c
                                                     WHERE Id = :testSR.Id LIMIT 1];
        
        System.debug('AfterUpdateVerify[0].Rejection_Reason__c' + AfterUpdateVerify[0].Rejection_Reason__c);
        
        /* Final Comment on Approval Process carried up to Service Request */
        /* System.assertEquals(AfterUpdateVerify[0].Rejection_Reason__c,'Rejecting request with a comment.');*/
        
    }    
   
    private static testMethod void testUpdateRejectPending(){
    	Service_Request__c sr=new Service_Request__c();
    	sr.recordTypeId= Schema.SObjectType.Service_Request__c.getRecordTypeInfosByName().get('GFRA - Adjustment').getRecordTypeId();
    	sr.Adjustment_Entry_Date__c=system.today();
    	sr.Adjustment_Process_Date__c=system.today();
    	sr.Adjustment_Request_Link__c='www.yahoo.com';
    	sr.Adjustment_Request_ID__c='12345';
        sr.Adjustment_Type__c='test';
        sr.BARS_Customer_Number__c='test2345';
        sr.Rejection_Reason__c=null;
        sr.Final_Approver_Name__c='test tester';
        sr.Adjustment_Amount__c=100000.00;
        sr.status__c='New';
        insert sr;
        
        Test.startTest();
        
        
        Service_Request__c oldSR=[select id, Adjustment_Request_ID__c,status__c, rejection_Reason__c from Service_Request__c where Adjustment_Request_ID__c='12345'];
        oldsr.Status__c='Rejected';
        oldsr.Rejection_Reason__c=null;
        update oldsr;
        
        Service_Request__c nwSR=[select id, Adjustment_Request_ID__c,status__c, rejection_Reason__c from Service_Request__c where Adjustment_Request_ID__c='12345'];
     
        nwsr.status__c='Pending for Rejection';
        nwsr.Rejection_Reason__c='test for rejection';
        update nwsr;
        
        Test.stopTest();
        
      	
    }
    
       private static testMethod void testCallSentOut(){
    	Service_Request__c sr=new Service_Request__c();
    	sr.recordTypeId= Schema.SObjectType.Service_Request__c.getRecordTypeInfosByName().get('GFRA - Adjustment').getRecordTypeId();
    	sr.Adjustment_Entry_Date__c=system.today();
    	sr.Adjustment_Process_Date__c=system.today();
    	sr.Adjustment_Request_Link__c='www.yahoo.com';
    	sr.Adjustment_Request_ID__c='12345';
        sr.Adjustment_Type__c='test';
        sr.BARS_Customer_Number__c='test2345';
        sr.Rejection_Reason__c=null;
     //   sr.Final_Approver_Name__c='test tester';
        sr.Adjustment_Amount__c=100000.00;
        sr.status__c='New';
        insert sr;
        
        Test.startTest();
        
        
        Service_Request__c oldSR=[select id, Adjustment_Request_ID__c,status__c, rejection_Reason__c from Service_Request__c where Adjustment_Request_ID__c='12345'];
        oldsr.Status__c='Approved';
        oldsr.Final_Approver_Name__c='test tester';
        oldsr.Rejection_Reason__c=null;
        update oldsr;
        
       
        Test.stopTest();
        
      	
    }
    
}