objects/Service_Request__c.object
<CustomObject>
    <description>Service Request custom object supports the Fess, VM, CBSR and Issue intake processes.</description>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending with Accountant/Manager</fullName>
                    <label>Pending with Lead Accountant/Manager</label>
                </value>
                <value>
                    <fullName>Pending with Director</fullName>
                </value>
                <value>
                    <fullName>Pending with Manager</fullName>
                </value>
                <value>
                    <fullName>Pending with SLT</fullName>
                </value>
                <value>
                    <fullName>Pending with SVP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AS400 &amp; BlueStar Update Completed</fullName>
                </value>
                <value>
                    <fullName>AS400 &amp; BlueStar Update Pending</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned to CS</fullName>
                </value>
                <value>
                    <fullName>BlueSTAR Entry Complete</fullName>
                </value>
                <value>
                    <fullName>BlueSTAR Walkthrough Complete</fullName>
                </value>
                <value>
                    <fullName>BW Approval Pending</fullName>
                </value>
                <value>
                    <fullName>BW Approval Received</fullName>
                </value>
                <value>
                    <fullName>BW Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>CDHP Team Approval Pending</fullName>
                </value>
                <value>
                    <fullName>CDHP Team Approval Received</fullName>
                </value>
                <value>
                    <fullName>Client Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Client Approval Received</fullName>
                </value>
                <value>
                    <fullName>Client Approval Received with Changes</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#F3D904</color>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Closed (Marked for Delete)</fullName>
                </value>
                <value>
                    <fullName>Closed - No Response</fullName>
                    <color>#A53711</color>
                    <label>Closed - No Response</label>
                </value>
                <value>
                    <fullName>Completed but No Signature Required</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Deferred for Business Decision</fullName>
                </value>
                <value>
                    <fullName>Deferred to Business Decision</fullName>
                </value>
                <value>
                    <fullName>Design In Progress</fullName>
                </value>
                <value>
                    <fullName>Developing Content</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>DTU Approval Pending</fullName>
                </value>
                <value>
                    <fullName>DTU Approval Received</fullName>
                </value>
                <value>
                    <fullName>DTU Approval Rejected</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>FEAK Approval Pendig</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Stage__c.object
<CustomObject>
    <label>Stage</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LGNA_ServiceRequestSubmitCntlr.cls
public class LGNA_ServiceRequestSubmitCntlr{

private final Service_Request__c sr,sr1;
    public string errorMessage {get;set;}
    public LGNA_ServiceRequestSubmitCntlr(ApexPages.StandardController stdController) {
        this.sr1= (Service_Request__c )stdController.getRecord();
        system.debug(sr1+'testss+++++');
         this.sr=[select Stage__c, Status__c from Service_Request__c  where Id=:sr1.Id];
        }

 public void SubmitFunction(){
        string recordTypeName = Schema.SObjectType.Service_Request__c.getRecordTypeInfosById().get(sr1.RecordTypeId).getName();
        if(recordTypeName == 'Open Enrollment'){
            // call the submit button. 
            srSubmitRequest();
        }
       }
       
    public PageReference srSubmitRequest(){
    system.debug('test suajtha');
     sr1.Stage__c = 'Submitted'; 
     update sr1;
     system.debug('Update suajtha'+sr1.Stage__c);
     return null;
    }
    
}