objects/SGR_Opportunity_Census__c.object
<CustomObject>
    <description>This object is used  for</description>
    <fields>
        <fullName>Membership_Number__c</fullName>
        <label>Membership Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscriber_Number__c</fullName>
        <label>Subscriber ID Number</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Census</label>
    <nameField>
        <label>Opportunity Census Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Censuses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SGRCensusWrapper.cls
global class SGRCensusWrapper implements Comparable{

    public SGR_Opportunity_Census__c oppCensus;

    public SGRCensusWrapper(SGR_Opportunity_Census__c oppCensus){
        this.oppCensus = oppCensus;
    }


    global Integer compareTo(Object obj) {
        SGRCensusWrapper compareWrapper = (SGRCensusWrapper)obj;
        if(oppCensus.Subscriber_Number__c != null){
            if(compareWrapper.oppCensus.Subscriber_Number__c != null){
                if(oppCensus.Subscriber_Number__c == compareWrapper.oppCensus.Subscriber_Number__c){
                    if(oppCensus.Membership_Number__c != null){
                        if(compareWrapper.oppCensus.Membership_Number__c != null){
                            return Integer.valueOf(oppCensus.Membership_Number__c - compareWrapper.oppCensus.Membership_Number__c);
                        }
                        return -1;
                    }
                    return (compareWrapper.oppCensus.Membership_Number__c != null ? 1 : 0);
                }
                return Integer.valueOf(oppCensus.Subscriber_Number__c - compareWrapper.oppCensus.Subscriber_Number__c);
            }
            return -1;
        }
        return (compareWrapper.oppCensus.Subscriber_Number__c != null ? 1 : 0);
    }
}