objects/SGR__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SGR EMAILS</label>
</CustomObject>

classes/SGR_EmailNotifications.cls
global class SGR_EmailNotifications {
    public static void sendEmailNotification(String emailMessgaeBody,String recordName)
    {
        List <string> toaddress = new List <string> ();         
        List<SGR__c> intgerationDlList= SGR__c.getAll().Values();
        for(SGR__c  integrationdl:intgerationDlList)
            toaddress.add(integrationdl.Email_Address__c); 
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();                                  
        mail.setToAddresses(toaddress) ;                     
        mail.setSubject('Salesforce Error Update in - ' +recordName);                          
        mail.setHtmlBody(emailMessgaeBody);
        if(!Test.isRunningTest())
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail } );       
    }                                 
}