objects/Ticket_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_City__c</fullName>
        <label>Event City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_State__c</fullName>
        <label>Event State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Street_Address__c</fullName>
        <label>Event Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Venue_Name__c</fullName>
        <description>Event Venue Name dependent on State picklist</description>
        <label>Event Venue</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Event_State__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Alamodome</fullName>
                </value>
                <value>
                    <fullName>American Airlines Center</fullName>
                </value>
                <value>
                    <fullName>Amon G. Carter Stadium</fullName>
                </value>
                <value>
                    <fullName>AT &amp; T Center</fullName>
                </value>
                <value>
                    <fullName>AT &amp; T Stadium</fullName>
                </value>
                <value>
                    <fullName>BBVA Compass Stadium</fullName>
                </value>
                <value>
                    <fullName>Boone Pickens Stadium</fullName>
                </value>
                <value>
                    <fullName>Chesapeake Energy Arena</fullName>
                </value>
                <value>
                    <fullName>Chickasaw Bricktown Ballpark</fullName>
                </value>
                <value>
                    <fullName>Darrell K. Royal-TX Memorial Stadium</fullName>
                </value>
                <value>
                    <fullName>Dell Diamond</fullName>
                </value>
                <value>
                    <fullName>Dr. Pepper Arena</fullName>
                </value>
                <value>
                    <fullName>Gallagher Iba Arena</fullName>
                </value>
                <value>
                    <fullName>Gaylord Family-OK Memorial Stadium</fullName>
                </value>
                <value>
                    <fullName>Globe Life Park</fullName>
                </value>
                <value>
                    <fullName>Guaranteed Rate Field</fullName>
                </value>
                <value>
                    <fullName>Isotopes Park (Baseball)</fullName>
                </value>
                <value>
                    <fullName>Jones AT &amp; T Stadium</fullName>
                </value>
                <value>
                    <fullName>Kyle Field</fullName>
                </value>
                <value>
                    <fullName>Lloyd Noble Center</fullName>
                </value>
                <value>
                    <fullName>McLane Stadium</fullName>
                </value>
                <value>
                    <fullName>Minute Maid Park</fullName>
                </value>
                <value>
                    <fullName>NRG Stadium</fullName>
                </value>
                <value>
                    <fullName>ONEOK Field</fullName>
                </value>
                <value>
                    <fullName>Soldier Field - (Chicago Bears)</fullName>
                </value>
                <value>
                    <fullName>Toyota Center</fullName>
                </value>
                <value>
                    <fullName>Toyota Stadium</fullName>
                </value>
                <value>
                    <fullName>United Center</fullName>
                </value>
                <value>
                    <fullName>University Stadium (Football)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Zip_Postal_Code__c</fullName>
        <label>Event Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ticket Event</label>
    <nameField>
        <label>Ticket Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket_Grouping__c.object
<CustomObject>
    <fields>
        <fullName>Ticket_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ticket Event</label>
        <referenceTo>Ticket_Event__c</referenceTo>
        <relationshipLabel>Ticket Groupings</relationshipLabel>
        <relationshipName>Ticket_Groupings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ticket Grouping</label>
    <nameField>
        <label>Ticket Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Groupings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TicketGroupingDAOTest.cls
/**************************************************************************************
  Apex Class Name     : TicketGroupingDAOTest
  Version             : 1.0
  Function            : This is a test class for the TicketGroupingDAO class
* Developer                        Date                  
* ----------------------------------------------------------------------------                 
* Nick Serafin/Slalom             10/26/2016
*************************************************************************************/

@isTest(SeeAllData=false)
private class TicketGroupingDAOTest { 

	@isTest
	static void ticketGroupingDAOTest(){

		TicketGroupingDAO.ITicketGroupingDAO ticketGroupingDAOInstance = new TicketGroupingDAO();

		Ticket_Event__c testEvent = new Ticket_Event__c();
		testEvent.Name = 'Game';
        testEvent.Event_Date__c = date.today();
        testEvent.Event_State__c = 'Texas';
        testEvent.Event_Venue_Name__c = 'Other';
        testEvent.Event_Street_Address__c = '121 Test Street';
        testEvent.Event_City__c = 'Plano';
        testEvent.Event_Zip_Postal_Code__c = '75024';
		insert testEvent;

		List<Ticket_Grouping__c> ticketGroupings = new List<Ticket_Grouping__c>();
		Ticket_Grouping__c ticketGrouping = new Ticket_Grouping__c();
		ticketGrouping.Ticket_Event__c = testEvent.Id;
		ticketGroupings.add(ticketGrouping);

		ticketGroupingDAOInstance.insertTicketGroupings(ticketGroupings);
		ticketGroupingDAOInstance.upsertTicketGroupings(ticketGroupings);

		List<Ticket_Grouping__c> ticketGroupingObjs = [SELECT Id FROM Ticket_Grouping__c];
		System.assertEquals(1, ticketGroupingObjs.size());

		ticketGroupingDAOInstance.deleteTicketGrouping(ticketGrouping);
		ticketGroupingDAOInstance.grabTicketGroupings(testEvent.Id);
	}
}