objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>AssignToProspect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AssignToProspect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AssignToVendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AssignToVendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <formula>IF (assignToClient__c = TRUE, &quot;Client&quot;, 
IF (assignToEmployee__c = TRUE, &quot;Employee&quot;, 
IF (assignToProducer__c = TRUE, &quot;Producer&quot;, 
IF (assignToHost__c = TRUE, &quot;Host&quot;, 
IF (assignToCharity__c = TRUE, &quot;Charity&quot;, 
IF (assignToEmployeeIncentive__c = TRUE, &quot;Employee Incentive&quot;, 
IF (AssignToProspect__c = TRUE, &quot;Prospect&quot;, 
IF (AssignToVendor__c = TRUE, &quot;Vendor&quot;,&quot;&quot; ))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned To</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Use_of_Ticket__c</fullName>
        <label>Ticket Use Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Charities</fullName>
                </value>
                <value>
                    <fullName>Employee Incentive</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charity_Organization__c</fullName>
        <description>Formula retrieves the Organization Name for the Contact if that Contact is a Charity Contact</description>
        <formula>IF(
Contact__r.RecordType.DeveloperName = &apos;Charity_Contact&apos;,
Contact__r.Organization_Name__c, 
&apos;&apos;)</formula>
        <label>Charity Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Number__c</fullName>
        <label>Client Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets (Client)</relationshipLabel>
        <relationshipName>Tickets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specific Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Internal Contact</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Charity Contact</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets (Internal Contact)</relationshipLabel>
        <relationshipName>Tickets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_for_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guest_Name__c</fullName>
        <label>Guest Name</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Producer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Producer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets (Producer Contact)</relationshipLabel>
        <relationshipName>Tickets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producer_Number__c</fullName>
        <label>Producer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Producer_for_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Producer for Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Producer_Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prospect</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets (Prospect)</relationshipLabel>
        <relationshipName>Tickets3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester (Old)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tickets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets (Requestor)</relationshipLabel>
        <relationshipName>Tickets3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specific_Prospect_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specific Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Internal Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets (Specific Contact)</relationshipLabel>
        <relationshipName>Tickets4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specific_Vendor_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>look up all contact</description>
        <label>Specific Vendor Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor Contact</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets (Specific Vendor Contact)</relationshipLabel>
        <relationshipName>Tickets5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Event__c</fullName>
        <label>Ticket Event</label>
        <referenceTo>Ticket_Event__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ticket_Grouping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ticket Grouping</label>
        <referenceTo>Ticket_Grouping__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Number__c</fullName>
        <label>Ticket Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ticket_Price__c</fullName>
        <label>Ticket Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ticket_Type__c</fullName>
        <label>Ticket Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Box Seats</fullName>
                </value>
                <value>
                    <fullName>Terrace Seats</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Suite</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unused_Ticket__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to calculate Unused Tickets of each category for the Event.</description>
        <label>Unused Ticket</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_for_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User for Event</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>contains</operation>
                <value>Competitor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets (Vendor)</relationshipLabel>
        <relationshipName>Tickets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>assignToCharity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>assignToCharity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>assignToClient__c</fullName>
        <defaultValue>false</defaultValue>
        <label>assignToClient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>assignToEmployeeIncentive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>assignToEmployeeIncentive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>assignToEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>assignToEmployee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>assignToHost__c</fullName>
        <defaultValue>false</defaultValue>
        <label>assignToHost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>assignToProducer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>assignToProducer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isSelected</label>
        <type>Checkbox</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket_Event__c.object
<CustomObject>
    <fields>
        <fullName>Business_Use_Of_Ticket__c</fullName>
        <label>Ticket Use Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ticket Event</label>
    <nameField>
        <label>Ticket Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket_Grouping__c.object
<CustomObject>
    <fields>
        <fullName>Ticket_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ticket Event</label>
        <referenceTo>Ticket_Event__c</referenceTo>
        <relationshipLabel>Ticket Groupings</relationshipLabel>
        <relationshipName>Ticket_Groupings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>groupingNumber__c</fullName>
        <label>groupingNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ticket Grouping</label>
    <nameField>
        <label>Ticket Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Groupings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TicketGroupingDAO.cls
/**********************************************************************************/
/*SFDC-7930 - 2018/02 - Added Charity_Organization__c to SOQL on                  */
/*                        grabTicketGroupings() method.                           */
/**********************************************************************************/
public with sharing class TicketGroupingDAO implements ITicketGroupingDAO {

  public interface ITicketGroupingDAO{
        List<Ticket_Grouping__c> insertTicketGroupings(List<Ticket_Grouping__c> ticketGroupingObjs);
        List<Ticket_Grouping__c> upsertTicketGroupings(List<Ticket_Grouping__c> ticketGroupingObjs);
        List<Ticket_Grouping__c> grabTicketGroupings(Id ticketObj);
        Ticket_Grouping__c deleteTicketGrouping(Ticket_Grouping__c ticketGroupingObj);
    }

    public List<Ticket_Grouping__c> insertTicketGroupings(List<Ticket_Grouping__c> ticketGroupingObjs){
        insert ticketGroupingObjs;
        return ticketGroupingObjs;
    }

    public List<Ticket_Grouping__c> upsertTicketGroupings(List<Ticket_Grouping__c> ticketGroupingObjs){
        upsert ticketGroupingObjs;
        return ticketGroupingObjs;
    }

    public Ticket_Grouping__c deleteTicketGrouping(Ticket_Grouping__c ticketGroupingObj){
      delete ticketGroupingObj;
      return ticketGroupingObj;
    }

    public List<Ticket_Grouping__c> grabTicketGroupings(Id ticketId){
        
        return [SELECT Name, groupingNumber__c, Ticket_Event__c,(SELECT Name, Contact__c, Charity_Organization__c, Ticket_Grouping__c, Ticket_Price__c, assignToClient__c,Guest_Name__c,Unused_Ticket__c,
        assignToEmployee__c, assignToProducer__c, AssignToVendor__c,AssignToProspect__c,assignToEmployeeIncentive__c, assignToHost__c, assignToCharity__c, isSelected__c, Business_Use_of_Ticket__c, 
        Requestor_contact__c, Requestor_contact__r.lastName, Requestor_contact__r.firstName, Requestor__r.FirstName, Requestor__r.LastName, Producer_Contact__c,
        Client__c, Client_Number__c, Contact_for_Event__c, Vendor__c,Prospect__c, Producer_for_Event__c,Specific_Prospect_Contact__c,Specific_Vendor_Contact__c, Producer_Number__c,
        Ticket_Event__c, Ticket_Number__c, Ticket_Type__c,Assigned_To__c FROM Tickets__r ORDER BY Ticket_Number__c) FROM Ticket_Grouping__c 
        WHERE Ticket_Event__c = :ticketId ORDER BY groupingNumber__c];
    }
}