src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Active_Health_Subscribers__c</fullName>
        <description>This field is used to capture the number of active health contracts for the Group Account as listed in BlueStar</description>
        <label>Active Health Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Ceded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if an account is ceded from another plan.</description>
        <label>Ceded?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Notification_in_days__c</fullName>
        <defaultValue>180</defaultValue>
        <description>This field is used to capture the number of days advance of the Renewal Date that the Account Owner should receive a notification to create a Renewal Opportunity (defaulted to 180)</description>
        <label>Renewal Notification (in days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Custom_Notification_Enabled_Profiles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to store the profile names enabled to receive custom notifications such as renewal reminders.</description>
    <fields>
        <fullName>Account_Renewal_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to store if Account Renewal tasks should be created for a profile.</description>
        <inlineHelpText>Select if Account Renewal tasks should be created for this profile.</inlineHelpText>
        <label>Account Renewal Tasks</label>
        <type>Checkbox</type>
    </fields>
    <label>Custom Notification Enabled Profiles</label>
</CustomObject>

classes/TestBatchAccountRenewalNotification.cls
/*
@Description : This is an test class for BatchAccountRenewalNotification
@author      : Deloitte
@date        : 10/29/2015
*/
@isTest
public with sharing class TestBatchAccountRenewalNotification {
    /*
@Description : This is a testMethod for testing the accountRenewalBatch
@author      : Deloitte
@date        : 10/29/2015
*/
    
    static testMethod void testWithAccountRenewalTaskSomeToSelect(){
        
        System.debug('!!BEGIN - testWithAccountRenewalTaskSomeToSelect');
        
        String accountRenewalTaskSubject     = Label.Account_Renewal_Task_Subject;
        String cedeAccountRenewalTaskSubject   = Label.Cede_Account_Renewal_Task_Subject;
        
        /* create a User */
        Profile p = [SELECT Id FROM Profile WHERE Name='LGNA - Sales MSR']; //Padma Update profile from LGNA - Sales to LGNA - Sales MSR Since profile deleted in prod.        
        User testUser = TestClassUtiltity.CreateUserRecord(p.Id, 'testlgnadev@user.com', 'testUser', 'test@user.com');        
        testUser.IsActive = True;        
        Update testUser;        
        System.debug('testUser: ' + testUser);
        
        system.runAs(testUser){           
            
            /* create an Account */
            Account TestAccount = TestClassUtiltity.CreateAccountRecord('TestAccount');            
            TestAccount.Effective_Date__c = Date.today().addDays(-365);
            TestAccount.Renewal_Notification_in_days__c = 2;
            TestAccount.Renewal_Date__c = date.today().addDays(2);
            TestAccount.Active_Health_Subscribers__c = 151;
            TestAccount.Ceded__c = true;
            TestAccount.Status__c = 'Active'; 
            TestAccount.HCSC_Division__c = 'IL';
            TestAccount.OwnerId = testUser.Id;
            Update TestAccount;     
            System.debug('TestAccount: ' + TestAccount);         
            
            /* create the Custom Setting used by the Query in the Class */
            Custom_Notification_Enabled_Profiles__c TestCustomSetting = new Custom_Notification_Enabled_Profiles__c();            
            TestCustomSetting.Name='LGNA - Sales MSR';//Padma Update profile from LGNA - Sales to LGNA - Sales MSR Since profile deleted in prod.
            TestCustomSetting.Account_Renewal_Tasks__c = true;
            Insert TestCustomSetting;                                                     
            
            test.startTest();
            
            BatchAccountRenewalNotification bt = new BatchAccountRenewalNotification();
            Id batchId=database.executeBatch(bt);
            
            /* successfully scheduled the Batch job verification */
            System.assertNOTEquals(batchId,null);            
            
            test.stopTest();    
            
            /* ensure that the renewal task was created for the Account */
            List<Task> AfterBatchTask = [SELECT Id FROM TASK WHERE 
                                         WhatId = :TestAccount.Id AND
                                         OwnerId = :TestAccount.OwnerId AND
                                         Subject = :cedeAccountRenewalTaskSubject];            
            System.assertEquals(1, AfterBatchTask.size());
            
        }        
        System.debug('!!END - testWithAccountRenewalTaskSomeToSelect');
    }
    
    static testMethod void myUnitTest1() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User testUser = TestClassUtiltity.CreateUserRecord(p.Id, 'testlgnadev@user.com', 'testUser', 'test@user.com');
        system.runAs(testUser){
            Account TestAcnt = TestClassUtiltity.CreateAccountRecord('TestAccount');
            TestAcnt.Renewal_Notification_in_days__c = 2;
            TestAcnt.Renewal_Date__c = date.today().addDays(2);
            TestAcnt.Ceded__c = true;
            TestAcnt.Status__c = 'Active';
            update TestAcnt;
            Custom_Notification_Enabled_Profiles__c ce = new Custom_Notification_Enabled_Profiles__c();            
            ce.Name='Standard User';
            ce.Account_Renewal_Tasks__c = true;
            insert ce;
            test.startTest();
            BatchAccountRenewalNotification bt = new BatchAccountRenewalNotification();
            Id batchId=database.executeBatch(bt);
            System.assertNOTEquals(batchId,null);
            test.stopTest();
        }
    }
}