src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>true</active>
        <description>Account record type that captures information about a competitor (carriers and vendors)</description>
        <label>Competitor</label>
    </recordTypes>

objects/GEMS_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABS</fullName>
                </value>
                <value>
                    <fullName>ACA CALCULATORS</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT CHANGE REQUEST FORM</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT STRUCTURE</fullName>
                </value>
                <value>
                    <fullName>ACH/WIRE FORM</fullName>
                </value>
                <value>
                    <fullName>ADDENDUM TO BPA FOR AFFILIATES</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRATIVE SERVICE AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO BENEFIT PROG APP (BPA)</fullName>
                </value>
                <value>
                    <fullName>ASO MANDATE CHECKLIST</fullName>
                </value>
                <value>
                    <fullName>BENEFIT ADHOC MEETING MINUTES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT BOOKLETS / CERTIFICATES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT EDIT TOOL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT MATRIX</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROG DESCRIPTION-DENTAL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROGRAM DESCRIPTION-BPD</fullName>
                </value>
                <value>
                    <fullName>BENEFIT WALLET DISCOVERY FORM</fullName>
                </value>
                <value>
                    <fullName>BINDER CHECK</fullName>
                </value>
                <value>
                    <fullName>BPA - ASO SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - ASO UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - DENTAL SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - DENTAL UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HCA SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HCA UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HEALTH SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HEALTH UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>BROKER TRANS/AOR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GEMS Attachments</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS  Attachments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Incumbent__c</fullName>
        <label>Incumbent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Carrier</fullName>
                </value>
                <value>
                    <fullName>Cigna</fullName>
                </value>
                <value>
                    <fullName>UHC</fullName>
                </value>
                <value>
                    <fullName>Aetna</fullName>
                </value>
                <value>
                    <fullName>Humana</fullName>
                </value>
                <value>
                    <fullName>PUG</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity_Product__c.object
<CustomObject>
    <description>Products related to the opportunity - acting as a junction object</description>
    <fields>
        <fullName>Incumbent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incumbent</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Products (Incumbent)</relationshipLabel>
        <relationshipName>Opportunity_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Name of product category</description>
        <formula>TEXT(Product__r.Product_Category__c)</formula>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Sales status of opportunity product</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>GeoAccess/Discount Analysis/Proposal Provided</fullName>
                </value>
                <value>
                    <fullName>Pricing/Presentation to Client</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{000}</displayFormat>
        <label>OP #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Captures product category</description>
        <inlineHelpText>required field for plans to flow correctly on BA to BlueSTAR</inlineHelpText>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BCC</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Disease Management</fullName>
                </value>
                <value>
                    <fullName>EPO</fullName>
                </value>
                <value>
                    <fullName>Group Govt</fullName>
                </value>
                <value>
                    <fullName>HCA</fullName>
                </value>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>IHI</fullName>
                </value>
                <value>
                    <fullName>Nurseline</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
                <value>
                    <fullName>Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Dearborn</fullName>
                </value>
                <value>
                    <fullName>Health Advocacy Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GEMS_UploadAttachmentControllerTest.cls
/**************************************************************************************
Apex Class Name     : GEMS_UploadAttachmentControllerTest
Version             : 1.0
Function            : This class serves as Unit Test Class for GEMS_UploadAttachmentController
Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
*   Siva               04/14/2016                Original Version
*************************************************************************************/
@isTest 
public class GEMS_UploadAttachmentControllerTest
{
    private static testmethod void GEMS_UploadAttachmentController1()
    {
        
        Id CompetitorAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Competitor').getRecordTypeId();
        Account testCompetitorAccount = TestClassUtiltity.createAccountWithRecType('Test Account2', CompetitorAccountRecordTypeId);
        
        Account acc = GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        System.assertEquals('BenefitAgreementControllerTest',acc.Name);
        
        Opportunity oppty= GEMS_UtilityClassTest.insertionOpp1(acc.Id);
        oppty.StageName=GEMS_UtilityClassTest.opportunityStatus();
        insert oppty;
        System.assertEquals('BenefitAgreementControllerTest',oppty.name);
        
        product2 productRec1=GEMS_UtilityClassTest.insertionProduct1();
        insert productRec1;
        System.assertEquals('HSA',productRec1.Product_Category__c);
        
        Opportunity_Product__c oppProd1=GEMS_UtilityClassTest.insertionOppProd1(productRec1.Id,oppty.Id);
        oppProd1.Incumbent__c = testCompetitorAccount.Id;
        insert oppProd1;
        System.assertEquals('In Progress',oppProd1.Status__c);
        
        Case caseobj = GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        caseObj.accountId = acc.id;
        caseObj.GEMS_Submission_Type__c ='Renewal';
        insert caseobj;
        Case caseRec = GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        caseRec.accountId = acc.id;
        caseRec.GEMS_Submission_Type__c ='Renewal';
        insert caseRec;
        
        GEMS_Attachment__c attach=GEMS_UtilityClassTest.insertionAttach(caseRec.Id);
        insert attach;
        System.assertEquals('ABS',attach.Type__c);
        
        
        test.starttest();
        ApexPages.currentpage().getParameters().put('id',caseobj.id);
        ApexPages.StandardController std = new ApexPages.standardController(caseobj);
        GEMS_UploadAttachmentController attctrl = new GEMS_UploadAttachmentController(std);
        attctrl.filename='test';
        attctrl.fileBody=Blob.valueOf('Unit Test Attachment Body');
        attctrl.saveCustomAttachment();
        attctrl.getLevelOptions();
        attctrl.getTypeOptions();
        attctrl.processUpload();
        attctrl.back();
        attctrl.getPageNumber();
        attctrl.getTotalPages();
        GEMS_UploadAttachmentController.WrapperClass wrapCls = new GEMS_UploadAttachmentController.WrapperClass(attach);
        wrapCls.checked=true;
        attctrl.allBool=true;
        attctrl.selectAll();
        attctrl.allBool=false;
        attctrl.selectAll();
        attctrl.del();
        attctrl.test();
        
        GEMS_UploadAttachmentController attctrl1 = new GEMS_UploadAttachmentController(std);
        attctrl1.saveCustomAttachment();
        attctrl1.saveStandardAttachment(attach.id);        
        attctrl1.getLevelOptions();
        attctrl1.getTypeOptions();
        attctrl1.filename='test';
        attctrl1.fileBody=Blob.valueOf('');
        attctrl1.processUpload();
        attctrl1.back();
        attctrl1.getPageNumber();
        attctrl1.getTotalPages();
        GEMS_UploadAttachmentController.WrapperClass wrapCls1 = new GEMS_UploadAttachmentController.WrapperClass(attach);
        wrapCls1.checked=true;
        attctrl1.allBool=true;
        attctrl1.selectAll();
        attctrl1.allBool=false;
        attctrl1.selectAll();
        attctrl1.del();
        attctrl1.test();
        
        test.stoptest();
    }
    
    private static testmethod void GEMS_UploadAttachmentController2()
    {
        
        Id CompetitorAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Competitor').getRecordTypeId();
        Account testCompetitorAccount = TestClassUtiltity.createAccountWithRecType('Test Account2', CompetitorAccountRecordTypeId);
        
        Account acc = GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        System.assertEquals('BenefitAgreementControllerTest',acc.Name);
        
        Opportunity oppty= GEMS_UtilityClassTest.insertionOpp1(acc.Id);
        oppty.StageName=GEMS_UtilityClassTest.opportunityStatus();//'In Progress';
        insert oppty;
        System.assertEquals('BenefitAgreementControllerTest',oppty.name);
        
        product2 productRec1=GEMS_UtilityClassTest.insertionProduct1();
        insert productRec1;
        System.assertEquals('HSA',productRec1.Product_Category__c);
        
        Opportunity_Product__c oppProd1=GEMS_UtilityClassTest.insertionOppProd1(productRec1.Id,oppty.Id);
        oppProd1.Incumbent__c = testCompetitorAccount.Id;
        insert oppProd1;
        System.assertEquals('In Progress',oppProd1.Status__c);
        
        Case caseobj = GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        caseObj.accountId = acc.id;
        caseObj.GEMS_Submission_Type__c ='Renewal';
        insert caseobj;
        
        GEMS_Attachment__c attach=GEMS_UtilityClassTest.insertionAttach(caseobj.Id);
        insert attach;
        System.assertEquals('ABS',attach.Type__c);
        
        test.starttest();
        ApexPages.currentpage().getParameters().put('id',caseobj.id);
        ApexPages.StandardController std = new ApexPages.standardController(caseobj);
        GEMS_UploadAttachmentController attctrl = new GEMS_UploadAttachmentController(std);
        attctrl.filename= null;
        attctrl.filebody=null;
        attctrl.processUpload();
        test.stoptest();
    }
    
    private static testmethod void GEMS_UploadAttachmentController3()
    {
        
        Id CompetitorAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Competitor').getRecordTypeId();
        Account testCompetitorAccount = TestClassUtiltity.createAccountWithRecType('Test Account2', CompetitorAccountRecordTypeId);
        
        Account acc = GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        System.assertEquals('BenefitAgreementControllerTest',acc.Name);
        
        Opportunity oppty= GEMS_UtilityClassTest.insertionOpp1(acc.Id);
        oppty.StageName=GEMS_UtilityClassTest.opportunityStatus();//'In Progress';
        insert oppty;
        System.assertEquals('BenefitAgreementControllerTest',oppty.name);
        
        product2 productRec1=GEMS_UtilityClassTest.insertionProduct1();
        insert productRec1;
        System.assertEquals('HSA',productRec1.Product_Category__c);
        
        Opportunity_Product__c oppProd1=GEMS_UtilityClassTest.insertionOppProd1(productRec1.Id,oppty.Id);
        oppProd1.Incumbent__c = testCompetitorAccount.Id;
        insert oppProd1;
        System.assertEquals('In Progress',oppProd1.Status__c);
        
        Case caseobj = GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        caseObj.accountId = acc.id;
        caseObj.GEMS_Submission_Type__c ='Renewal';
        insert caseobj;
        
        GEMS_Attachment__c attach=GEMS_UtilityClassTest.insertionAttach(caseobj.Id);
        insert attach;
        System.assertEquals('ABS',attach.Type__c);
        test.starttest();
        ApexPages.currentpage().getParameters().put('id',caseobj.id);
        ApexPages.StandardController std = new ApexPages.standardController(caseobj);
        GEMS_UploadAttachmentController attctrl = new GEMS_UploadAttachmentController(std);
        attctrl.filename='test';
        attctrl.fileBody=Blob.valueOf('Unit Test Attachment Body');
        attctrl.selectedType='TypeTest';
        attctrl.description='Test';
        attctrl.selectedLevel='TestLevel';
        attctrl.bainfo='Info';
        attctrl.processUpload();
        test.stoptest();
    }
    
    private static testmethod void GEMS_UploadAttachmentController4()
    {
        
        Id CompetitorAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Competitor').getRecordTypeId();
        Account testCompetitorAccount = TestClassUtiltity.createAccountWithRecType('Test Account2', CompetitorAccountRecordTypeId);
        
        Account acc = GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        System.assertEquals('BenefitAgreementControllerTest',acc.Name);
        
        Opportunity oppty= GEMS_UtilityClassTest.insertionOpp1(acc.Id);
        oppty.StageName=GEMS_UtilityClassTest.opportunityStatus();//'In Progress';
        insert oppty;
        System.assertEquals('BenefitAgreementControllerTest',oppty.name);
        
        product2 productRec1=GEMS_UtilityClassTest.insertionProduct1();
        insert productRec1;
        System.assertEquals('HSA',productRec1.Product_Category__c);
        
        Opportunity_Product__c oppProd1=GEMS_UtilityClassTest.insertionOppProd1(productRec1.Id,oppty.Id);
        oppProd1.Incumbent__c = testCompetitorAccount.Id;
        insert oppProd1;
        System.assertEquals('In Progress',oppProd1.Status__c);
        
        Case caseobj = GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        caseObj.accountId = acc.id;
        caseObj.GEMS_Submission_Type__c ='Renewal';
        insert caseobj;
        
        GEMS_Attachment__c attach=GEMS_UtilityClassTest.insertionAttach(caseobj.Id);
        insert attach;
        System.assertEquals('ABS',attach.Type__c);
        test.starttest();
        ApexPages.currentpage().getParameters().put('id',caseobj.id);
        ApexPages.StandardController std = new ApexPages.standardController(caseobj);
        GEMS_UploadAttachmentController attctrl = new GEMS_UploadAttachmentController(std);
        attctrl.filename='test';
        attctrl.fileBody=null;
        attctrl.selectedType='--None--';
        attctrl.description='Test';
        attctrl.selectedLevel='TestLevel';
        attctrl.bainfo='Info';
        attctrl.processUpload();
        test.stoptest();
    }
}