src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Account_Cluster_Name__c</fullName>
        <description>This field is used to capture the name of the marketing individual represented by the cluster number as listed in BlueStar</description>
        <inlineHelpText>This field is pulling the Account Executive name from BlueStar, listed as Account Cluster Name in BlueStar</inlineHelpText>
        <label>Account Executive 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Account_Executive_2__c</fullName>
        <description>This field is used to capture the second Account Executive as listed in BlueStar</description>
        <label>Account Executive 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Underwriter_Name__c</fullName>
        <description>This field is used to capture the name of the Underwriter for the account as listed in BlueStar</description>
        <label>Underwriter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Encryption_Key__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Encryption key used in the environment</description>
    <fields>
        <fullName>Encryption_Key__c</fullName>
        <description>Encryption key for the BlueSTAR integration system</description>
        <label>Encryption Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Encryption Key</label>
</CustomObject>

objects/items_SharePoint__x.object
<CustomObject>
    <externalDataSource>SharePoint</externalDataSource>
    <externalName>items_SharePoint</externalName>
    <label>items_SharePoint</label>
    <pluralLabel>items_SharePoint</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <description>This field is used to capture the requested effective date for the opportunity.</description>
        <label>Opportunity Effective Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote_Request_Summary__c.object
<CustomObject>
    <description>This object is used to store the request summary of the quote request data after is sent to UW.</description>
    <fields>
        <fullName>Account_Executive1_Name__c</fullName>
        <formula>Account_Sales_Executive1__r.FirstName +&apos; &apos;+Account_Sales_Executive1__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Executive1 Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Executive2_Name__c</fullName>
        <formula>Account_Sales_Executive2__r.FirstName +&apos; &apos;+ Account_Sales_Executive2__r.LastName</formula>
        <label>Account Executive2 Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name_tx__c</fullName>
        <label>Account Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <label>Opportunity Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Name</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Request</relationshipLabel>
        <relationshipName>Quote_Request_Summarys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Description__c</fullName>
        <description>Required when Get Rate button is clicked to make callout to Heron.</description>
        <label>Quote Req Desc</label>
        <length>53</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Effective_Date__c</fullName>
        <label>Request Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <label>Sales Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Sales</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Up Sales</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Request</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Quote Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Requests</pluralLabel>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SharePoint_Configuration__mdt.object
<CustomObject>
    <label>SharePoint Configuration</label>
    <pluralLabel>SharePoint Configurations</pluralLabel>
</CustomObject>

objects/SharePoint_TEST_HeronQuotes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Access_Token_1__c</fullName>
        <label>Access Token 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_2__c</fullName>
        <label>Access Token 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_3__c</fullName>
        <label>Access Token 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_4__c</fullName>
        <label>Access Token 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_5__c</fullName>
        <label>Access Token 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URI__c</fullName>
        <label>Redirect URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token_1__c</fullName>
        <label>Refresh Token 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token_2__c</fullName>
        <label>Refresh Token 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SharePoint TEST HeronQuotes</label>
</CustomObject>

classes/QuoteFilesConnectTest.cls
@isTest
public class QuoteFilesConnectTest {

    static public List<Case> accSubCase;
    static public Account accRec;
    static public product2 prd;
    static public case cs2;
    static User userIntProfile;
    String callingSource = 'LGNAQuoteRq';
    @testSetup
    static void dataSetupQR() {
                     
        OrganizationDAO.IOrganizationDAO organizationDAOInstance = new OrganizationDAO();        
        SharePoint_TEST_HeronQuotes__c cs = new SharePoint_TEST_HeronQuotes__c();
        if (!organizationDAOInstance.isRunningInSandbox()) {
            cs.Name = System.URL.getSalesforceBaseUrl().getHost().substringbefore('.').toLowerCase();
        } else {
            cs.Name = System.URL.getSalesforceBaseUrl().getHost().substringAfterLast('--').substringbefore('.').toLowerCase();
        }              
        cs.Access_Token_1__c = '00000000000000000000000000000000';
        cs.Access_Token_2__c = '00000000000000000000000000000000';
        cs.Access_Token_3__c = '00000000000000000000000000000000';
        cs.Access_Token_4__c = '00000000000000000000000000000000';
        cs.Access_Token_5__c = '00000000000000000000000000000000';
        cs.Client_ID__c = '123456789ABCDEFG';
        cs.Client_Secret__c = 'secret';
        cs.Redirect_URI__c = System.URL.getSalesforceBaseUrl().getHost().toLowerCase();
        cs.Refresh_Token_1__c = '00000000000000000000000000000000';
        cs.Refresh_Token_2__c = '00000000000000000000000000000000';
        insert cs;
               
        Test.startTest();
        
        Id groudActRecId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
		Account groupAccount = TestClassUtiltity.createAccountWithRecType('Test Account234', groudActRecId);
		groupAccount.Underwriter_Name__c='Smith Testing';
		groupAccount.Account_Executive_2__c='Smith Testing';
		groupAccount.Account_Cluster_Name__c='Smith Testing';
		update groupAccount;
		         
	    List<Opportunity> testOpp = TestClassUtiltity.CreateOpportunities(groupAccount.Id);
		testOpp[0].Requested_Effective_Date__c = System.now().date();//oppName 1
		testOpp[0].RecordtypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Sale').getRecordTypeId();
		testOpp[1].RecordtypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
	    testOpp[2].RecordtypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Sale').getRecordTypeId();
		insert testOpp;
		
			
	Profile uw = [SELECT Id FROM Profile WHERE Name = 'Underwriting'];
		User uwUser = new User(Alias = 'standt12', Email = 'smit.testing@testorg24.com',EmailEncodingKey = 'UTF-8', LastName = 'Testing', FirstName = 'Smith', LanguageLocaleKey = 'en_US',LocaleSidKey = 'en_US', ProfileId = uw.Id, TimeZoneSidKey = 'America/Los_Angeles',UserName = 'smith.testing@testorg24.com', isActive = TRUE);
		insert uwUser;
		
		
	  Id PriceBook2Id =TestClassUtiltity.getNonStandardPriceBook('Underwriting Price Book');
	  Quote existingQuote=TestClassUtiltity.createQuote(testOpp[0].id);
	  existingQuote.pricebook2Id=priceBook2Id;
	  insert existingQuote;
	  
	  Quote_Request_Summary__c testReq=TestClassUtiltity.createQuoteReq(existingQuote.id, uwUser.id);
	  testReq.Opportunity_Name__c=testOpp[0].name;
      testReq.Opportunity_Id__c=String.valueOf(testOpp[0].id);
      testReq.Request_Description__c='testreq123';
      //testReq.Account_Executive2_Name__c='John Smith';
      //testReq.Account_Executive1_Name__c='Test dummy';
      testReq.HCSC_Division__c='IL';
      testReq.Account_Name_tx__c='Heron test Account';
      testReq.Account_Number__c='0000555';
      testReq.Request_Effective_Date__c=system.today();
      testReq.Sales_Type__c='New Sale';
	    insert testReq;
   
        Test.stopTest();                     
       
    }
    
     @isTest static void testMethodQR() {
        Test.startTest();
        Profile profileRec = [SELECT Id FROM Profile WHERE Name='Integration Profile'];
        List<User> userList = new List<User>();
        User testUser1 = GEMS_UtilityClassTest.CreateUserRecord(profileRec.Id, 'test1@user11.com', 'testUser1', 'test1@user.com');
        userList.add(testUser1);
        insert userList;
        //userIntProfile = userList[0];
        
          Id groudActRecId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
		Account groupAccount = TestClassUtiltity.createAccountWithRecType('Test Account234', groudActRecId);
		groupAccount.Underwriter_Name__c='Smith Testing';
		groupAccount.Account_Executive_2__c='Smith Testing';
		groupAccount.Account_Cluster_Name__c='Smith Testing';
		update groupAccount;
		         
	    List<Opportunity> testOpp = TestClassUtiltity.CreateOpportunities(groupAccount.Id);
		testOpp[0].Requested_Effective_Date__c = System.now().date();//oppName 1
		testOpp[0].RecordtypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Sale').getRecordTypeId();
		testOpp[1].RecordtypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
	    testOpp[2].RecordtypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Sale').getRecordTypeId();
		insert testOpp;
		
		
         
	Profile uw = [SELECT Id FROM Profile WHERE Name = 'Underwriting'];
		User uwUser1 = new User(Alias = 'standt12', Email = 'smit.testing@testorg24.com',EmailEncodingKey = 'UTF-8', LastName = 'Testing', FirstName = 'Smith', LanguageLocaleKey = 'en_US',LocaleSidKey = 'en_US', ProfileId = uw.Id, TimeZoneSidKey = 'America/Los_Angeles',UserName = 'smith.testing1@testorg24.com', isActive = TRUE);
		insert uwUser1;
		
		
	  Id PriceBook2Id =TestClassUtiltity.getNonStandardPriceBook('Underwriting Price Book');
	  Quote existingQuote=TestClassUtiltity.createQuote(testOpp[0].id);
	  existingQuote.pricebook2Id=priceBook2Id;
	  insert existingQuote;
	  
	  Quote_Request_Summary__c testReq=TestClassUtiltity.createQuoteReq(existingQuote.id, uwUser1.id);
	  testReq.Opportunity_Name__c=testOpp[0].name;
      testReq.Opportunity_Id__c=String.valueOf(testOpp[0].id);
      testReq.Request_Description__c='testreq123';
      //testReq.Account_Executive2_Name__c='John Smith';
      //testReq.Account_Executive1_Name__c='Test dummy';
      testReq.HCSC_Division__c='IL';
      testReq.Account_Name_tx__c='Heron test Account';
      testReq.Account_Number__c='0000555';
      testReq.Quote_Name__c = existingQuote.Id;      
      testReq.Request_Effective_Date__c=system.today();            
      testReq.Sales_Type__c='New Sale';
	    insert testReq;
         //system.assertEquals(testReq.Id, existingQuote.Id);
       
        //PageReference pageRef = Page.QuoteRequestSharepoint;
        //Test.setCurrentPage(pageRef);
         
        //Quote_Request_Summary__c c = [SELECT Id FROM Quote_Request_Summary__c LIMIT 1];
        ApexPages.CurrentPage().getParameters().put('id', existingQuote.id);
        Encryption_Key__c testKey = new Encryption_Key__c();
        testKey.Name = 'Test Key';
        testKey.Encryption_Key__c = EncodingUtil.base64Encode(Crypto.generateAesKey(256));
        testKey.SetupOwnerId = profileRec.Id;
        insert testKey;
         
        ApexPages.StandardController std = new ApexPages.StandardController(existingQuote);
         //QuoteFilesConnect con = new QuoteFilesConnect(std);
         
         //SharePoint_Configuration__mdt sharePointConfiguration;
         
         //CaseDAO.ICaseDAO caseDAOInstance;
         CaseDAO caseDAOInstance = new CaseDAO();
         ItemsSharePointDAO.IItemsSharePointDAO itemsSharePointDAOInstance;
         //SharePointCalloutUtility.ISharePointCalloutUtility sharePointCalloutUtilityInstance;
         SharePointConfiguration sharePointConfiguration = new SharePointConfiguration('LGNAQuoteRq'); 
         SharePointCalloutUtility sharePointCalloutUtilityInstance = new  SharePointCalloutUtility(sharePointConfiguration);
           QuoteFilesConnect con = new QuoteFilesConnect(std,
                                           caseDAOInstance,
                                           itemsSharePointDAOInstance,
                                           sharePointCalloutUtilityInstance,
                                           SharePointConfiguration);
         
         /*QuoteFilesConnect(ApexPages.StandardController std,
                                           CaseDAO.ICaseDAO caseDAOInstance,
                                           ItemsSharePointDAO.IItemsSharePointDAO itemsSharePointDAOInstance,
                                           SharePointCalloutUtility.ISharePointCalloutUtility sharePointCalloutUtilityInstance,
                                           SharePointConfiguration sharePointConfiguration)*/

                
        try{    
          con.pageSize = 0;
          con.totalNoOfRecs = 1;
          con.getInitialDocumentSet();
        } catch(System.MathException e) {
          System.assert(true);
        }
    
        con.totalNoOfRecs = 0;
        con.pageSize = 2;
        con.getInitialDocumentSet();
    
        con.totalNoOfRecs = 3;
        con.getInitialDocumentSet();
         try{
          con.next();
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
        System.assertEquals(1, con.pageNumber);
    
        try{
          con.previous();
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
    
        try{
          con.previous();
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
    
        con.fileType = 'application';
        con.fileName = 'Test file name';
        con.linkFile();
        con.fileType = 'other';
        con.fileName = 'Test file name';
        con.linkFile();
        try{
            con.fileType = 'other';
            con.fileName = 'Test file name';
            con.SFlinkFile(con.fileName);
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
        
        //con.isAuthUser= true;
        con.verifySharePointButton();
        try{
            con.downloadURL();
            con.fileType = 'application';
            con.fileName = 'abcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklAASmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcde';
            con.subStringAttachmentName(con.fileName);
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
        Test.stopTest();
        
    }
    
      @isTest static void testMethodQR2() {
        Test.startTest();
        Profile profileRec = [SELECT Id FROM Profile WHERE Name='Integration Profile'];
        List<User> userList = new List<User>();
        User testUser1 = GEMS_UtilityClassTest.CreateUserRecord(profileRec.Id, 'test1@user11.com', 'testUser1', 'test1@user.com');
        userList.add(testUser1);
        insert userList;
        //userIntProfile = userList[0];
        
          Id groudActRecId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
		Account groupAccount = TestClassUtiltity.createAccountWithRecType('Test Account234', groudActRecId);
		groupAccount.Underwriter_Name__c='Smith Testing';
		groupAccount.Account_Executive_2__c='Smith Testing';
		groupAccount.Account_Cluster_Name__c='Smith Testing';
		update groupAccount;
		         
	    List<Opportunity> testOpp = TestClassUtiltity.CreateOpportunities(groupAccount.Id);
		testOpp[0].Requested_Effective_Date__c = System.now().date();//oppName 1
		testOpp[0].RecordtypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Sale').getRecordTypeId();
		testOpp[1].RecordtypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
	    testOpp[2].RecordtypeId=Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Sale').getRecordTypeId();
		insert testOpp;
		
		
         
	Profile uw = [SELECT Id FROM Profile WHERE Name = 'Underwriting'];
		User uwUser1 = new User(Alias = 'standt12', Email = 'smit.testing@testorg24.com',EmailEncodingKey = 'UTF-8', LastName = 'Testing', FirstName = 'Smith', LanguageLocaleKey = 'en_US',LocaleSidKey = 'en_US', ProfileId = uw.Id, TimeZoneSidKey = 'America/Los_Angeles',UserName = 'smith.testing2@testorg24.com', isActive = TRUE);
		insert uwUser1;
		
		
	  Id PriceBook2Id =TestClassUtiltity.getNonStandardPriceBook('Underwriting Price Book');
	  Quote existingQuote=TestClassUtiltity.createQuote(testOpp[0].id);
	  existingQuote.pricebook2Id=priceBook2Id;
	  insert existingQuote;
	  
	  Quote_Request_Summary__c testReq=TestClassUtiltity.createQuoteReq(existingQuote.id, uwUser1.id);
	  testReq.Opportunity_Name__c=testOpp[0].name;
      testReq.Opportunity_Id__c=String.valueOf(testOpp[0].id);
      testReq.Request_Description__c='testreq123';
      //testReq.Account_Executive2_Name__c='John Smith';
      //testReq.Account_Executive1_Name__c='Test dummy';
      testReq.HCSC_Division__c='IL';
      testReq.Account_Name_tx__c='Heron test Account';
      testReq.Account_Number__c='0000555';
      testReq.Quote_Name__c = existingQuote.Id;      
      testReq.Request_Effective_Date__c=system.today();            
      testReq.Sales_Type__c='New Sale';
	    insert testReq;
         //system.assertEquals(testReq.Id, existingQuote.Id);
       
        //PageReference pageRef = Page.QuoteRequestSharepoint;
        //Test.setCurrentPage(pageRef);
         
        //Quote_Request_Summary__c c = [SELECT Id FROM Quote_Request_Summary__c LIMIT 1];
        ApexPages.CurrentPage().getParameters().put('id', testReq.id);
        Encryption_Key__c testKey = new Encryption_Key__c();
        testKey.Name = 'Test Key';
        testKey.Encryption_Key__c = EncodingUtil.base64Encode(Crypto.generateAesKey(256));
        testKey.SetupOwnerId = profileRec.Id;
        insert testKey;
         
        ApexPages.StandardController std = new ApexPages.StandardController(testReq);
         //QuoteFilesConnect con = new QuoteFilesConnect(std);
         
         //SharePoint_Configuration__mdt sharePointConfiguration;
         
         //CaseDAO.ICaseDAO caseDAOInstance;
         CaseDAO caseDAOInstance = new CaseDAO();
         ItemsSharePointDAO.IItemsSharePointDAO itemsSharePointDAOInstance;
         //SharePointCalloutUtility.ISharePointCalloutUtility sharePointCalloutUtilityInstance;
         SharePointConfiguration sharePointConfiguration = new SharePointConfiguration('LGNAQuoteRq'); 
         SharePointCalloutUtility sharePointCalloutUtilityInstance = new  SharePointCalloutUtility(sharePointConfiguration);
           QuoteFilesConnect con = new QuoteFilesConnect(std,
                                           caseDAOInstance,
                                           itemsSharePointDAOInstance,
                                           sharePointCalloutUtilityInstance,
                                           SharePointConfiguration);
         
         /*QuoteFilesConnect(ApexPages.StandardController std,
                                           CaseDAO.ICaseDAO caseDAOInstance,
                                           ItemsSharePointDAO.IItemsSharePointDAO itemsSharePointDAOInstance,
                                           SharePointCalloutUtility.ISharePointCalloutUtility sharePointCalloutUtilityInstance,
                                           SharePointConfiguration sharePointConfiguration)*/

                
        try{    
          con.pageSize = 0;
          con.totalNoOfRecs = 1;
          con.getInitialDocumentSet();
        } catch(System.MathException e) {
          System.assert(true);
        }
    
        con.totalNoOfRecs = 0;
        con.pageSize = 2;
        con.getInitialDocumentSet();
    
        con.totalNoOfRecs = 3;
        con.getInitialDocumentSet();
         try{
          con.next();
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
        System.assertEquals(1, con.pageNumber);
    
        try{
          con.previous();
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
    
        try{
          con.previous();
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
    
        con.fileType = 'application';
        con.fileName = 'Test file name';
        con.linkFile();
        con.fileType = 'other';
        con.fileName = 'Test file name';
        con.linkFile();
        try{
            con.fileType = 'other';
            con.fileName = 'Test file name';
            con.SFlinkFile(con.fileName);
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
        
        //con.isAuthUser= true;
        con.verifySharePointButton();
        try{
            con.downloadURL();
            con.fileType = 'application';
            con.fileName = 'abcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklAASmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyzabcde';
            con.subStringAttachmentName(con.fileName);
        } catch(System.NullPointerException e){
          //Requires Items_Sharepoint__x External Object to be populated, cannot do this
          System.assert(true);
        }
        Test.stopTest();
        
    }

}