src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>This field is used to capture the error message received from BlueStar during Account reservation if the callout is not successful.</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Line_of_business__c</fullName>
        <label>Line of business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ENA,</fullName>
                    <label>ENA</label>
                </value>
                <value>
                    <fullName>Major National</fullName>
                </value>
                <value>
                    <fullName>Major National GET</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Municipal</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>Student Health</fullName>
                </value>
                <value>
                    <fullName>ENA GET</fullName>
                </value>
                <value>
                    <fullName>Large/Mid Market</fullName>
                </value>
                <value>
                    <fullName>Municipal GET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <description>the CLass from which error is thrown.</description>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Group_Section__c.object
<CustomObject>
    <description>Group Section information associated to a Group Account will be stored using this object</description>
    <fields>
        <fullName>Group_Account__c</fullName>
        <description>Group Section related to the Group Account</description>
        <label>Group Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Group Sections</relationshipLabel>
        <relationshipName>Group_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Group Section</label>
    <nameField>
        <displayFormat>GS-{000000}</displayFormat>
        <label>Group Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>changed field from number to text as suggested by cesar</inlineHelpText>
        <label>Zip Code</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Plan__c.object
<CustomObject>
    <description>To capture all the plans related to products - Loaded from BlueStar</description>
    <fields>
        <fullName>Line_Of_Business__c</fullName>
        <label>Line Of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>HDL</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Census__c.object
<CustomObject>
    <description>This object is used  for</description>
    <fields>
        <fullName>Dental_Group_Section__c</fullName>
        <label>Dental Group Section</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dental_Plan_ID__c</fullName>
        <label>Dental Plan ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Health_Group_Section__c</fullName>
        <label>Health Group Section</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Health_Plan_ID__c</fullName>
        <label>Health Plan ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Group_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Group Section</label>
        <referenceTo>SGR_Opportunity_Group_Section__c</referenceTo>
        <relationshipLabel>Opportunity Censuses</relationshipLabel>
        <relationshipName>Opportunity_Censuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <label>Plan Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscriber</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Civil Union Spouse</fullName>
                </value>
                <value>
                    <fullName>Class II Dependent</fullName>
                </value>
                <value>
                    <fullName>Dependent Child</fullName>
                </value>
                <value>
                    <fullName>Disabled Dependent</fullName>
                </value>
                <value>
                    <fullName>Sponsored Dependent- Child</fullName>
                </value>
                <value>
                    <fullName>Sponsored Dep-Adult</fullName>
                </value>
                <value>
                    <fullName>Surviving Spouse</fullName>
                </value>
                <value>
                    <fullName>Ex-Civil Union Spouse</fullName>
                </value>
                <value>
                    <fullName>Ex-Spouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vision_Group_Section__c</fullName>
        <label>Vision Group Section</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vision_Plan_ID__c</fullName>
        <description>Plan ID. Only applicable to Vision Subscriber section for NM &amp; MT.</description>
        <label>Vision Plan ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Opportunity Census</label>
    <nameField>
        <label>Opportunity Census Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Censuses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Group_Section__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Group_Section_Number__c</fullName>
        <displayFormat>OGS-{0000}</displayFormat>
        <label>Opportunity Group Section Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Opportunity Group Section</label>
    <nameField>
        <label>Opportunity Group Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Group Section</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Member_Benefits__c.object
<CustomObject>
    <description>This object acts as a junction object between the Opportunity Group Section and Opportunity Census objects</description>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <formula>TEXT(Opportunity_Plan_Rate__r.Plan__r.Line_Of_Business__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Census__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Census</label>
        <referenceTo>SGR_Opportunity_Census__c</referenceTo>
        <relationshipLabel>Opportunity Member Benefits</relationshipLabel>
        <relationshipName>Opportunity_Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Group_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Group Section</label>
        <referenceTo>SGR_Opportunity_Group_Section__c</referenceTo>
        <relationshipLabel>Opportunity Member Benefits</relationshipLabel>
        <relationshipName>Opportunity_Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Plan_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Plan Rate</label>
        <referenceTo>SGR_Opportunity_Plan_Rate__c</referenceTo>
        <relationshipLabel>Opportunity Member Benefits</relationshipLabel>
        <relationshipName>Opportunity_Member_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Member Benefits</label>
    <nameField>
        <label>Opportunity Member Benefits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Member Benefits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Plan_Rate__c.object
<CustomObject>
    <description>This object contains details about opportunity plan Rates.</description>
    <fields>
        <fullName>Group_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Section</label>
        <referenceTo>SGR_Opportunity_Group_Section__c</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <label>Plan Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Alternate</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                    <isActive>false</isActive>
                    <label>Alternative</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Plan Rate</label>
    <nameField>
        <label>Opportunity Plan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGR_Trigger_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Controls SGR Triggers</description>
    <fields>
        <fullName>Trigger_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking indicates that Trigger will execute</description>
        <label>Trigger Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trigger_Name__c</fullName>
        <description>Name of the Trigger Class</description>
        <label>Trigger Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_SubMethod__c</fullName>
        <description>Method inside the Trigger to be controlled.</description>
        <label>Trigger SubMethod</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SGR Trigger Settings</label>
</CustomObject>

classes/Trigger_SGR_Opportunity_Census_test.cls
@isTest 
private class Trigger_SGR_Opportunity_Census_test {
    
    @testSetup static void setup() {                      
                
        List<SGR_Trigger_Settings__c> triggerCustomSettings = new List<SGR_Trigger_Settings__c>();
        
        SGR_Trigger_Settings__c entry001 = new SGR_Trigger_Settings__c();
        entry001.Name = 'entry001';
        entry001.Trigger_Is_Active__c = true;
        entry001.Trigger_Name__c = 'Trigger_SGR_Opportunity_Census';
        entry001.Trigger_SubMethod__c = 'createSGROpportunityMemberBenefits';
        triggerCustomSettings.add(entry001);
        
        SGR_Trigger_Settings__c entry002 = new SGR_Trigger_Settings__c();
        entry002.Name = 'entry002';
        entry002.Trigger_Is_Active__c = true;
        entry002.Trigger_Name__c = 'Trigger_SGR_Opportunity_Census';
        entry002.Trigger_SubMethod__c = 'updateSGROpportunityMemberBenefits';
        triggerCustomSettings.add(entry002);
        
        SGR_Trigger_Settings__c entry003 = new SGR_Trigger_Settings__c();
        entry003.Name = 'entry003';
        entry003.Trigger_Is_Active__c = true;
        entry003.Trigger_Name__c = 'Trigger_SGR_Opportunity_Census';
        entry003.Trigger_SubMethod__c = 'deleteSGROpportunityMemberBenefits';        
        triggerCustomSettings.add(entry003);
        
        insert triggerCustomSettings;

        List<Plan__c> listPlans = new List<Plan__c>();
        
        for (Integer i = 0 ; i < 5; i++) {
            Plan__c aPlan = new Plan__c();
            aPlan.Name = 'Test Health Plan' + String.valueOf(i);
            aPlan.Line_Of_Business__c = 'H';        
            listPlans.add(aPlan);        
        }        
        
        for (Integer i = 0 ; i < 5; i++) {
            Plan__c aPlan = new Plan__c();
            aPlan.Name = 'Test Vision Plan' + String.valueOf(i);
            aPlan.Line_Of_Business__c = 'V';        
            listPlans.add(aPlan);        
        }        
        
        for (Integer i = 0 ; i < 5; i++) {
            Plan__c aPlan = new Plan__c();
            aPlan.Name = 'Test Dental Plan' + String.valueOf(i);
            aPlan.Line_Of_Business__c = 'D';        
            listPlans.add(aPlan);        
        }       
        
        insert listPlans;   
        
        List<Plan__c> listHealthPlans = new List<Plan__c>();
        List<Plan__c> listVisionPlans = new List<Plan__c>();
        List<Plan__c> listDentalPlans = new List<Plan__c>();
        
        listHealthPlans = [SELECT Id, Name, Line_Of_Business__c FROM Plan__c WHERE Line_Of_Business__c = 'H']; 
        System.debug('listHealthPlans: ' + listHealthPlans.size());
        listVisionPlans = [SELECT Id, Name, Line_Of_Business__c FROM Plan__c WHERE Line_Of_Business__c = 'V']; 
        System.debug('listVisionPlans: ' + listVisionPlans.size());
        listDentalPlans = [SELECT Id, Name, Line_Of_Business__c FROM Plan__c WHERE Line_Of_Business__c = 'D']; 
        System.debug('listDentalPlans: ' + listDentalPlans.size());
                
        List<SGR_Opportunity_Plan_Rate__c> listOpportunityPlanRates = new List<SGR_Opportunity_Plan_Rate__c>();
        
        for (Integer i = 0 ; i < 5; i++) {
            SGR_Opportunity_Plan_Rate__c aRate = new SGR_Opportunity_Plan_Rate__c();
            aRate.Name = 'TestHealthRate' + String.valueOf(i);
            aRate.Plan_Name__c = 'Health' + String.valueOf(i);  //Health1, Health2, etc.
            aRate.Type__c = 'Renewal';
            if(listHealthPlans.size() == 5){
                aRate.Plan__c = listHealthPlans[i].Id;                
            }            
            listOpportunityPlanRates.add(aRate);            
        }       
        
        for (Integer i = 0 ; i < 5; i++) {
            SGR_Opportunity_Plan_Rate__c aRate = new SGR_Opportunity_Plan_Rate__c();
            aRate.Name = 'TestDentalRate' + String.valueOf(i);
            aRate.Plan_Name__c = 'Dental' + String.valueOf(i); //Dental1, Dental2, etc.
            aRate.Type__c = 'Renewal';
            if(listDentalPlans.size() == 5){
                aRate.Plan__c = listDentalPlans[i].Id;                
            }            
            listOpportunityPlanRates.add(aRate);            
        }       
        
        for (Integer i = 0 ; i < 5; i++) {
            SGR_Opportunity_Plan_Rate__c aRate = new SGR_Opportunity_Plan_Rate__c();
            aRate.Name = 'TestVisionRate' + String.valueOf(i);
            aRate.Plan_Name__c = 'Vision' + String.valueOf(i); //Vision1, Vision2, etc.
            aRate.Type__c = 'Renewal';
            if(listVisionPlans.size() == 5){
                aRate.Plan__c = listVisionPlans[i].Id;                
            }
            listOpportunityPlanRates.add(aRate);            
        }       
        
        insert listOpportunityPlanRates;

        Account testAccount = Sgr_TestDataUtility.createAcc('TestAccount', 773, 'ExID56', 'IL', System.today(), 'Active', 'SG', 'PREM');
        
        List<Group_Section__c> listGroupSections = new List<Group_Section__c>();
        
        Group_Section__c aGroupSection = new Group_Section__c();
        aGroupSection.Group_Account__c = testAccount.Id;
        listGroupSections.add(aGroupSection);
        
        insert listGroupSections;
        
        List<SGR_Opportunity_Group_Section__c> listOpportunityGroupSections = new List<SGR_Opportunity_Group_Section__c>();
        
        SGR_Opportunity_Group_Section__c anOpportunityGroupSection = new SGR_Opportunity_Group_Section__c(); 
        anOpportunityGroupSection.Name = 'Test Opp Grp Section';
        listOpportunityGroupSections.add(anOpportunityGroupSection);
        
        insert listOpportunityGroupSections;
        
    }
    
    static testMethod void testInsertUpdateVersion1(){
        
        List<SGR_Opportunity_Group_Section__c> listOpportunityGroupSections = new List<SGR_Opportunity_Group_Section__c>();
        listOpportunityGroupSections = [SELECT Id, Name, Opportunity_Group_Section_Number__c FROM SGR_Opportunity_Group_Section__c LIMIT 1];        
        
        SGR_Opportunity_Census__c aRecord = new SGR_Opportunity_Census__c();
        aRecord.Name = 'Test Opportunity Census 001';
        aRecord.Gender__c = 'M';
        aRecord.Zip_Code__c = '60601';
        aRecord.Relationship__c = 'Subscriber';
        aRecord.Health_Plan_ID__c = 'Health1'; 
        aRecord.Health_Group_Section__c = String.valueOf(listOpportunityGroupSections[0].Opportunity_Group_Section_Number__c);
        aRecord.Dental_Plan_ID__c = 'Dental2';
        aRecord.Dental_Group_Section__c = String.valueOf(listOpportunityGroupSections[0].Opportunity_Group_Section_Number__c);
        aRecord.Vision_Plan_ID__c = 'Vision3';
        aRecord.Vision_Group_Section__c = String.valueOf(listOpportunityGroupSections[0].Opportunity_Group_Section_Number__c);
        
        //test the Insert
        insert aRecord;
        
        String QueryString = 'SELECT count() FROM SGR_Opportunity_Member_Benefits__c'; 
        Integer countOpportunityMemberBenefits = Database.countQuery(QueryString);        
        System.debug('countOpportunityMemberBenefits after Insert: ' + countOpportunityMemberBenefits);
        
        //test the Update
        aRecord = [SELECT 
                   Id, 
                   Name, 
                   Gender__c, 
                   Zip_Code__c,
                   Relationship__c,
                   Health_Plan_ID__c,
                   Dental_Plan_ID__c,
                   Vision_Plan_ID__c
                   FROM SGR_Opportunity_Census__c];
        
        aRecord.Name = 'Test Opportunity Census 002';
        aRecord.Gender__c = 'F';
        aRecord.Relationship__c = 'Spouse';
        aRecord.Health_Plan_ID__c = 'Health2';
        aRecord.Dental_Plan_ID__c = 'Dental3';
        aRecord.Vision_Plan_ID__c = 'Vision4';
        
        update aRecord;    
        
        List<Error_Log__c> listErrorLogs = new List<Error_Log__c>();
        listErrorLogs = [SELECT Id, Class__c, Error_Message__c FROM Error_Log__c LIMIT 100];
        
        for(Error_Log__c aLog : listErrorLogs){
            System.debug('testInsertUpdate Error Log: ' + aLog.Class__c + ' ' +  aLog.Error_Message__c);
        }
    }
    
    static testMethod void testInsertUpdateVersion2(){
        
        List<SGR_Opportunity_Group_Section__c> listOpportunityGroupSections = new List<SGR_Opportunity_Group_Section__c>();
        listOpportunityGroupSections = [SELECT Id, Name, Opportunity_Group_Section_Number__c FROM SGR_Opportunity_Group_Section__c LIMIT 1];        
        
        SGR_Opportunity_Census__c aRecord = new SGR_Opportunity_Census__c();
        aRecord.Name = 'Test Opportunity Census 001';
        aRecord.Gender__c = 'M';
        aRecord.Zip_Code__c = '60601';
        aRecord.Relationship__c = 'Subscriber';
        aRecord.Health_Plan_ID__c = 'Health1'; 
        aRecord.Health_Group_Section__c = String.valueOf(listOpportunityGroupSections[0].Opportunity_Group_Section_Number__c);
        aRecord.Dental_Plan_ID__c = 'Dental2';
        aRecord.Dental_Group_Section__c = String.valueOf(listOpportunityGroupSections[0].Opportunity_Group_Section_Number__c);
        aRecord.Vision_Plan_ID__c = 'Vision3';
        aRecord.Vision_Group_Section__c = String.valueOf(listOpportunityGroupSections[0].Opportunity_Group_Section_Number__c);
        
        //test the Insert
        insert aRecord;
        
        String QueryString = 'SELECT count() FROM SGR_Opportunity_Member_Benefits__c'; 
        Integer countOpportunityMemberBenefits = Database.countQuery(QueryString);        
        System.debug('countOpportunityMemberBenefits after Insert: ' + countOpportunityMemberBenefits);
        
        //test the Update
        aRecord = [SELECT 
                   Id, 
                   Name, 
                   Gender__c, 
                   Zip_Code__c,
                   Relationship__c,
                   Health_Plan_ID__c,
                   Dental_Plan_ID__c,
                   Vision_Plan_ID__c
                   FROM SGR_Opportunity_Census__c];
        
        aRecord.Name = 'Test Opportunity Census 001';
        aRecord.Gender__c = 'F';
        aRecord.Relationship__c = 'Spouse';
        aRecord.Health_Plan_ID__c = null;
        aRecord.Dental_Plan_ID__c = 'Dental3';
        aRecord.Vision_Plan_ID__c = 'Vision4';
        
        update aRecord;    
        
        List<Error_Log__c> listErrorLogs = new List<Error_Log__c>();
        listErrorLogs = [SELECT Id, Class__c, Error_Message__c FROM Error_Log__c LIMIT 100];
        
        for(Error_Log__c aLog : listErrorLogs){
            System.debug('testInsertUpdate Error Log: ' + aLog.Class__c + ' ' +  aLog.Error_Message__c);
        }
    }
       
    static testMethod void testInsertUpdateVersion3(){
        
        List<SGR_Opportunity_Group_Section__c> listOpportunityGroupSections = new List<SGR_Opportunity_Group_Section__c>();
        listOpportunityGroupSections = [SELECT Id, Name, Opportunity_Group_Section_Number__c FROM SGR_Opportunity_Group_Section__c LIMIT 1];        
        
        SGR_Opportunity_Census__c aRecord = new SGR_Opportunity_Census__c();
        aRecord.Name = 'Test Opportunity Census 003';
        aRecord.Gender__c = 'M';
        aRecord.Zip_Code__c = '60601';
        aRecord.Relationship__c = 'Subscriber';
        aRecord.Health_Plan_ID__c = null;
        aRecord.Health_Group_Section__c = null;
        aRecord.Dental_Plan_ID__c = 'Dental2';
        aRecord.Dental_Group_Section__c = String.valueOf(listOpportunityGroupSections[0].Opportunity_Group_Section_Number__c);
        aRecord.Vision_Plan_ID__c = 'Vision3';
        aRecord.Vision_Group_Section__c = String.valueOf(listOpportunityGroupSections[0].Opportunity_Group_Section_Number__c);
        
        //test the Insert
        insert aRecord;
        
        String QueryString = 'SELECT count() FROM SGR_Opportunity_Member_Benefits__c'; 
        Integer countOpportunityMemberBenefits = Database.countQuery(QueryString);        
        System.debug('countOpportunityMemberBenefits after Insert: ' + countOpportunityMemberBenefits);
        
        //test the Update
        aRecord = [SELECT 
                   Id, 
                   Name, 
                   Gender__c, 
                   Zip_Code__c,
                   Relationship__c,
                   Health_Plan_ID__c,
                   Health_Group_Section__c,
                   Dental_Plan_ID__c,
                   Dental_Group_Section__c,
                   Vision_Plan_ID__c,
                   Vision_Group_Section__c
                   FROM SGR_Opportunity_Census__c];
        
        aRecord.Name = 'Test Opportunity Census 003';
        aRecord.Gender__c = 'F';
        aRecord.Relationship__c = 'Spouse';
        aRecord.Health_Plan_ID__c = 'Health1';
        aRecord.Health_Group_Section__c = String.valueOf(listOpportunityGroupSections[0].Opportunity_Group_Section_Number__c);
        aRecord.Dental_Plan_ID__c = 'Dental2';
        aRecord.Vision_Plan_ID__c = 'Vision3';
        
        countOpportunityMemberBenefits = Database.countQuery(QueryString);        
        System.debug('countOpportunityMemberBenefits before Update: ' + countOpportunityMemberBenefits);
       
        update aRecord;    
        
        countOpportunityMemberBenefits = Database.countQuery(QueryString);        
        System.debug('countOpportunityMemberBenefits after Update: ' + countOpportunityMemberBenefits);

        
        List<Error_Log__c> listErrorLogs = new List<Error_Log__c>();
        listErrorLogs = [SELECT Id, Class__c, Error_Message__c FROM Error_Log__c LIMIT 100];
        
        for(Error_Log__c aLog : listErrorLogs){
            System.debug('testInsertUpdate Error Log: ' + aLog.Class__c + ' ' +  aLog.Error_Message__c);
        }
    }
    
    static testMethod void testDelete(){
        
        SGR_Opportunity_Census__c aRecord = new SGR_Opportunity_Census__c();
        aRecord.Name = 'Test Opportunity Census 001';
        aRecord.Gender__c = 'M';
        aRecord.Zip_Code__c = '60601';
        aRecord.Relationship__c = 'Subscriber';
        aRecord.Health_Plan_ID__c = 'Health1';
        aRecord.Dental_Plan_ID__c = 'Dental2';
        aRecord.Vision_Plan_ID__c = 'Vision3';
        
        //test the Insert
        insert aRecord;
        
        List<SGR_Opportunity_Member_Benefits__c> listOppMbrBene = new List<SGR_Opportunity_Member_Benefits__c>();
        listOppMbrBene = [SELECT 
                          ID,
                          Name,
                          Opportunity_Census__c,
                          Opportunity_Group_Section__c,
                          Opportunity_Plan_Rate__c
                          FROM SGR_Opportunity_Member_Benefits__c];
        
        system.debug('BEFORE listOppMbrBene: ' + listOppMbrBene);
        
        //test the Delete
        aRecord = [SELECT 
                   Id, 
                   Name, 
                   Gender__c, 
                   Zip_Code__c,
                   Relationship__c,
                   Health_Plan_ID__c,
                   Dental_Plan_ID__c,
                   Vision_Plan_ID__c
                   FROM SGR_Opportunity_Census__c];
        
        delete aRecord;        
        
        listOppMbrBene = [SELECT 
                          ID,
                          Name,
                          Opportunity_Census__c,
                          Opportunity_Group_Section__c,
                          Opportunity_Plan_Rate__c
                          FROM SGR_Opportunity_Member_Benefits__c];
        
        system.debug('AFTER listOppMbrBene: ' + listOppMbrBene);
        
        List<Error_Log__c> listErrorLogs = new List<Error_Log__c>();
        listErrorLogs = [SELECT Id, Class__c, Error_Message__c FROM Error_Log__c LIMIT 100];
        
        for(Error_Log__c aLog : listErrorLogs){
            System.debug('testDelete Error Log: ' + aLog.Class__c + ' ' +  aLog.Error_Message__c);
        }
        
    }
    
}