src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_Decision_Date__c</fullName>
        <description>This field is used to capture the date when a decision is expected for the Opportunity.</description>
        <label>Expected Decision Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_RFP_Release_Date__c</fullName>
        <description>This field is used to capture the expected date an RFI or RFP will be received.</description>
        <label>Expected In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Closed_Reason__c</fullName>
        <description>This field is used to capture the primary reason why an Opportunity is won, lost or declined.</description>
        <label>Primary Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absorbed by Parent Group</fullName>
                </value>
                <value>
                    <fullName>Change of Ownership</fullName>
                </value>
                <value>
                    <fullName>Consol. Covg with 1 Carrier</fullName>
                </value>
                <value>
                    <fullName>Headquarters Relocated</fullName>
                </value>
                <value>
                    <fullName>Lack of Narrow Network</fullName>
                </value>
                <value>
                    <fullName>Market Check by Group</fullName>
                </value>
                <value>
                    <fullName>Organizational Changes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Guarantees</fullName>
                </value>
                <value>
                    <fullName>Plan Design-Other</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Purchase by Another Company</fullName>
                </value>
                <value>
                    <fullName>Rates-Aggregate Stop Loss-Claim/Attch Factor</fullName>
                </value>
                <value>
                    <fullName>Rates-Incumbent Reduced</fullName>
                </value>
                <value>
                    <fullName>Rates-Individual Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Rates-Insured</fullName>
                </value>
                <value>
                    <fullName>Repricing</fullName>
                </value>
                <value>
                    <fullName>Reputation of Selected Carrier</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Broker Relationship</fullName>
                </value>
                <value>
                    <fullName>Changed Brokers</fullName>
                </value>
                <value>
                    <fullName>Network Discounts</fullName>
                </value>
                <value>
                    <fullName>Network Disruption</fullName>
                </value>
                <value>
                    <fullName>Product Packaging</fullName>
                </value>
                <value>
                    <fullName>Did Not Want to Disrupt Ees</fullName>
                </value>
                <value>
                    <fullName>Not Enough Diff. to Change</fullName>
                </value>
                <value>
                    <fullName>PUG Did not meet participation</fullName>
                </value>
                <value>
                    <fullName>Rates-Admin. Charge too High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFI_RFP_Received_Date__c</fullName>
        <description>This field is used to capture the date when the RFP or RFI is received.</description>
        <label>RFI/RFP Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <description>This field is used to capture the requested effective date for the opportunity.</description>
        <label>Opportunity Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Rate__c.object
<CustomObject>
    <description>Contains the rate information pertaining to BPA</description>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>Captures HCSC division</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secure_Information__c</fullName>
        <description>Associated benefit plan application</description>
        <label>Secure Information</label>
        <referenceTo>Secure_Information__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rate_Group__c.object
<CustomObject>
    <fields>
        <fullName>Group_1_Amount__c</fullName>
        <label>Grouping 1 Amt</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Rate Groups</relationshipLabel>
        <relationshipName>Rate_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Group</label>
    <nameField>
        <label>Rate Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RateGroupDAOTest.cls
/**************************************************************************************
  Apex Class Name     : RateGroupDAOTest
  Version             : 1.0
  Function            : This is a test class for the RateGroupDAO class
* Developer                        Date                  
* ----------------------------------------------------------------------------                 
* Nick Serafin/Slalom             6/6/2016
*************************************************************************************/

@isTest(SeeAllData=false)
private class RateGroupDAOTest { 

	@isTest
	static void rateGroupDAOTest(){

		RateGroupDAO.IRateGroupDAO rateGroupDAOInstance = new RateGroupDAO();

		Account testAcnt = TestClassUtiltity.CreateAccountRecord('TestAccount');

		Opportunity opp = new Opportunity(AccountId = testAcnt.Id, HCSC_Division__c = 'IL', Name='oppName 2',StageName = 'Expected In', CloseDate = System.Today().addYears(2), Expected_RFP_Release_Date__c = System.Today().addYears(1), Expected_Decision_Date__c = System.Today().addYears(1), RFI_RFP_Received_Date__c = System.Today().addYears(1), Primary_Closed_Reason__c = 'Savings');
        opp.Requested_Effective_Date__c = System.Today() + 1;    
        insert opp;

		Secure_Information__c testSecure = new Secure_Information__c(Opportunity_Name__c = opp.Id);
		insert testSecure;

		Rate__c testRate = new Rate__c(Secure_Information__c = testSecure.Id);
		insert testRate;

		List<Rate_Group__c> rateGroups = new List<Rate_Group__c>();
		Rate_Group__c rateGroupObj = new Rate_Group__c();
		rateGroupObj.Rate__c = testRate.Id;
		rateGroupObj.Name = 'Group 1';
		rateGroups.add(rateGroupObj);

		rateGroupDAOInstance.insertRateGroup(rateGroups);
		rateGroupDAOInstance.grabRateGroups(testRate.Id);

		rateGroups[0].Group_1_Amount__c = 2;
		rateGroupDAOInstance.upsertRateGroup(rateGroups);

		List<Rate_Group__c> rateGroup = [SELECT Id, Group_1_Amount__c FROM Rate_Group__c];

		System.assertEquals(1, rateGroup.size());
		System.assertEquals(2, rateGroup[0].Group_1_Amount__c);

	}
}