src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Business need is to show the products that were renewed for the account last year.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>renewal_duration_is_infinite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indefinite Hold</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>SGR_Hold_Reason__c</fullName>
        <label>Hold Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Wage &amp; Tax Audit</fullName>
                </value>
                <value>
                    <fullName>1st Year Renewal</fullName>
                </value>
                <value>
                    <fullName>Block Acquisition</fullName>
                </value>
                <value>
                    <fullName>Special Adjustments</fullName>
                </value>
                <value>
                    <fullName>Market Segment Verification</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>SGR_Other_Hold_Reasons__c</fullName>
        <label>Other Hold Reasons</label>
        <type>TextArea</type>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Comments__c</fullName>
        <description>This field is used to capture the detailed description on why an Opportunity is closed won, lost or declined.</description>
        <label>Closed Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>This field is used to capture the date when the opportunity is won or lost.</description>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Closed_Reason__c</fullName>
        <description>This field is used to capture the primary reason why an Opportunity is won, lost or declined.</description>
        <label>Primary Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absorbed by Parent Group</fullName>
                </value>
                <value>
                    <fullName>Change of Ownership</fullName>
                </value>
                <value>
                    <fullName>Consol. Covg with 1 Carrier</fullName>
                </value>
                <value>
                    <fullName>Headquarters Relocated</fullName>
                </value>
                <value>
                    <fullName>Lack of Narrow Network</fullName>
                </value>
                <value>
                    <fullName>Market Check by Group</fullName>
                </value>
                <value>
                    <fullName>Organizational Changes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Guarantees</fullName>
                </value>
                <value>
                    <fullName>Plan Design-Other</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Purchase by Another Company</fullName>
                </value>
                <value>
                    <fullName>Rates-Aggregate Stop Loss-Claim/Attch Factor</fullName>
                </value>
                <value>
                    <fullName>Rates-Incumbent Reduced</fullName>
                </value>
                <value>
                    <fullName>Rates-Individual Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Rates-Insured</fullName>
                </value>
                <value>
                    <fullName>Repricing</fullName>
                </value>
                <value>
                    <fullName>Reputation of Selected Carrier</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Broker Relationship</fullName>
                </value>
                <value>
                    <fullName>Changed Brokers</fullName>
                </value>
                <value>
                    <fullName>Network Discounts</fullName>
                </value>
                <value>
                    <fullName>Network Disruption</fullName>
                </value>
                <value>
                    <fullName>Product Packaging</fullName>
                </value>
                <value>
                    <fullName>Did Not Want to Disrupt Ees</fullName>
                </value>
                <value>
                    <fullName>Not Enough Diff. to Change</fullName>
                </value>
                <value>
                    <fullName>PUG Did not meet participation</fullName>
                </value>
                <value>
                    <fullName>Rates-Admin. Charge too High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SGR_OpportunitySuppressionClass_Test.cls
@isTest
public class SGR_OpportunitySuppressionClass_Test {
   //Static Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId(); 
     @isTest 
    static void OpportunitySuppression(){
        
        
        String updatePlanChange = 'Yes';
        String ratingStatus = 'sold';
        
        List<Account> lstAcc = new List<Account>();
        Account a= new Account();
        a.name='Test';
        a.HCSC_Division__c='IL';
        a.Market_Segment__c='LG';
        a.Funding_Type__c='ACAP';
        a.Renewal_Date__c=date.today();
        a.SGR_Hold_Reason__c = 'Miscellaneous';
        a.renewal_duration_is_infinite__c = True;
        a.SGR_Other_Hold_Reasons__c = 'Saurav';
        insert a;
        
        Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId(); 
        List<opportunity> oplist = new List<opportunity>();
        opportunity opp = new opportunity();
        opp.AccountId = a.id;
        opp.Name = 'Sample';
        opp.StageName = 'lost';
        opp.Product_Type__c='H';
        opp.Primary_Closed_Reason__c ='Political';
        opp.Closed_Comments__c = 'XYZ';
        opp.Date_Closed__c = date.today().adddays(-1);
        opp.CloseDate = date.today().adddays(2);
        opp.Rating_Status__c = 'Sold';
        opp.Plan_Change_Needed__c = 'Yes';
        opp.SGR_Workflow_Activity__c = 'Plan Change in Progress';
        opp.RecordTypeId = sgrProdOpp;
        
        oplist.add(opp);      
        
        
        insert oplist;
        opportunity oppr = [select id,SGR_Workflow_Activity__c from opportunity where id =:oplist[0].id ];
        //System.AssertEquals(oppr.SGR_Workflow_Activity__c,'Plan Change in Progress');
        id ide = oplist[0].id;
        
        SGR_OpportunitySuppressionClass.getOpportunityData(ide);
        SGR_OpportunitySuppressionClass.updateOpportunityData(ide, updatePlanChange, ratingStatus);
        
             
        
    }
    @isTest 
    static void OpportunitySuppressionStatusChange(){
        
        
        String updatePlanChange = 'Complete';
        String ratingStatus = 'Finalized';
        
        List<Account> lstAcc = new List<Account>();
        Account a= new Account();
        a.name='Test';
        a.HCSC_Division__c='IL';
        a.Market_Segment__c='LG';
        a.Funding_Type__c='ACAP';
        a.Renewal_Date__c=date.today();
        a.SGR_Hold_Reason__c = 'Miscellaneous';
        a.renewal_duration_is_infinite__c = True;
        a.SGR_Other_Hold_Reasons__c = 'Saurav';
        insert a;
        
        Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId(); 
        List<opportunity> oplist = new List<opportunity>();
        opportunity opp = new opportunity();
        opp.AccountId = a.id;
        opp.Name = 'Sample';
        opp.StageName = 'lost';
        opp.Product_Type__c='H';
        opp.Primary_Closed_Reason__c ='Political';
        opp.Closed_Comments__c = 'XYZ';
        opp.Date_Closed__c = date.today().adddays(-1);
        opp.CloseDate = date.today().adddays(2);
        opp.Rating_Status__c = 'Finalized';
        opp.Plan_Change_Needed__c = 'Complete';
        opp.SGR_Workflow_Activity__c = 'Plan Change in Progress';
        opp.RecordTypeId = sgrProdOpp;
        oplist.add(opp);      
        
        
        insert oplist;
        id ide = oplist[0].id;
        
        SGR_OpportunitySuppressionClass.getOpportunityData(ide);
        SGR_OpportunitySuppressionClass.updateOpportunityData(ide, updatePlanChange, ratingStatus);
        
             
        
    }

    	 @isTest 
    static void OpportunitySuppressionStatusChange1(){
        
        
        String updatePlanChange = 'Complete';
        String ratingStatus = 'Sold';
        
        List<Account> lstAcc = new List<Account>();
        Account a= new Account();
        a.name='Test';
        a.HCSC_Division__c='IL';
        a.Market_Segment__c='LG';
        a.Funding_Type__c='ACAP';
        a.Renewal_Date__c=date.today();
        a.SGR_Hold_Reason__c = 'Miscellaneous';
        a.renewal_duration_is_infinite__c = True;
        a.SGR_Other_Hold_Reasons__c = 'Saurav';
        insert a;
        
        Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId(); 
        List<opportunity> oplist = new List<opportunity>();
        opportunity opp = new opportunity();
        opp.AccountId = a.id;
        opp.Name = 'Sample';
        opp.StageName = 'lost';
        opp.Product_Type__c='H';
        opp.Primary_Closed_Reason__c ='Political';
        opp.Closed_Comments__c = 'XYZ';
        opp.Date_Closed__c = date.today().adddays(-1);
        opp.CloseDate = date.today().adddays(2);
        opp.Rating_Status__c = 'Sold';
        opp.Plan_Change_Needed__c = 'Complete';
        opp.SGR_Workflow_Activity__c = 'Plan Change in Progress';
        opp.RecordTypeId = sgrProdOpp;
        oplist.add(opp);      
        
        
        insert oplist;
        id ide = oplist[0].id;
        
        SGR_OpportunitySuppressionClass.getOpportunityData(ide);
        SGR_OpportunitySuppressionClass.updateOpportunityData(ide, updatePlanChange, ratingStatus);
        
             
        
    }
    
      	 @isTest 
    static void OpportunitySuppressionStatusChange2(){
        
        
        String updatePlanChange = 'Complete';
        String ratingStatus = 'Sold';
        
        List<Account> lstAcc = new List<Account>();
        Account a= new Account();
        a.name='Test';
        a.HCSC_Division__c='IL';
        a.Market_Segment__c='LG';
        a.Funding_Type__c='ACAP';
        a.Renewal_Date__c=date.today();
        a.SGR_Hold_Reason__c = 'Miscellaneous';
        a.renewal_duration_is_infinite__c = True;
        a.SGR_Other_Hold_Reasons__c = 'Saurav';
        insert a;
        
        Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId(); 
       	List<opportunity> oplist = new List<opportunity>();
        opportunity opp = new opportunity();
        opp.AccountId = a.id;
        opp.Name = 'Sample';
        opp.StageName = 'lost';
        opp.Product_Type__c='H';
        opp.Primary_Closed_Reason__c ='Political';
        opp.Closed_Comments__c = 'XYZ';
        opp.Date_Closed__c = date.today().adddays(-1);
        opp.CloseDate = date.today().adddays(2);
        opp.Rating_Status__c = 'Finalized';
        opp.Plan_Change_Needed__c = 'Complete';
        opp.SGR_Workflow_Activity__c = 'Plan Change Progress';
        opp.RecordTypeId = sgrProdOpp;
        oplist.add(opp);      
        
        
        insert oplist;
        id ide = oplist[0].id;
        
        SGR_OpportunitySuppressionClass.getOpportunityData(ide);
        SGR_OpportunitySuppressionClass.updateOpportunityData(ide, updatePlanChange, ratingStatus);
        
             
        
    }

      	 @isTest 
    static void OpportunitySuppressionStatusChange3(){
        
        
        String updatePlanChange = 'Complete';
        String ratingStatus = 'Marketing Release';
        
        List<Account> lstAcc = new List<Account>();
        Account a= new Account();
        a.name='Test';
        a.HCSC_Division__c='IL';
        a.Market_Segment__c='LG';
        a.Funding_Type__c='ACAP';
        a.Renewal_Date__c=date.today();
        a.SGR_Hold_Reason__c = 'Miscellaneous';
        a.renewal_duration_is_infinite__c = True;
        a.SGR_Other_Hold_Reasons__c = 'Saurav';
        insert a;
        
        Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId(); 
       	List<opportunity> oplist = new List<opportunity>();
        opportunity opp = new opportunity();
        opp.AccountId = a.id;
        opp.Name = 'Sample';
        opp.StageName = 'lost';
        opp.Product_Type__c='H';
        opp.Primary_Closed_Reason__c ='Political';
        opp.Closed_Comments__c = 'XYZ';
        opp.Date_Closed__c = date.today().adddays(-1);
        opp.CloseDate = date.today().adddays(2);
        opp.Rating_Status__c = 'Marketing Release';
        opp.Plan_Change_Needed__c = 'Complete';
        opp.SGR_Workflow_Activity__c = 'Plan Change Progress';
        opp.RecordTypeId = sgrProdOpp;
        oplist.add(opp);      
        
        
        insert oplist;
        id ide = oplist[0].id;
        
        SGR_OpportunitySuppressionClass.getOpportunityData(ide);
        SGR_OpportunitySuppressionClass.updateOpportunityData(ide, updatePlanChange, ratingStatus);
        
             
        
    }
}