src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Market_Segment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Segment Picklist values from Account</description>
    <label>Market Segment</label>
</CustomObject>

classes/SGR_AccoutsHoldBatchTest.cls
@isTest
public class SGR_AccoutsHoldBatchTest {

    static  testmethod void testmethod1() {
        
       		Account a = new Account();
            a.Name ='Test';
            a.HCSC_Division__c='IL';
            a.Market_Segment__c='FEP';
            a.Funding_Type__c='ACAP';
            a.Renewal_Date__c=date.today();
            insert a;
            
            List<String> divisions;
            String marketSegment;
            String fundingType;
            String renewEffDate;
            String renType;
            String returnMsg;
            divisions=new List<String>{'IL'};
            marketSegment='FEP';
            fundingType='ACAP';
            renewEffDate ='2018-09-10';
            renType='Production';
            
            
            test.startTest();
            
            List<Account> acc=new List<Account>();
            //acc= SGR_AccontsHoldBatch.start();
        	//SGR_AccontsHoldBatch.execute();
        	//SGR_AccontsHoldBatch.finish();
            
            test.stopTest();
        }
        
    }