src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Actuary_Gate__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prem</fullName>
                    <default>true</default>
                    <label>PREM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OppCount__c</fullName>
        <label>Number of Total Opportunities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Gate Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Up</fullName>
                </value>
                <value>
                    <fullName>Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Gate</label>
    <nameField>
        <displayFormat>G-{000}</displayFormat>
        <label>Gate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assigned_UW__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned UW</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dental_Count__c</fullName>
        <description># of Subscribers enrolled for Dental(does not include members count)</description>
        <label>Dental Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gate</label>
        <referenceTo>Actuary_Gate__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Health_Count__c</fullName>
        <description># of Subscribers enrolled for Health(does not include members count)</description>
        <label>Health Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscribers_Count__c</fullName>
        <description># of Subscribers enrolled for Health and Dental(does not include members count)</description>
        <label>Subscribers Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <recordTypes>
        <fullName>SGR_Analytical_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <label>SGR Analytical Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>SGR_Production_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>SGR Oppurtunity Record Type</description>
        <label>SGR Production Opportunity</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SGR_ViewGateControllerTest.cls
@isTest
public class SGR_ViewGateControllerTest { 
    
    @testSetup 
    public static void setup() {
        insertAccs();
        insertGate();
        insertOpps();
    }
    
    @isTest
    public static void testGetRelatedOpportunities() {
        Test.startTest();
        Actuary_Gate__c g = [Select Id from Actuary_Gate__c WHERE Division__c='IL' LIMIT 1][0];
        List<Opportunity> oppsList = SGR_ViewGateController.getRelatedOpportunities(g.id, 10, 'Renewal_Date__c','asc');
        Test.stopTest();
        System.assertEquals(2, oppsList.size());
    }

    @isTest
    public static void testGetRelOppsCount() {   
        Test.startTest();
        Actuary_Gate__c g1 = [Select Id from Actuary_Gate__c WHERE Division__c='IL' LIMIT 1][0];
        SGR_ViewGateController.getRelOppsCount(g1.id);
        Actuary_Gate__c g2 = [Select Id, OppCount__c from Actuary_Gate__c LIMIT 1][0];
        Test.stopTest();
        System.assertEquals(2, g2.OppCount__c);
    }
    @isTest
    public static void testGetRelOppsCountWithEmptyGate() { 
                    
            Test.startTest();
            Actuary_Gate__c g = [Select Id, OppCount__c from Actuary_Gate__c WHERE Division__c='OK' LIMIT 1][0];
            SGR_ViewGateController.getRelOppsCount(g.id);
            
            Test.stopTest();
            System.assertEquals(0, g.OppCount__c);
         
    }
    
    @isTest
    public static void testGetRelOppsCountWithInvalidGate() { 
        try {
            
            Test.startTest();           
            SGR_ViewGateController.getRelOppsCount('SomeInvalidGateId');            
            Test.stopTest();
        } catch(Exception e) {
            System.Assert(e.getMessage()!=null);
        } 
    }
/****** Added by Akhi *******/
    @isTest
    public static void tesprocessSelectedOpty() { 
        try {
            
            Test.startTest(); 
        Id prodRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Production_Opportunity').getRecordTypeId();
        Id analyRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Analytical_Opportunity').getRecordTypeId();
        
       
         List<Opportunity> opps = new List<Opportunity>();
        opps.add(new Opportunity(Name='Oppty1', RecordTypeId=prodRecId, StageName='Triggered', CloseDate= System.today().addYears(2),Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c='Rated', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55 , Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty2', RecordTypeId=prodRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c='Rated', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55 , Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty3', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(1),Renewal_Date__c = System.Today().addMonths(5), Rating_Status__c='Rated', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55 , Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty4', RecordTypeId=prodRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(1), Rating_Status__c='Rated', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55 , Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty5', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(-3), Rating_Status__c='Rated', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55 , Assigned_UW__c = Userinfo.getUserId()));
        insert opps;
            SGR_ViewGateController.processSelectedOptys(opps);            
            Test.stopTest();
        } catch(Exception e) {
            System.Assert(e.getMessage()!=null);
        } 
    }
    
      public static testmethod void tesSelectedOpty() { 
        try {
            
            Test.startTest(); 
        Id prodRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Production_Opportunity').getRecordTypeId();
        Id analyRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Analytical_Opportunity').getRecordTypeId();
        
       
         List<Opportunity> opps = new List<Opportunity>();
        opps.add(new Opportunity(Name='Oppty1', RecordTypeId=prodRecId, StageName='Triggered', CloseDate= System.today().addYears(2),Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c='Rated', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55, Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty2', RecordTypeId=prodRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c='Rated', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55, Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty3', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(1),Renewal_Date__c = System.Today().addMonths(5), Rating_Status__c='Some Rating Status', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55, Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty4', RecordTypeId=prodRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(1), Rating_Status__c='Actuarial-Released', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55,Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty5', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(-3), Rating_Status__c='Released', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55,Assigned_UW__c = Userinfo.getUserId()));
        insert opps;
        SGR_ViewGateController.getSelectedOpty(new List<Id>{opps[0].Id,opps[1].Id});
            
                      
            Test.stopTest();
        } catch(Exception e) {
            System.Assert(e.getMessage()!=null);
        } 
    }
    
    /************Akhil End ************/
    
    /****** Added by Saurav *******/
    @isTest
    public static void testliftGate() { 
        try {
            
            Test.startTest(); 
        Id prodRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Production_Opportunity').getRecordTypeId();
        Id analyRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Analytical_Opportunity').getRecordTypeId();
        
        List<Actuary_Gate__c> gates = new List<Actuary_Gate__c>();
        gates.add(new Actuary_Gate__c(Division__c='IL',OppCount__c=0,Funding_Type__c='PREM',Status__c='Down',Market_Segment__c='SG', Effective_Date__c=System.Today().addMonths(-5)));
        insert gates;
        
         List<Opportunity> opps = new List<Opportunity>();
        opps.add(new Opportunity(Name='Test VSR1', RecordTypeId=analyRecId, StageName='Qualify', CloseDate= System.today().addYears(2),Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c='Rated',Gate__c=gates[0].Id, Assigned_UW__c = Userinfo.getUserId() ));
        opps.add(new Opportunity(Name='Oppty2', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c='Rated',Gate__c=gates[0].Id, Assigned_UW__c = Userinfo.getUserId() ));
        opps.add(new Opportunity(Name='Oppty3', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(1),Renewal_Date__c = System.Today().addMonths(5), Rating_Status__c='Some Rating Status',Gate__c=gates[0].Id, Assigned_UW__c = Userinfo.getUserId() ));
        opps.add(new Opportunity(Name='Oppty4', RecordTypeId=prodRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(1), Rating_Status__c='Actuarial-Released',Gate__c=gates[0].Id, Assigned_UW__c = Userinfo.getUserId() ));
        opps.add(new Opportunity(Name='Oppty5', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(-3), Rating_Status__c='Released',Gate__c=gates[0].Id, Assigned_UW__c = Userinfo.getUserId() ));
        insert opps;
        
            SGR_ViewGateController.liftGate(gates[0].Id);            
            Test.stopTest();
        } catch(Exception e) {
            System.Assert(e.getMessage()!=null);
        } 
    }
    
    @isTest
    public static void testgetGateStatus() { 
                    
            Test.startTest();
            Actuary_Gate__c g = [Select Id, OppCount__c from Actuary_Gate__c WHERE Division__c='OK' LIMIT 1][0];
            SGR_ViewGateController.getGateStatus(g.id);
            
            Test.stopTest();
            System.assertEquals(0, g.OppCount__c);
         
    }
    @isTest
    public static void testGateStatus() { 
                    
            Test.startTest();
            Actuary_Gate__c g = [Select Id, OppCount__c from Actuary_Gate__c WHERE Division__c='OK' LIMIT 1];        	
            SGR_ViewGateController.GateStatus(g.id);
            
            Test.stopTest();
            System.assertEquals(0, g.OppCount__c);
         
    }
     /************Saurav End ************/
    
    
    public static void insertAccs() {
        List<Account> accs = new List<Account>();
        accs.add(new Account(Name='TestAcc1', External_Id__c='A1234',Market_Segment__c='SG',hold_end_date__c=Date.today()-1,SGR_Hold_Reason__c='1st Year Renewal'));
        accs.add(new Account(Name='TestAcc2', External_Id__c='A5678',Market_Segment__c='SG',hold_end_date__c=Date.today()-1,SGR_Hold_Reason__c='1st Year Renewal'));
        insert accs;
    }
    public static void insertOpps() {
        Id prodRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Production_Opportunity').getRecordTypeId();
        Id analyRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Analytical_Opportunity').getRecordTypeId();
        Actuary_Gate__c g1 =[SELECT Id from Actuary_Gate__c where Division__c='IL' LIMIT 1];
        Actuary_Gate__c g2 =[SELECT Id from Actuary_Gate__c where Division__c='OK' LIMIT 1];
        
        List<Opportunity> opps = new List<Opportunity>();
        opps.add(new Opportunity(Name='Oppty1', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(2),Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c='Rated', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55, Gate__c=g1.Id, Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty2', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c='Rated', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55, Gate__c=g1.Id, Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty3', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(1),Renewal_Date__c = System.Today().addMonths(5), Rating_Status__c='Some Rating Status', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55, Gate__c=g2.Id, Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty4', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(1), Rating_Status__c='Actuarial-Released', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55, Gate__c=g1.Id, Assigned_UW__c = Userinfo.getUserId()));
        opps.add(new Opportunity(Name='Oppty5', RecordTypeId=analyRecId, StageName='Triggered', CloseDate= System.today().addYears(3),Renewal_Date__c = System.Today().addMonths(-3), Rating_Status__c='Released', Subscribers_Count__c=4, Health_Count__c=44, Dental_Count__c=55, Gate__c=g2.Id, Assigned_UW__c = Userinfo.getUserId()));
        insert opps;
    }
    public static void insertGate() {
        List<Actuary_Gate__c> gates = new List<Actuary_Gate__c>();
        gates.add(new Actuary_Gate__c(Division__c='IL', OppCount__c=0,Funding_Type__c='PREM',Status__c='Down',Market_Segment__c='SG', Effective_Date__c=System.Today().addMonths(-5)));
        gates.add(new Actuary_Gate__c(Division__c='OK', OppCount__c=0,Funding_Type__c='PREM',Status__c='Down',Market_Segment__c='SG', Effective_Date__c=System.Today().addMonths(-4)));
        insert gates;
    }    
}