src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>ComplexityScoreContractAdministration__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Hidden complexity score field for Contract Administration object</description>
        <label>ComplexityScoreContractAdministration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Contract_Administration__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Custom Contracts</relationshipLabel>
        <relationshipName>Contract_Administrations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complexity__c</fullName>
        <label>Complexity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request from Sales &amp; Marketing, Draft</fullName>
                </value>
                <value>
                    <fullName>Sent to Sales &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Draft sent to Employer</fullName>
                </value>
                <value>
                    <fullName>Sales &amp; Marketing returns draft to Contract Admin</fullName>
                </value>
                <value>
                    <fullName>Internal HCSC SME Review</fullName>
                </value>
                <value>
                    <fullName>Submitted for Legal Review</fullName>
                </value>
                <value>
                    <fullName>Plan President Approval Received</fullName>
                </value>
                <value>
                    <fullName>Internal Employer Group Review</fullName>
                </value>
                <value>
                    <fullName>Final sent to Employer Group</fullName>
                </value>
                <value>
                    <fullName>Fully Executed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract Administration</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Administrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractAdministrationTriggerHandlerTest.cls
@isTest(SeeAllData = false)
public class ContractAdministrationTriggerHandlerTest { 
	@isTest
	static void calculateContractAdministrationComplexityScoreTest() {
		Test.StartTest();

		Account testAcnt = TestClassUtiltity.CreateAccountRecord('TestAccount');
		Contract_Administration__c contractAdmin = new Contract_Administration__c(Account__c = testAcnt.id, Status__c = 'Fully Executed', Complexity__c = 'Medium');
		insert contractAdmin;

		testAcnt = [SELECT ComplexityScoreContractAdministration__c FROM Account WHERE Id = :testAcnt.Id];

		System.assertEquals(testAcnt.ComplexityScoreContractAdministration__c, 5);

		Test.StopTest();
	}
}