src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Active_Dental_Members__c</fullName>
        <description>This field is used to capture the number of active dental members for the Group Account as listed in BlueStar</description>
        <label>Active Dental Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Active_Health_Members__c</fullName>
        <description>This field is used to capture the number of active health members for the Group Account as listed in BlueStar</description>
        <label>Active Health Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>X1_31_Account_Status__c</fullName>
        <description>This field is used to capture the status of account on 1/31 to be used in sales and account metrics</description>
        <inlineHelpText>Status of account on 1/31</inlineHelpText>
        <label>1/31 Account Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>X1_31_Membership__c</fullName>
        <description>This field is used to capture the total number of active health members on 1/31 to be used in sales and account metrics</description>
        <inlineHelpText>Total active members on 1/31</inlineHelpText>
        <label>1/31 Membership</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestHPS_MyMetricsController.cls
@isTest
private class TestHPS_MyMetricsController {

    static testMethod void myUnitTest() {
        try{
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            User testUser = TestClassUtiltity.CreateUserRecord(p.Id, 'testlgnadev@user.com', 'testUser', 'test@user.com');
            system.runAs(testUser){
                Account testAccount = TestClassUtiltity.CreateAccountRecord('Test Account');
                testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
                testAccount.status__c = 'Active';
                testAccount.Fax = '1234567';
                testAccount.Active_Health_Members__c = 10;
                testAccount.Active_Dental_Members__c = 10;
                testAccount.X1_31_Account_Status__c = 'Active';
                testAccount.X1_31_Membership__c = 10;
                update testAccount;
                
                //create Opportunity records
                list<Opportunity> opportunities = TestClassUtiltity.CreateOpportunities(testAccount.Id);
                
                opportunities[1].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
                opportunities[1].StageName = 'RFI Received';
                 opportunities[0].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
                opportunities[0].StageName = 'RFI Received';
                 opportunities[2].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
                opportunities[2].StageName = 'RFI Received';
                 opportunities[3].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
                opportunities[3].StageName = 'RFI Received';
                 opportunities[4].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
                opportunities[4].StageName = 'RFI Received';
                 opportunities[5].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
                opportunities[5].StageName = 'RFI Received';
                opportunities[0].Probability = 10;
                opportunities[1].Probability = 10;
                opportunities[2].Probability = 10;
                opportunities[3].Probability = 10;
                opportunities[4].Probability = 10;
                opportunities[5].Probability = 10;
                
                insert opportunities;
                
                
                //Initializing the Constructor
                HPS_MyMetricsController tempController = new HPS_MyMetricsController();
                //assert the size of the Task list
                System.assertEquals(tempController.medicalRecordsCount,10);
            }
        }catch(Exception e){
            throw e;
        }
    }
    static testMethod void myUnitTest1() {
        try{
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            User testUser = TestClassUtiltity.CreateUserRecord(p.Id, 'testlgnadev@user.com', 'testUser', 'test@user.com');
            system.runAs(testUser){
                Account testAccount = TestClassUtiltity.CreateAccountRecord('Test Account');
                testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
                testAccount.status__c = 'Sold';
                testAccount.Fax = '1234567';
                testAccount.Active_Health_Members__c = 10;
                testAccount.Active_Dental_Members__c = 10;
                testAccount.X1_31_Account_Status__c = 'Sold';
                testAccount.X1_31_Membership__c = 10;
                update testAccount;
                
                //create Opportunity records
                list<Opportunity> opportunities = TestClassUtiltity.CreateOpportunities(testAccount.Id);
                opportunities[0].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
                opportunities[0].StageName = 'Prospective';
                
                opportunities[1].RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
                opportunities[1].StageName = 'Prospective';
                
                insert opportunities;
                
                //Initializing the Constructor
                HPS_MyMetricsController tempController = new HPS_MyMetricsController();
                //assert the size of the Task list
                System.assertEquals(tempController.medicalRecordsCount,0);
            }
        }catch(Exception e){
            
        }
    }
}