src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Producer_Group_Association__c.object
<CustomObject>
    <description>Producer and Group associations will be stored using this object</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Effective Date of the Association (Relationship between Group Account and Producer Account)</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Stores the external ID from Source System (Concat of Group Account # and Producer Account #) for Upsert Operation</description>
        <externalId>true</externalId>
        <label>PGA External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Group_Account__c</fullName>
        <description>Stores the group account related in this association</description>
        <label>Group Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Group Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Prospect</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Prospect (Non BlueSTAR)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Group Account (Non BlueSTAR)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Producers Associated to Group</relationshipLabel>
        <relationshipName>Group_Associated</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Producer_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Producer Account related in the association</description>
        <label>Producer Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Producer_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Consultant_Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups Associated to Producer</relationshipLabel>
        <relationshipName>Producer_Association</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Producer Group Association</label>
    <nameField>
        <displayFormat>PAG-{0000}</displayFormat>
        <label>PAG #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Producer Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SGR_BAP_GetProducerDataHelperTest.cls
@isTest
public class SGR_BAP_GetProducerDataHelperTest {
    
    @isTest
  static void testProducerNumberNotNull(){
        
    SGR_BAP_GetProducerDataRequest req = new SGR_BAP_GetProducerDataRequest();
    SGR_BAP_GetProducerDataResponse res = new SGR_BAP_GetProducerDataResponse();
    req.producerNumber= '35435';
        req.pageSize = 10;
        req.pageNumber =1;
        req.producerName='xyz';
        req.effectiveDate='2019-01-01';
        req.accountNumber='35435345';
        req.accountName='grpxyz';
    String myJSON = JSON.serialize(req);

        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();
        Id RecordTypeIdGrpAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        Account acc = new Account(name='xyz',recordtypeid=RecordTypeIdAccount,Type='Producer',External_ID__c='35435');
        insert acc;
            
        Account grpacct = new Account(name='grpxyz',recordtypeid=RecordTypeIdGrpAccount,External_ID__c='35435345');
        insert grpacct;
        
        Producer_Group_Association__c grpAcc = new Producer_Group_Association__c(Group_Account__c =grpacct.id,Producer_Account__c=acc.id,Effective_Date__c = Date.valueOf('2019-01-01'));
        insert grpAcc;
        
        Opportunity oppr = new Opportunity(Name='Oppr1',Renewal_Date__c=system.today(),AccountId=grpacct.id);
        RestRequest request = new RestRequest();
        request.requestUri =URL.getSalesforceBaseUrl().toExternalForm()+'/services/apexrest/BAP_GetProducerData';
        request.httpMethod = 'POST';
    request.requestBody = Blob.valueof(myJSON);
        RestContext.request = request;
        res.pageNumber=0;
        res.pageSize=1;
        RestResponse response = new RestResponse();
        response.responseBody = Blob.valueOf(String.valueof(res));
        RestContext.response = response;
    SGR_BAP_GetProducerData.getProducerData();
    System.assertNotEquals(RestContext.response,null);
    
    
  }
  @isTest
  static void testProducerGrpAccNull(){
        
    SGR_BAP_GetProducerDataRequest req = new SGR_BAP_GetProducerDataRequest();
    SGR_BAP_GetProducerDataResponse res = new SGR_BAP_GetProducerDataResponse();
    req.producerNumber= '35435';
        req.pageSize = 10;
        req.pageNumber =1;
        req.producerName='xyz';
        req.effectiveDate='2018-01-01';
        req.accountNumber='35435345';
        req.accountName='grpxyz';
    String myJSON = JSON.serialize(req);

        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();
        Id RecordTypeIdGrpAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        Account acc = new Account(name='xyz',recordtypeid=RecordTypeIdAccount,Type='Producer',External_ID__c='35435');
        insert acc;
            
        Account grpacct = new Account(name='grpxyz',recordtypeid=RecordTypeIdGrpAccount,External_ID__c='35435345');
        insert grpacct;
        
        Producer_Group_Association__c grpAcc = new Producer_Group_Association__c(Group_Account__c =grpacct.id,Producer_Account__c=acc.id,Effective_Date__c = Date.valueOf('2019-01-01'));
        insert grpAcc;
        
        Opportunity oppr = new Opportunity(Name='Oppr1',Renewal_Date__c=system.today(),AccountId=grpacct.id);
        RestRequest request = new RestRequest();
        request.requestUri =URL.getSalesforceBaseUrl().toExternalForm()+'/services/apexrest/BAP_GetProducerData';
        request.httpMethod = 'POST';
    request.requestBody = Blob.valueof(myJSON);
        RestContext.request = request;
        res.pageNumber=0;
        res.pageSize=1;
        RestResponse response = new RestResponse();
        response.responseBody = Blob.valueOf(String.valueof(res));
        RestContext.response = response;
    SGR_BAP_GetProducerData.getProducerData();
    System.assertNotEquals(RestContext.response,null);
    
    
  }    
     @isTest
  static void testProducerAccNull(){
        
    SGR_BAP_GetProducerDataRequest req = new SGR_BAP_GetProducerDataRequest();
    SGR_BAP_GetProducerDataResponse res = new SGR_BAP_GetProducerDataResponse();
    req.producerNumber= '45346456';
        req.pageSize = 10;
        req.pageNumber =1;
    String myJSON = JSON.serialize(req);
    
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();
        Id RecordTypeIdGrpAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        Account acc = new Account(name='xyz',recordtypeid=RecordTypeIdAccount,Type='Sub Producer',External_ID__c='35435');
        insert acc;
        
        Account grpacct = new Account(name='grpxyz',recordtypeid=RecordTypeIdGrpAccount,External_ID__c='35435345');
        insert grpacct;
        
        Producer_Group_Association__c grpAcc = new Producer_Group_Association__c(Group_Account__c =grpacct.id,Producer_Account__c=acc.id,Effective_Date__c = system.today().addDays(-2));
        insert grpAcc;
        
        Opportunity oppr = new Opportunity(Name='Oppr1',Renewal_Date__c=system.today(),AccountId=acc.id);
        RestRequest request = new RestRequest();
        request.requestUri =URL.getSalesforceBaseUrl().toExternalForm()+'/services/apexrest/BAP_GetProducerData';
        request.httpMethod = 'POST';
    request.requestBody = Blob.valueof(myJSON);
        RestContext.request = request;
        res.pageNumber=0;
        res.pageSize=1;
        RestResponse response = new RestResponse();
        response.responseBody = Blob.valueOf(String.valueof(res));
        RestContext.response = response;
    SGR_BAP_GetProducerData.getProducerData();
    System.assertNotEquals(RestContext.response,null);
    
    
  }
    
     @isTest
  static void testProducerNumberNull(){
        
    SGR_BAP_GetProducerDataRequest req = new SGR_BAP_GetProducerDataRequest();
    SGR_BAP_GetProducerDataResponse res = new SGR_BAP_GetProducerDataResponse();
    req.producerNumber= '';
        req.pageSize = 10;
        req.pageNumber =1;
    String myJSON = JSON.serialize(req);
    
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();
        Id RecordTypeIdGrpAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        Account acc = new Account(name='xyz',recordtypeid=RecordTypeIdAccount,Type='Producer',External_ID__c='456456');
        insert acc;
        
        Account grpacct = new Account(name='grpxyz',recordtypeid=RecordTypeIdGrpAccount,External_ID__c='35435345');
        insert grpacct;
        
        Producer_Group_Association__c grpAcc = new Producer_Group_Association__c(Group_Account__c =grpacct.id,Producer_Account__c=acc.id,Effective_Date__c = system.today().addDays(-2));
        insert grpAcc;
        
        Opportunity oppr = new Opportunity(Name='Oppr1',Renewal_Date__c=system.today(),AccountId=acc.id);
        RestRequest request = new RestRequest();
        request.requestUri =URL.getSalesforceBaseUrl().toExternalForm()+'/services/apexrest/BAP_GetProducerData';
        request.httpMethod = 'POST';
    request.requestBody = Blob.valueof(myJSON);
        RestContext.request = request;
        res.pageNumber=0;
        res.pageSize=1;
        RestResponse response = new RestResponse();
        response.responseBody = Blob.valueOf(String.valueof(res));
        RestContext.response = response;
    SGR_BAP_GetProducerData.getProducerData();
    System.assertNotEquals(RestContext.response,null);
    
    
  }
    
     @isTest
  static void testGroupAccNull(){
        
    SGR_BAP_GetProducerDataRequest req = new SGR_BAP_GetProducerDataRequest();
    SGR_BAP_GetProducerDataResponse res = new SGR_BAP_GetProducerDataResponse();
    req.producerNumber= '35435';
        req.pageSize = 10;
        req.pageNumber =1;
    String myJSON = JSON.serialize(req);
    
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();
        Id RecordTypeIdGrpAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        Account acc = new Account(name='xyz',recordtypeid=RecordTypeIdAccount,Type='Producer',External_ID__c='456456');
        insert acc;
        
        Account acc2 = new Account(name='xyz',recordtypeid=RecordTypeIdAccount,Type='Sub Producer',External_ID__c='4575676');
        insert acc2;
        
        Account grpacct = new Account(name='grpxyz',recordtypeid=RecordTypeIdGrpAccount,External_ID__c='35435345');
        insert grpacct;
        
        Producer_Group_Association__c grpAcc = new Producer_Group_Association__c(Group_Account__c =grpacct.id,  Effective_Date__c=system.today(),Producer_Account__c=acc2.id);
        insert grpAcc;
        
        Opportunity oppr = new Opportunity(Name='Oppr1',Renewal_Date__c=system.today(),AccountId=acc.id);
        RestRequest request = new RestRequest();
        request.requestUri =URL.getSalesforceBaseUrl().toExternalForm()+'/services/apexrest/BAP_GetProducerData';
        request.httpMethod = 'POST';
    request.requestBody = Blob.valueof(myJSON);
        RestContext.request = request;
        res.pageNumber=0;
        res.pageSize=1;
        RestResponse response = new RestResponse();
        response.responseBody = Blob.valueOf(String.valueof(res));
        RestContext.response = response;
    SGR_BAP_GetProducerData.getProducerData();
    System.assertNotEquals(RestContext.response,null);
    
    
  }


}