src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Business need is to show the products that were renewed for the account last year.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/BA_GS_Assignment__c.object
<CustomObject>
    <description>Benefit Agreement assigned to Group Section information for the Group Account will be stored using this object</description>
    <fields>
        <fullName>Benefit_Agreement__c</fullName>
        <description>Benefit Agreement related to the Group Section</description>
        <label>Benefit Agreement</label>
        <referenceTo>Benefit_Agreement__c</referenceTo>
        <relationshipLabel>Group Sections Assigned</relationshipLabel>
        <relationshipName>BA_GS_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>BA GS Assignment</label>
    <nameField>
        <displayFormat>BAGS-{00000000}</displayFormat>
        <label>BA GS Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BA GS Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Benefit_Agreement__c.object
<CustomObject>
    <description>Benefit Agreement information offered to the employees for the Group Account will be stored using this object</description>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>This field is used to capture the business type for the Benefit Agreement.</description>
        <label>Business Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Cede</fullName>
                </value>
                <value>
                    <fullName>Slice</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the financial billing arrangement that an account designates for the Benefit Agreement.</description>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Account__c</fullName>
        <description>This field is used to capture the Group Account associated to the Benefit Agreement</description>
        <label>Group Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Agreements</relationshipLabel>
        <relationshipName>Benefit_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <description>This field is no longer used.</description>
        <label>Members</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>This field is used to capture the category of the product associated to the Benefit Agreement</description>
        <formula>Text(Product__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the name of the product associated to the Benefit Agreement as listed in BlueStar</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product2.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>HCSC_Non_BlueStar_Product</value>
            </filterItems>
            <filterItems>
                <field>Product2.NotSimple__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>You must add only Non BlueSTAR products</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Benefit Agreements</relationshipLabel>
        <relationshipName>Benefit_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>This field is used to capture the date the Benefit Agreement will renew as listed in BlueStar</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the Benefit Agreement is active or cancelled as listed in BlueStar</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Agreement</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Benefit Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Plan__c.object
<CustomObject>
    <description>To capture all the plans related to products - Loaded from BlueStar</description>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>TEXT(Product__r.Product_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product the Plan is related</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Product Status Code of the Plan</description>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Captures product category</description>
        <inlineHelpText>required field for plans to flow correctly on BA to BlueSTAR</inlineHelpText>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BCC</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Disease Management</fullName>
                </value>
                <value>
                    <fullName>EPO</fullName>
                </value>
                <value>
                    <fullName>Group Govt</fullName>
                </value>
                <value>
                    <fullName>HCA</fullName>
                </value>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>IHI</fullName>
                </value>
                <value>
                    <fullName>Nurseline</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
                <value>
                    <fullName>Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Dearborn</fullName>
                </value>
                <value>
                    <fullName>Health Advocacy Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Health Care Management</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>Dearborn</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Simplified_Product__c</fullName>
        <label>Simple Product</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BenefitAgreementDAO.cls
public class BenefitAgreementDAO implements IBenefitAgreementDAO {
	public interface IBenefitAgreementDAO {
		List<Benefit_Agreement__c> getBatchBenefitAgreements(Set<Id> accountIds);
		List<Benefit_Agreement__c> getGroupAccountBenefitAgreements(List<Account> groupAccounts);
		List<Benefit_Agreement__c> getActiveBenefitAgreementsAndCoverages(Map<Id, Account> groupAccounts);
		void updateBenefitAgreements(List<Benefit_Agreement__c> bnftAgrmnts);
		List<Benefit_Agreement__c> getActiveBlueStarBenefitAgreements(Set<Id> baIds, Id BlueSTARRecType);
		List<Benefit_Agreement__c> getBenefitAgreementsForCurrentProds(Id acctId);
	}

	public List<Benefit_Agreement__c> getBatchBenefitAgreements(Set<Id> accountIds) {
		return [Select Id, Group_Account__c, Group_Account__r.Status__c, Product__c, Product__r.Product_Category__c, Product__r.Product_Type__c, Funding_Type__c, Product__r.Simplified_Product__c, Product__r.Name, Business_Type__c, Renewal_Date__c, Members__c, Product__r.Family from Benefit_Agreement__c where  Group_Account__c in :accountIds and Group_Account__c != null and Product__c != null and Group_Account__r.Status__c = 'Active' and Status__c = 'Active' and Effective_Date__c < :System.today() and (Cancellation_Status__c != 'Cancelled' and Status__c != 'Cancelled')];
	}

	public List<Benefit_Agreement__c> getGroupAccountBenefitAgreements(List<Account> groupAccounts) {
		return [SELECT Id, Group_Account__r.Id, Funding_Type__c FROM Benefit_Agreement__c WHERE Group_Account__c IN :groupAccounts];
	}

	public List<Benefit_Agreement__c> getActiveBenefitAgreementsAndCoverages( Map<Id, Account> groupAccounts ) {
		return [SELECT Group_Account__c, Status__c, Stop_Loss__c, Product_Category__c, Plan__r.Name, ComplexityScoreCoverage__c 
					FROM Benefit_Agreement__c WHERE Group_Account__c IN :groupAccounts.keySet() AND Status__c = :Label.Active];
	}

	public void updateBenefitAgreements(List<Benefit_Agreement__c> bnftAgrmnts) {
		update bnftAgrmnts; 
	}

	public List<Benefit_Agreement__c> getActiveBlueStarBenefitAgreements(Set<Id> baIds, Id BlueSTARRecType) {
		return [SELECT ComplexityScoreCoverage__c, RecordTypeId FROM Benefit_Agreement__c WHERE Id 
				IN :baIds AND RecordTypeId =:BlueSTARRecType AND Status__c = :Label.Active];
	}

	public List<Benefit_Agreement__c> getBenefitAgreementsForCurrentProds(Id acctId) {
		return [SELECT Product__c, Product__r.Product_Type__c, Product__r.Simplified_Product__c, Funding_type__c, (SELECT Group_Section__r.Total_Dental_Active_Members__c,
				Group_Section__r.Total_Healthcare_Active_Members__c, Group_Section__r.Total_Active_Subscribers__c
				FROM BA_GS_Assignments__r WHERE Group_Section__r.Status__c = :Label.Active),
				Premium_Type__c FROM Benefit_Agreement__c WHERE Status__c = :Label.Active AND Group_Account__c = :acctId AND Effective_Date__c < :System.today()
				AND(Cancellation_Status__c != :Label.Cancelled AND Status__c != :Label.Cancelled)
				ORDER BY Product__r.Product_Type__c ASC limit :Limits.getLimitQueryRows() - Limits.getQueryRows()];
	}
}