src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Total_Num_of_Potential_Subscribers__c</fullName>
        <description>This field is used to capture the total number of potential subscribers to enroll in insurance.</description>
        <label>Eligible Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>true</active>
        <description>Account record type that captures information about a competitor (carriers and vendors)</description>
        <label>Competitor</label>
    </recordTypes>

objects/Account.object
    <recordTypes>
        <fullName>Group_Account</fullName>
        <active>true</active>
        <description>Account record type for Group / Sold Accounts</description>
        <label>Group Account</label>
    </recordTypes>

objects/Account.object
    <recordTypes>
        <fullName>Producer_Account</fullName>
        <active>true</active>
        <description>Account record type for producers / brokers</description>
        <label>Producer Account</label>
    </recordTypes>

objects/Account.object
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Account record type for vendors of HCSC</description>
        <label>Vendor</label>
    </recordTypes>

objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Audits</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Billing Explained</fullName>
                </value>
                <value>
                    <fullName>Case Management and Wellness</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>CMS Demand Letters</fullName>
                </value>
                <value>
                    <fullName>Contract Administration</fullName>
                </value>
                <value>
                    <fullName>General Inquiry</fullName>
                </value>
                <value>
                    <fullName>Group Exception</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Real Time Benefits</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>Service Center</fullName>
                </value>
                <value>
                    <fullName>Subrogation</fullName>
                </value>
                <value>
                    <fullName>Vendor Type</fullName>
                </value>
                <value>
                    <fullName>Care Management and Wellness</fullName>
                    <isActive>false</isActive>
                    <label>Care Management and Wellness</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>90-day email</fullName>
                </value>
                <value>
                    <fullName>60-day email</fullName>
                </value>
                <value>
                    <fullName>Paperwork initiated</fullName>
                </value>
                <value>
                    <fullName>Paperwork submitted</fullName>
                </value>
                <value>
                    <fullName>Open Enrollment</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3rd Party Disease Management</fullName>
                </value>
                <value>
                    <fullName>ABS/Matrix Updates</fullName>
                </value>
                <value>
                    <fullName>ACA</fullName>
                </value>
                <value>
                    <fullName>Accums Inquiry</fullName>
                </value>
                <value>
                    <fullName>Additional Information Request</fullName>
                </value>
                <value>
                    <fullName>Add Member</fullName>
                </value>
                <value>
                    <fullName>Adjustment Request</fullName>
                </value>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Alt Net Related Issue</fullName>
                </value>
                <value>
                    <fullName>Appeal</fullName>
                </value>
                <value>
                    <fullName>Audit</fullName>
                </value>
                <value>
                    <fullName>BAE Portal</fullName>
                </value>
                <value>
                    <fullName>BAM PortaL</fullName>
                </value>
                <value>
                    <fullName>Benefit Booklet</fullName>
                </value>
                <value>
                    <fullName>Benefit Inquiry</fullName>
                </value>
                <value>
                    <fullName>Benefit Interpretation</fullName>
                </value>
                <value>
                    <fullName>Benefit Overview/Clarification</fullName>
                </value>
                <value>
                    <fullName>Benefits Exception</fullName>
                </value>
                <value>
                    <fullName>Benefit Value Advisor</fullName>
                </value>
                <value>
                    <fullName>Blue Care Connection/Blue Elite</fullName>
                </value>
                <value>
                    <fullName>Call Routing</fullName>
                </value>
                <value>
                    <fullName>Cancel Member</fullName>
                </value>
                <value>
                    <fullName>Case Management</fullName>
                </value>
                <value>
                    <fullName>Claim Denial</fullName>
                </value>
                <value>
                    <fullName>Claim Detail/Status Request</fullName>
                </value>
                <value>
                    <fullName>Claim Detail Request</fullName>
                </value>
                <value>
                    <fullName>Claim Exception</fullName>
                </value>
                <value>
                    <fullName>Claim Impact Reports</fullName>
                </value>
                <value>
                    <fullName>Claim in Process</fullName>
                </value>
                <value>
                    <fullName>Claim Not on File</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Competitor_Relationship__c.object
<CustomObject>
    <description>Competitors related to a Group Account as Carriers and to an Opportunity as Incumbent/ Won / Competing</description>
    <fields>
        <fullName>Competitor_Account__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Carrier or vendor account related to the relationship record of Group Account or Opportunity</description>
        <label>Competitor/3rd Party Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 3) OR 2</booleanFilter>
            <errorMessage>Please select Competitor Account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Competitor Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Competitor_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Group Account related to the Competitor Relationship for Carrier Information</description>
        <label>Group Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <errorMessage>Please select Prospect or Group or Prospect (Non BlueSTAR) or Group (Non BlueSTAR) account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Prospect_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Prospect_Non_BlueSTAR</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Account_Non_BlueSTAR</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Competitor_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Competitor Relationship</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Members__c</fullName>
        <description>Total number of members the competitor/vendor has for the related account</description>
        <label>Total Members</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competitors / 3rd Party Vendors</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors / 3rd Party Vendors</pluralLabel>
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>false</active>
        <description>Competitor for a Sales Opportunity</description>
        <label>Competitors</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture the HR status of the contact from PeopleSoft.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Leave</fullName>
                </value>
                <value>
                    <fullName>Probation</fullName>
                </value>
                <value>
                    <fullName>Short Term Leave</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Producer_Group_Association__c.object
<CustomObject>
    <description>Producer and Group associations will be stored using this object</description>
    <fields>
        <fullName>Group_Account__c</fullName>
        <description>Stores the group account related in this association</description>
        <label>Group Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Group Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Prospect</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Prospect (Non BlueSTAR)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Group Account (Non BlueSTAR)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Producers Associated to Group</relationshipLabel>
        <relationshipName>Group_Associated</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Producer Group Association</label>
    <nameField>
        <displayFormat>PAG-{0000}</displayFormat>
        <label>PAG #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Producer Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProspectingAppCtrlTest.cls
@isTest
private class ProspectingAppCtrlTest {
    static testMethod void validateQueryRecord() {
        Account compAcc = new Account();
        compAcc.Name = 'Test Competitor Account';
        compAcc.RecordTypeId = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName='Vendor' AND SobjectType='Account'].Id;
        insert compAcc;
        
        Account prodAcc = new Account();
        prodAcc.Name = 'Test Producer Account';
        prodAcc.RecordTypeId = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName='Producer_Account' AND SobjectType='Account'].Id;
        insert prodAcc;
        
        Account testAcc = new Account();
        testAcc.Name = 'Test Account';
        testAcc.Total_Num_of_Potential_Subscribers__c = 100;
        testAcc.Status__c = 'Active';
        testAcc.RecordTypeId = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName='Group_Account' AND SobjectType='Account'].Id;
        insert testAcc;
        
        List<Attachment> atts = new List<Attachment>();
        Attachment att1 = new Attachment();
        att1.Body = Blob.valueOf('Body of a png file');
        att1.Name='logo.png';
        att1.ContentType = 'image/png';
        att1.parentId = testAcc.Id;
        att1.CreatedDate = System.today();
        atts.add(att1);
        Attachment att2 = new Attachment();
        att2.Body = Blob.valueOf('Body of a png file');
        att2.Name='logo2.png';
        att2.ContentType = 'image/png';
        att2.parentId = testAcc.Id;
        att2.CreatedDate = System.today()-1;
        atts.add(att2);
        insert atts;
        
        List<Contact> cons = new List<Contact>();
        Contact con1 = new Contact();
        con1.LastName = 'Almond';
        con1.AccountId = testAcc.Id;
        cons.add(con1);
        Contact con2 = new Contact();
        con2.LastName = 'Bratwurst';
        con2.AccountId = testAcc.Id;
        cons.add(con2);
        insert cons;
        
        List<Note> notes = new List<Note>();
        Note note1 = new Note();
        note1.Title = 'Test Title 1';
        note1.CreatedDate = System.today();
        note1.ParentId = testAcc.Id;
        notes.add(note1);
        Note note2 = new Note();
        note2.Title = 'Test Title 2';
        note2.CreatedDate = System.today()-1;
        note2.ParentId = testAcc.Id;
        notes.add(note2);
        insert notes;
        
        List<Task> tasks = new List<Task>();
        Task task1 = new Task();
        
        /* had to updated Field Security to allow System Admin to View in order to access */
        /* the Category__c and Sub_Category__c custom Activity Fields.  Without the       */
        /* change the Error 'INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, bad value for       */
        /* restricted picklist field' was encountered.  Also had to update the  Field     */
        /* dependency for Sub_Category__c to allow for Category = "Other" to map to       */
        /* Sub Category = "Other".                                                        */
        
        task1.Category__c = 'Other';
        task1.Sub_Category__c = 'Other';
        
        task1.Subject = 'Subject 1';
        task1.CreatedDate = System.today();
        task1.WhatId = testAcc.Id;
        tasks.add(task1);
        Task task2 = new Task();
        
        task2.Category__c = 'Other';
        task2.Sub_Category__c = 'Other';
        
        task2.Subject = 'Subject 2';
        task2.CreatedDate = System.today()-1;
        task2.WhatId = testAcc.Id;
        tasks.add(task2);
        insert tasks;
        
        List<Competitor_Relationship__c> compRels = new List<Competitor_Relationship__c>();
        Competitor_Relationship__c compRel1 = new Competitor_Relationship__c();
        compRel1.Competitor_Account__c = compAcc.Id;
        compRel1.Group_Account__c = testAcc.Id;
        compRel1.Total_Members__c = 100;
        compRels.add(compRel1);
        Competitor_Relationship__c compRel2 = new Competitor_Relationship__c();
        compRel2.Competitor_Account__c = compAcc.Id;
        compRel2.Group_Account__c = testAcc.Id;
        compRel2.Total_Members__c = 100;
        compRels.add(compRel2);
        insert compRels;
        
        List<Producer_Group_Association__c> prodGroups = new List<Producer_Group_Association__c>();
        Producer_Group_Association__c prodGroup1 = new Producer_Group_Association__c();
        prodGroup1.Producer_Account__c = prodAcc.Id;
        prodGroup1.Group_Account__c = testAcc.Id;
        prodGroups.add(prodGroup1);
        Producer_Group_Association__c prodGroup2 = new Producer_Group_Association__c();
        prodGroup2.Producer_Account__c = prodAcc.Id;
        prodGroup2.Group_Account__c = testAcc.Id;
        prodGroups.add(prodGroup2);
        insert prodGroups;
        
        Account queriedAcc = (Account)ProspectingAppController.queryRecord('Account', testAcc.Id);
        System.assertEquals(testAcc.Id, queriedAcc.Id);
        
        queriedAcc = (Account)ProspectingAppController.queryRecord('Case', testAcc.Id);
        System.assertEquals(null, queriedAcc);
    }
    
    static testMethod void validateIsLightningProfile() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        User testUser = TestClassUtiltity.CreateUserRecord(p.Id, 'testlgnadev@user.com', 'testUser', 'test@user.com');
        system.runAs(testUser) {
            
        }
        
        
        
    }
}