src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Account record type for vendors of HCSC</description>
        <label>Vendor</label>
    </recordTypes>

objects/Competitor_Relationship__c.object
<CustomObject>
    <description>Competitors related to a Group Account as Carriers and to an Opportunity as Incumbent/ Won / Competing</description>
    <fields>
        <fullName>Competitor_Account__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <description>Carrier or vendor account related to the relationship record of Group Account or Opportunity</description>
        <label>Competitor/3rd Party Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 3) OR 2</booleanFilter>
            <errorMessage>Please select Competitor Account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Competitor Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Competitor_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Group Account related to the Competitor Relationship for Carrier Information</description>
        <label>Group Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <errorMessage>Please select Prospect or Group or Prospect (Non BlueSTAR) or Group (Non BlueSTAR) account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Prospect_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Prospect_Non_BlueSTAR</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Account_Non_BlueSTAR</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Competitor_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Competitor Relationship</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Contracts__c</fullName>
        <description>Total number of contracts the competitor/vendor has for the related account</description>
        <label>Total Contracts</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Members__c</fullName>
        <description>Total number of members the competitor/vendor has for the related account</description>
        <label>Total Members</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competitors / 3rd Party Vendors</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors / 3rd Party Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CompetitorRelationshipDAOTest.cls
@isTest(SeeAllData = false)
public class CompetitorRelationshipDAOTest { 

	@isTest
	static void competitorRelationshipDAOTest() {
		Test.StartTest();
		Id competitorAccRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get( 'Vendor' ).getRecordTypeId();
		Id groupAccRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get( 'Group Account' ).getRecordTypeId();

		CompetitorRelationshipDAO.ICompetitorRelationshipDAO competitorRelationshipDAOInstance = new CompetitorRelationshipDAO();
		
		Account compAcnt = TestClassUtiltity.CreateAccountWithRecType('TestAccount', competitorAccRecType );
		Account groupAcnt = TestClassUtiltity.CreateAccountWithRecType('TestAccount2', groupAccRecType );
		Competitor_Relationship__c compRelationship = new Competitor_Relationship__c(Status__c = 'Active', 	Total_Contracts__c = 50, Total_Members__c = 50);
		compRelationship.Competitor_Account__c = compAcnt.Id;
		compRelationship.Group_Account__c = groupAcnt.Id;
		insert compRelationship;

		Map<Id, Account> groupAccounts = new Map<Id, Account>();
		groupAccounts.put(groupAcnt.Id, groupAcnt);
		
		List<Competitor_Relationship__c> compRelationships = competitorRelationshipDAOInstance.getActiveCompetitorRelationships(groupAccounts);

		System.assertEquals(compRelationships.size(), 1);

		Test.StopTest();
	}
}