src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>District__c</fullName>
        <description>This field is used to capture the district number for a Prospect or Group Account.</description>
        <label>District</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>001</fullName>
                </value>
                <value>
                    <fullName>002</fullName>
                </value>
                <value>
                    <fullName>004</fullName>
                </value>
                <value>
                    <fullName>005</fullName>
                </value>
                <value>
                    <fullName>006</fullName>
                </value>
                <value>
                    <fullName>007</fullName>
                </value>
                <value>
                    <fullName>015</fullName>
                </value>
                <value>
                    <fullName>016</fullName>
                </value>
                <value>
                    <fullName>017</fullName>
                </value>
                <value>
                    <fullName>025</fullName>
                </value>
                <value>
                    <fullName>026</fullName>
                </value>
                <value>
                    <fullName>027</fullName>
                </value>
                <value>
                    <fullName>028</fullName>
                </value>
                <value>
                    <fullName>029</fullName>
                </value>
                <value>
                    <fullName>030</fullName>
                </value>
                <value>
                    <fullName>031</fullName>
                </value>
                <value>
                    <fullName>032</fullName>
                </value>
                <value>
                    <fullName>037</fullName>
                </value>
                <value>
                    <fullName>038</fullName>
                </value>
                <value>
                    <fullName>043</fullName>
                </value>
                <value>
                    <fullName>061</fullName>
                </value>
                <value>
                    <fullName>062</fullName>
                </value>
                <value>
                    <fullName>063</fullName>
                </value>
                <value>
                    <fullName>098</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
                <value>
                    <fullName>116</fullName>
                </value>
                <value>
                    <fullName>200</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
                <value>
                    <fullName>290</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Region__c</fullName>
        <description>This field is used to capture the region for a sold or prospect account.</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>000</fullName>
                </value>
                <value>
                    <fullName>001</fullName>
                </value>
                <value>
                    <fullName>002</fullName>
                </value>
                <value>
                    <fullName>003</fullName>
                </value>
                <value>
                    <fullName>006</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <description>This field is used to capture the district of the opportunity.</description>
        <label>District</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Region__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>001</fullName>
                </value>
                <value>
                    <fullName>002</fullName>
                </value>
                <value>
                    <fullName>004</fullName>
                </value>
                <value>
                    <fullName>005</fullName>
                </value>
                <value>
                    <fullName>006</fullName>
                </value>
                <value>
                    <fullName>007</fullName>
                </value>
                <value>
                    <fullName>015</fullName>
                </value>
                <value>
                    <fullName>016</fullName>
                </value>
                <value>
                    <fullName>017</fullName>
                </value>
                <value>
                    <fullName>025</fullName>
                </value>
                <value>
                    <fullName>026</fullName>
                </value>
                <value>
                    <fullName>027</fullName>
                </value>
                <value>
                    <fullName>028</fullName>
                </value>
                <value>
                    <fullName>029</fullName>
                </value>
                <value>
                    <fullName>030</fullName>
                </value>
                <value>
                    <fullName>031</fullName>
                </value>
                <value>
                    <fullName>032</fullName>
                </value>
                <value>
                    <fullName>037</fullName>
                </value>
                <value>
                    <fullName>038</fullName>
                </value>
                <value>
                    <fullName>043</fullName>
                </value>
                <value>
                    <fullName>061</fullName>
                </value>
                <value>
                    <fullName>062</fullName>
                </value>
                <value>
                    <fullName>063</fullName>
                </value>
                <value>
                    <fullName>098</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
                <value>
                    <fullName>116</fullName>
                </value>
                <value>
                    <fullName>200</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
                <value>
                    <fullName>290</fullName>
                </value>
                <value>
                    <fullName>300</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date_Notification_in_Days__c</fullName>
        <defaultValue>2</defaultValue>
        <description>This field is used to capture the number of days advance of the Due Date that the Opportunity Owner should receive a notification (defaulted to 2)</description>
        <label>Due Date Notification (in Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exchange_Offering_Type__c</fullName>
        <description>This field is used to capture the type of quote opportunity is requesting (Private Exchange or not)</description>
        <inlineHelpText>Type of quote opportunity is requesting - On Private Exchange and/or Off Private Exchange</inlineHelpText>
        <label>Exchange Offering Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Private Exchange</fullName>
                </value>
                <value>
                    <fullName>All On Private Exchange</fullName>
                </value>
                <value>
                    <fullName>All On Private Exchange or No Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Part On Private Exchange and Part No Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Private Exchange - Blue Directions</fullName>
                </value>
                <value>
                    <fullName>Private Exchange - External</fullName>
                </value>
                <value>
                    <fullName>Private Exchange - Blue Directions and External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Health_Members__c</fullName>
        <description>This field is used to capture the expected number of health members for the opportunity.</description>
        <inlineHelpText>Expected Health Members can be managed with the opportunities products. Please manage the membership of the products associated with this opportunity to update the number of Expected Health Members</inlineHelpText>
        <label>Expected Health Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_RFP_Release_Date__c</fullName>
        <description>This field is used to capture the expected date an RFI or RFP will be received.</description>
        <label>Expected In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFI_RFP_Received_Date__c</fullName>
        <description>This field is used to capture the date when the RFP or RFI is received.</description>
        <label>RFI/RFP Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>This field is used to capture the region of the opportunity.</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>000</fullName>
                </value>
                <value>
                    <fullName>001</fullName>
                </value>
                <value>
                    <fullName>002</fullName>
                </value>
                <value>
                    <fullName>003</fullName>
                </value>
                <value>
                    <fullName>006</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>DN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <description>This field is used to capture the requested effective date for the opportunity.</description>
        <label>Opportunity Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the user is associated</description>
        <label>Region</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GEMS_AccountStructureProductsTest.cls
/**************************************************************************************
  Apex Class Name     : GEMS_AccountStructureProductsTest
  Version             : 1.0
  Function            : This class is serves as Unit Test Class for GEMS_AccountStructureProducts 
  Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
*   Siva             06/16/2016                Original Version
*************************************************************************************/
@isTest 
public class GEMS_AccountStructureProductsTest {
private static testmethod void GEMS_AccountStructureProducts1() {
         
    Profile profileRec = [SELECT Id FROM Profile WHERE Name='System Administrator'];
    User testUser = TestClassUtiltity.CreateUserRecord(profileRec.Id, 'test@user11.com', 'testUser', 'test@user.com'); 
    
    Account acc = GEMS_UtilityClassTest.insertionAccount();
    insert acc;
    System.assertEquals('BenefitAgreementControllerTest',acc.Name);
    
         ID OppRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Sale').getRecordTypeId();
        Opportunity oppty= new Opportunity();
        oppty.RecordTypeId=OppRecTypeId;
        oppty.Name='BenefitAgreementControllerTest';
        oppty.AccountId=acc.id;
        oppty.Type='RFI';
        oppty.StageName='Expected In';
        oppty.Exchange_Offering_Type__c='No Private Exchange';
        oppty.CloseDate=Date.Today().addDays(8);
        oppty.Due_Date_Notification_in_Days__c=2;
        oppty.Expected_RFP_Release_Date__c=Date.Today().addDays(8);
        oppty.RFI_RFP_Received_Date__c=Date.Today().addDays(8);
        oppty.Requested_Effective_Date__c=Date.Today().addDays(8);
        oppty.Expected_Health_Members__c=2;
        oppty.HCSC_Division__c='IL';
        oppty.Region__c='N/A - IL';
        oppty.District__c='290';
        oppty.Clusters__c='020';
        oppty.Account_Market_Segment__c='LG';
        oppty.FSU_Location__c='Chicago';
        insert oppty;
        
        System.assertEquals('BenefitAgreementControllerTest',oppty.name);
    
        product2 productRec1=GEMS_UtilityClassTest.insertionProduct1();
        insert productRec1;
        System.assertEquals('HSA',productRec1.Product_Category__c);
       
        Opportunity_Product__c oppProd1=GEMS_UtilityClassTest.insertionOppProd1(productRec1.Id,oppty.Id);
        
        oppProd1.Status__c='Won';
        System.assertEquals('Won',oppProd1.Status__c);
        
       //oppty.Primary_Closed_Reason__c='Other';
        //oppty.StageName='Won';
       // update oppty;
        
         Case subRec= GEMS_UtilityClassTest.insertionCase('GEMS Account Submission');
        subRec.status = 'In Progress';
        subRec.Funding_Type_Multiselect__c = 'ACAP';
        subRec.GEMS_AEP_Account__c= true;
        insert subRec;
        
        Id subCaserecordTypeId= Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS Account Submission').getRecordTypeId();
        
        Case subCaseRec = [Select id, recordtype.id from case where recordtypeid=:subCaserecordTypeId];
        System.assertEquals(subCaserecordTypeId,subCaseRec.recordtype.id);
        
    
    /*GEMS_UtilityClassTest.insertionAccount(); 
    GEMS_UtilityClassTest.insertionOpp();
    GEMS_UtilityClassTest.insertionProduct();    
    GEMS_UtilityClassTest.insertionOpportunityProduct();      
    Id GEMSAccstructurerectyid = Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS Account Structure').getRecordTypeId();
    case CaseObj = GEMS_UtilityClassTest.insertionCase(GEMSAccstructurerectyid);*/
   
        system.runAs(testUser){
        //ApexPages.currentpage().getParameters().put('OppProd',OppProd.id);
        ApexPages.currentPage().getParameters().put('caseId',subCaseRec .id);
        ApexPages.StandardController stdController   = new ApexPages.StandardController(subCaseRec );
        GEMS_AccountStructureProducts gems = new GEMS_AccountStructureProducts(stdController);
        
        gems.getOpportunityProduct();
   }    
        
}

 }