src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Account_Cluster_Name__c</fullName>
        <description>This field is used to capture the name of the marketing individual represented by the cluster number as listed in BlueStar</description>
        <inlineHelpText>This field is pulling the Account Executive name from BlueStar, listed as Account Cluster Name in BlueStar</inlineHelpText>
        <label>Account Executive 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Account_Executive_2__c</fullName>
        <description>This field is used to capture the second Account Executive as listed in BlueStar</description>
        <label>Account Executive 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Ceded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if an account is ceded from another plan.</description>
        <label>Ceded?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>COBRA_Administration_Type__c</fullName>
        <description>This field is used to capture the COBRA Administration type as listed in BlueStar; GRP = Group Administers; HCSC = COBRA Admin Marion; OTHR = Non HCSC Vendor administers; N/A.</description>
        <label>COBRA Administration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GRP</fullName>
                </value>
                <value>
                    <fullName>HCSC</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>OTHR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Critical_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator for high-profile accounts (current groups or prospects) that are large in size or have some material impact on the plan</description>
        <label>Critical Account?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Current_Risk_Level__c</fullName>
        <description>This field is used to capture the risk level for a Group Account (1 being Renewed and 6 being Cancelled).</description>
        <label>Risk Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Renewed</fullName>
                    <label>1 - Low (Renewed)</label>
                </value>
                <value>
                    <fullName>3 - Medium</fullName>
                    <label>2 - Medium</label>
                </value>
                <value>
                    <fullName>4 - High</fullName>
                    <label>3 - High</label>
                </value>
                <value>
                    <fullName>5 - In Jeopardy</fullName>
                    <label>4 - In Jeopardy</label>
                </value>
                <value>
                    <fullName>6 - Terminated</fullName>
                    <label>5 - Terminated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Exchange_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if the client is interested in or has group products offered on a private exchange.</description>
        <label>Exchange Account?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Exchange_Name__c</fullName>
        <description>This field is used to capture the name of the group private exchange offered to members.</description>
        <label>Group Private Exchange</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blue Directions for Individuals</fullName>
                </value>
                <value>
                    <fullName>Blue Directions for Small Business</fullName>
                </value>
                <value>
                    <fullName>Blue Directions for Large Business</fullName>
                </value>
                <value>
                    <fullName>Blue Directions for Retirees</fullName>
                </value>
                <value>
                    <fullName>Aon Hewitt Active Exchange</fullName>
                </value>
                <value>
                    <fullName>Mercer Marketplace</fullName>
                </value>
                <value>
                    <fullName>Buck RightOpt</fullName>
                </value>
                <value>
                    <fullName>Towers Watson OneExchange</fullName>
                </value>
                <value>
                    <fullName>Gallagher Marketplace</fullName>
                </value>
                <value>
                    <fullName>Willis Marketplace</fullName>
                </value>
                <value>
                    <fullName>USI Marketplace</fullName>
                </value>
                <value>
                    <fullName>BB&amp;T / McGriff Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Buck/Right Opt Private Exchange</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCM_Program_Model__c</fullName>
        <description>This field is used to capture the Health Care Management program offered by the group</description>
        <label>HCM Program Model</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BCC Standard</fullName>
                </value>
                <value>
                    <fullName>BCC Enhanced</fullName>
                </value>
                <value>
                    <fullName>BCC Elite</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>MHA</fullName>
                </value>
                <value>
                    <fullName>Primary Nurse 1</fullName>
                </value>
                <value>
                    <fullName>Primary Nurse 2</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Risk_Reason__c</fullName>
        <description>This field is used to capture the rationale of Risk Rating given to the Group.</description>
        <label>Risk Reason</label>
        <type>TextArea</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Sliced__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if an account has sliced business across multiple carriers.  It is populated based on Carriers associated to the account.</description>
        <label>Split?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCM_Program_Model__c</fullName>
        <description>This field is used to capture the Health Care Management program proposed as part of the opportunity</description>
        <inlineHelpText>Health Care Management program the group is interested in purchasing</inlineHelpText>
        <label>HCM Program Model</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BCC Standard</fullName>
                </value>
                <value>
                    <fullName>BCC Enhanced</fullName>
                </value>
                <value>
                    <fullName>BCC Elite</fullName>
                </value>
                <value>
                    <fullName>MHA</fullName>
                </value>
                <value>
                    <fullName>Primary Nurse 1</fullName>
                </value>
                <value>
                    <fullName>Primary Nurse 2</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LGNA_RenewalWarningMessageCntlrTest.cls
/**************************************************************************************
  Apex Class Name     : LGNA_RenewalWarningMessageCntlr 
  Version             : 1.0
  Function            : This is Test Class for LGNA_RenewalWarningMessageCntlr
  Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------
*  Sujatha Gondi       09/21/2017                Original Version
*************************************************************************************/
@isTest   
public class LGNA_RenewalWarningMessageCntlrTest {
 static  Account testAccount,testAccount1 ;
     static  Opportunity testOpp,testopp1 ;
    static
    {
       
        testAccount = new Account();
        testAccount.Ceded__c = true;
        testAccount.HCM_Program_Model__c = 'BCC Elite';
        testAccount.Funding_Type__c = 'PREM';
        testAccount.Cobra_Administration_Type__c = 'HCSC';
        testAccount.Exchange_Account__c = true;
        testAccount.Exchange_Name__c = 'Mercer Marketplace';
        testAccount.Sliced__c = true;
        //testAccount.recordtypeid='Group Account';
        testAccount.Current_Risk_Level__c = '3 - Medium';
        testAccount.Status__c = 'Active';
        testAccount.Critical_Account__c = True;
        testAccount.Risk_Reason__c = 'Test';
        testAccount.HCSC_Division__c = 'TX';
        testAccount.Account_Cluster_Name__c = 'John Testing';
        testAccount.Account_Executive_2__c = 'Jane Testing';
        testAccount.Underwriter_User_ID__c = 'UU456';
        testAccount.Name='test Account';
        insert testAccount;
        
        testAccount1 = new Account();
        
        List<User> testUsers = new List<User>();
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
            testUsers.add(new User(Alias = 'standt1', Email = 'john.testing@testorg.com',EmailEncodingKey = 'UTF-8', LastName = 'Testing', FirstName = 'John', LanguageLocaleKey = 'en_US',LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles',UserName = 'john.testing@testorg.com', isActive = TRUE));
            testUsers.add(new User(Alias = 'standt6', Email = 'sana.testing@testorg.com',EmailEncodingKey = 'UTF-8', LastName = 'Testing', FirstName = 'Sana', LanguageLocaleKey = 'en_US',LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles',UserName = 'sana.testing@testorg.com', isActive = TRUE, Lan_Id__c = 'UU4569'));
        insert testUsers;
        
        testOpp = new Opportunity();
        testOpp.Type = 'RFP';
        testOpp.AccountId = testAccount.Id;
        testOpp.RecordTypeId = '01233000000QMPDAA4';
        testOpp.Exchange_Offering_Type__c = 'All On Private Exchange';
        testOpp.Probability = 60;
        testOpp.StageName = 'Prospecting';
        testOpp.Finalist__c = 'No';
        testOpp.Due_Date_Notification_in_Days__c = 45;
        //testOpp.recordtypeid='Group Account';
        testOpp.Expected_Health_Members__c = 23;
        testOpp.Expected_Health_Contracts__c = 56;
        testOpp.Projected_Membership_Gain_Loss__c = 78;
        testOpp.Expected_Dental_Members__c = 43;
        testOpp.Expected_Dental_Contracts__c = 78;
        testOpp.Description = 'tests today description';
        testOpp.Primary_Closed_Reason__c = 'Change of Ownership';
        testOpp.Weekly_Activity_Report__c = false;
        testOpp.Name='test Opportuntiy';
        testOpp.Requested_Effective_Date__c=Date.today();
        testOpp.CloseDate=Date.today();
         testOpp.RFI_RFP_Received_Date__c=Date.today();
        insert testOpp;
 
     }
    public static testMethod void testDetailPage(){
        Test.startTest();
        //LGNA_OpenEnrollCntlr oe= new LGNA_OpenEnrollCntlr();
        LGNA_RenewalWarningMessageCntlr.getOpportunityRenewalList(testAccount.id,testOpp.RecordTypeId);
        Test.stopTest();
    }
    
    
}