src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/GEMS_Benefit_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>AccountStructureCase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Structure Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Benefit Agreements</relationshipLabel>
        <relationshipName>GEMS_Benefit_Agreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Agreements</relationshipLabel>
        <relationshipName>GEMS_Benefit_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BA_Description__c</fullName>
        <label>BA Description</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BA_Fund_Type__c</fullName>
        <label>BA Fund Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>BASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Assoc__c</fullName>
        <label>Billing Assoc</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Profile__c</fullName>
        <label>Billing Profile</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancel_Date__c</fullName>
        <label>Cancel Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_Card_Type__c</fullName>
        <label>ID Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BA Plan</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Plan__c.Product__c</field>
                <operation>equals</operation>
                <valueField>$Source.Product__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>GEMS Benefit Agreements</relationshipLabel>
        <relationshipName>GEMS_Benefit_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BA Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>GEMS Benefit Agreements</relationshipLabel>
        <relationshipName>GEMS_Benefit_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <description>TX Only</description>
        <label>Schedule</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>GEMS Benefit Agreement</label>
    <nameField>
        <label>BA No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Benefit Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Market_Segment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Segment Picklist values from Account</description>
    <label>Market Segment</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the product related to the child opportunity.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Plan__c.object
<CustomObject>
    <description>To capture all the plans related to products - Loaded from BlueStar</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External id for integration with BlueStar.</description>
        <externalId>true</externalId>
        <inlineHelpText>REQUIRED for user to submit plan to BlueSTAR must be the corp plan ID from BlueSTAR</inlineHelpText>
        <label>Plan Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product the Plan is related</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GEMS_CaptureBenefitAgreementsController.cls
public class GEMS_CaptureBenefitAgreementsController {


    public Id caseId;
    public Id accountId;
    public List<BAWrapper> listOfBAs {get; set;}
    public Integer numberOfRowToRemove {get; set;}
    public Id recordToDelete {get; set;}
    public boolean hasEditAccess{get;set;}
    public string rowCount{get;set;}
    public string BARecordId{get;set;}
    public Map<Id, GEMS_Benefit_Agreement__c> mapOfIdAndBA;
    public BAWrapper BA;
    public List<GEMS_Benefit_Agreement__c> selectedBAs;
    public GEMS_CaptureBenefitAgreementsController(ApexPages.StandardSetController controller) {
        caseId = ApexPages.currentPage().getParameters().get('caseId');
        accountId = ApexPages.currentPage().getParameters().get('accountId');
        UserRecordAccess userAccess = [SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId = :UserInfo.getUserId() AND RecordId = :caseId limit 1][0];
        if(userAccess.HasEditAccess){
            hasEditAccess= true;
            try{
                List<GEMS_Benefit_Agreement__c> existingBAs = getBAs();
                mapOfIdAndBA = new Map<Id, GEMS_Benefit_Agreement__c>(existingBAs);
                listOfBAs = new List<BAWrapper>();
                if(!existingBAs.isEmpty()){
                    GEMS_Benefit_Agreement__c tempBA;
                    for(GEMS_Benefit_Agreement__c existingBA : existingBAs){
                        BA = new BAWrapper(true, existingBA);
                        listOfBAs.add(BA);
                    }
                }else{
                    listOfBAs= new List<BAWrapper>();
                    BA = new BAWrapper(true, new GEMS_Benefit_Agreement__c(Account__c = accountId, AccountStructureCase__c = caseId));
                    listOfBAs.add(BA);
                    System.debug('New - ' + listOfBAs);
                }
                
            }
            catch(Exception e){
                GEMS_CreateExceptionLog.insertErrorLog(e, null, null, null, 'Apex Class', 'opportunity', null, 'GEMS_CaptureBenefitAgreementsController(ApexPages.StandardSetController controller)','High'); 
            }
        }else{
            hasEditAccess = false;
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, system.label.InsufficientError)); 
        }
        
    }
    
    /*
    public Case getParentCase(){
    Case C = [SELECT Id, CaseNumber, HCSC_Division__c, GEMS_Case_Effective_Date__c, GEMS_Submission_Type__c, GEMS_Submission_Sub_Type__c, 
                GEMS_Line_of_Business__c, GEMS_Account_Submission_Info__c, Market_Segment__c, Status, Owner.Name, GEMS_Type__c,
                    Account.AccountNumber, Account.External_ID__c, Account.Name, GEMS_Account_Submission_Info__r.Funding_Type_Multiselect__c
                         FROM Case WHERE id =: caseId AND AccountId =: accountId];
      
     String[] tmpString = C.GEMS_Account_Submission_Info__r.Funding_Type_Multiselect__c.split(';');                   
     for(String Val : tmpString){
         if (Val == 'ASO'){
             renderMe = 1;
         }
         else if (Val == 'Premium'){
             renderMe = 0;
         }
         else {
             renderMe = 2;
         }
     }
    return C;
    }
    
    */
    
    public Case ParCase {
    get{
    return     [SELECT Id, CaseNumber, HCSC_Division__c, GEMS_Case_Effective_Date__c, GEMS_Submission_Type__c, GEMS_Submission_Sub_Type__c, 
                GEMS_Line_of_Business__c, GEMS_Account_Submission_Info__c, Market_Segment__c, Status, Owner.Name, GEMS_Type__c,
                    Account.AccountNumber, Account.External_ID__c, Account.Name, GEMS_Account_Submission_Info__r.Funding_Type_Multiselect__c
                         FROM Case WHERE id =: caseId AND AccountId =: accountId];
                         }
    set;
    }
    
        public Integer renderMe{
    get{
     String[] tmpString = ParCase.GEMS_Account_Submission_Info__r.Funding_Type_Multiselect__c.split(';'); 
     Integer renderMe = 2;                  
     for(String Val : tmpString){
         if (Val == 'ASO'){
             renderMe =  1;
         }
         else if (Val == 'Premium'){
             renderMe = 0;
         }
     }
     return renderMe;
    }
    set;}
    /*
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT Id, Name, Account__c, BA_Description__c, BA_Fund_Type__c,Effective_Date__c, Product__c,Cancel_Date__c,Schedule__c, Plan__c,
                    ID_Card_Type__c, Billing_Profile__c, Billing_Assoc__c,
                    AccountStructureCase__r.HCSC_Division__c
                     FROM GEMS_Benefit_Agreement__c
                     WHERE AccountStructureCase__c = : caseId
                     ORDER BY Name ASC]));
            }
            setCon.setPageSize(500);
            return setCon;
        }
        set;
    }
    */
    
    public PageReference removeBA(){
        system.debug('numberOfRowToRemove--'+numberOfRowToRemove);
        try{
            listOfBAs.remove(numberOfRowToRemove - 1);
            
            if(recordToDelete !=null && !mapOfIdAndBA.isEmpty()){
                if(mapOfIdAndBA.containsKey(recordToDelete)){
                    delete mapOfIdAndBA.get(recordToDelete);
                }
            }
            
        }catch(Exception ex){
            CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'opportunity', null, 'AddOpportunityProductsController.removeRow()','High'); 
        }
        return null;
    }
    public void getTheUpdatedMembersCount(){
        try{
            decimal recCount = 1;
            for(BAWrapper opw : listOfBAs){                
                ++recCount;
            }
        }catch(Exception e){
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage())); 
        }
    }
    public PageReference removeRow(){
        system.debug('numberOfRowToRemove--'+numberOfRowToRemove);
        try{
            listOfBAs.remove(numberOfRowToRemove - 1);
            if(recordToDelete !=null && !mapOfIdAndBA.isEmpty()){
                if(mapOfIdAndBA.containsKey(recordToDelete)){
                    delete mapOfIdAndBA.get(recordToDelete);
                }
            }
        }catch(Exception ex){
            CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'opportunity', null, 'AddOpportunityProductsController.removeRow()','High'); 
        }
        return null;
    }
    public List<GEMS_Benefit_Agreement__c> getBAs() {
        //return (List<GEMS_Benefit_Agreement__c>) setCon.getRecords();
        return (List<GEMS_Benefit_Agreement__c>) ([SELECT Id, Name, Account__c, BA_Description__c, BA_Fund_Type__c, Product__c,Schedule__c, Plan__c,
                    ID_Card_Type__c, Billing_Profile__c, Billing_Assoc__c,
                    AccountStructureCase__r.HCSC_Division__c
                     FROM GEMS_Benefit_Agreement__c
                     WHERE AccountStructureCase__c = : caseId
                     ORDER BY Name ASC]);
    }
    public PageReference addBA(){
        BA = new BAWrapper(true, new GEMS_Benefit_Agreement__c(Account__c = accountId, AccountStructureCase__c = caseId));
        listOfBAs.add(BA);
        return null;
    }
    public PageReference saveBAs() {
        selectedBAs = new List<GEMS_Benefit_Agreement__c>();
        try{
            for(BAWrapper BAWrapper : listOfBAs){
                if(BAWrapper .isSelected == true){
                    selectedBAs.add(BAWrapper.BA);
                    //TODO : Need to add duplicate check
                }
            }
            String recs = 'recs=';
            if(!selectedBAs.isEmpty()){
                upsert selectedBAs;
                Integer count = selectedBAs.size();
                recs = recs + selectedBAs[0].Id;
                Integer i = 1;
                while(i < count){
                    recs = recs + '%2C' + selectedBAs[i].id;
                    i = i +1;
                }
                return new PageReference( '/apex/GEMSAssignBACat?' + recs);
                //return new PageReference('/apex/GEMSCaptureBenefitAgreements?caseId=' + caseId + '&accountId=' + accountId);
                //return new PageReference('/'+CaseId);
            }
            else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select at least one BA'));
                return null;
            }
        }catch(Exception ex){
            CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'opportunity', null, 'AddOpportunityProductsController.removeRow()','High');
            ApexPages.addMessages(ex);
            return null;
        }
    }
    public PageReference gotoCase() {
        //return new PageReference('/GEMSAccountStructure?Id=' + caseId);
        return new PageReference('/'+caseId);
    }
    
    /*
     public PageReference gotoAssignment(){
        saveBAs();
        selectedBAs = new List<GEMS_Benefit_Agreement__c>();
        try{
            for(BAWrapper BAWrapper : listOfBAs){
                if(BAWrapper .isSelected == true){
                    selectedBAs.add(BAWrapper.BA);
                    //TODO : Need to add duplicate check
                }
            }
        String recs = 'recs=';
        if(!selectedBAs.isEmpty()){
            Integer count = selectedBAs.size();
            recs = recs + selectedBAs[0].Id;
            Integer i = 1;
            while(i < count){
                recs = recs + '%2C' + selectedBAs[i].id;
                i = i +1;
            }
        }
        return new PageReference( '/apex/GEMSAssignBACat?' + recs);
        }catch(Exception ex){
            CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'opportunity', null, 'AddOpportunityProductsController.removeRow()','High'); 
            return null;
        }
    }
    */
    public class BAWrapper {
        public boolean isSelected {get; set;}
        public GEMS_Benefit_Agreement__c BA {get; set;}
        //public boolean benefitAgreementCheck {get; set;}
        public BAWrapper (boolean isSelected, GEMS_Benefit_Agreement__c BA){
            this.isSelected = isSelected;
            this.BA = BA;
        }
    }
    
}