src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Business need is to show the products that were renewed for the account last year.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_Decision_Date__c</fullName>
        <description>This field is used to capture the date when a decision is expected for the Opportunity.</description>
        <label>Expected Decision Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_RFP_Release_Date__c</fullName>
        <description>This field is used to capture the expected date an RFI or RFP will be received.</description>
        <label>Expected In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Closed_Reason__c</fullName>
        <description>This field is used to capture the primary reason why an Opportunity is won, lost or declined.</description>
        <label>Primary Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absorbed by Parent Group</fullName>
                </value>
                <value>
                    <fullName>Change of Ownership</fullName>
                </value>
                <value>
                    <fullName>Consol. Covg with 1 Carrier</fullName>
                </value>
                <value>
                    <fullName>Headquarters Relocated</fullName>
                </value>
                <value>
                    <fullName>Lack of Narrow Network</fullName>
                </value>
                <value>
                    <fullName>Market Check by Group</fullName>
                </value>
                <value>
                    <fullName>Organizational Changes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Guarantees</fullName>
                </value>
                <value>
                    <fullName>Plan Design-Other</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Purchase by Another Company</fullName>
                </value>
                <value>
                    <fullName>Rates-Aggregate Stop Loss-Claim/Attch Factor</fullName>
                </value>
                <value>
                    <fullName>Rates-Incumbent Reduced</fullName>
                </value>
                <value>
                    <fullName>Rates-Individual Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Rates-Insured</fullName>
                </value>
                <value>
                    <fullName>Repricing</fullName>
                </value>
                <value>
                    <fullName>Reputation of Selected Carrier</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Broker Relationship</fullName>
                </value>
                <value>
                    <fullName>Changed Brokers</fullName>
                </value>
                <value>
                    <fullName>Network Discounts</fullName>
                </value>
                <value>
                    <fullName>Network Disruption</fullName>
                </value>
                <value>
                    <fullName>Product Packaging</fullName>
                </value>
                <value>
                    <fullName>Did Not Want to Disrupt Ees</fullName>
                </value>
                <value>
                    <fullName>Not Enough Diff. to Change</fullName>
                </value>
                <value>
                    <fullName>PUG Did not meet participation</fullName>
                </value>
                <value>
                    <fullName>Rates-Admin. Charge too High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFI_RFP_Received_Date__c</fullName>
        <description>This field is used to capture the date when the RFP or RFI is received.</description>
        <label>RFI/RFP Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <description>This field is used to capture the requested effective date for the opportunity.</description>
        <label>Opportunity Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity_Product__c.object
<CustomObject>
    <description>Products related to the opportunity - acting as a junction object</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Sales status of opportunity product</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>GeoAccess/Discount Analysis/Proposal Provided</fullName>
                </value>
                <value>
                    <fullName>Pricing/Presentation to Client</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{000}</displayFormat>
        <label>OP #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rate__c.object
<CustomObject>
    <description>Contains the rate information pertaining to BPA</description>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>Captures HCSC division</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rate</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RatingMatrixControllerTest.cls
/**************************************************************************************
  Apex Class Name     : RatingMatrixControllerTest
  Version             : 1.0
  Function            : This is a test class for the RatingMatrixController class
* Developer                        Date                  
* ----------------------------------------------------------------------------                 
* Nick Serafin/Slalom             6/1/2016
*************************************************************************************/
@isTest(SeeAllData=false)
private class RatingMatrixControllerTest { 

	@isTest static void ratingMatrixTest(){
		
		Account TestAcnt = new Account();
        TestAcnt.Id = fflib_IDGenerator.generate( Account.SObjectType );

		Opportunity opp = new Opportunity(AccountId = TestAcnt.id, HCSC_Division__c = 'IL', Name='oppName 3',StageName = 'Expected In', CloseDate = System.Today().addYears(2), Expected_RFP_Release_Date__c = System.Today().addYears(1), Expected_Decision_Date__c = System.Today().addYears(1), RFI_RFP_Received_Date__c = System.Today().addYears(1), Primary_Closed_Reason__c = 'Savings');
        opp.Requested_Effective_Date__c = System.Today() - 1;         
        opp.Id = fflib_IDGenerator.generate( Opportunity.SObjectType );

		List<Product2> product = TestClassUtiltity.createProducts();
        product[0].Id = fflib_IDGenerator.generate( Product2.SObjectType ); 
        product[1].Id = fflib_IDGenerator.generate( Product2.SObjectType ); 
            
        List<Opportunity_Product__c> opptyProd = TestClassUtiltity.createOppProducts(opp.id,product[0].Id);
        opptyProd[0].Status__c = 'In Progress';
        opptyProd[0].Product_Type__c = 'New Sale';
        opptyProd[0].Id = fflib_IDGenerator.generate( Opportunity_Product__c.SObjectType ); 

		Secure_Information__c testSecure = new Secure_Information__c(Opportunity_Name__c = opp.Id);
		testSecure.Id = fflib_IDGenerator.generate( Secure_Information__c.SObjectType ); 

		Rate__c testRate = new Rate__c(Secure_Information__c = testSecure.Id);
		testRate.Id = fflib_IDGenerator.generate( Rate__c.SObjectType );

		List<Rate_Product__c> rateProdsInsert = new List<Rate_Product__c>();

		Rate_Product__c rateProd = new Rate_Product__c(Rate__c = testRate.Id);
		rateProd.Id = fflib_IDGenerator.generate( Rate_Product__c.SObjectType );

		rateProdsInsert.add(rateProd);

		PageReference pageRef = new PageReference('/apex/RatingMatrix');
		pageRef.getParameters().put('oid',  opp.Id);
		pageRef.getParameters().put('state', 'IL');
		pageRef.getParameters().put('secure', testSecure.Id);
		Test.setCurrentPage(pageRef);

		fflib_ApexMocks oppProductsMocks = new fflib_ApexMocks(); 

        OpportunityProductDAO.IOpportunityProductDAO opportunityProductInstance;
        opportunityProductInstance = new MockDAOs.OpportunityProductDAOMock(oppProductsMocks);  

        oppProductsMocks.startStubbing();
        oppProductsMocks.when(opportunityProductInstance.getRatingProducts(opp.Id))
                    .thenReturn(opptyProd);
        oppProductsMocks.stopStubbing();

       	fflib_ApexMocks rateMocks = new fflib_ApexMocks(); 

        RateDAO.IRateDAO rateInstance;
        rateInstance = new MockDAOs.RateDAOMock(rateMocks);  

        rateMocks.startStubbing();
        rateMocks.when(rateInstance.insertRate(testRate))
                    .thenReturn(testRate);
        rateMocks.stopStubbing();

        fflib_ApexMocks rateProductMocks = new fflib_ApexMocks(); 

        RateProductDAO.IRateProductDAO rateProductInstance;
        rateProductInstance = new MockDAOs.RateProductDAOMock(rateProductMocks);

        rateProductMocks.startStubbing();
        rateProductMocks.when(rateProductInstance.insertRateProducts(rateProdsInsert))
                    .thenReturn(rateProdsInsert);
        rateProductMocks.stopStubbing();   

		Test.startTest();

		ApexPages.StandardController sc2 = new ApexPages.StandardController(testRate);
		RatingMatrixController ratingController = new RatingMatrixController(sc2, opportunityProductInstance, rateInstance, rateProductInstance);

		ratingController.opportunityProductDAOInstance = opportunityProductInstance;
		ratingController.rateDAOInstance = rateInstance;
		ratingController.rateProductDAOInstance = rateProductInstance;

		System.assertEquals(1, ratingController.opportunityProds.size());

		ratingController.numberOfYears = 'One Year';
		ratingController.hcscDivision = 'IL';
		ratingController.otherRate = 'test';
		ratingController.rateStructure = 'Employee Only';
		ratingController.saveRateBackground();
		ratingController.saveNewRateRecord();
		ratingController.cancel();

		System.assertEquals(1, ratingController.rateProds.size());

		Test.stopTest();
	}

	@isTest static void ratingMatrixEditTest(){
		
		Account TestAcnt = new Account();
        TestAcnt.Id = fflib_IDGenerator.generate( Account.SObjectType );

		Opportunity opp = new Opportunity(AccountId = TestAcnt.id, HCSC_Division__c = 'IL', Name='oppName 3',StageName = 'Expected In', CloseDate = System.Today().addYears(2), Expected_RFP_Release_Date__c = System.Today().addYears(1), Expected_Decision_Date__c = System.Today().addYears(1), RFI_RFP_Received_Date__c = System.Today().addYears(1), Primary_Closed_Reason__c = 'Savings');
        opp.Requested_Effective_Date__c = System.Today() - 1;         
        opp.Id = fflib_IDGenerator.generate( Opportunity.SObjectType );

		List<Product2> product = TestClassUtiltity.createProducts();
        product[0].Id = fflib_IDGenerator.generate( Product2.SObjectType ); 
        product[1].Id = fflib_IDGenerator.generate( Product2.SObjectType ); 
            
        List<Opportunity_Product__c> opptyProd = TestClassUtiltity.createOppProducts(opp.id,product[0].Id);
        opptyProd[0].Status__c = 'In Progress';
        opptyProd[0].Product_Type__c = 'New Sale';
        opptyProd[0].Id = fflib_IDGenerator.generate( Opportunity_Product__c.SObjectType ); 

		Secure_Information__c testSecure = new Secure_Information__c(Opportunity_Name__c = opp.Id);
		testSecure.Id = fflib_IDGenerator.generate( Secure_Information__c.SObjectType ); 

		Rate__c testRate = new Rate__c(Secure_Information__c = testSecure.Id);
		testRate.Id = fflib_IDGenerator.generate( Rate__c.SObjectType );

		List<Rate_Product__c> rateProdsInsert = new List<Rate_Product__c>();

		Rate_Product__c rateProd = new Rate_Product__c(Rate__c = testRate.Id);
		rateProd.Id = fflib_IDGenerator.generate( Rate_Product__c.SObjectType );

		rateProdsInsert.add(rateProd);

		PageReference pageRef = new PageReference('/apex/RatingMatrix');
		pageRef.getParameters().put('rateId',  testRate.Id);
		Test.setCurrentPage(pageRef);

		fflib_ApexMocks oppProductsMocks = new fflib_ApexMocks(); 

        OpportunityProductDAO.IOpportunityProductDAO opportunityProductInstance;
        opportunityProductInstance = new MockDAOs.OpportunityProductDAOMock(oppProductsMocks);

		fflib_ApexMocks rateMocks = new fflib_ApexMocks(); 

        RateDAO.IRateDAO rateInstance;
        rateInstance = new MockDAOs.RateDAOMock(rateMocks);  

        rateMocks.startStubbing();
        rateMocks.when(rateInstance.grabRateObj(testRate.Id))
                    .thenReturn(testRate);
        rateMocks.stopStubbing();

        rateMocks.startStubbing();
        rateMocks.when(rateInstance.updateRate(testRate))
                    .thenReturn(testRate);
        rateMocks.stopStubbing();

        fflib_ApexMocks rateProductMocks = new fflib_ApexMocks(); 

        RateProductDAO.IRateProductDAO rateProductInstance;
        rateProductInstance = new MockDAOs.RateProductDAOMock(rateProductMocks);  

        rateProductMocks.startStubbing();
        rateProductMocks.when(rateProductInstance.grabRateProducts(testRate.Id))
                    .thenReturn(rateProdsInsert);
        rateProductMocks.stopStubbing();

        rateProductMocks.startStubbing();
        rateProductMocks.when(rateProductInstance.updateRateProducts(rateProdsInsert))
                    .thenReturn(rateProdsInsert);
        rateProductMocks.stopStubbing();

		Test.startTest();

		ApexPages.StandardController sc2 = new ApexPages.StandardController(testRate);
		RatingMatrixController ratingController = new RatingMatrixController(sc2, opportunityProductInstance, rateInstance, rateProductInstance);

		ratingController.opportunityProductDAOInstance = opportunityProductInstance;
		ratingController.rateDAOInstance = rateInstance;
		ratingController.rateProductDAOInstance = rateProductInstance;

		System.assertEquals(1, ratingController.rateProds.size());

		ratingController.numberOfYears = 'One Year';
		ratingController.hcscDivision = 'IL';
		ratingController.otherRate = 'test';
		ratingController.rateStructure = 'Employee Only';
		ratingController.saveRateBackground();
		ratingController.otherRate = 'New Test';
		ratingController.saveNewRateRecord();
		ratingController.cancel();

		System.assertEquals('New Test', ratingController.otherRate);

		Test.stopTest();
	}

	@isTest static void testException(){
	
	try{	

		Account TestAcnt = new Account();
        TestAcnt.Id = fflib_IDGenerator.generate( Account.SObjectType );

		Opportunity opp = new Opportunity(AccountId = TestAcnt.id, HCSC_Division__c = 'IL', Name='oppName 3',StageName = 'Expected In', CloseDate = System.Today().addYears(2), Expected_RFP_Release_Date__c = System.Today().addYears(1), Expected_Decision_Date__c = System.Today().addYears(1), RFI_RFP_Received_Date__c = System.Today().addYears(1), Primary_Closed_Reason__c = 'Savings');
        opp.Requested_Effective_Date__c = System.Today() - 1;         
        opp.Id = fflib_IDGenerator.generate( Opportunity.SObjectType );

		Secure_Information__c testSecure = new Secure_Information__c(Opportunity_Name__c = opp.Id);
		testSecure.Id = fflib_IDGenerator.generate( Secure_Information__c.SObjectType ); 

		Rate__c testRate = new Rate__c(Secure_Information__c = testSecure.Id);
		testRate.Id = fflib_IDGenerator.generate( Rate__c.SObjectType );

		PageReference pageRef = new PageReference('/apex/RatingMatrix');
		pageRef.getParameters().put('state', 'IL');
		pageRef.getParameters().put('secure', '');
		Test.setCurrentPage(pageRef);

		fflib_ApexMocks oppProductsMocks = new fflib_ApexMocks(); 

        OpportunityProductDAO.IOpportunityProductDAO opportunityProductInstance;
        opportunityProductInstance = new MockDAOs.OpportunityProductDAOMock(oppProductsMocks);

		fflib_ApexMocks rateMocks = new fflib_ApexMocks(); 

        RateDAO.IRateDAO rateInstance;
        rateInstance = new MockDAOs.RateDAOMock(rateMocks);  

        fflib_ApexMocks rateProductMocks = new fflib_ApexMocks(); 

        RateProductDAO.IRateProductDAO rateProductInstance;
        rateProductInstance = new MockDAOs.RateProductDAOMock(rateProductMocks);  

        Test.startTest(); 

		ApexPages.StandardController sc2 = new ApexPages.StandardController(testRate);
		RatingMatrixController ratingController = new RatingMatrixController(sc2, opportunityProductInstance, rateInstance, rateProductInstance);

		ratingController.opportunityProductDAOInstance = opportunityProductInstance;
		ratingController.rateDAOInstance = rateInstance;
		ratingController.rateProductDAOInstance = rateProductInstance;

		ratingController.saveRateBackground();

		}catch(Exception ex){

			System.assertEquals('System.NullPointerException: Attempt to de-reference a null object', ex.getMessage());
		}

		Test.stopTest();
	}

}