src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Hold_End_Date__c</fullName>
        <label>Hold End Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Business need is to show the products that were renewed for the account last year.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>SGR_Hold_Reason__c</fullName>
        <label>Hold Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Wage &amp; Tax Audit</fullName>
                </value>
                <value>
                    <fullName>1st Year Renewal</fullName>
                </value>
                <value>
                    <fullName>Block Acquisition</fullName>
                </value>
                <value>
                    <fullName>Special Adjustments</fullName>
                </value>
                <value>
                    <fullName>Market Segment Verification</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Sgr_Beng_PreviewPDFTest.cls
@Istest
public with sharing class Sgr_Beng_PreviewPDFTest {
  Public static testmethod void Validte_sgrBengRequest(){
      Beng_PDF_Preview_profiles__c cs = Beng_PDF_Preview_profiles__c.getValues(UserInfo.getProfileId());
        opportunity opp = new opportunity();
             Account newAccount1 = new Account(Name='TarunFinalTest',External_ID__c ='1992', HCSC_Division__c = 'IL', 
                                         Renewal_Date__c = date.today(),status__c = 'Active', Hold_End_Date__c =date.today(),
                                         Funding_Type__c='PREM',Product_Type__c='H',Market_Segment__c='SG',SGR_Hold_Reason__c='1st Year Renewal');
                                           
             insert newAccount1;
        
            opp.Accountid = newAccount1.id;
            opp.Name = 'Sample';
            opp.StageName = 'lost';
            opp.Product_Type__c='H';
            //opp.Rating_Status__c = 'Underwriting-Released'
            opp.Primary_Closed_Reason__c ='Political';
            opp.Closed_Comments__c = 'XYZ';
            opp.Date_Closed__c = date.today().adddays(-1);
            opp.CloseDate = date.today().adddays(2);
            opp.Assigned_UW__c = UserInfo.getuserid();
            opp.Rating_Status__c = 'Actuarial-Released';
            insert opp;
            
            Beng_PDF_Preview_profiles__c custS = new Beng_PDF_Preview_profiles__c(SetupOwnerId=UserInfo.getProfileId());
            insert custS;
            system.debug('+++custS'+custS );
            SGR_Beng_XML_Response xmlResponse = new SGR_Beng_XML_Response();
            Test.loadData(Username_Password__c.sObjectType,'UserNamePasswordTestData');
            Test.loadData(OAuth_Jwt_Token2__c.sObjectType,'JwtOauth2TestData');
            Test.starttest();
                Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorSgr_bng()); 
                
                Sgr_Beng_PreviewPDF.getOppData(opp.id);
                Sgr_Beng_PreviewPDF.oppDetails(opp.id,'DRAFT' ,'Account',newAccount1.External_ID__c);
                SGR_Beng_XML_Input inp = new SGR_Beng_XML_Input();

            Test.stoptest();
    }
}