src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Carve_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if an account has carved out business to other vendors.  It is populated based on Carriers associated to the account.</description>
        <label>Carve Out?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>ComplexityScoreCompetitorRelationship__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Field used to hold the complexity score for Competitor Relationship components. Should remain hidden.</description>
        <label>ComplexityScoreCompetitorRelationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Sliced__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if an account has sliced business across multiple carriers.  It is populated based on Carriers associated to the account.</description>
        <label>Split?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>true</active>
        <description>Account record type that captures information about a competitor (carriers and vendors)</description>
        <label>Competitor</label>
    </recordTypes>

objects/Account.object
    <recordTypes>
        <fullName>Group_Account</fullName>
        <active>true</active>
        <description>Account record type for Group / Sold Accounts</description>
        <label>Group Account</label>
    </recordTypes>

objects/Competitor_Relationship__c.object
<CustomObject>
    <description>Competitors related to a Group Account as Carriers and to an Opportunity as Incumbent/ Won / Competing</description>
    <fields>
        <fullName>Carve_Out__c</fullName>
        <formula>IF( Number_of_Carve_Out_Products__c &gt;0, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Carve Out?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Group Account related to the Competitor Relationship for Carrier Information</description>
        <label>Group Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <errorMessage>Please select Prospect or Group or Prospect (Non BlueSTAR) or Group (Non BlueSTAR) account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Prospect_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Prospect_Non_BlueSTAR</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Account_Non_BlueSTAR</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Competitor_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sliced__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a carrier has sliced business with HCSC</description>
        <label>Split</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sliced_with__c</fullName>
        <description>Field to indicate if there are any sliced products for this carrier</description>
        <formula>IF(Number_of_Sliced_Products__c&gt;0,TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Split?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Competitor Relationship</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategic_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategic Plan</label>
        <referenceTo>Strategic_Plan__c</referenceTo>
        <relationshipName>Competitor_3rd_Party_Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitors / 3rd Party Vendors</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors / 3rd Party Vendors</pluralLabel>
    <recordTypes>
        <fullName>Carrier</fullName>
        <active>true</active>
        <description>Record type that captures the relationship between a Group Account and a Carrier</description>
        <label>Competitor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>false</active>
        <description>Competitor for a Sales Opportunity</description>
        <label>Competitors</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Strategic_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>associated account of strategic plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Plans</relationshipLabel>
        <relationshipName>Strategic_Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>is plan active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Strategic Plan</label>
    <nameField>
        <label>Strategic Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CompetitorRelationshipTriggerHandler.cls
/**************************************************************************************
  Apex Class Name     : CompetitorRelationshipTriggerHandler
  Version             : 1.0
  Function            : This is a handler Class for the CompetitorRelationshipTrigger 
  Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Nitin Paliwal           09/15/2015                Original Version
*************************************************************************************/
public with sharing class CompetitorRelationshipTriggerHandler{
    /*************************************************
     * Method name  : updateSlicedAccountDetails
     * Description  : Static method to update the sliced field of the Account while inserting/updating carrier relationship
     * Return Type  : Void
   *************************************************/
    public static void updateSlicedAccountDetails(list<Competitor_Relationship__c> newList, map<Id,Competitor_Relationship__c > oldMap,list<Competitor_Relationship__c > oldList){
        list<Account> updateAccounts = new list<Account>();
        set<String> accountIds = new set<String>();
        string carrierRecordTypeId;
        //query the record type of carrier 
        for(RecordType rt : [select Id from RecordType where SobjectType = 'Competitor_Relationship__c' and DeveloperName ='Carrier'])
        {
            carrierRecordTypeId = rt.Id;
        }
        //get the account records ids to be update
        if(newList != null){
            for(Competitor_Relationship__c cr : newList){
                if(cr.RecordTypeId == carrierRecordTypeId ){
                    if(oldMap != null && oldMap.containsKey(cr.Id) ){
                        accountIds.add(cr.Group_Account__c);
                        accountIds.add(oldMap.get(cr.Id).Group_Account__c);
                    }
                    else if(oldMap == null || !(oldMap.containsKey(cr.Id))){
                        accountIds.add(cr.Group_Account__c);
                    }
                }
            }
        }
        if(oldList != null){
            for(Competitor_Relationship__c cr : oldList){
                if(cr.RecordTypeId == carrierRecordTypeId && cr.Sliced__c == true && cr.Status__c == 'Active'){
                    accountIds.add(cr.Group_Account__c);
                }
            }
        }
        //query on the account records and in the inner query find out if there is any carrier which is active and sliced set as true
        for(Account acc : [select Sliced__c,Carve_Out__c,Id,(select Id,Sliced_with__c,Carve_Out__c from Competitor_Relationships1__r where (Sliced_with__c = true or Carve_Out__c = true) and Status__c = 'Active' and RecordtypeId =:carrierRecordTypeId) from account where Id In :accountIds]){
            boolean sliced = false;
            boolean carved = false;
            boolean ischanged = false;
            for(Competitor_Relationship__c cr : acc.Competitor_Relationships1__r){
                if(cr.Carve_Out__c)
                    carved = true;
                if(cr.Sliced_with__c)
                    sliced = true;
            }
            
            if(sliced && !acc.Sliced__c){
                acc.Sliced__c = true;
               ischanged = true;
            }
            else if(!sliced && acc.Sliced__c){
                acc.Sliced__c = false;
                ischanged = true;
            }
            
            if(carved && !acc.Carve_Out__c){
                acc.Carve_Out__c = true;
                 ischanged = true;
            }
            else if(!carved && acc.Carve_Out__c){
                acc.Carve_Out__c = false;
                ischanged = true;
            }
            if(ischanged)
                updateAccounts.add(acc);
        }
        //update the account records
        if(updateAccounts.size() >0)
            update updateAccounts;
    }

    /**
    * @author       Sana Fatima/Slalom
    * @description  Computes the Account Complexity Score for the Competitor Relationship object
    */
    public static void updateAccountComplexityScoreForCompetitorRelationship(List<Competitor_Relationship__c> competitorsToUpdate) {
        Id groupAccountRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get( Label.Group_Account ).getRecordTypeId();
        AccountDAO.IAccountDAO accountDAOInstance = new AccountDAO();

        Set<Id> parentAccountIds = new Set<Id>();
        Map<Id, Account> groupAccounts = new Map<Id, Account>();

        for ( Competitor_Relationship__c currCompetitor : competitorsToUpdate ) {
            if( currCompetitor.Group_Account__c != null)
                parentAccountIds.add(currCompetitor.Group_Account__c);
        }
        if( !parentAccountIds.isEmpty() ) {
            groupAccounts = new Map<Id, Account>( accountDAOInstance.getCompetitorRelationshipComplexityGroupAccounts(parentAccountIds, groupAccountRecordType) );
        }
        if( !groupAccounts.isEmpty() )
            calculateCompetitorComplexityScore(groupAccounts);
    }

    /**
    * @author       Sana Fatima/Slalom
    * @description  Computes the Account Complexity Score for the Competitor Relationship object
    */
    public static void calculateCompetitorComplexityScore(Map<Id, Account> groupAccounts) {
        try {
            List<Competitor_Relationship__c> childCompetitors = new List<Competitor_Relationship__c>();
            Map<Id, Integer> numCompetitorsByAccIds = new Map<Id, Integer>();
            List<Account> accountsToUpdate = new List<Account>();
            AccountDAO.IAccountDAO accountDAOInstance = new AccountDAO();
            CompetitorRelationshipDAO.ICompetitorRelationshipDAO competitorRelationshipDAOInstance = new CompetitorRelationshipDAO();
            Decimal oldValue;

            childCompetitors = competitorRelationshipDAOInstance.getActiveCompetitorRelationships( groupAccounts );
            for( Competitor_Relationship__c currCompetitor :childCompetitors ) {    
                if( !numCompetitorsByAccIds.containsKey(currCompetitor.Group_Account__c)) {
                    numCompetitorsByAccIds.put(currCompetitor.Group_Account__c, 1);
                } else {
                    numCompetitorsByAccIds.put(currCompetitor.Group_Account__c, numCompetitorsByAccIds.get(currCompetitor.Group_Account__c)+ 1 );
                }
            }
            for( Account currAccount: groupAccounts.values() ) {
                oldValue = currAccount.ComplexityScoreCompetitorRelationship__c;
                if (numCompetitorsByAccIds.containsKey(currAccount.Id) && numCompetitorsByAccIds.get(currAccount.Id) >= 1  && numCompetitorsByAccIds.get(currAccount.Id) <= 3) {
                    currAccount.ComplexityScoreCompetitorRelationship__c = 5; 
                } else if (numCompetitorsByAccIds.containsKey(currAccount.Id) && numCompetitorsByAccIds.get(currAccount.Id) >= 4 ) {
                    currAccount.ComplexityScoreCompetitorRelationship__c = 10; 
                } else if ( !numCompetitorsByAccIds.containsKey(currAccount.Id) ){
                    currAccount.ComplexityScoreCompetitorRelationship__c = 0;  
                }
                if( currAccount.ComplexityScoreCompetitorRelationship__c != oldValue) {
                    accountsToUpdate.add(currAccount);
                } 
            }
            if( !accountsToUpdate.isEmpty() ) {
                accountDAOInstance.updateAccounts( accountsToUpdate );
            }
        } catch (Exception ex) {
            CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'CompetitorRelationship', 'CompetitorRelationshipTrigger', 'CompetitorRelationshiprHandler.calculateCompetitorComplexityScore', 'High');
        }
    }
    
    /****************************************************************
* Method name  : strategicPlanUpdate
* Description  : Static method to update the Active Strategic Plan for associated Account on insert
* Return Type  : Void
//------Start of Jira # 4115 ---------------------------   
* *************************************************************/
    
    public void onInsertorUpdate(List<Competitor_Relationship__c> affectedCompetitorRecords){
        Id SPId ;
        Id CompAccountId;
        if(!affectedCompetitorRecords.isEmpty()){
            CompAccountId = affectedCompetitorRecords[0].Group_Account__c;
            SPId = getStrategicPlanIdForAccount(CompAccountId);            
        }//if
        System.debug('**SPID ' + SPID);
        for(Competitor_Relationship__c affectedCompRec :  affectedCompetitorRecords ){
            affectedCompRec.Strategic_Plan__c = SPId;
        }//for
    }//onUpdate 
    //-----------------------------------------------------------
    public Id getStrategicPlanIdForAccount(Id vAccountId){
        Id strategicPlanId;
        List<Strategic_Plan__c> StrategicPlanRecs =
            [SELECT Id FROM Strategic_Plan__c 
             where Account_Name__c =: vAccountId
             AND Active__c = true order by CreatedDate desc limit 1];
        System.debug('*** StrategicPlanRecs : '+StrategicPlanRecs);
        if(!StrategicPlanRecs.isEmpty()){strategicPlanId = StrategicPlanRecs[0].Id;}
        return strategicPlanId;
    }//getStrategicPlanIdForAccount
//------End of Jira # 4115 ---------------------------       
}