src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the unique identifier number of the contact in the source system (e.g., BlueStar, Siebel SFA)</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Identifier Number of the Contact in the Source System</inlineHelpText>
        <label>Contact Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Can_Approve_Strategic_Plans__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox determines whether or not this user has the ability to approve Strategic Plans.</description>
        <inlineHelpText>Check if the user is allowed to approve strategic plans.</inlineHelpText>
        <label>Can Approve Strategic Plans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Super_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the the user is a super user for the application</description>
        <inlineHelpText>Check if the the user is a super user for the application</inlineHelpText>
        <label>Super User</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestUserTriggerHandler.cls
/*
    @Description : This is an test class for UserTriggerHandler
    @author      : Deloitte
    @date        : 10/16/2015
	@updated	 : 6/6/2016
*/
@isTest
public with sharing class TestUserTriggerHandler {

	static testMethod void updateContactTest() {
		Account acc = TestClassUtiltity.CreateAccountRecord('test');
		RecordType rt = [select Id from RecordType where SobjectType = 'Contact' and DeveloperName = :ConstantsController.ContactRecordType][0];
		Contact con = new Contact();
		con.LastName = 'Test';
		con.AccountId = acc.Id;
		con.External_ID__c = '124';
		con.RecordTypeId = rt.Id;
		insert con;
		Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
		User testUser = TestClassUtiltity.CreateUserRecord(p.Id, 'testlgnadev@user.com', 'testUser', 'test@user.com');
		testUser = [select EmployeeNumber from User where Id = :testUser.Id][0];
		testUser.EmployeeNumber = '124';
		update testUser;
		List<PermissionSet> superUserPermissionSet = [SELECT Id, Name, PermissionsModifyAllData FROM PermissionSet WHERE Name = :System.Label.Super_User_Permissions LIMIT 1];
		System.assertEquals(superUserPermissionSet.size(), 1);
		testUser.EmployeeNumber = '125';
		update testUser;

		testUser.EmployeeNumber = '124';
		update testUser;
	}

	static testMethod void assignPermissionSetsOnInsertTest() {
		String superUserLabel = System.Label.Super_User_Permissions;
		String strategicPlanLabel = System.Label.PermissionSetCanApproveStrategicPlans;
		List<PermissionSet> permSets = [SELECT Id FROM PermissionSet WHERE Name = :superUserLabel OR Name = :strategicPlanLabel];

		Profile anyProfile = [SELECT Id FROM Profile LIMIT 1];
		User newUser = new User(Alias = 'test', Email = 'TestUsername@uniqueexample.com', EmailEncodingKey = 'UTF-8', LastName = 'Test Lastname', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = anyProfile.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = 'TestUsername@uniqueexample.com');
		newUser.Is_Super_User__c = true;
		newUser.Can_Approve_Strategic_Plans__c = true;
		insert newUser;
		List<PermissionSetAssignment> psAsg = [SELECT Id, PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = : newUser.Id];
		Map<Id, PermissionSetAssignment> psAsgMap = new Map<Id, PermissionSetAssignment>();
		for (PermissionSetAssignment psa : psAsg) {
			psAsgMap.put(psa.PermissionSetId, psa);
		}
		for (PermissionSet ps : permSets) {
			System.assert(psAsgMap.containsKey(ps.Id));
		}
	}

	static testMethod void assignPermissionSetsOnUpdateTest() {
		String superUserLabel = System.Label.Super_User_Permissions;
		String strategicPlanLabel = System.Label.PermissionSetCanApproveStrategicPlans;
		List<PermissionSet> permSets = [SELECT Id FROM PermissionSet WHERE Name = :superUserLabel OR Name = :strategicPlanLabel];

		Profile anyProfile = [SELECT Id FROM Profile LIMIT 1];
		User newUser = new User(Alias = 'test', Email = 'TestUsername@uniqueexample.com', EmailEncodingKey = 'UTF-8', LastName = 'Test Lastname', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = anyProfile.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = 'TestUsername@uniqueexample.com');
		newUser.Is_Super_User__c = false;
		newUser.Can_Approve_Strategic_Plans__c = false;
		insert newUser;

		List<PermissionSetAssignment> psAsgIns = [SELECT Id, PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = : newUser.Id];
		Map<Id, PermissionSetAssignment> psAsgMapIns = new Map<Id, PermissionSetAssignment>();
		for (PermissionSetAssignment psa : psAsgIns) {
			psAsgMapIns.put(psa.PermissionSetId, psa);
		}
		for (PermissionSet ps : permSets) {
			System.assert(!psAsgMapIns.containsKey(ps.Id));
		}

		newUser.Is_Super_User__c = true;
		newUser.Can_Approve_Strategic_Plans__c = true;
		update newUser;

		List<PermissionSetAssignment> psAsgUpd = [SELECT Id, PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = : newUser.Id];
		Map<Id, PermissionSetAssignment> psAsgMapUpd = new Map<Id, PermissionSetAssignment>();
		for (PermissionSetAssignment psa : psAsgUpd) {
			psAsgMapUpd.put(psa.PermissionSetId, psa);
		}
		for (PermissionSet ps : permSets) {
			System.assert(psAsgMapUpd.containsKey(ps.Id));
		}
	}

	static testMethod void unassignPermissionSetsOnUpdateTest() {
		String superUserLabel = System.Label.Super_User_Permissions;
		String strategicPlanLabel = System.Label.PermissionSetCanApproveStrategicPlans;
		List<PermissionSet> permSets = [SELECT Id FROM PermissionSet WHERE Name = :superUserLabel OR Name = :strategicPlanLabel];

		Profile anyProfile = [SELECT Id FROM Profile LIMIT 1];
		User newUser = new User(Alias = 'test', Email = 'TestUsername@uniqueexample.com', EmailEncodingKey = 'UTF-8', LastName = 'Test Lastname', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = anyProfile.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = 'TestUsername@uniqueexample.com');
		newUser.Is_Super_User__c = true;
		newUser.Can_Approve_Strategic_Plans__c = true;
		insert newUser;

		List<PermissionSetAssignment> psAsgIns = [SELECT Id, PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = : newUser.Id];
		Map<Id, PermissionSetAssignment> psAsgMapIns = new Map<Id, PermissionSetAssignment>();
		for (PermissionSetAssignment psa : psAsgIns) {
			psAsgMapIns.put(psa.PermissionSetId, psa);
		}
		for (PermissionSet ps : permSets) {
			System.assert(psAsgMapIns.containsKey(ps.Id));
		}

		newUser.Is_Super_User__c = false;
		newUser.Can_Approve_Strategic_Plans__c = false;
		update newUser;

		List<PermissionSetAssignment> psAsgUpd = [SELECT Id, PermissionSetId FROM PermissionSetAssignment WHERE AssigneeId = : newUser.Id];
		Map<Id, PermissionSetAssignment> psAsgMapUpd = new Map<Id, PermissionSetAssignment>();
		for (PermissionSetAssignment psa : psAsgUpd) {
			psAsgMapUpd.put(psa.PermissionSetId, psa);
		}
		for (PermissionSet ps : permSets) {
			System.assert(!psAsgMapUpd.containsKey(ps.Id));
		}
	}
}