src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Business need is to show the products that were renewed for the account last year.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Projected_Dental_Members__c</fullName>
        <description>This field is used to capture the total number of projected BCBS Enrolled Dental Members for a Prospect Account.</description>
        <label>Projected Dental Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Market_Segment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Segment Picklist values from Account</description>
    <label>Market Segment</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Comments__c</fullName>
        <description>This field is used to capture the detailed description on why an Opportunity is closed won, lost or declined.</description>
        <label>Closed Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>This field is used to capture the date when the opportunity is won or lost.</description>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Closed_Reason__c</fullName>
        <description>This field is used to capture the primary reason why an Opportunity is won, lost or declined.</description>
        <label>Primary Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absorbed by Parent Group</fullName>
                </value>
                <value>
                    <fullName>Change of Ownership</fullName>
                </value>
                <value>
                    <fullName>Consol. Covg with 1 Carrier</fullName>
                </value>
                <value>
                    <fullName>Headquarters Relocated</fullName>
                </value>
                <value>
                    <fullName>Lack of Narrow Network</fullName>
                </value>
                <value>
                    <fullName>Market Check by Group</fullName>
                </value>
                <value>
                    <fullName>Organizational Changes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Guarantees</fullName>
                </value>
                <value>
                    <fullName>Plan Design-Other</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Purchase by Another Company</fullName>
                </value>
                <value>
                    <fullName>Rates-Aggregate Stop Loss-Claim/Attch Factor</fullName>
                </value>
                <value>
                    <fullName>Rates-Incumbent Reduced</fullName>
                </value>
                <value>
                    <fullName>Rates-Individual Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Rates-Insured</fullName>
                </value>
                <value>
                    <fullName>Repricing</fullName>
                </value>
                <value>
                    <fullName>Reputation of Selected Carrier</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Broker Relationship</fullName>
                </value>
                <value>
                    <fullName>Changed Brokers</fullName>
                </value>
                <value>
                    <fullName>Network Discounts</fullName>
                </value>
                <value>
                    <fullName>Network Disruption</fullName>
                </value>
                <value>
                    <fullName>Product Packaging</fullName>
                </value>
                <value>
                    <fullName>Did Not Want to Disrupt Ees</fullName>
                </value>
                <value>
                    <fullName>Not Enough Diff. to Change</fullName>
                </value>
                <value>
                    <fullName>PUG Did not meet participation</fullName>
                </value>
                <value>
                    <fullName>Rates-Admin. Charge too High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/REST_UCRKafkaUpdate_Test.cls
@istest
public class REST_UCRKafkaUpdate_Test{
    
    @isTest
    public static void testHttpPost() {
        
        List<Account> lstAcc = new List<Account>();
        Account a= new Account();
        a.name='Test';
        a.HCSC_Division__c='IL';
        a.Market_Segment__c='LG';
        a.Funding_Type__c='ACAP';
        a.Renewal_Date__c=date.today();
        a.Projected_Dental_Members__c = 23456;
        insert a;
        
        List<opportunity> oplist = new List<opportunity>();
        opportunity opp = new opportunity();
        opp.AccountId = a.id;
        opp.Name = 'Sample';
        opp.StageName = 'lost';
        opp.Product_Type__c='H';
        opp.Primary_Closed_Reason__c ='Political';
        opp.Closed_Comments__c = 'XYZ';
        opp.Date_Closed__c = date.today().adddays(-1);
        opp.CloseDate = date.today().adddays(2);
        oplist.add(opp);
        
        opportunity opp1 = new opportunity();
        opp1.AccountId = a.id;
        opp1.Name = 'Sample';
        opp1.StageName = 'lost';
        opp1.Product_Type__c='H';
        opp1.Primary_Closed_Reason__c ='Political';
        opp1.Closed_Comments__c = 'XYZ';
        opp1.Date_Closed__c = date.today().adddays(-1);
        opp1.CloseDate = date.today().adddays(2);
        oplist.add(opp1);
        insert oplist;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/UCRKafkaUpdate'; //Request URL
        req.httpMethod = 'POST';
        
        RestContext.request = req;
        RestContext.response= res;
        
        //String AccountNumber = '987456321';
        String AccountNumber = 'AD1234';
        String OpportunityId = 'Opp1234';
        String CorrespondanceId = 'Co12344';
        String failMessage = 'Request process failed';
        String FailureStatus = 'FAILURE';
        
        Test.startTest();
        List<account> acclist = new List<account>();
        String ide = oplist[0].id;
        String opportunityId1 = '0064D000004HnsiQAC';
        REST_UCRKafkaUpdate.updateOpportuniy(AccountNumber,ide,CorrespondanceId);
        acclist = REST_UCRKafkaUpdate.getAccounts(AccountNumber);
        oplist = REST_UCRKafkaUpdate.getOpportunities(opportunityId1);
        // REST_UCRKafkaUpdate.updateOpportuniy(AccountNumber,ide,CorrespondanceId);
        
        REST_UCRKafkaUpdate.UCRKafkaSFResponse response = new REST_UCRKafkaUpdate.UCRKafkaSFResponse();
        response.Message = failMessage;
        response.Status = FailureStatus;
        Test.stopTest();
    }
    
}