src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Account_Cluster_Effective_Date__c</fullName>
        <description>This field is used to capture the first date that the cluster for this account is effective as listed in BlueStar</description>
        <label>Account Cluster Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Account_Cluster_Number__c</fullName>
        <description>This field is used to capture the number assigned to the sales and account executives as listed in BlueStar</description>
        <label>Account Cluster Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Account_Cluster_User_Identification__c</fullName>
        <description>This field is used to capture the Identification number of the Account Cluster Marketing Representative as listed in BlueStar</description>
        <label>Account Cluster User Identification</label>
        <length>100</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Billing_County__c</fullName>
        <description>This field is used to capture the Billing County for an Account.</description>
        <label>Billing County</label>
        <length>50</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Ceded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if an account is ceded from another plan.</description>
        <label>Ceded?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Ceded_From_ICL__c</fullName>
        <description>This field is used to capture the plan that an account is ceded from (Initial Control Licensee)</description>
        <label>Ceded From (ICL)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Premera AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>Anthem CA</fullName>
                </value>
                <value>
                    <fullName>Anthem CO</fullName>
                </value>
                <value>
                    <fullName>Anthem CT</fullName>
                </value>
                <value>
                    <fullName>Anthem GA</fullName>
                </value>
                <value>
                    <fullName>Anthem IN</fullName>
                </value>
                <value>
                    <fullName>Anthem KY</fullName>
                </value>
                <value>
                    <fullName>Anthem ME</fullName>
                </value>
                <value>
                    <fullName>Anthem MO</fullName>
                </value>
                <value>
                    <fullName>Anthem NH</fullName>
                </value>
                <value>
                    <fullName>Anthem NV</fullName>
                </value>
                <value>
                    <fullName>Anthem NY</fullName>
                </value>
                <value>
                    <fullName>Anthem OH</fullName>
                </value>
                <value>
                    <fullName>Anthem VA</fullName>
                </value>
                <value>
                    <fullName>Anthem WI</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA BS</fullName>
                </value>
                <value>
                    <fullName>Capital PA</fullName>
                </value>
                <value>
                    <fullName>Carefirst DC</fullName>
                </value>
                <value>
                    <fullName>Carefirst MD</fullName>
                </value>
                <value>
                    <fullName>Carefirst VA</fullName>
                </value>
                <value>
                    <fullName>Highmark DE</fullName>
                </value>
                <value>
                    <fullName>Excellus NY</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>HCSC</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>Highmark PA</fullName>
                </value>
                <value>
                    <fullName>IBC PA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Ceded_To_ACL__c</fullName>
        <description>This field is used to capture the plan that an account is ceded to (Alternative Control Licensee)</description>
        <inlineHelpText>Plan that an account is ceded to (Alternative Control Licensee)</inlineHelpText>
        <label>Ceded To (ACL)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Premera AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>Anthem CA</fullName>
                </value>
                <value>
                    <fullName>Anthem CO</fullName>
                </value>
                <value>
                    <fullName>Anthem CT</fullName>
                </value>
                <value>
                    <fullName>Anthem GA</fullName>
                </value>
                <value>
                    <fullName>Anthem IN</fullName>
                </value>
                <value>
                    <fullName>Anthem KY</fullName>
                </value>
                <value>
                    <fullName>Anthem ME</fullName>
                </value>
                <value>
                    <fullName>Anthem MO</fullName>
                </value>
                <value>
                    <fullName>Anthem NH</fullName>
                </value>
                <value>
                    <fullName>Anthem NV</fullName>
                </value>
                <value>
                    <fullName>Anthem NY</fullName>
                </value>
                <value>
                    <fullName>Anthem OH</fullName>
                </value>
                <value>
                    <fullName>Anthem VA</fullName>
                </value>
                <value>
                    <fullName>Anthem WI</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA BS</fullName>
                </value>
                <value>
                    <fullName>Capital PA</fullName>
                </value>
                <value>
                    <fullName>Carefirst DC</fullName>
                </value>
                <value>
                    <fullName>Carefirst MD</fullName>
                </value>
                <value>
                    <fullName>Carefirst VA</fullName>
                </value>
                <value>
                    <fullName>Highmark DE</fullName>
                </value>
                <value>
                    <fullName>Excellus NY</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>HCSC</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>Highmark PA</fullName>
                </value>
                <value>
                    <fullName>IBC PA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>COBRA_Administration_Type__c</fullName>
        <description>This field is used to capture the COBRA Administration type as listed in BlueStar; GRP = Group Administers; HCSC = COBRA Admin Marion; OTHR = Non HCSC Vendor administers; N/A.</description>
        <label>COBRA Administration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GRP</fullName>
                </value>
                <value>
                    <fullName>HCSC</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>OTHR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Contract_End__c</fullName>
        <description>This field is used to capture the end date of the Group Account&apos;s contract.</description>
        <label>Contract End</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Contract_Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This contact must be related to this Account. The contact will be the designated signer for contracts sent out by contract administration</inlineHelpText>
        <label>Contract Recipient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Group Contact</value>
            </filterItems>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Critical_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator for high-profile accounts (current groups or prospects) that are large in size or have some material impact on the plan</description>
        <label>Critical Account?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Grandfathered_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if an account is grandfathered.</description>
        <label>Grandfathered Account?</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Grandfathered_Date__c</fullName>
        <description>This field is used to capture when an account is grandfathered.</description>
        <label>Grandfathered Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Group_Anniversary_Date__c</fullName>
        <description>This field is used to capture the Date in which the Group Account&apos;s contracts renew (mm/dd)</description>
        <label>Anniversary Date</label>
        <length>5</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_as_Fiduciary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if HCSC has fiduciary responsibility.</description>
        <label>HCSC as Fiduciary</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Key_Locations__c</fullName>
        <description>This field is used to capture primary member locations for a Prospect or Group Account.</description>
        <label>Key Locations</label>
        <type>TextArea</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Open_Enrollment_Date__c</fullName>
        <description>The date Open Enrollment begins for a Group Account&apos;s members</description>
        <label>Open Enrollment Start Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Open_Enrollment_End_Date__c</fullName>
        <description>The date Open Enrollment ends for a Group Account&apos;s members</description>
        <label>Open Enrollment End Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Premium_Type__c</fullName>
        <description>This field is used to capture the type of premium when funding type of PREM is selected (e.g., Prospective Premium, Retrospective Premium)</description>
        <label>Premium Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PP</fullName>
                </value>
                <value>
                    <fullName>RP</fullName>
                </value>
                <value>
                    <fullName>RC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Sales_Team__c</fullName>
        <description>The Sales Executive assigned to the Account as listed in BlueStar</description>
        <inlineHelpText>This field is pulling the Sales Executive name from BlueStar, listed as Sales Team in BlueStar</inlineHelpText>
        <label>Sales Executive</label>
        <type>TextArea</type>
    </fields>

classes/LGNA_OperationTabDataEdit.cls
//************************************************************************//
// Purpose:
// 	Apex Class for use with Lightning Component LGNA_OperationTabDataEdit
// History:
//   Date               Developer                  Description
//                  Rakesh 	      SFDC-8545 - Initial Version - 2018-04 
//                  Rakesh        SFDC-9901 - Modified By Rakesh Nunna
// 06/19/2018	    Mei           SFDC-9901 - Add Method hasModifyAllPermission to check if current user has ModifyAll permission
//************************************************************************//

public class LGNA_OperationTabDataEdit {
    
    public class A { 
        String str;        
        public A(String s) { str = s; }
    }
    
    
    @AuraEnabled
    public static Boolean hasModifyAllPermission(){
    	
    Id userId=UserInfo.getUserId();
    list<PermissionSetAssignment> perm=[SELECT AssigneeId, id FROM PermissionSetAssignment WHERE PermissionSet.PermissionsModifyAllData = true and AssigneeId=:userId limit 1];
    system.debug('permission result::'+perm);
     if( perm!=null && !perm.isEmpty()){
     	return true;
     }
     return false;
    }
    @AuraEnabled
    public static String getselectOptions(sObject objObject, string fld) {
        
        //Used to return Picklist Values for Specified sObject/Fields for use 
        // 	in Lightning Components
        
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);        
        
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();       
        
        
        //create the JSON to Return from the Method
        JSONGenerator gen = JSON.createGenerator(true);
        
        // Create an object to write to the JSON string.
        A x = new A('X');       
        
        gen.writeStartArray();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {            
            gen.writeStartObject();            
            gen.writeStringField('label', a.getLabel());
            gen.writeStringField('value', a.getValue());
            gen.writeEndObject();            
        }
        
        gen.writeEndArray();
        
        // Get the JSON string.
        String resultJSON = gen.getAsString();
        System.debug('JSON : ' + resultJSON);
        
        return resultJSON;        
    }    
    @AuraEnabled
    public static Map<String,boolean> getFieldAccess() {
        
        
        Map<String,boolean> fieldAccessMap = new Map<String,boolean>();
        String [] accountAccessFields = new String [] {'Id',
                              'Name',
                              'Effective_Date__c',
                              'Group_Anniversary_Date__c',
                              'Contract_End__c',
                              'Contract_Signer__c',                             
                              'Open_Enrollment_End_Date__c',
                              'Open_Enrollment_Date__c',
                              'Renewal_Date__c',
                              'Ceded_From_ICL__c',
                              'Ceded_To_ACL__c',
                              'Ceded__c',
                              'HCSC_as_Fiduciary__c',
 	                          'Critical_Account__c',
                              'Funding_Type__c',
                              'Grandfathered_Account__c',
                              'Grandfathered_Date__c',
                              'Premium_Type__c',
                              'COBRA_Administration_Type__c',
                              'BillingStreet',
                              'BillingCity',
                              'BillingState',
                              'BillingPostalCode',
                              'BillingCountry',	
                              'Billing_County__c',						                              
                              'ShippingStreet',
                              'ShippingCity',
                              'ShippingState',
                              'ShippingPostalCode',
                              'ShippingCountry',                              
                              'Key_Locations__c',
                              'Sales_Team__c',
                              'Account_Cluster_Effective_Date__c',
		                      'Account_Cluster_Number__c',
                              'Account_Cluster_User_Identification__c',
                              'Account_Cluster_Name__c',
                              'Account_Executive_2__c',
                              'Sales_Cluster_Number__c',
                              'Underwriter_Effective_Date__c',
                              'Underwriter_End_Date__c',
                              'Underwriter__c',
                              'Underwriter_Name__c',
                              'Underwriter_Team_Code__c',
                              'Underwriter_User_ID__c',
                              'Cancellation_Code__c',
                              'Cancellation_Date__c',
                              'Cancellation_Explanation__c',
                              'Cancellation_Reason__c',
                              'Cancellation_Submitted_Date__c',
                              'Cancelled_Health_Contracts__c',
                              'Cancelled_Health_Members__c',
                              'Claim_Stop_Date__c',
                              'Integration_Status__c',
                              'Requested_Cancellation_Date__c'                                                     
            };
                
                
                // Obtain the field name/token map for the Expense object
                Map<String,Schema.SObjectField> m = Schema.SObjectType.Account.fields.getMap();
        System.debug('=m='+m);
        
        for (String fieldToCheck : accountAccessFields) {
        	Boolean hasEdit=m.get(fieldToCheck).getDescribe().isUpdateable();
            system.debug('field to Check:::'+fieldToCheck+ 'is Updateable??'+hasEdit);
            
            fieldAccessMap.put(fieldToCheck,m.get(fieldToCheck).getDescribe().isUpdateable());
            
        }
        System.debug('=fieldAccessMap='+fieldAccessMap);
        return fieldAccessMap;
    }
    
}