src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Line_of_business__c</fullName>
        <label>Line of business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ENA,</fullName>
                    <label>ENA</label>
                </value>
                <value>
                    <fullName>Major National</fullName>
                </value>
                <value>
                    <fullName>Major National GET</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Municipal</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>Student Health</fullName>
                </value>
                <value>
                    <fullName>ENA GET</fullName>
                </value>
                <value>
                    <fullName>Large/Mid Market</fullName>
                </value>
                <value>
                    <fullName>Municipal GET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Rate_Type_Code__c</fullName>
        <label>Rate Type Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>AGE</fullName>
                </value>
                <value>
                    <fullName>STN</fullName>
                </value>
                <value>
                    <fullName>UNK</fullName>
                </value>
                <value>
                    <fullName>URE</fullName>
                </value>
                <value>
                    <fullName>MIX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To retrieve days to submit for each division for calcuating Submit_Date__c on opportunity</description>
    <label>SGR Days to Submit</label>
</CustomObject>

objects/Plan__c.object
<CustomObject>
    <description>To capture all the plans related to products - Loaded from BlueStar</description>
    <fields>
        <fullName>Line_Of_Business__c</fullName>
        <label>Line Of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>HDL</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Benefit_Agreement__c.object
<CustomObject>
    <description>This object is connected to Opportunity object using a look up field (Opportunity).</description>
    <fields>
        <fullName>Include_BA__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include BA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Product Line of Business(H,D,V)</description>
        <formula>TEXT( Plan1__r.Line_Of_Business__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Benefit Agreements</relationshipLabel>
        <relationshipName>Opportunity_Benefit_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Benefit Agreement</label>
    <nameField>
        <label>Opportunity Benefit Agreement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Benefit Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Plan_Rate__c.object
<CustomObject>
    <description>This object contains details about opportunity plan Rates.</description>
    <fields>
        <fullName>Coverage_Type__c</fullName>
        <label>Coverage Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>HDL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Age_Total_Est_Tax_and_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Age Total Est Tax and Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Age_Total_Monthly_Premium__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Age Total Monthly Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Comp_Total_Est_Tax_and_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Comp Total Est Tax and Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Comp_Total_Monthly_Premium__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Current Comp Total Monthly Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Enrolled_Member_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Enrolled Member Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Enrolled_Subscriber_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Enrolled Subscriber Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Benefit_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Benefit Agreement</label>
        <referenceTo>SGR_Opportunity_Benefit_Agreement__c</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <label>Plan Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type_Code__c</fullName>
        <description>STN or AGE for standard rate and age rate</description>
        <label>Rate Type Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renw_Age_Total_Est_Tax_and_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renw Age Total Est Tax and Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Renw_Age_Total_Monthly_Premium__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renw Age Total Monthly Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Renw_Comp_Total_Est_Tax_and_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renw Comp Total Est Tax and Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Renw_Comp_Total_Monthly_Premium__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renw Comp Total Monthly Premium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Alternate</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                    <isActive>false</isActive>
                    <label>Alternative</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Plan Rate</label>
    <nameField>
        <label>Opportunity Plan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SGR_OppPlanRateSummary_Controller_test.cls
@isTest 
private class SGR_OppPlanRateSummary_Controller_test {
    
    @testSetup static void setup() {   
        
        Account anAccount1 = Sgr_TestDataUtility.createAcc('TestAccount1');
        Account anAccount2 = Sgr_TestDataUtility.createAcc('TestAccount2');
        
        Opportunity anOpportunity = Sgr_TestDataUtility.createOpty2(String.valueOf(anAccount1.Id),'Initiated');
        Opportunity anOppWithoutRates = Sgr_TestDataUtility.createOpty2(String.valueOf(anAccount2.Id),'Initiated');
        
        SGR_Opportunity_Benefit_Agreement__c anOppBeneAgreement = Sgr_TestDataUtility.createOptyBenAgr(anOpportunity.Id);
        anOppBeneAgreement.Include_BA__c = true;
        insert anOppBeneAgreement;        
        
        List<Plan__c> listPlans = new List<Plan__c>();
        
        for (Integer i = 0 ; i < 5; i++) {
            Plan__c aPlan = new Plan__c();
            aPlan.Name = 'Test Health Plan' + String.valueOf(i);
            aPlan.Line_Of_Business__c = 'H';        
            listPlans.add(aPlan);        
        }        
        
        for (Integer i = 0 ; i < 5; i++) {
            Plan__c aPlan = new Plan__c();
            aPlan.Name = 'Test Vision Plan' + String.valueOf(i);
            aPlan.Line_Of_Business__c = 'V';        
            listPlans.add(aPlan);        
        }        
        
        for (Integer i = 0 ; i < 5; i++) {
            Plan__c aPlan = new Plan__c();
            aPlan.Name = 'Test Dental Plan' + String.valueOf(i);
            aPlan.Line_Of_Business__c = 'D';        
            listPlans.add(aPlan);        
        }       
        
        insert listPlans;   
        
        List<Plan__c> listHealthPlans = new List<Plan__c>();
        List<Plan__c> listVisionPlans = new List<Plan__c>();
        List<Plan__c> listDentalPlans = new List<Plan__c>();
        
        listHealthPlans = [SELECT Id, Name, Line_Of_Business__c FROM Plan__c WHERE Line_Of_Business__c = 'H']; 
        System.debug('listHealthPlans: ' + listHealthPlans.size());
        listVisionPlans = [SELECT Id, Name, Line_Of_Business__c FROM Plan__c WHERE Line_Of_Business__c = 'V']; 
        System.debug('listVisionPlans: ' + listVisionPlans.size());
        listDentalPlans = [SELECT Id, Name, Line_Of_Business__c FROM Plan__c WHERE Line_Of_Business__c = 'D']; 
        System.debug('listDentalPlans: ' + listDentalPlans.size());
                
        List<SGR_Opportunity_Plan_Rate__c> listOpportunityPlanRates = new List<SGR_Opportunity_Plan_Rate__c>();
        
        for (Integer i = 0 ; i < 5; i++) {
            SGR_Opportunity_Plan_Rate__c aRate = new SGR_Opportunity_Plan_Rate__c();
            aRate.Name = 'TestHealthRate' + String.valueOf(i);
            aRate.Plan_Name__c = 'Health' + String.valueOf(i);  //Health1, Health2, etc.
            aRate.Type__c = 'Renewal';
            aRate.Opportunity__c = anOpportunity.Id;
            //aRate.Coverage_Type__c = 'H';
            if(i == 1){
                aRate.Rate_Type_Code__c = 'STN';                
            }else{
                aRate.Rate_Type_Code__c = 'AGE';                
            }            
            aRate.Opportunity_Benefit_Agreement__c = anOppBeneAgreement.Id;
            aRate.Enrolled_Subscriber_Count__c = 1;
            aRate.Enrolled_Member_Count__c = 2;
            aRate.Current_Comp_Total_Monthly_Premium__c = 1.00;
            aRate.Renw_Comp_Total_Monthly_Premium__c = 2.00;
            aRate.Current_Comp_Total_Est_Tax_and_Fees__c = 3.00;
            aRate.Renw_Comp_Total_Est_Tax_and_Fees__c = 4.00;
            aRate.Current_Age_Total_Monthly_Premium__c = 5.00;
            aRate.Renw_Age_Total_Monthly_Premium__c = 6.00;
            aRate.Current_Age_Total_Est_Tax_and_Fees__c = 7.00;
            aRate.Renw_Age_Total_Est_Tax_and_Fees__c = 8.00;
            if(listHealthPlans.size() == 5){
                aRate.Plan__c = listHealthPlans[i].Id;                
            }            
            listOpportunityPlanRates.add(aRate);            
        }       
        
        for (Integer i = 0 ; i < 5; i++) {
            SGR_Opportunity_Plan_Rate__c aRate = new SGR_Opportunity_Plan_Rate__c();
            aRate.Name = 'TestDentalRate' + String.valueOf(i);
            aRate.Plan_Name__c = 'Dental' + String.valueOf(i); //Dental1, Dental2, etc.
            aRate.Type__c = 'Renewal';
            aRate.Opportunity__c = anOpportunity.Id;
            //aRate.Coverage_Type__c = 'D';
            aRate.Rate_Type_Code__c = 'AGE';    
            aRate.Opportunity_Benefit_Agreement__c = anOppBeneAgreement.Id;
            aRate.Enrolled_Subscriber_Count__c = 1;
            aRate.Enrolled_Member_Count__c = 2;
            aRate.Current_Comp_Total_Monthly_Premium__c = 1.00;
            aRate.Renw_Comp_Total_Monthly_Premium__c = 2.00;
            aRate.Current_Comp_Total_Est_Tax_and_Fees__c = 3.00;
            aRate.Renw_Comp_Total_Est_Tax_and_Fees__c = 4.00;
            aRate.Current_Age_Total_Monthly_Premium__c = 5.00;
            aRate.Renw_Age_Total_Monthly_Premium__c = 6.00;
            aRate.Current_Age_Total_Est_Tax_and_Fees__c = 7.00;
            aRate.Renw_Age_Total_Est_Tax_and_Fees__c = 8.00;
            if(listDentalPlans.size() == 5){
                aRate.Plan__c = listDentalPlans[i].Id;                
            }            
            listOpportunityPlanRates.add(aRate);            
        }       
        
        for (Integer i = 0 ; i < 5; i++) {
            SGR_Opportunity_Plan_Rate__c aRate = new SGR_Opportunity_Plan_Rate__c();
            aRate.Name = 'TestVisionRate' + String.valueOf(i);
            aRate.Plan_Name__c = 'Vision' + String.valueOf(i); //Vision1, Vision2, etc.
            aRate.Type__c = 'Renewal';
            aRate.Opportunity__c = anOpportunity.Id;
           // aRate.Coverage_Type__c = 'V';
            aRate.Rate_Type_Code__c = 'AGE';
            aRate.Opportunity_Benefit_Agreement__c = anOppBeneAgreement.Id;
            aRate.Enrolled_Subscriber_Count__c = 1;
            aRate.Enrolled_Member_Count__c = 2;
            aRate.Current_Comp_Total_Monthly_Premium__c = 1.00;
            aRate.Renw_Comp_Total_Monthly_Premium__c = 2.00;
            aRate.Current_Comp_Total_Est_Tax_and_Fees__c = 3.00;
            aRate.Renw_Comp_Total_Est_Tax_and_Fees__c = 4.00;
            aRate.Current_Age_Total_Monthly_Premium__c = 5.00;
            aRate.Renw_Age_Total_Monthly_Premium__c = 6.00;
            aRate.Current_Age_Total_Est_Tax_and_Fees__c = 7.00;
            aRate.Renw_Age_Total_Est_Tax_and_Fees__c = 8.00;
            if(listVisionPlans.size() == 5){
                aRate.Plan__c = listVisionPlans[i].Id;                
            }
            listOpportunityPlanRates.add(aRate);            
        }       
        
        insert listOpportunityPlanRates;
        
    }
    
    static testMethod void testFetchRates(){
        
        system.debug('SGR_OppPlanRateSummary_Controller_test.testFetchRates()');

        Opportunity anOpportunity = [SELECT 
                                     Id,
                                     Name
                                     FROM Opportunity
                                     WHERE Account.Name = 'TestAccount1'
                                     LIMIT 1];
         
        List <SGR_Opportunity_Plan_Rate__c > listOpportunityPlanRates = new List<SGR_Opportunity_Plan_Rate__c >();
        
        SGR_OppPlanRateSummary_Controller.wrapperOppPlanRateSummary aWrapper = new SGR_OppPlanRateSummary_Controller.wrapperOppPlanRateSummary(); 

        //cover Health logic
        aWrapper = SGR_OppPlanRateSummary_Controller.fetchRates(anOpportunity.Id, 'Health');
        system.debug('Health: ' + aWrapper);
        
        //cover Dental logic
        aWrapper = SGR_OppPlanRateSummary_Controller.fetchRates(anOpportunity.Id, 'Dental');
        system.debug('Dental: ' + aWrapper);
        
        //cover Vision logic
        aWrapper = SGR_OppPlanRateSummary_Controller.fetchRates(anOpportunity.Id, 'Vision');
        system.debug('Vision: ' + aWrapper);
        
        anOpportunity = [SELECT 
                         Id,
                         Name
                         FROM Opportunity
                         WHERE Account.Name = 'TestAccount2'
                         LIMIT 1];
        
        //cover Health logic where no related record exists
        aWrapper = SGR_OppPlanRateSummary_Controller.fetchRates(anOpportunity.Id, 'Health');
        system.debug('Health no related record: ' + aWrapper);
        
    }
    
}