src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <recordTypes>
        <fullName>Group_Account</fullName>
        <active>true</active>
        <description>Account record type for Group / Sold Accounts</description>
        <label>Group Account</label>
    </recordTypes>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
    <fields>
        <fullName>Associated_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the user name if an Internal Contact is also a system user.</description>
        <inlineHelpText>Internal Contacts to User mapping</inlineHelpText>
        <label>Associated User</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>

objects/Contact.object
    <fields>
        <fullName>Type__c</fullName>
        <description>This field is used to capture the type of Group, Producer, or Consultant Contact.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Producer - GA</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Mailing</fullName>
                </value>
                <value>
                    <fullName>BAE</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
                <value>
                    <fullName>Privacy Officer</fullName>
                </value>
                <value>
                    <fullName>Union</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Contact.object
    <recordTypes>
        <fullName>Group_Contact</fullName>
        <active>true</active>
        <description>Contact record type that captures information about a person who works for a Group Account / Group Prospect Account</description>
        <label>Group Contact</label>
    </recordTypes>

classes/ContactDAOTest.cls
/**************************************************************************************
  Apex Class Name     : ContactDAOTest
  Version             : 1.0
  Function            : This is a test class for ContactDAO.
  Modification Log    :
* Developer					Date
* ----------------------------------------------------------------------------
* Alec Klein				6/8/2016
*************************************************************************************/
@isTest(SeeAllData = false)
public class ContactDAOTest {
	@isTest static void getContactsWithAssociatedUsersTest() {
		Set<String> associatedUsers = new Set<String>();
		Map<String, User> employeeUsers = new Map<String, User>();
		RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Contact' LIMIT 1];
		Profile p = [SELECT Id FROM Profile LIMIT 1];
		User u = new User(Alias = 'test', Email = 'uniqueUsername@testemail.com', EmailEncodingKey = 'UTF-8', LastName = 'Last Name', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = 'uniqueUsername@testemail.com');
		u.EmployeeNumber = 'TestEmployeeNumber';
		insert u;
		associatedUsers.add(u.Id);

		Account a = TestClassUtiltity.CreateAccountRecord('Test Account');
		Contact newContact = new Contact(AccountId = a.Id, Fax = '1234567', Phone = '(000) 000-0000-000', FirstName = 'FirstName', LastName = 'LastName');
		newContact.Associated_User__c = u.Id;
		newContact.RecordTypeId = rt.Id;
		insert newContact;

		ContactDAO.IContactDAO contactDAOInstance = new ContactDAO();
		List<Contact> associatedContacts = contactDAOInstance.getContactsWithAssociatedUsers(associatedUsers, employeeUsers, rt.Id);
		System.assert(associatedContacts.size() > 0);
	}

	@isTest static void updateContactsTest() {
		Account a = TestClassUtiltity.CreateAccountRecord('Test Account');
		Contact newContact = new Contact(AccountId = a.Id, Phone = '(000) 000-0000-000', Fax = '1234567', FirstName = 'FirstName', LastName = 'LastName');
		insert newContact;
		Contact updateContact = [SELECT Id, Firstname FROM Contact WHERE Id = : newContact.Id];
		updateContact.Firstname = 'Updated';
		ContactDAO.IContactDAO contactDAOInstance = new ContactDAO();
		contactDAOInstance.updateContacts(new List<Contact> {updateContact});
		Contact finalContact = [SELECT Id, Firstname FROM Contact WHERE Id = : newContact.Id];
		System.assertEquals(finalContact.Firstname, 'Updated');
	}

	@isTest
	static void contactDAOComplexityScoreTest() {
		Test.startTest();

		Id groupContactRecordType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get( Label.Group_Contact ).getRecordTypeId();
		Id groupAccRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get( Label.Group_Account ).getRecordTypeId();
		ContactDAO.IContactDAO contactDAOInstance = new ContactDAO();

		Account testAcnt = TestClassUtiltity.createAccountWithRecType('TestAccount', groupAccRecId);
		Map<Id, Account> accountMap = new Map<Id, Account>();
        accountMap.put(testAcnt.id, testAcnt);

		Contact testContact = new Contact(accountId = testAcnt.id, Phone = '(000) 000-0000-000', LastName = 'Smith', Type__c = 'Primary' );
		insert testContact;

		List<Contact> primaryContacts = contactDAOInstance.getPrimaryGroupContacts( accountMap, groupContactRecordType );
		System.assert(!primaryContacts.isEmpty());

		Test.stopTest();
	}
	@isTest
	static void getContactsByIDTest() {
		List<Id> ids = new List<Id>();

		Account a = TestClassUtiltity.CreateAccountRecord('Test Account');
		Contact newContact = new Contact(AccountId = a.Id, Fax = '1234567', FirstName = 'FirstName', LastName = 'LastName');
		
		insert newContact;

		ids.add(newContact.Id);

		ContactDAO.IContactDAO contactDAOInstance = new ContactDAO();
		List<Contact> contacts = contactDAOInstance.getContactsById(ids);

		System.assertEquals(contacts[0].id,newContact.Id);

	}
}