src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Strategic_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>associated account of strategic plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Plans</relationshipLabel>
        <relationshipName>Strategic_Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>is plan active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>For existing Accounts, select the upcoming Renewal Date.
For new Accounts, select the Effective Date.</inlineHelpText>
        <label>Renewal Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Strategic_Plan_Name_URL__c</fullName>
        <formula>HYPERLINK(&quot;/apex/NewStrategicPlanLayout?id=&quot;&amp;Id , Name ,&apos;_self&apos;)</formula>
        <label>Strategic Plan Link (Consolidated View)</label>
        <type>Text</type>
    </fields>
    <label>Strategic Plan</label>
    <nameField>
        <label>Strategic Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LGNA_AccountComponentCntlr.cls
/**************************************************************************************
  Apex Class Name     : LGNA_AccountComponentCntlr 
  Version             : 1.0
  Function            : This is for Strategic Plan Details
  Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------
*  Sujatha Gondi       08/30/2017                Original Version
*************************************************************************************/


public class LGNA_AccountComponentCntlr {
  public static String selectStr= 'Select';
  public static String exceptionStr= 'An exception occurred: ';
   
  /*************************************************************************************************************************************
    *  getsplanDetails
    *   @description:  Method is used to Update the Account Record
    *   @parameters : Account Id
    *   @return type : List<Strategic_Plan__c> 
    *******************************************************************************************************************************************/ 
    @AuraEnabled
    public static List<Strategic_Plan__c> getsplanDetails(Id accountId){
        List<Strategic_Plan__c> strategicPlanList = new List<Strategic_Plan__c>();
     
        try{
             system.debug('**** accountId--> ' + accountId);
             strategicPlanList = [SELECT Id,name,Strategic_Plan_Name_URL__c,Account_Name__c ,Account_name__r.name, 
                                  Account_Name__r.recordType.name,recordType.name, lastModifiedBy.name, lastModifiedDate, 
                                  CreatedBy.name, CreatedDate, Active__c, Effective_Date__c FROM Strategic_Plan__c
                                  WHERE Account_Name__c =:accountId and Active__c=true ORDER BY Effective_Date__c ASC Limit 1];
            
                     system.debug('* strategicPlanList--> ' + strategicPlanList.size());  
        return strategicPlanList;
        }catch(Exception e){
            system.debug('*** Exception ex --> ' + e);
        }
        return null;
    }
}