src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Hold_End_Date__c</fullName>
        <label>Hold End Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>SGR_Hold_Reason__c</fullName>
        <label>Hold Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Wage &amp; Tax Audit</fullName>
                </value>
                <value>
                    <fullName>1st Year Renewal</fullName>
                </value>
                <value>
                    <fullName>Block Acquisition</fullName>
                </value>
                <value>
                    <fullName>Special Adjustments</fullName>
                </value>
                <value>
                    <fullName>Market Segment Verification</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Market_Segment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Segment Picklist values from Account</description>
    <label>Market Segment</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Dental_Count__c</fullName>
        <description># of Subscribers enrolled for Dental(does not include members count)</description>
        <label>Dental Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Health_Count__c</fullName>
        <description># of Subscribers enrolled for Health(does not include members count)</description>
        <label>Health Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscribers_Count__c</fullName>
        <description># of Subscribers enrolled for Health and Dental(does not include members count)</description>
        <label>Subscribers Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <recordTypes>
        <fullName>SGR_Analytical_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <label>SGR Analytical Opportunity</label>
    </recordTypes>
    <recordTypes>
        <fullName>SGR_Production_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>SGR Oppurtunity Record Type</description>
        <label>SGR Production Opportunity</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SGR_CloneOppty_Test.cls
/***********************
Name : Roopa Pothuluri
Date : 1/12/2019
Description : Test class for SGR_CloneOppty
************************/

@isTest
public class SGR_CloneOppty_Test {
    public static testmethod void clontest() {

        List<Account> accs = new List<Account>();
        accs.add(new Account(Name = 'TestAcc1', External_Id__c = 'A1234', Market_Segment__c = 'SG', hold_end_date__c = Date.today() - 1, SGR_Hold_Reason__c = '1st Year Renewal'));
        accs.add(new Account(Name = 'TestAcc2', External_Id__c = 'A5678', Market_Segment__c = 'SG', hold_end_date__c = Date.today() - 1, SGR_Hold_Reason__c = '1st Year Renewal'));
        insert accs;

        Id prodRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Production_Opportunity').getRecordTypeId();
        Id analyRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Analytical_Opportunity').getRecordTypeId();
        Opportunity opp = new Opportunity(AccountId = accs.get(0).Id, Name = 'Oppty1', RecordTypeId = prodRecId, StageName = 'Triggered', CloseDate = System.today().addYears(2), Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c = 'Rated', Subscribers_Count__c = 4, Health_Count__c = 44, Dental_Count__c = 55);
        Opportunity opp1 = new Opportunity(AccountId = accs.get(0).Id, Name = 'Oppty1', RecordTypeId = prodRecId, StageName = 'Triggered', CloseDate = System.today().addYears(2), Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c = 'Sold', Subscribers_Count__c = 4, Health_Count__c = 44, Dental_Count__c = 55);
        insert opp1;
        Opportunity opp2 = new Opportunity(AccountId = accs.get(0).Id, Name = 'Oppty1', RecordTypeId = prodRecId, StageName = 'Triggered', CloseDate = System.today().addYears(2), Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c = 'Closed', Subscribers_Count__c = 4, Health_Count__c = 44, Dental_Count__c = 55);
        insert opp2;
        Opportunity opp3 = new Opportunity(AccountId = accs.get(0).Id, Name = 'Oppty1', RecordTypeId = prodRecId, StageName = 'Triggered', CloseDate = System.today().addYears(2), Renewal_Date__c = System.Today().addMonths(3), Rating_Status__c = 'Finalized', Subscribers_Count__c = 4, Health_Count__c = 44, Dental_Count__c = 55);
        insert opp3;
        Map<id, id> newRecID = new Map<id, id>();
        map<string, string> replaceValues = new map<string, string>();
        insert opp;
        Test.starttest();
        Sgr_CloneOppty.OppNew(opp.Id);
        Sgr_CloneOppty.createChildRecord(opp, newRecID, 'sobjectRelName', replaceValues);
        Sgr_CloneOppty.OppNew(opp1.Id);
        Sgr_CloneOppty.createChildRecord(opp1, newRecID, 'sobjectRelName', replaceValues);
        Sgr_CloneOppty.OppNew(opp2.Id);
        Sgr_CloneOppty.createChildRecord(opp2, newRecID, 'sobjectRelName', replaceValues);
        Sgr_CloneOppty.OppNew(opp3.Id);
        Sgr_CloneOppty.createChildRecord(opp3, newRecID, 'sobjectRelName', replaceValues);
        Test.stoptest();
    }
}