src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Benefit_Agreement__c.object
<CustomObject>
    <description>Benefit Agreement information offered to the employees for the Group Account will be stored using this object</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the date the Benefit Agreement was effective as listed in BlueStar</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the financial billing arrangement that an account designates for the Benefit Agreement.</description>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Account__c</fullName>
        <description>This field is used to capture the Group Account associated to the Benefit Agreement</description>
        <label>Group Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Agreements</relationshipLabel>
        <relationshipName>Benefit_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the Benefit Agreement is active or cancelled as listed in BlueStar</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Benefit Agreement</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Benefit Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Agreements</pluralLabel>
    <recordTypes>
        <fullName>BlueStar</fullName>
        <active>true</active>
        <description>Records that are sent from Bluestar</description>
        <label>BlueStar</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BenefitAgreementDAOTest.cls
@isTest(SeeAllData = false)
private class BenefitAgreementDAOTest {

	@isTest
	static void benefitAgreementDAOTest() {
		Test.StartTest();

		List<Account> accountList = new List<Account>();
		BenefitAgreementDAO.IBenefitAgreementDAO benefitAgreementDAOInstance = new BenefitAgreementDAO();

		Account testAcnt = TestClassUtiltity.CreateAccountRecord('TestAccount');
		accountList.add(testAcnt);
		Benefit_Agreement__c testBnftAgrmnt = new Benefit_Agreement__c(Group_Account__c = testAcnt.Id, Funding_Type__c = 'PREM', Effective_Date__c = (System.today() - 1), Status__c = 'Active');
		insert testBnftAgrmnt;
		List<Benefit_Agreement__c> bnftAgrmnts = benefitAgreementDAOInstance.getGroupAccountBenefitAgreements( accountList );

		System.assertEquals( bnftAgrmnts.size(), 1);

		Set<Id> accIds = new Set<Id>();
		accIds.add(testAcnt.Id);
		List<Benefit_Agreement__c> batchBAs = benefitAgreementDAOInstance.getBatchBenefitAgreements(accIds);
		Test.StopTest();
	}

	@isTest
	static void benefitAgreementComplexityDAOTest() {
		Test.StartTest();

		List<Account> accountList = new List<Account>();
		BenefitAgreementDAO.IBenefitAgreementDAO benefitAgreementDAOInstance = new BenefitAgreementDAO();
		Id BlueSTARRecType = Schema.SObjectType.Benefit_Agreement__c.getRecordTypeInfosByName().get( ConstantsController.BlueStar ).getRecordTypeId();

		Account testAcnt = TestClassUtiltity.CreateAccountRecord('TestAccount');
		accountList.add(testAcnt);
		Benefit_Agreement__c testBnftAgrmnt = new Benefit_Agreement__c(Group_Account__c = testAcnt.Id, RecordTypeId = BlueSTARRecType, Funding_Type__c = 'PREM', Effective_Date__c = (System.today() - 1), Status__c = 'Active');
		insert testBnftAgrmnt;
		Set<id> baIds = new Set<id>{testBnftAgrmnt.id};
		List<Benefit_Agreement__c> bnftAgrmnts = benefitAgreementDAOInstance.getActiveBlueStarBenefitAgreements( baIds, BlueSTARRecType);
		System.assertEquals( bnftAgrmnts.size(), 1);

		bnftAgrmnts[0].Funding_Type__c = 'ASO';
		benefitAgreementDAOInstance.updateBenefitAgreements(bnftAgrmnts);
		Test.StopTest();
	}
}