src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Hold_End_Date__c</fullName>
        <label>Hold End Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>renewal_duration_is_infinite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indefinite Hold</label>
        <type>Checkbox</type>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assigned_UW__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned UW</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <description>This field is used to capture the requested effective date for the opportunity.</description>
        <label>Opportunity Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Workflow_Activity__c</fullName>
        <label>Workflow Activity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
                <value>
                    <fullName>UW Review - Validation Errors</fullName>
                </value>
                <value>
                    <fullName>Actuarial Gate</fullName>
                </value>
                <value>
                    <fullName>Awaiting BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>Plan Change in Progress</fullName>
                </value>
                <value>
                    <fullName>Pend in Progress</fullName>
                </value>
                <value>
                    <fullName>Not Eligible to be Transferred</fullName>
                </value>
                <value>
                    <fullName>UW Review</fullName>
                </value>
                <value>
                    <fullName>IT Review - Rating Failed</fullName>
                </value>
                <value>
                    <fullName>Underwriting Review</fullName>
                </value>
                <value>
                    <fullName>Actuarial Release</fullName>
                </value>
                <value>
                    <fullName>Ready for Distribution</fullName>
                </value>
                <value>
                    <fullName>Group Verifier Review - BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>BlueStar Transfer Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workflow_System_Status__c</fullName>
        <label>Workflow System Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to Fetch Mapped Plans</fullName>
                    <default>true</default>
                    <label>Ready to Fetch Mapped Plans</label>
                </value>
                <value>
                    <fullName>Ready to Validate</fullName>
                </value>
                <value>
                    <fullName>Failed Validation</fullName>
                </value>
                <value>
                    <fullName>Ready to Rate</fullName>
                </value>
                <value>
                    <fullName>Ready For Gate Processing</fullName>
                </value>
                <value>
                    <fullName>Ready to Send to B-Engaged</fullName>
                </value>
                <value>
                    <fullName>Ready to Send to BlueSTAR</fullName>
                </value>
                <value>
                    <fullName>Not Eligible to Send to BlueSTAR</fullName>
                </value>
                <value>
                    <fullName>Workflow Completed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Review Task Completion</fullName>
                </value>
                <value>
                    <fullName>Awaiting Hold Task Completion</fullName>
                </value>
                <value>
                    <fullName>Gate Processing Completed</fullName>
                </value>
                <value>
                    <fullName>Failed Rating</fullName>
                </value>
                <value>
                    <fullName>Ready for BlueSTAR Initiation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>SGR_Task</fullName>
        <active>true</active>
        <label>SGR_Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Sgr_OpportunityHelper.cls
public class Sgr_OpportunityHelper{
    public static boolean rerun = false;
    public static void updatestatus(list<Opportunity> opptyList, map<Id,Opportunity> oldmap){
    
        set<Id> oppHistorySet = new set<Id>();
        list<Opportunity> updateOpptyList=new list<Opportunity>();
        set<Id> accountIdSet = new set<Id>();
        set<Id> oppsIdSet=new set<Id>();
        list<Task> taskList = new list<Task>();
        Id sGRTR =Schema.SObjectType.task.getRecordTypeInfosByName().get('SGR_Task').getRecordTypeId();
        
        list<Task> inserttaskList = new list<Task>();
        for(OpportunityFieldHistory oph : [SELECT Id,opportunityId,oldvalue, NewValue from OpportunityFieldHistory where 
                                           opportunityId IN : opptyList AND Field = 'Rating_Status__c']){
             if(oph.oldvalue == 'Actuarial-Released'){
                 oppHistorySet.add(oph.opportunityId);
             }                            
                                      
        }
        List<Opportunity> opps =[SELECT Id,Assigned_UW__c, Account.renewal_duration_is_infinite__c,Account.Hold_End_Date__c from Opportunity where Id IN : opptyList];
        for(Opportunity op : opps){
           
           DateTime dT = date.today();
           Date myDate = date.newinstance(dT.year(), dT.month(), dT.day());
            if(op.Account.renewal_duration_is_infinite__c || op.Account.Hold_End_Date__c > myDate){
                accountIdSet.add(op.AccountId);
            }
        }
       
        for(Opportunity op : opptyList){
            if(((op.Assigned_UW__c!=null)  && ((op.Rating_Status__c == 'Actuarial-Released' && oldmap.get(op.Id).Rating_Status__c != 'Actuarial-Released' && 
               oppHistorySet.contains(op.Id) && !accountIdSet.contains(op.AccountId)) && (op.SGR_Workflow_Activity__c!='Underwriting Hold')))){
                op.SGR_Workflow_Activity__c = 'UW Review';
                op.Workflow_System_Status__c='Awaiting Review Task Completion';//#SFDC-16646 global workflow
                updateOpptyList.add(op);
                Task newTask = new task();
                newTask.Subject = 'Underwriter Review Complete';
                newTask.OwnerId = op.Assigned_UW__c;
                newTask.Status = 'Not started';
                newtask.Priority = 'Normal';
                newtask.RecordTypeId =sGRTR;
                newTask.WhatId = op.Id; 
                   
                taskList.add(newTask);
            }
            
        }
        if(taskList.size()>0){
            insert taskList;
        }
          
    }
    
    public static void creatingChildtask(list<Opportunity> opptyList, map<Id,Opportunity> oldmap){
       set<Id> oppHistorySet = new set<Id>();
        list<task> oppSet= new list<task>();
      if(opptyList!=null && opptyList.size()>0){
        oppSet = [select whatid,status from task where status!='Completed' and subject='Edit Complete' and whatid= :opptyList[0].id];
        }
        set<Id> accountIdSet = new set<Id>();
        list<Task> taskList = new list<Task>();
        Id sGRTR =Schema.SObjectType.task.getRecordTypeInfosByName().get('SGR_Task').getRecordTypeId();
             
       
       for(Opportunity op : opptyList){
            if(op.Assigned_UW__c!=null && (op.Rating_Status__c == 'Pended'&& oldmap.get(op.Id).Rating_Status__c != 'Pended') && oppSet.size()==0 && rerun== false){
                op.SGR_Workflow_Activity__c = 'Pend in Progress';
                Task newTask = new task();
                newTask.Subject = 'Edit Complete';
                newTask.OwnerId = op.Assigned_UW__c;
                newTask.Status = 'Not started';
                newtask.Priority = 'Normal';
                newtask.RecordTypeId =sGRTR;
                newTask.WhatId = op.Id; 
                taskList.add(newTask);
            }
            
        }
        if(taskList.size()>0){
            insert taskList;
        }
        rerun=true; 
    }
    
    //Story: SFDC-17474
    //Author: Landry Harris
    public static void updateOpportunityEffectiveDate(List<Opportunity> newOpps, Map<Id,Opportunity> oldmap) {
        for (Opportunity o: newOpps) {
            if (o.Renewal_Date__c != null && (o.Renewal_Date__c != oldmap.get(o.Id).Renewal_Date__c)) {
                o.Requested_Effective_Date__c = o.Renewal_Date__c;
            }
        }
    }
   
}