src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Beng_PDF_Preview_profiles__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Beng PDF Preview profiles</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Beng_LatestTransactionID__c</fullName>
        <label>Beng LatestTransactionID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentUserProfileName__c</fullName>
        <formula>$Profile.Name</formula>
        <label>CurrentUserProfileName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Sgr_Beng_PreviewPDF.cls
public class Sgr_Beng_PreviewPDF {    
    @AuraEnabled
    public static Opportunity getOppData(Id oppId) {
        
        Opportunity opp = [SELECT ID,Rating_Status__c,CurrentUserProfileName__c,Account.External_ID__c FROM Opportunity WHERE ID=:oppId];
        return opp;
    }
    
    @AuraEnabled
    public static Map<ID,String> oppDetails(String oppId,String documentVersion,string printtype, String accNumber) {
        
        Map<ID,String> conDocIdAndMessage= new Map<ID,String>();
        Beng_PDF_Preview_profiles__c cs = Beng_PDF_Preview_profiles__c.getValues(UserInfo.getProfileId());
        if(cs!=null){
            SGR_Beng_XML_Response Response = Sgr_Beng_Request.SendRequest(oppId, 'DRAFT','Account');       
            // pass to SGR_Beng_DocHandler to start testing
            SGR_Beng_DocHandler handler = new SGR_Beng_DocHandler();
            handler.oppId = oppId;  
            String dt = Datetime.now().format('yyyy-MM-dd\'_\'HHmmss');
            handler.fileName = accNumber+'_'+dt+'.pdf';    
            handler.documentBase64Encoded=String.valueOf(Response.base64Template);
            handler.saveDraft();
            system.debug('+++Response'+Response);
            if(Response!=null){
                String docName = accNumber+'_'+dt+'.pdf';
                List<contentDocument> contDocList = [Select id,Title,FileType,CreatedBy.Name,ContentSize From contentDocument where Title=:docName LIMIT 1];
                Opportunity opty = [SELECT Id,Beng_LatestTransactionID__c FROM Opportunity WHERE ID=:oppId];    
                opty.Beng_LatestTransactionID__c=Response.transactionId;
                update opty;
                if(contDocList.size()>0){
                    conDocIdAndMessage.put(contDocList[0].Id,Response.message);
                }else{
                    conDocIdAndMessage.put(null,Response.message);
                }
            }
        }else{
            conDocIdAndMessage.put(null,null);
        }
        return conDocIdAndMessage;
    }
}