src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/GEMS_Benefit_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>BA_Description__c</fullName>
        <label>BA Description</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GEMS_BAs_SpHandling__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Gems BA&apos;s for special handling to create Downstream cases for only these selected BA&apos;s.</description>
        <label>BAs for Downstream Processing</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS Benefit Agreement</label>
    <nameField>
        <label>BA No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Benefit Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Group_Section__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Group Sections</relationshipLabel>
        <relationshipName>Group_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>GEMS Group Section</label>
    <nameField>
        <label>Group Section No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Group Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Prospective_ID_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account_Setup_OSS_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Setup/OSS User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Prospective_ID_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actual_Owner__c</fullName>
        <label>Actual Owner</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Applicable_BAs__c</fullName>
        <label>Applicable BAs</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Applicable_GSs__c</fullName>
        <label>Applicable GSs</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Agreement</fullName>
                </value>
                <value>
                    <fullName>Group Section</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ID_Card_Mailed_Date__c</fullName>
        <label>ID Card Mailed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ID_Card_Mailed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ID Card Mailed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ID_Card_Suppression_Date__c</fullName>
        <label>ID Card Suppression Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_ID_Card_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent ID Card Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Prospective ID Card Request</relationshipLabel>
        <relationshipName>GEMS_Prospective_ID_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prospective_ID_Card_Approved_Date__c</fullName>
        <label>Prospective ID Card Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prospective_ID_Card_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prospective ID Card Approved?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prospective_ID_card_Requested_date__c</fullName>
        <label>Prospective ID Card Requested date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prospective_ID_sent_for_approval_date__c</fullName>
        <label>Prospective ID Sent for Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Removal_of_ID_Card_Suppression_Date__c</fullName>
        <label>Removal of ID Card Suppression Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Request for prospective ID</fullName>
                </value>
                <value>
                    <fullName>Prospective ID Card Completed</fullName>
                </value>
                <value>
                    <fullName>Removal of Suppression Completed</fullName>
                    <isActive>false</isActive>
                    <label>Removal of Suppression Completed</label>
                </value>
                <value>
                    <fullName>Request for Removal of Suppression</fullName>
                    <isActive>false</isActive>
                    <label>Request for Removal of Suppression</label>
                </value>
                <value>
                    <fullName>Request for Suppression</fullName>
                    <isActive>false</isActive>
                    <label>Request for Suppression</label>
                </value>
                <value>
                    <fullName>Suppression Completed</fullName>
                    <isActive>false</isActive>
                    <label>Suppression Completed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GEMS Prospective ID Card</label>
    <nameField>
        <displayFormat>PID#{0000000}</displayFormat>
        <label>Prospective ID Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GEMS Prospective ID Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Group_Section__c.object
<CustomObject>
    <description>Group Section information associated to a Group Account will be stored using this object</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Unique identifier of Group Section for the Group Account</description>
        <externalId>true</externalId>
        <label>Group Section ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Group Section</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Group Section</label>
    <nameField>
        <displayFormat>GS-{000000}</displayFormat>
        <label>Group Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>External ID of the record from Source System</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>market segment user belongs to</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GEMS_ProspectiveIDCardBAAssignCntlr.cls
/**************************************************************************************
* Apex Class Name       : GEMS_ProspectiveIDCardBAAssignCntlr
* Version               : 1.0
* Function              : This Class is for assigning Prospective ID Card record to ID Card Child Case under Selected BA(For GEMS Project).
* Modification Log      :
* Developer           Date                  Description
* ------------------------------------------------------------------------------------
* Praveen             06/10/2016            Original Version
* Mark Naumann        08/15/2016            remove two fields: ID_Card_Suppression_Date__c & Removal_of_ID_Card_Suppression_Date__c
* Phani Kommareddy    06/12/2017            SFDC-3064 Change how BAs are associated to Custom ID Card, Prospective and Suppression requests
* Phani Kommareddy    09/13/2017            SFDC-2835 GEMS - Ability to request ID Card Prospective by Group Section
* Phani Kommareddy    11/27/2017            SFDC-6369 GEMS - ID Card Maintenance: ID Card Case Page Layout & Functionality
* Phani Kommareddy	  02/19/2017			SFDC-4244 GEMS: Acct Structure - Special Handling of Complex/Co-op Accounts (Downstream Processing)
*************************************************************************************/

public without sharing class GEMS_ProspectiveIDCardBAAssignCntlr {
    public Id caseId {get; set;}
    public Case parentIdCardCase {get; set;}
    public Id prospectiveRecId{get;set;}
    public GEMS_Prospective_ID_Card__c prospectiveRec{get;set;}
    public List<GEMS_Benefit_Agreement__c> benefitAgreementsList{set;get;}
    public List<Case> structureBAs{get;set;}
    public String assignmentType = 'Benefit Agreement';
    public List<GEMS_BAIdWrapper> listOfBARecords{get; set;}
    public List<GEMS_GSIdWrapper> listOfGSRecords{get; set;}
    public String baCaseNums{set;get;}    
    public String gsCaseNums{set;get;}    
    public boolean disableSubmitButton{set;get;}
    
    public GEMS_ProspectiveIDCardBAAssignCntlr(ApexPages.StandardController controller) {
        caseId = ApexPages.currentPage().getParameters().get('caseId');
        prospectiveRecId = ApexPages.currentPage().getParameters().get('id');
        Id caseAccountStructureRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS Account Structure').getRecordTypeId();
        Id  balevelIdCardCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS BA Level ID Card').getRecordTypeId();
        if(caseId!=null) {
            disableSubmitButton = true;
            parentIdCardCase = [SELECT Id, CaseNumber, HCSC_Division__c, GEMS_Case_Effective_Date__c, GEMS_Submission_Type__c, GEMS_Submission_Sub_Type__c, 
                                GEMS_Line_of_Business__c, GEMS_Account_Submission_Info__c, Market_Segment__c, Status, Owner.Name, GEMS_Type__c, OwnerId,
                                Account.AccountNumber, Account.External_ID__c, Account.Name,Gems_Assigned_BAs__c
                                FROM Case WHERE id =: caseId];
            prospectiveRec = new GEMS_Prospective_ID_Card__c();
            prospectiveRec.Parent_ID_Card_Case__c=caseId;
            prospectiveRec.OwnerID=parentIdCardCase.OwnerId;
            prospectiveRec.Actual_Owner__c=parentIdCardCase.OwnerId;            
        } else if(prospectiveRecId!=null) {
            prospectiveRec = [SELECT ID, Name, ID_Card_Mailed__c, Parent_ID_Card_Case__c, Prospective_ID_card_Requested_date__c,
                              Prospective_ID_sent_for_approval_date__c, ID_Card_Mailed_Date__c,Prospective_ID_Card_Approved__c,Actual_Owner__c,
                              Prospective_ID_Card_Approved_Date__c, Status__c, Account_Setup_OSS_User__c,ownerid, Applicable_BAs__c,Applicable_GSs__c,Assignment_Type__c 
                              FROM GEMS_Prospective_ID_Card__c WHERE ID=:prospectiveRecId];
            
            parentIdCardCase = [SELECT Id, CaseNumber, HCSC_Division__c, GEMS_Case_Effective_Date__c, GEMS_Submission_Type__c, GEMS_Submission_Sub_Type__c, 
                                GEMS_Line_of_Business__c, GEMS_Account_Submission_Info__c, Market_Segment__c, Status, Owner.Name, GEMS_Type__c,
                                Account.AccountNumber, Account.External_ID__c, Account.Name,Gems_Assigned_BAs__c, OwnerId
                                FROM Case WHERE id =: prospectiveRec.Parent_ID_Card_Case__c];
            if(prospectiveRec.Assignment_Type__c != null && prospectiveRec.Assignment_Type__c != '') {
                assignmentType = prospectiveRec.Assignment_Type__c;
            } else {
                assignmentType = 'Benefit Agreement';
            }
        }
        
        
        //SFDC-4244 - Added GEMS_BAs_SpHandling__c condition
        structureBAs = [SELECT id, 
                        (SELECT ID, Name, BA_Description__c, BA_Fund_Type__c, product__r.Name from GEMS_Benefit_Agreements__r where GEMS_BAs_SpHandling__c = true  order by Name),
                        (select name,group_no__c,section_no__c,section_description__c from Group_Sections__r) 
                        FROM Case WHERE RecordTypeId= :caseAccountStructureRecordTypeId AND GEMS_Account_Submission_Info__c= :parentIdCardCase.GEMS_Account_Submission_Info__c LIMIT 1];
        
        listOfBARecords = new List<GEMS_BAIdWrapper>();
        listOfGSRecords = new List<GEMS_GSIdWrapper>();
        
        if(!structureBAs.isEmpty()){
            Case baCase = structureBAs.get(0);
            List<GEMS_Benefit_Agreement__c> baList = new List<GEMS_Benefit_Agreement__c>();
            baList = baCase.GEMS_Benefit_Agreements__r;
            for(GEMS_Benefit_Agreement__c ba: baList) {
                listOfBARecords.add(new GEMS_BAIdWrapper(false, ba));                
            }
            
            List<GEMS_Group_Section__c> gsList = new List<GEMS_Group_Section__c>();
            gsList = baCase.Group_Sections__r;
            for(GEMS_Group_Section__c gs: gsList) {
                listOfGSRecords.add(new GEMS_GSIdWrapper(false, gs));                
            }
        }       
    }
    
    public List<SelectOption> getAssignmentItems() {
        return GEMS_IDCardUtil.getAssignmentItems();    
    }
    
    
    public PageReference saveAndAssignBAs() {
        try {
            prospectiveRec.Applicable_BAs__c=baCaseNums;
            prospectiveRec.Applicable_GSs__c=gsCaseNums;
            //SFDC-6369 GEMS - ID Card Maintenance: ID Card Case Page Layout & Functionality
            if(parentIdCardCase.GEMS_Submission_Type__c == GEMS_Constants.SubmissionTypeIDCardMaintenance) {
                if(String.isNotBlank(baCaseNums) && String.isNotBlank(gsCaseNums))
                    prospectiveRec.Assignment_Type__c = GEMS_Constants.IDCardAssignTypeBoth;
                else if(String.isNotBlank(baCaseNums)) {
                    prospectiveRec.Assignment_Type__c = GEMS_Constants.IDCardAssignTypeBA;
                } else if(String.isNotBlank(gsCaseNums))  {
                    prospectiveRec.Assignment_Type__c = GEMS_Constants.IDCardAssignTypeGS;
                } else {
                    prospectiveRec.Assignment_Type__c = GEMS_Constants.IDCardAssignTypeNone;
                }
            } else {
                prospectiveRec.Assignment_Type__c   = assignmentType;
            }
            upsert prospectiveRec;
            
            if(prospectiveRec.id !=null) {
                prospectiveRecId = prospectiveRec.id;
            }
            //SFDC-6369 GEMS - ID Card Maintenance: ID Card Case Page Layout & Functionality
            if(parentIdCardCase.GEMS_Submission_Type__c != GEMS_Constants.SubmissionTypeIDCardMaintenance) {
                List<GEMS_Prospective_ID_Card__c> prospectiveIDCardOfParentIDCard =
                    [Select ID, Applicable_BAs__c,Applicable_GSs__c,Assignment_Type__c from GEMS_Prospective_ID_Card__c where Parent_ID_Card_Case__c=:parentIdCardCase.id];
                Map<Id, GEMS_Prospective_ID_Card__c> prospectiveIDMap = new Map<Id, GEMS_Prospective_ID_Card__c>();
                for(GEMS_Prospective_ID_Card__c pidForm : prospectiveIDCardOfParentIDCard) {
                    prospectiveIDMap.put(pidForm.id,pidForm);
                }
                
                List<GEMS_IDCompare> idCompareList = GEMS_IDCardUtil.CopyProspectiveIDFormToIDCompare(prospectiveIDCardOfParentIDCard);
                GEMS_CustomFormInput customFormInput = new GEMS_CustomFormInput(prospectiveRecId,assignmentType,baCaseNums,gsCaseNums,idCompareList);
                List<GEMS_IDCompare> idcompareListUpdated = GEMS_IDCardUtil.updateExistingAssignments(customFormInput);
                List<GEMS_Prospective_ID_Card__c> prospectiveIdUpdateList = GEMS_IDCardUtil.copyIDCompareToProspectiveIDForm(idcompareListUpdated, prospectiveIDMap);
                update prospectiveIdUpdateList; 
            }
            return new pageReference('/'+prospectiveRecId);   
        } catch(Exception ex) {
            String msg = ex.getMessage();
            if(msg.contains('Queue not associated')){
                msg = 'Please check the case owner associated to the ID Card';
            } 
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, msg));      
            return null;
        }

    }
    
    
    
    public PageReference submitProspectiveIdCard() {
        if(prospectiveRec.Status__c=='Request for prospective ID'){
            CaseTeamMember caseTemMem = [SELECT Id, memberid, TeamRole.name FROM CaseTeamMember WHERE ParentId =: parentIdCardCase.GEMS_Account_Submission_Info__c AND TeamRole.name = 'Account Specialist'];
            prospectiveRec.OwnerId=caseTemMem.memberid;
        } else if(prospectiveRec.Status__c=='Prospective ID Card Completed') {
            User actualOwnerRec = [SELECT ID FROM User WHERE ID=:prospectiveRec.Actual_Owner__c];
            prospectiveRec.OwnerId=actualOwnerRec.Id;
        }
        update prospectiveRec;
        return null;
    }
    

    
    public PageReference gotoCase() {
        Id returnId;
        if(caseId!=null) {
            returnId=caseId;
        } else {
            returnId=parentIdCardCase.Id;
        }
        return new PageReference('/'+returnId);
    }
    
    public void dummy() {
        
    }
    
    public String getAssignmentType() {
        return assignmentType;
    }
    
    public void setAssignmentType(String assignmentType) {
        this.assignmentType = assignmentType;
    }
}