src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/items_SharePoint__x.object
<CustomObject>
    <externalDataSource>SharePoint</externalDataSource>
    <externalName>items_SharePoint</externalName>
    <label>items_SharePoint</label>
    <pluralLabel>items_SharePoint</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RFI_RFP_Received_Date__c</fullName>
        <description>This field is used to capture the date when the RFP or RFI is received.</description>
        <label>RFI/RFP Received Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ItemsSharePointDAOTest.cls
@isTest(SeeAllData=false)
private class ItemsSharePointDAOTest {
	@testSetup static void setupTestData(){
		Account a = new Account(Name='Test', External_Id__c='AC102981');
		insert a;
		Opportunity o = new Opportunity(Name='Test', RFI_RFP_Received_Date__c=System.Today());
		o.StageName='RFI Received';
		o.Probability = 10;
		o.CloseDate=System.Today();
		insert o;
		Case c = new Case(Subject='Test');
		c.Opportunity_Name__c = o.Id;
		c.AccountId = a.Id;
		insert c;
	}

	@isTest static void daoTest(){
		Account a = [SELECT Id FROM Account LIMIT 1];
		Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];
		Case c = [SELECT Id FROM Case LIMIT 1];

		ItemsSharePointDAO itemsSharepointDaoInstance = new ItemsSharePointDAO();

		Integer aCount = itemsSharepointDaoInstance.getAccountsCountById(a.Id);
		System.assertEquals(0, aCount);
		Integer oCount = itemsSharepointDaoInstance.getOpportunitiesCountById(o.Id);
		System.assertEquals(0, oCount);
		Integer cCount = itemsSharepointDaoInstance.getCasesCountById(c.Id);
		System.assertEquals(0, cCount);
		List<items_Sharepoint__x> listResults = itemsSharepointDaoInstance.getItemizedSharePointRecordsDynamically('select id from items_Sharepoint__x');
		System.assertEquals(0, listResults.size());
	}
}