src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Business need is to show the products that were renewed for the account last year.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>true</active>
        <description>Account record type that captures information about a competitor (carriers and vendors)</description>
        <label>Competitor</label>
    </recordTypes>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the account associated to the contact.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>

objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture the HR status of the contact from PeopleSoft.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Leave</fullName>
                </value>
                <value>
                    <fullName>Probation</fullName>
                </value>
                <value>
                    <fullName>Short Term Leave</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_Decision_Date__c</fullName>
        <description>This field is used to capture the date when a decision is expected for the Opportunity.</description>
        <label>Expected Decision Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the product related to the child opportunity.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RFI_RFP_Received_Date__c</fullName>
        <description>This field is used to capture the date when the RFP or RFI is received.</description>
        <label>RFI/RFP Received Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity_Product__c.object
<CustomObject>
    <description>Products related to the opportunity - acting as a junction object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Winning Carrier / Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Competitor Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <formula>Opportunity_Name__r.Requested_Effective_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Opportunity Name related to the Product</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Name of product category</description>
        <formula>TEXT(Product__r.Product_Category__c)</formula>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>State__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New Sale</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Add-On Gain</fullName>
                </value>
                <value>
                    <fullName>Add-On Loss</fullName>
                </value>
                <value>
                    <fullName>Market Check</fullName>
                </value>
                <value>
                    <fullName>Upsell – IL</fullName>
                </value>
                <value>
                    <fullName>Product Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product related to the opportunity record</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Service</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{000}</displayFormat>
        <label>OP #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Captures product category</description>
        <inlineHelpText>required field for plans to flow correctly on BA to BlueSTAR</inlineHelpText>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BCC</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Disease Management</fullName>
                </value>
                <value>
                    <fullName>EPO</fullName>
                </value>
                <value>
                    <fullName>Group Govt</fullName>
                </value>
                <value>
                    <fullName>HCA</fullName>
                </value>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>IHI</fullName>
                </value>
                <value>
                    <fullName>Nurseline</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
                <value>
                    <fullName>Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Dearborn</fullName>
                </value>
                <value>
                    <fullName>Health Advocacy Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Health Care Management</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>Dearborn</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Simplified_Product__c</fullName>
        <label>Simple Product</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Tracking__c.object
<CustomObject>
    <description>This object provides tracking information.</description>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Product</label>
        <referenceTo>Opportunity_Product__c</referenceTo>
        <relationshipLabel>Product Tracking</relationshipLabel>
        <relationshipName>Product_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Tracking</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Product Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestProductTracking.cls
@isTest(seeAllData=false)
private class TestProductTracking {
    
    @isTest static void TestInsertProductTracking(){
        
        Account theAccount = new Account();
        theAccount.Name = 'My Test Account';
        theAccount.Fax = '1234567';
        theAccount.Effective_Date__c = system.today().addyears(2);
        theAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        insert theAccount;
        
        Id CompetitorAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Competitor').getRecordTypeId();
        Account testCompetitorAccount = TestClassUtiltity.createAccountWithRecType('Test Account2', CompetitorAccountRecordTypeId);
        
        Account theWinner = new Account();
        theWinner.Name = 'My Competitor Account';
        theWinner.Fax = '7654321';
        theWinner.Effective_Date__c = system.today().addyears(2);
        theWinner.Type = 'Competitor Account';
        theWinner.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Competitor').getRecordTypeId();
        insert theWinner;        
        
        Contact theContact = new Contact();
        theContact.FirstName = 'John';
        theContact.LastName = 'Doe';
        theContact.Account__c = theAccount.Id;        
        insert theContact;
        
        AccountContactRole theACR = new AccountContactRole();
        theACR.AccountId = theAccount.Id;
        theACR.ContactId = theContact.Id;
        theACR.IsPrimary = true;
        theACR.Role = 'Producer';
        insert theACR;
        
        Id OppRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New Sale').getRecordTypeId();
        Opportunity theOpportunity = new Opportunity();
        theOpportunity.AccountId = theAccount.Id;
        theOpportunity.Name = 'oppName 1';
        theOpportunity.StageName = 'RFI Received';
        theOpportunity.CloseDate = system.Today().addYears(2);
        theOpportunity.Expected_Decision_Date__c = system.Today().addYears(1);
        theOpportunity.RFI_RFP_Received_Date__c = system.Today().addYears(1);        
        insert theOpportunity;
        
        Id ProductrecTypeId=Schema.SObjectType.Product2.getRecordTypeInfosByName().get('HCSC BlueStar Product').getRecordTypeId();
        Product2 theProduct = new Product2();
        theProduct.Name = 'RX';
        theProduct.IsActive = true;
        theProduct.Product_Category__c = 'Pharmacy';
        theProduct.Family = 'Ancillary and other';
        theProduct.RecordTypeId = ProductrecTypeId;
        theProduct.Product_Type__c = 'Non-Medical';
        theProduct.Simplified_Product__c = 'RX';
        insert theProduct;      
        
        Opportunity_Product__c aOpportunityProduct = new Opportunity_Product__c();
        aOpportunityProduct.Opportunity_Name__c = theOpportunity.Id;
        aOpportunityProduct.Product__c = theProduct.Id;
        aOpportunityProduct.Status__c = 'Lost';
        aOpportunityProduct.Incumbent__c = testCompetitorAccount.Id;
        aOpportunityProduct.Account__c = theWinner.Id;
        insert aOpportunityProduct;
        
        Product_Tracking__c theProductTracking = new Product_Tracking__c();
        theProductTracking.Opportunity_Product__c = aOpportunityProduct.Id; 
        theProductTracking.Consultant__c = null; /*setting null to test that its populated by Trigger */
               
        test.startTest();
        
        insert theProductTracking;        
        Product_Tracking__c afterTriggerProductTracking = [SELECT Id, Consultant__c
                                                           FROM Product_Tracking__c 
                                                           WHERE Id = :theProductTracking.Id];
        system.assertEquals(afterTriggerProductTracking.Consultant__c,theContact.Id);                
        
        theProductTracking.PBMCarrier__c = theWinner.Id;                      
        update theProductTracking;        
        Opportunity_Product__c afterTriggerOpportunityProduct = [SELECT Id, Account__c
                                                                 FROM Opportunity_Product__c
                                                                 WHERE Id = :aOpportunityProduct.Id];        
        system.assertEquals(afterTriggerOpportunityProduct.Account__c, theProductTracking.PBMCarrier__c); 
        
        test.stopTest();
        
        
    }
    
    
}