src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Hold_End_Date__c</fullName>
        <label>Hold End Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>renewal_duration_is_infinite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indefinite Hold</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>SGR_Hold_Reason__c</fullName>
        <label>Hold Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Wage &amp; Tax Audit</fullName>
                </value>
                <value>
                    <fullName>1st Year Renewal</fullName>
                </value>
                <value>
                    <fullName>Block Acquisition</fullName>
                </value>
                <value>
                    <fullName>Special Adjustments</fullName>
                </value>
                <value>
                    <fullName>Market Segment Verification</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Workflow_Activity__c</fullName>
        <label>Workflow Activity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
                <value>
                    <fullName>UW Review - Validation Errors</fullName>
                </value>
                <value>
                    <fullName>Actuarial Gate</fullName>
                </value>
                <value>
                    <fullName>Awaiting BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>Plan Change in Progress</fullName>
                </value>
                <value>
                    <fullName>Pend in Progress</fullName>
                </value>
                <value>
                    <fullName>Not Eligible to be Transferred</fullName>
                </value>
                <value>
                    <fullName>UW Review</fullName>
                </value>
                <value>
                    <fullName>IT Review - Rating Failed</fullName>
                </value>
                <value>
                    <fullName>Underwriting Review</fullName>
                </value>
                <value>
                    <fullName>Actuarial Release</fullName>
                </value>
                <value>
                    <fullName>Ready for Distribution</fullName>
                </value>
                <value>
                    <fullName>Group Verifier Review - BlueSTAR Transfer</fullName>
                </value>
                <value>
                    <fullName>BlueStar Transfer Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SGR_ReleaseValidationsTest.cls
@isTest
public class SGR_ReleaseValidationsTest {

     static testmethod  void testmethod1()
     {
         // Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId();
   // List<Account> accLst = new List<Account>(); 
    Account a = new Account();
    a.Status__c='Active';
    a.Name='santosh1';
    a.HCSC_Division__c='IL';
    a.Market_Segment__c='SG';
    a.Funding_Type__c='PREM';
    a.renewal_duration_is_infinite__c=false;
    a.Renewal_Date__c=date.today();
    a.hold_end_date__c=Date.today()+2;

     a.SGR_Hold_Reason__c='Block Acquisition';
        
         insert a;

    List<Opportunity> oppLst1 = new List<Opportunity>();  
    Opportunity opp= new Opportunity();
         opp.Account = a;
        opp.Name = 'Sample';
        opp.Renewal_Date__c=Date.today().adddays(-1);
         
         opp.SGR_Workflow_Activity__c='';
         opp.Workflow_System_Status__c='Awaiting Hold Task Completion';
        opp.StageName = 'lost';
        opp.Primary_Closed_Reason__c ='Political';
        opp.Rating_Status__c='Rated';
        opp.Closed_Comments__c = 'XYZ';
       
       opp.Assigned_UW__c = Userinfo.getUserId();
         opp.RecordTypeId=SGR_ReleaseValidationsTest.getOpptyRecordTypeIds('Opportunity','SGR Production Opportunity');//'SGR Analytical Opportunity');
        opp.Date_Closed__c = date.today().adddays(-1);
        opp.CloseDate = date.today().adddays(2);
         
        oppLst1.add(opp);
         
         insert oppLst1;
         
         // List<Opportunity> oppLst = new List<Opportunity>{opp,opp1,opp2,opp3};
         
         Test.startTest();
         SGR_ReleaseValidations.initiateValidation(oppLst1);

          Test.stopTest();
     }

    static testmethod  void testmethod2()
     {
         // Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId();
   // List<Account> accLst = new List<Account>();   
    Account a = new Account();
    a.Status__c='Active';
    a.Name='santosh1';
    a.HCSC_Division__c='IL';
    a.Market_Segment__c='SG';
    a.Funding_Type__c='PREM';
    a.renewal_duration_is_infinite__c=false;
    a.Renewal_Date__c=date.today();
    a.hold_end_date__c=Date.today();

     a.SGR_Hold_Reason__c='Block Acquisition';
        
         insert a;

    List<Opportunity> oppLst1 = new List<Opportunity>();
    Opportunity opp= new Opportunity();
         opp.Account = a;
        opp.Name = 'Sample';
        opp.Renewal_Date__c=Date.today().adddays(2);
         
         opp.SGR_Workflow_Activity__c='';
         opp.Workflow_System_Status__c='Awaiting Hold Task Completion';
        opp.StageName = 'lost';
        opp.Primary_Closed_Reason__c ='Political';
        opp.Rating_Status__c='Rated';
        opp.Closed_Comments__c = 'XYZ';
       
       opp.Assigned_UW__c = Userinfo.getUserId();
         opp.RecordTypeId=SGR_ReleaseValidationsTest.getOpptyRecordTypeIds('Opportunity','SGR Production Opportunity');//'SGR Analytical Opportunity');
        opp.Date_Closed__c = date.today().adddays(-1);
        opp.CloseDate = date.today().adddays(2);
         
        oppLst1.add(opp);
         insert oppLst1;
         
         // List<Opportunity> oppLst = new List<Opportunity>{opp,opp1,opp2,opp3};
         
         Test.startTest();
         
         SGR_ReleaseValidations.initiateValidation(oppLst1);
         opportunity oppcheck = [select Rating_Status__c from opportunity where id = :oppLst1[0].id];
        system.assertEquals('Marketing Release', oppcheck.rating_status__c, '2Opportunity is not updated as Marketing Release after it is updated as Underwriting Released.');

          Test.stopTest();
     }
    
     
     public Static String getOpptyRecordTypeIds(String ObjectName,String recTypeName){
         Map<String, Schema.SObjectType> mapSchemaobject = Schema.getGlobalDescribe() ;
        Schema.SObjectType SchemaObject = mapSchemaobject.get(ObjectName) ;
        Schema.DescribeSObjectResult getDescribeSchema = SchemaObject.getDescribe() ;
        Map<String,Schema.RecordTypeInfo> RecordTypeInfo = getDescribeSchema.getRecordTypeInfosByName();
        String recordTypeId = RecordTypeInfo.get(recTypeName).getRecordTypeId();
        System.debug(':::RECTYPE:::'+recordTypeId);
        return recordTypeId;
       
    }
    
}