src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Active_Health_Subscribers__c</fullName>
        <description>This field is used to capture the number of active health contracts for the Group Account as listed in BlueStar</description>
        <label>Active Health Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Contract_End__c</fullName>
        <description>This field is used to capture the end date of the Group Account&apos;s contract.</description>
        <label>Contract End</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Client_Since__c</fullName>
        <description>This field is used to capture the date a Group Account first became an HCSC client as listed in BlueStar</description>
        <label>HCSC Client Since</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Open_Enrollment_Date__c</fullName>
        <description>The date Open Enrollment begins for a Group Account&apos;s members</description>
        <label>Open Enrollment Start Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Open_Enrollment_End_Date__c</fullName>
        <description>The date Open Enrollment ends for a Group Account&apos;s members</description>
        <label>Open Enrollment End Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Total_Num_of_Potential_Subscribers__c</fullName>
        <description>This field is used to capture the total number of potential subscribers to enroll in insurance.</description>
        <label>Eligible Employees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <recordTypes>
        <fullName>Group_Account</fullName>
        <active>true</active>
        <description>Account record type for Group / Sold Accounts</description>
        <label>Group Account</label>
    </recordTypes>

objects/Account_Framework__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Framework</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stickiness Scoring</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Framework Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stickiness Scoring</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>This field is used to capture the date when the opportunity is won or lost.</description>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Closed_Reason__c</fullName>
        <description>This field is used to capture the primary reason why an Opportunity is won, lost or declined.</description>
        <label>Primary Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absorbed by Parent Group</fullName>
                </value>
                <value>
                    <fullName>Change of Ownership</fullName>
                </value>
                <value>
                    <fullName>Consol. Covg with 1 Carrier</fullName>
                </value>
                <value>
                    <fullName>Headquarters Relocated</fullName>
                </value>
                <value>
                    <fullName>Lack of Narrow Network</fullName>
                </value>
                <value>
                    <fullName>Market Check by Group</fullName>
                </value>
                <value>
                    <fullName>Organizational Changes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Guarantees</fullName>
                </value>
                <value>
                    <fullName>Plan Design-Other</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Purchase by Another Company</fullName>
                </value>
                <value>
                    <fullName>Rates-Aggregate Stop Loss-Claim/Attch Factor</fullName>
                </value>
                <value>
                    <fullName>Rates-Incumbent Reduced</fullName>
                </value>
                <value>
                    <fullName>Rates-Individual Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Rates-Insured</fullName>
                </value>
                <value>
                    <fullName>Repricing</fullName>
                </value>
                <value>
                    <fullName>Reputation of Selected Carrier</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Broker Relationship</fullName>
                </value>
                <value>
                    <fullName>Changed Brokers</fullName>
                </value>
                <value>
                    <fullName>Network Discounts</fullName>
                </value>
                <value>
                    <fullName>Network Disruption</fullName>
                </value>
                <value>
                    <fullName>Product Packaging</fullName>
                </value>
                <value>
                    <fullName>Did Not Want to Disrupt Ees</fullName>
                </value>
                <value>
                    <fullName>Not Enough Diff. to Change</fullName>
                </value>
                <value>
                    <fullName>PUG Did not meet participation</fullName>
                </value>
                <value>
                    <fullName>Rates-Admin. Charge too High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <description>This field is used to capture the requested effective date for the opportunity.</description>
        <label>Opportunity Effective Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Producer_Group_Association__c.object
<CustomObject>
    <description>Producer and Group associations will be stored using this object</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Effective Date of the Association (Relationship between Group Account and Producer Account)</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Stores the external ID from Source System (Concat of Group Account # and Producer Account #) for Upsert Operation</description>
        <externalId>true</externalId>
        <label>PGA External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Producer Group Association</label>
    <nameField>
        <displayFormat>PAG-{0000}</displayFormat>
        <label>PAG #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Producer Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Strategic_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>For existing Accounts, select the upcoming Renewal Date.
For new Accounts, select the Effective Date.</inlineHelpText>
        <label>Renewal Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Strategic Plan</label>
    <nameField>
        <label>Strategic Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>market segment user belongs to</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestGroupAccount360Controller.cls
/********************************************************************************
* Apex Class Name     : TestGroupAccount360Controller
* Version             : 1.0
* Function            : This is a test class for GroupAccount360Controller .
* Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Zachary Campbell		6/09/2017	added code to create and populate
*									Lightning_Prospecting_Profiles__c.  
* Zachary Campbell		10/20/2017	SFDC-5801 To increase code coverage of GroupAccount360Controller
*									myUnitTest2() and myUnitTest3() was added and code was split with myUnitTest()
*********************************************************************************/
@isTest
public  class TestGroupAccount360Controller {
    
    static testMethod void myUnitTest() {

        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User testUser = TestClassUtiltity.CreateUserRecord(p.Id, 'testlgnadev@user.com', 'testUser', 'test@user.com');
        System.runAs(testUser) {        
            try{
                //create account
                Account testAccount = TestClassUtiltity.CreateAccountRecord('Test Account 1');
                /*** start SFDC-5801 ***/
                testAccount.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
                /*** end SFDC-5801 ***/
                testAccount.ShippingStreet = 'test';
                testAccount.ShippingCity = 'test';
                testAccount.ShippingState = 'TX';
                //testAccount.ShippingCountry= 'United States';
                testAccount.ShippingPostalCode = '1002';
                testAccount.Website = 'test.com';
                testAccount.Industry = 'test';
                testAccount.External_ID__c = 'test';
                testAccount.Market_Segment__c = 'LG';
                testAccount.Effective_Date__c = system.today().addYears(1);
                testAccount.Open_Enrollment_Date__c = system.today().addYears(-2);
                testAccount.HCSC_Client_Since__c = system.today().addYears(-4);
                testAccount.Contract_End__c = system.today().addYears(2);
                testAccount.Open_Enrollment_End_Date__c = system.today().addYears(3);
                testAccount.Total_Num_of_Potential_Subscribers__c = 10;
                testAccount.Active_Health_Subscribers__c = 8;
                update testAccount;

                /*** SFDC-5801 create producer account ***/ 
				Account prodAccount = TestClassUtiltity.CreateAccountRecord('Test Account 2');
				prodAccount.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();
				update prodAccount;
                
                list<AccountTeamMember> accountTeamMembers = TestClassUtiltity.createAccountTeamMembersRecords(testAccount.Id,testUser.Id);
                accountTeamMembers[0].TeamMemberRole = 'Consultant';
                upsert accountTeamMembers[0];

                /*** SFDC-5801 create account framework ***/
                Account_Framework__c afw = new Account_Framework__c();
                afw.Account__c = testAccount.Id;
				insert afw;

                List<Lightning_Prospecting_Profiles__c> pProfiles = new List<Lightning_Prospecting_Profiles__c>();
                Lightning_Prospecting_Profiles__c pProfiles1 = new Lightning_Prospecting_Profiles__c();            
                pProfiles1.Name = 'System Administrator';       
                pProfiles.add(pProfiles1);
                insert pProfiles;
                
                List<Lightning_Prospecting_Pilot_Names__c> pNames = new List<Lightning_Prospecting_Pilot_Names__c>();
                Lightning_Prospecting_Pilot_Names__c pNames1 = new Lightning_Prospecting_Pilot_Names__c();            
                pNames1.Name = 'testtestUser';       
                pNames.add(pNames1);
                insert pNames;
                
                test.startTest();
                ApexPages.StandardController sc = new ApexPages.StandardController(testAccount);
                ApexPages.currentPage().getParameters().put('id',testAccount.Id);
                GroupAccount360Controller tempExtension = new GroupAccount360Controller(sc);
                tempExtension.getPieData();
                tempExtension.nextActivityDate = null;
                tempExtension.lastActivityDate = null;
                tempExtension.strategyPlanId = null;
                tempExtension.openActivitiesReportObj = new Report();
                tempExtension.pastDueActivitiesReportObj = new Report();
                tempExtension.openCasesByPriorityReportObj = new Report();
                tempExtension.LastrenewalOppId = null;
                system.assertEquals(accountTeamMembers.size(),1);
                test.stopTest();
                
            }catch(Exception e){
                throw e;
            }
        }
    }
    
    /*** SFDC-5801 add myUnitTest2() ***/
    static testMethod void myUnitTest2() {

        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User testUser = TestClassUtiltity.CreateUserRecord(p.Id, 'testlgnadev@user.com', 'testUser', 'test@user.com');
        System.runAs(testUser) {        
            try{
                //create account
                Account testAccount = TestClassUtiltity.CreateAccountRecord('Test Account 1');
                /*** start SFDC-5801 ***/
                testAccount.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
                /*** end SFDC-5801 ***/
                testAccount.ShippingStreet = 'test';
                testAccount.ShippingCity = 'test';
                testAccount.ShippingState = 'TX';
                //testAccount.ShippingCountry= 'United States';
                testAccount.ShippingPostalCode = '1002';
                testAccount.Website = 'test.com';
                testAccount.Industry = 'test';
                testAccount.External_ID__c = 'test';
                testAccount.Market_Segment__c = 'LG';
                testAccount.Effective_Date__c = system.today().addYears(1);
                testAccount.Open_Enrollment_Date__c = system.today().addYears(-2);
                testAccount.HCSC_Client_Since__c = system.today().addYears(-4);
                testAccount.Contract_End__c = system.today().addYears(2);
                testAccount.Open_Enrollment_End_Date__c = system.today().addYears(3);
                testAccount.Total_Num_of_Potential_Subscribers__c = 10;
                testAccount.Active_Health_Subscribers__c = 8;
                update testAccount;
                
                /*** SFDC-5801 create opportunity ***/
            	list<Opportunity> opps = TestClassUtiltity.CreateOpportunities(testAccount.Id);
            	opps[0].Requested_Effective_Date__c = date.today() + 5;
				opps[0].recordtypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
                opps[0].stageName = 'Expected In';
				upsert opps[0];  
                opps[0].stageName = 'Won';
                opps[0].Primary_Closed_Reason__c = 'Other';
                opps[0].Date_Closed__c = system.today();
				upsert opps[0];  

                list<AccountTeamMember> accountTeamMembers = TestClassUtiltity.createAccountTeamMembersRecords(testAccount.Id,testUser.Id);
                accountTeamMembers[0].TeamMemberRole = 'Consultant';
                upsert accountTeamMembers[0];
               
                test.startTest();
                ApexPages.StandardController sc = new ApexPages.StandardController(testAccount);
                ApexPages.currentPage().getParameters().put('id',testAccount.Id);
                GroupAccount360Controller tempExtension = new GroupAccount360Controller(sc);
                tempExtension.getPieData();
                tempExtension.nextActivityDate = null;
                tempExtension.lastActivityDate = null;
                tempExtension.strategyPlanId = null;
                tempExtension.openActivitiesReportObj = new Report();
                tempExtension.pastDueActivitiesReportObj = new Report();
                tempExtension.openCasesByPriorityReportObj = new Report();
                tempExtension.LastrenewalOppId = null;
                system.assertEquals(accountTeamMembers.size(),1);
                test.stopTest();
                
            }catch(Exception e){
                throw e;
            }
        }
    }    
    
    /*** SFDC-5801 add myUnitTest3() ***/
    static testMethod void myUnitTest3() {

        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User testUser = TestClassUtiltity.CreateUserRecord(p.Id, 'testlgnadev@user.com', 'testUser', 'test@user.com');
        System.runAs(testUser) {        
            try{
                //create account
                Account testAccount = TestClassUtiltity.CreateAccountRecord('Test Account 1');
                /*** start SFDC-5801 ***/
                testAccount.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
                /*** end SFDC-5801 ***/
                testAccount.ShippingStreet = 'test';
                testAccount.ShippingCity = 'test';
                testAccount.ShippingState = 'TX';
                //testAccount.ShippingCountry= 'United States';
                testAccount.ShippingPostalCode = '1002';
                testAccount.Website = 'test.com';
                testAccount.Industry = 'test';
                testAccount.External_ID__c = 'test';
                testAccount.Market_Segment__c = 'LG';
                testAccount.Effective_Date__c = system.today().addYears(1);
                testAccount.Open_Enrollment_Date__c = system.today().addYears(-2);
                testAccount.HCSC_Client_Since__c = system.today().addYears(-4);
                testAccount.Contract_End__c = system.today().addYears(2);
                testAccount.Open_Enrollment_End_Date__c = system.today().addYears(3);
                testAccount.Total_Num_of_Potential_Subscribers__c = 10;
                testAccount.Active_Health_Subscribers__c = 8;
                update testAccount;

                /*** SFDC-5801 create producer account ***/
                Account prodAccount = TestClassUtiltity.CreateAccountRecord('Test Account 2');
				prodAccount.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();
				update prodAccount;

                list<AccountTeamMember> accountTeamMembers = TestClassUtiltity.createAccountTeamMembersRecords(testAccount.Id,testUser.Id);
                accountTeamMembers[0].TeamMemberRole = 'Consultant';
                upsert accountTeamMembers[0];
                
                /*** SFDC-5801 create strategic plan ***/
				Strategic_Plan__c stPlan = new Strategic_Plan__c();
				stPlan.Account_Name__c = testAccount.id;
				stPlan.Active__c = true;
				stPlan.Effective_Date__c = system.today();
				insert stPlan;

                /*** SFDC-5801 create producer group association ***/
				Producer_Group_Association__c pga = new Producer_Group_Association__c();
				pga.Producer_Account__c = prodAccount.id;
				pga.Group_Account__c = testAccount.id;
				insert pga;

                /*** SFDC-5801 create non-salesforce account team ***/              
                Account_Team_Non_SF__c att = new Account_Team_Non_SF__c();
                att.Member_Role__c = 'Consultant';
                att.Account_Name__c = testAccount.Id;
                att.Team_Member_Name__c = null;
                insert att;

                /*** SFDC-5801 create account 360 team ***/               
				Team_Member_360Views__c tm360 = new Team_Member_360Views__c();
                tm360.Name = 'test record';
				tm360.Team_Role_Name__c = 'Consultant';
				tm360.Sort_Order__c = 1;
				tm360.Account_Record_Types__c = 'Group_Account';
                insert tm360;
                
                List<Lightning_Prospecting_Profiles__c> pProfiles = new List<Lightning_Prospecting_Profiles__c>();
                Lightning_Prospecting_Profiles__c pProfiles1 = new Lightning_Prospecting_Profiles__c();            
                pProfiles1.Name = 'System Administrator';       
                pProfiles.add(pProfiles1);
                insert pProfiles;
              
                test.startTest();
                ApexPages.StandardController sc = new ApexPages.StandardController(testAccount);
                ApexPages.currentPage().getParameters().put('id',testAccount.Id);
                GroupAccount360Controller tempExtension = new GroupAccount360Controller(sc);
                tempExtension.getPieData();
                tempExtension.nextActivityDate = null;
                tempExtension.lastActivityDate = null;
                tempExtension.strategyPlanId = null;
                tempExtension.openActivitiesReportObj = new Report();
                tempExtension.pastDueActivitiesReportObj = new Report();
                tempExtension.openCasesByPriorityReportObj = new Report();
                tempExtension.LastrenewalOppId = null;
                system.assertEquals(accountTeamMembers.size(),1);
                test.stopTest();
                
            }catch(Exception e){
                throw e;
            }
        }
    }    
}