src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Case__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Maintanance Related picklist values</description>
    <label>Maintanance Type</label>
</CustomObject>

objects/GEMS_BA_Category_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>BA Category Assignments</relationshipLabel>
        <relationshipName>BA_Category_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>GEMS BA Category Association</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS BA Category Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Benefit_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>BA_Fund_Type__c</fullName>
        <label>BA Fund Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>BASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>GEMS Benefit Agreement</label>
    <nameField>
        <label>BA No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Benefit Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Cat_Char_Value_Association__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>GEMS_Category_Characteristic_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GEMS Cat Char Value Association</label>
    <nameField>
        <label>Category Characteristic Association</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Cat Char Value Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Category__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>GEMS_Categories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Cobra_Code__c</fullName>
        <label>Category Cobra Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>MC</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Usage_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Usage - Billing</label>
        <type>Checkbox</type>
    </fields>
    <label>GEMS Category</label>
    <nameField>
        <label>Category No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Characteristic__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Characteristics</relationshipLabel>
        <relationshipName>GEMS_Characteristics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>GEMS Characteristic</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Characteristic No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GEMS Characteristics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GEMS_Characteristic_Value__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>GEMS Characteristic Values</relationshipLabel>
        <relationshipName>GEMS_Characteristic_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Characteristic__c</fullName>
        <label>Characteristic</label>
        <referenceTo>GEMS_Characteristic__c</referenceTo>
        <relationshipLabel>GEMS Characteristic Values</relationshipLabel>
        <relationshipName>GEMS_Characteristic_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Value Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>GEMS Characteristic Value</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Characteristic Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>This field is used to capture the date when the opportunity is won or lost.</description>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Closed_Reason__c</fullName>
        <description>This field is used to capture the primary reason why an Opportunity is won, lost or declined.</description>
        <label>Primary Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absorbed by Parent Group</fullName>
                </value>
                <value>
                    <fullName>Change of Ownership</fullName>
                </value>
                <value>
                    <fullName>Consol. Covg with 1 Carrier</fullName>
                </value>
                <value>
                    <fullName>Headquarters Relocated</fullName>
                </value>
                <value>
                    <fullName>Lack of Narrow Network</fullName>
                </value>
                <value>
                    <fullName>Market Check by Group</fullName>
                </value>
                <value>
                    <fullName>Organizational Changes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Guarantees</fullName>
                </value>
                <value>
                    <fullName>Plan Design-Other</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Purchase by Another Company</fullName>
                </value>
                <value>
                    <fullName>Rates-Aggregate Stop Loss-Claim/Attch Factor</fullName>
                </value>
                <value>
                    <fullName>Rates-Incumbent Reduced</fullName>
                </value>
                <value>
                    <fullName>Rates-Individual Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Rates-Insured</fullName>
                </value>
                <value>
                    <fullName>Repricing</fullName>
                </value>
                <value>
                    <fullName>Reputation of Selected Carrier</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Broker Relationship</fullName>
                </value>
                <value>
                    <fullName>Changed Brokers</fullName>
                </value>
                <value>
                    <fullName>Network Discounts</fullName>
                </value>
                <value>
                    <fullName>Network Disruption</fullName>
                </value>
                <value>
                    <fullName>Product Packaging</fullName>
                </value>
                <value>
                    <fullName>Did Not Want to Disrupt Ees</fullName>
                </value>
                <value>
                    <fullName>Not Enough Diff. to Change</fullName>
                </value>
                <value>
                    <fullName>PUG Did not meet participation</fullName>
                </value>
                <value>
                    <fullName>Rates-Admin. Charge too High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Captures product category</description>
        <inlineHelpText>required field for plans to flow correctly on BA to BlueSTAR</inlineHelpText>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BCC</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Disease Management</fullName>
                </value>
                <value>
                    <fullName>EPO</fullName>
                </value>
                <value>
                    <fullName>Group Govt</fullName>
                </value>
                <value>
                    <fullName>HCA</fullName>
                </value>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>IHI</fullName>
                </value>
                <value>
                    <fullName>Nurseline</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
                <value>
                    <fullName>Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Dearborn</fullName>
                </value>
                <value>
                    <fullName>Health Advocacy Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GEMS_AssociateCatBAControllerTest.cls
/**************************************************************************************
  Apex Class Name     : GEMS_AssociateCatBAControllerTest 
  Version             : 1.0
  Function            : This class is serves as Unit Test Class for GEMS_AssociateBACatController 
  Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
*   Siva             06/16/2016                Original Version
*************************************************************************************/
@isTest
public class GEMS_AssociateCatBAControllerTest {

private static testmethod void GEMS_AssociateCatBAController()
 {

  Integer SizeOflist=1;
  Profile profileRec = [SELECT Id FROM Profile WHERE Name='System Administrator'];
  User testUser = TestClassUtiltity.CreateUserRecord(profileRec.Id, 'test@user11.com', 'testUser', 'test@user.com'); 
    
    
        Account acc = GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        System.assertEquals('BenefitAgreementControllerTest',acc.Name);
        
        
       /* Opportunity oppty= GEMS_UtilityClassTest.insertionOpp1(acc.Id);
        oppty.StageName='Won';
        oppty.Date_Closed__c = system.today();
        oppty.Primary_Closed_Reason__c='Other';
        insert oppty;
        System.assertEquals('BenefitAgreementControllerTest',oppty.name);*/
        
        product2 productRec1=GEMS_UtilityClassTest.insertionProduct1();
        insert productRec1;
        System.assertEquals('HSA',productRec1.Product_Category__c);
        
        
        Case caseobj = GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        caseobj.GEMS_Submission_Type__c = 'Renewal';
        caseobj.accountid= acc.id;
        insert caseobj;
        
        GEMS_Benefit_Agreement__c  benefit=GEMS_UtilityClassTest.insertionBenefitAgg(acc.Id,caseobj.Id,productRec1.Id);
        insert benefit;
        System.assertEquals('ACAP',benefit.BA_Fund_Type__c);
        List<GEMS_Benefit_Agreement__c> gemsben = new List<GEMS_Benefit_Agreement__c>();
        gemsben.add(benefit);
        
        GEMS_Category__c   gemscat1=GEMS_UtilityClassTest.insertiongemscat1(acc.Id,caseobj.Id);
        gemscat1.Usage_Billing__c = true;
        insert gemscat1;
        
   
        System.assertEquals('CO',gemscat1.Category_Cobra_Code__c);
        
        List<GEMS_Category__c> gemsCatList = new List<GEMS_Category__c>();
        gemsCatList.add(gemscat1);
       
     
      
        
        
        GEMS_BA_Category_Assignment__c  bacateg=GEMS_UtilityClassTest.insertionBACategory(acc.Id,caseobj.Id,benefit.Id,gemscat1.Id);
      
        insert bacateg;
       
      
        
        GEMS_Characteristic__c gemscha =GEMS_UtilityClassTest.insertionCharacteristic(acc.Id, caseobj.Id);
        insert gemscha;
        
        List<GEMS_Characteristic__c> gemsListChart = new List<GEMS_Characteristic__c>();
        gemsListChart.add(gemscha);
        
        GEMS_Characteristic_Value__c value = new GEMS_Characteristic_Value__c();
            value.Case__c=caseobj.Id;
    value.Characteristic__c=gemscha.Id;
     value.Code__c='ABS';
     value.Effective_Date__c = Date.Today().addDays(8);
        insert value;
        
        GEMS_Cat_Char_Value_Association__c associate =GEMS_UtilityClassTest.insertionAssociate(caseobj.Id,acc.Id,value.Id,gemscat1.Id);
        insert associate ;
        //System.assertEquals('CO',associate.Category_Cobra_Code__c);
        
        
       system.runAs(testUser){ 
     Test.setCurrentPage(Page.GEMSAssignBACat);
      
     List<Case> caseList = new List<case>();
     caseList.add(caseobj);
     ApexPages.currentpage().getParameters().put('recs',benefit.Id);
        ApexPages.StandardSetController std = new ApexPages.StandardSetController(caseList);
       GEMS_AssociateBACatController contr= new GEMS_AssociateBACatController(std); 
       Map<Id, GEMS_Category__c> catIdCat = new Map<Id, GEMS_Category__c>();
       catIdCat.put(gemscat1.Id, gemscat1);
       contr.mapOfIdAndCat=catIdCat;
       List<Integer> intList;
       contr.iter = new List<Integer>();
       List<Integer> intList1 = contr.iter;
       contr.listOfBAs =gemsben;
       contr.listOfChars=gemsListChart;
       contr.sizeOfList=4;
       contr.removeCat();
       contr.assignCat();
       contr.getTheUpdatedMembersCount();
       contr.addCat();
       contr.numberOfRowToRemove=1;
       contr.recordToDelete=gemscat1.id;
       contr.removeRow();
       contr.gotoCreateAccountStructure();
       contr.gotoCase();
        contr.getOptions();
        contr.rowCount='ABS';
           //     contr.recordToDelete='1234';
        contr.numberOfRowToRemove=2;
        
        contr.hasEditAccess=true;
        
        contr.selectedCat=gemsCatList;
        List<List<SelectOption>> sdf = contr.listOfOptions;
    }
    



    }
    }