src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <recordTypes>
        <fullName>Group_Account</fullName>
        <active>true</active>
        <description>Account record type for Group / Sold Accounts</description>
        <label>Group Account</label>
    </recordTypes>

objects/Competitor_Relationship__c.object
<CustomObject>
    <description>Competitors related to a Group Account as Carriers and to an Opportunity as Incumbent/ Won / Competing</description>
    <fields>
        <fullName>Group_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Group Account related to the Competitor Relationship for Carrier Information</description>
        <label>Group Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <errorMessage>Please select Prospect or Group or Prospect (Non BlueSTAR) or Group (Non BlueSTAR) account</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Prospect_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Prospect_Non_BlueSTAR</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Group_Account_Non_BlueSTAR</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Competitor_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Competitor Relationship</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Competitors / 3rd Party Vendors</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Relationship ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors / 3rd Party Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProspectingAppCompVendListCtrlTest.cls
@isTest
private class ProspectingAppCompVendListCtrlTest {
	@testSetup
    static void setupData() {
        Account groupAcc = new Account();
        groupAcc.Name = 'Group Account';
        groupAcc.RecordTypeId = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName='Group_Account' LIMIT 1].Id;
        insert groupAcc;
        
        List<Competitor_Relationship__c> compRels = new List<Competitor_Relationship__c>();
        Competitor_Relationship__c compRelOne = new Competitor_Relationship__c();
        compRelOne.Group_Account__c = groupAcc.Id;
        compRelOne.Status__c = 'Active';
        compRels.add(compRelOne);
        Competitor_Relationship__c compRelTwo = new Competitor_Relationship__c();
        compRelTwo.Group_Account__c = groupAcc.Id;
        compRelTwo.Status__c = 'Active';
        compRels.add(compRelTwo);
        insert compRels;
    }
    
    static testMethod void validateQueryAccountCompetitorsAndVendorsList() {
        Account groupAcc = [SELECT Id FROM Account WHERE Name='Group Account'];
        
        List<Competitor_Relationship__c>  compRels = ProspectingAppCompVendListController.queryAccountCompetitorsAndVendorsList(groupAcc);
        System.assertEquals(2, compRels.size());
    }
    
    static testMethod void validateQueryCompetitorInfo() {
        Account groupAcc = [SELECT Id FROM Account WHERE Name='Group Account'];
        
        List<Competitor_Relationship__c> compRels = new List<Competitor_Relationship__c>();
        
        compRels = [SELECT Id, Group_Account__c FROM Competitor_Relationship__c WHERE Group_Account__r.Id = :groupAcc.Id];
        
        for (Competitor_Relationship__c aCompetitor : compRels){
                    Competitor_Relationship__c FunctionReturned = ProspectingAppCompVendListController.getExistingCompetitorDetails(aCompetitor.id);
                    System.assertEquals(aCompetitor.Group_Account__c, groupAcc.Id);
           
        }

        
    }
    
    
}