src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>This field is used to capture the list of group numbers received during the account number reservations. Will be a semicolon separated list of values.</description>
        <label>Group Number</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Case__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Maintanance Related picklist values</description>
    <label>Maintanance Type</label>
</CustomObject>

objects/GEMS_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Attachment__c</fullName>
        <label>Attachment</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>GEMS  Attachments</relationshipLabel>
        <relationshipName>GEMS_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABS</fullName>
                </value>
                <value>
                    <fullName>ACA CALCULATORS</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT CHANGE REQUEST FORM</fullName>
                </value>
                <value>
                    <fullName>ACCOUNT STRUCTURE</fullName>
                </value>
                <value>
                    <fullName>ACH/WIRE FORM</fullName>
                </value>
                <value>
                    <fullName>ADDENDUM TO BPA FOR AFFILIATES</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRATIVE SERVICE AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO AGREEMENT</fullName>
                </value>
                <value>
                    <fullName>ASO BENEFIT PROG APP (BPA)</fullName>
                </value>
                <value>
                    <fullName>ASO MANDATE CHECKLIST</fullName>
                </value>
                <value>
                    <fullName>BENEFIT ADHOC MEETING MINUTES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT BOOKLETS / CERTIFICATES</fullName>
                </value>
                <value>
                    <fullName>BENEFIT EDIT TOOL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT MATRIX</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROG DESCRIPTION-DENTAL</fullName>
                </value>
                <value>
                    <fullName>BENEFIT PROGRAM DESCRIPTION-BPD</fullName>
                </value>
                <value>
                    <fullName>BENEFIT WALLET DISCOVERY FORM</fullName>
                </value>
                <value>
                    <fullName>BINDER CHECK</fullName>
                </value>
                <value>
                    <fullName>BPA - ASO SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - ASO UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - DENTAL SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - DENTAL UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HCA SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HCA UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HEALTH SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - HEALTH UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - SIGNED</fullName>
                </value>
                <value>
                    <fullName>BPA - UNSIGNED</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>BROKER TRANS/AOR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GEMS Attachments</label>
    <nameField>
        <label>Attachment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS  Attachments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/GEMS_AccountScreeningCaseCreation_Test.cls
/**************************************************************************************
  Apex Class Name     : GEMS_AccountScreeningCaseCreation_Test 
  Version             : 1.0
  Function            : This class is serves as Unit Test Class for GEMS_AccountScreeningCaseCreation
  Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------------                 
*   Siva                    06/22/2016                Original Version
*************************************************************************************/
@isTest
public class GEMS_AccountScreeningCaseCreation_Test {
    private static testmethod void AccountScreeningCaseCreation()
    {
      Account acc= GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        
        Account accRec=[SELECT ID, Name from Account where Name='BenefitAgreementControllerTest'];
        System.assertEquals('BenefitAgreementControllerTest',accRec.Name); 
        
        List<Case> caseList = New List<Case>();
        Case subRec= GEMS_UtilityClassTest.insertionCase('GEMS Account Submission');
        subRec.status = 'In Progress';
        subRec.Funding_Type_Multiselect__c = 'ACAP';
        subRec.GEMS_AEP_Account__c= true;
        caseList.add(subRec);
        insert caseList; 
        
        Id subCaserecordTypeId= Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS Account Submission').getRecordTypeId();
        
        Case subCaseRec = [Select id, recordtype.id from case where recordtypeid=:subCaserecordTypeId];
        System.assertEquals(subCaserecordTypeId,subCaseRec.recordtype.id);
        test.startTest();
        CaseTeamMember caseTeamAccSpecMem = GEMS_UtilityClassTest.insertionCaseTeam(subCaseRec.Id,'Account Specialist');
        insert caseTeamAccSpecMem;
        System.assertEquals(subCaseRec.Id,caseTeamAccSpecMem.ParentId );
        
        GEMS_Attachment__c gemsAttach11 = new GEMS_Attachment__c();
        gemsAttach11.type__c='SIGNED BPA';
        gemsAttach11.Attachment__c = 'ts';
        gemsAttach11.case__c=subCaseRec.Id;
        insert gemsAttach11;
        
        Case strRec= GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        strRec.GEMS_Account_Submission_Info__c  = subCaseRec.Id;
        strRec.accountId = acc.Id;
        strRec.Status = 'Design In Progress';
        insert strRec;

        
        Id accStrRecordTypeId= Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS Account Structure').getRecordTypeId();
        Case strCaseRec=[SELECT Id, GEMS_Account_Submission_Info__c, status, RecordTypeId from Case 
                         where RecordTypeId=:accStrRecordTypeId and GEMS_Account_Submission_Info__c =: subCaseRec.Id ];
        System.assertEquals('Design In Progress',strCaseRec.status);
        
       
        GEMS_AccountScreeningCaseCreation.screeningCasesCreation(caseList,True);
        
        test.stopTest();  
    }
    
    
    private static testmethod void AccountScreeningCaseCreation2()
    {
      Account acc= GEMS_UtilityClassTest.insertionAccount();
        insert acc;
        
        Account accRec=[SELECT ID, Name from Account where Name='BenefitAgreementControllerTest'];
        System.assertEquals('BenefitAgreementControllerTest',accRec.Name); 
        
        List<Case> caseList = New List<Case>();
        Case subRec= GEMS_UtilityClassTest.insertionCase('GEMS Account Submission');
        subRec.status = 'In Progress';
        subRec.Funding_Type_Multiselect__c = 'ACAP';
        subRec.GEMS_AEP_Account__c= true;
        subRec.GEMS_Submission_Type__c= 'New';
        subRec.GEMS_StdCust_Product__c= 'Custom Products only';
        caseList.add(subRec);
        insert caseList; 
        
        Id subCaserecordTypeId= Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS Account Submission').getRecordTypeId();
        
        Case subCaseRec = [Select id, recordtype.id from case where recordtypeid=:subCaserecordTypeId];
        System.assertEquals(subCaserecordTypeId,subCaseRec.recordtype.id);
        test.startTest();
        CaseTeamMember caseTeamAccSpecMem = GEMS_UtilityClassTest.insertionCaseTeam(subCaseRec.Id,'Account Specialist');
        insert caseTeamAccSpecMem;
        System.assertEquals(subCaseRec.Id,caseTeamAccSpecMem.ParentId );
        
        GEMS_Attachment__c gemsAttach11 = new GEMS_Attachment__c();
        gemsAttach11.type__c='SIGNED BPA';
        gemsAttach11.Attachment__c = 'ts';
        gemsAttach11.case__c=subCaseRec.Id;
        insert gemsAttach11;
        
        Case strRec= GEMS_UtilityClassTest.insertionCase('GEMS Account Structure');
        strRec.GEMS_Account_Submission_Info__c  = subCaseRec.Id;
        strRec.accountId = acc.Id;
        strRec.Status = 'Design In Progress';
        insert strRec;

        
        Id accStrRecordTypeId= Schema.SObjectType.Case.getRecordTypeInfosByName().get('GEMS Account Structure').getRecordTypeId();
        Case strCaseRec=[SELECT Id, GEMS_Account_Submission_Info__c, status, RecordTypeId from Case 
                         where RecordTypeId=:accStrRecordTypeId and GEMS_Account_Submission_Info__c =: subCaseRec.Id ];
        System.assertEquals('Design In Progress',strCaseRec.status);
        
       
        GEMS_AccountScreeningCaseCreation.screeningCasesCreation(caseList,true);
        
        test.stopTest();  
    }
    
    private static testmethod void testCreateAccountMaintenanceDownstreamCases(){
    	Account accRec;
        accRec = new Account();
        accRec.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        accRec.Name = 'TestAccountForCaseTriggerHandler';
        accRec.Group_Number__c= 'B06093';
        accRec.external_id__c= 'B06093';
        accRec.BillingStreet ='Testing';
        accRec.BillingCity='TX';
        accRec.BillingState='CT';
        accRec.BillingPostalCode='534323';
        accRec.status__c = 'Active';
        accRec.AccountNumber = '012456';
        insert accRec;
        
        Entitlement en = new Entitlement();
        en.name='GEMS Process Entitlement';
        en.accountid = accRec.id;
        en.startdate = system.today();
        en.enddate = system.today();
        insert en;
        
        Profile profileRec = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User testUser1 = GEMS_UtilityClassTest.CreateUserRecord(profileRec.Id, 'test1@user11.com', 'testUser1', 'test1@user.com');
        insert testUser1;
        
        AccountTeamMember accTeamMemberAccSpecialist = new AccountTeamMember ();
        accTeamMemberAccSpecialist.UserId =testUser1.id;
        accTeamMemberAccSpecialist.TeamMemberRole = 'Account Specialist';
        accTeamMemberAccSpecialist.AccountId =accRec.id;
        insert accTeamMemberAccSpecialist;
        
        Id caseAccountSubmissionId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Account Maintenance').getRecordTypeId();
        case cs = new case();
        cs.accountid = accRec.Id;
        cs.recordtypeid = caseAccountSubmissionId;
        cs.status = 'New';
        cs.GEMS_Case_Effective_Date__c = system.today();
        insert cs;
        Set<ID> strucMainCaseIds = new Set<Id>(); 
        List<string> TypeofDownStCases=new List<string>(); 
        
        TypeofDownStCases.add('GEMS Account Setup');
        strucMainCaseIds.add(cs.id);
        GEMS_AccountScreeningCaseCreation.CreateAccountMaintenanceDownstreamCases(strucMainCaseIds,TypeofDownStCases,'BlueSTAR Entry Complete');

    }

}