src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Callout_Configuration__mdt.object
<CustomObject>
    <label>Callout Configuration</label>
    <pluralLabel>Callout Configurations</pluralLabel>
</CustomObject>

objects/Complexity_Score_Fields__mdt.object
<CustomObject>
    <description>Metadata type used to store the Account fields that are used to calculate the Account Complexity Score.</description>
    <label>Complexity Score Field</label>
    <pluralLabel>Complexity Score Fields</pluralLabel>
</CustomObject>

objects/CP_Completion_Rate_Fields__mdt.object
<CustomObject>
    <description>Contains the field api name and point values for the client profile completion rate calculation engine.</description>
    <label>CP Completion Rate Field</label>
    <pluralLabel>CP Completion Rate Fields</pluralLabel>
</CustomObject>

classes/CustomMetadataTypeDAOTest.cls
/**************************************************************************************
  Apex Class Name     : CustomMetadataTypeTest
  Version             : 1.0
  Function            : This is a test class for CustomMetadataType.
  Modification Log    :
* Developer					Date
* ----------------------------------------------------------------------------
* Sana Fatima			6/3/2016
*************************************************************************************/
@isTest
public class CustomMetadataTypeDAOTest { 

	@isTest static void getClientProfileCompletionRateFieldsTest() {
		CustomMetadataTypeDAO.ICustomMetadataTypeDAO customMetadataTypeDAOInstance = new CustomMetadataTypeDAO(); 
		List<CP_Completion_Rate_Fields__mdt> rateFields = customMetadataTypeDAOInstance.getClientProfileCompletionRateFields();
		System.assert( !rateFields.isEmpty() );
	}

	@isTest static void getComplexityScoreFieldsTest() {
		CustomMetadataTypeDAO.ICustomMetadataTypeDAO customMetadataTypeDAOInstance = new CustomMetadataTypeDAO(); 
		List<Complexity_Score_Fields__mdt> complexityScoreFields = customMetadataTypeDAOInstance.getComplexityScoreFields();
		System.assert( !complexityScoreFields.isEmpty() );
	}
	@isTest static void getCustomMetadaTypeDynamicallyTest(){
		CustomMetadataTypeDAO.ICustomMetadataTypeDAO customMetadataTypeDAOInstance = new CustomMetadataTypeDAO();
		Account a = new Account();
		a.Name = 'Slalom Test Account';
		a.HCSC_Division__c = 'IL';
		insert a;
	    Account dynamicMetaData =(Account)customMetadataTypeDAOInstance.getCustomMetadaTypeDynamically('SELECT Id,Name FROM Account');

	    System.assertEquals('Slalom Test Account',dynamicMetaData.Name);
	}
	@isTest static void getCustomDataTypeByNameTest(){
		CustomMetadataTypeDAO.ICustomMetadataTypeDAO customMetadataTypeDAOInstance = new CustomMetadataTypeDAO();
	    List<Callout_Configuration__mdt> metaDataTypeNameList = new List<Callout_Configuration__mdt>();
	    metaDataTypeNameList.add(customMetadataTypeDAOInstance.getCustomMetadaTypeByName('BlueSTAR_Meab139_TEST'));
	    System.assert(!metaDataTypeNameList.isEmpty());

	}

}