src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>EIN__c</fullName>
        <description>This field is used to capture the Group Tax ID Number or Employer Identification Number of the Account.</description>
        <label>EIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the account associated to the contact.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>

objects/Contact.object
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if the contact is the primary Producer or Consultant contact for the associated account.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>

objects/EIN__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>EIN</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bluestar_Transfer_Status__c</fullName>
        <label>Bluestar Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Due for Transfer</fullName>
                    <default>true</default>
                    <label>Due for Transfer</label>
                </value>
                <value>
                    <fullName>Transfer In Transit</fullName>
                </value>
                <value>
                    <fullName>Transfer Complete</fullName>
                </value>
                <value>
                    <fullName>Seq# Requested</fullName>
                </value>
                <value>
                    <fullName>Seq# updated</fullName>
                </value>
                <value>
                    <fullName>Wait BS Confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Change_Reason__c</fullName>
        <label>Change Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ADD</fullName>
                    <default>true</default>
                    <label>ADD</label>
                </value>
                <value>
                    <fullName>CHG</fullName>
                </value>
                <value>
                    <fullName>END</fullName>
                </value>
                <value>
                    <fullName>ERR</fullName>
                </value>
                <value>
                    <fullName>NONE</fullName>
                </value>
                <value>
                    <fullName>ENDSENT</fullName>
                </value>
                <value>
                    <fullName>null</fullName>
                    <isActive>false</isActive>
                    <label>null</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EIN_Sequence_Number__c</fullName>
        <label>BlueStar EIN Sequence Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Setting any EIN as Primary will clear any other EIN which is already set as Primary for that Account.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Employer Identification Number</label>
    <nameField>
        <label>Employer Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employer Identification Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>GEMS Address</label>
    <nameField>
        <label>Street</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LGNA_EIN_ConfirmControllerApx.cls
/**************************************************************************************
* Apex Class Name     : LGNA_EIN_ConfirmControllerApx 
* Version             : 1.0
* Function            : This is server side controller for EIN confirmation component.
* Modification Log    :
* Developer           Date                   Description
* ----------------------------------------------------------------------------                 
* Bharath            04/12/2018             Original Version
*************************************************************************************/
public class LGNA_EIN_ConfirmControllerApx {
    
    /******************************************************************** 
*    Method Name : returnEIN
*   @description : This method returns the list of EINs which are ready for transmission to BlueStar.
*   @parameters  : Account ID
*   @return type :   List<EIN__c> 
*   @Author      : Bharath
***************************************************************/       
    @AuraEnabled
    public static list<EIN__c> returnEIN(id Accid){
        if(Accid <> null){
            //Retrieve the list of EINs which are ready for transmission to BlueStar.
            ////Bharath0626
            /*List<EIN__c> sendReady = [select id, name, location_name__c, effective_date__c, end_date__c, gems_address__c, EIN_Sequence_Number__c, primary__c, change_reason__c,
                    Bluestar_Transfer_Status__c from EIN__c where Account__c =: Accid and change_reason__c != null and change_reason__c != 'ENDSENT' 
                    and Bluestar_Transfer_Status__c = 'Due for Transfer'];*/
            List<EIN__c> sendReady = [select id, name, location_name__c, effective_date__c, end_date__c, EIN_Sequence_Number__c, primary__c, change_reason__c,
                    Bluestar_Transfer_Status__c from EIN__c where Account__c =: Accid and change_reason__c != null and change_reason__c != 'ENDSENT' 
                    and Bluestar_Transfer_Status__c = 'Due for Transfer'];
            //Retrieve the records which are stuck in retrieving sequence number status for more than an hour and make them available for transmission.
            DateTime timeCheck = system.now().addHours(-2);
            ////Bharath0626
            /*List<EIN__c> stuckEINs = [select id, name, location_name__c, SystemModStamp, effective_date__c, end_date__c, gems_address__c, EIN_Sequence_Number__c, primary__c, change_reason__c,
                    Bluestar_Transfer_Status__c from EIN__c where Account__c =:Accid and (Bluestar_Transfer_Status__c = 'Seq# Requested' or Bluestar_Transfer_Status__c = 'Seq# updated'
                                                                                         or Bluestar_Transfer_Status__c = 'Wait BS Confirm') and SystemModStamp < :timeCheck];*/
            List<EIN__c> stuckEINs = [select id, name, location_name__c, SystemModStamp, effective_date__c, end_date__c, EIN_Sequence_Number__c, primary__c, change_reason__c,
                    Bluestar_Transfer_Status__c from EIN__c where Account__c =:Accid and (Bluestar_Transfer_Status__c = 'Seq# Requested' or Bluestar_Transfer_Status__c = 'Seq# updated'
                                                                                         or Bluestar_Transfer_Status__c = 'Wait BS Confirm') and SystemModStamp < :timeCheck];            
			List<EIN__c> updateStuckEIN = new List<EIN__c>();
            for(EIN__c stuckEIN : stuckEINs){
                stuckEIN.Bluestar_Transfer_Status__c = 'Due for Transfer';
                updateStuckEIN.add(stuckEIN);
                sendReady.add(stuckEIN);
            }
            if(!updateStuckEIN.isEmpty()){
                //Update the stuck EINs so that they are ready for transmission to BlueStar again.
                upsert updateStuckEIN;
            }
            if(!sendReady.isEmpty()){
                return sendReady;
            } else {
                List<EIN__c> dummyrecs = new List<EIN__c>();
                return dummyrecs;
            }
        }
        else {
            List<EIN__c> dummyrecs1 = new List<EIN__c>();
            return dummyrecs1;
        }
    }
    
    /******************************************************************** 
*    Method Name : sentEIN
*   @description : This method returns the list of EINs which have been already updated to BlueStar.
*   @parameters  : Account ID
*   @return type :   List<EIN__c> 
*   @Author      : Bharath
***************************************************************/           
    @AuraEnabled
    public static list<EIN__c> sentEIN(id Accid){
        if(Accid <> null){
            //Retrieve the list of EINs already transmitted to BlueStar successfully.
            //////Bharath0626
            /*return [select id, name, location_name__c,lastmodifieddate, effective_date__c, end_date__c, gems_address__c, EIN_Sequence_Number__c, primary__c, change_reason__c 
                    from EIN__c where Account__c =: Accid and (change_reason__c = '' or change_reason__c = 'ENDSENT') and Bluestar_Transfer_Status__c != 'Transfer In Transit' and 
                   Bluestar_Transfer_Status__c != 'Seq# Requested' and Bluestar_Transfer_Status__c != 'Seq# updated' and Bluestar_Transfer_Status__c != 'Due for Transfer'
                   and Bluestar_Transfer_Status__c != 'Wait BS Confirm'];            */
            return [select id, name, location_name__c,lastmodifieddate, effective_date__c, end_date__c, EIN_Sequence_Number__c, primary__c, change_reason__c 
                    from EIN__c where Account__c =: Accid and (change_reason__c = '' or change_reason__c = 'ENDSENT') and Bluestar_Transfer_Status__c != 'Transfer In Transit' and 
                   Bluestar_Transfer_Status__c != 'Seq# Requested' and Bluestar_Transfer_Status__c != 'Seq# updated' and Bluestar_Transfer_Status__c != 'Due for Transfer'
                   and Bluestar_Transfer_Status__c != 'Wait BS Confirm'];                        
        }
        else {
            List<EIN__c> dummyrecs = new List<EIN__c>();
            return dummyrecs;
        }
    }
    
    /******************************************************************** 
*    Method Name : returnEIN
*   @description : This method will returns the list of EINs for which transmission has been initiated as future method and response is awaited.
*   @parameters  : Account ID
*   @return type :   List<EIN__c> 
*   @Author      : Bharath
***************************************************************/           
    @AuraEnabled
    public static list<EIN__c> sendProgress(id Accid){
        if(Accid <> null){
            ////Bharath0626
            /*return [select id, name, location_name__c, lastmodifieddate, effective_date__c, end_date__c, gems_address__c, EIN_Sequence_Number__c, primary__c, change_reason__c 
                    from EIN__c where Account__c =: Accid and change_reason__c != null and (Bluestar_Transfer_Status__c = 'Transfer In Transit' or Bluestar_Transfer_Status__c = 'Seq# Requested' 
                                                                                            or Bluestar_Transfer_Status__c = 'Seq# updated' or Bluestar_Transfer_Status__c = 'Wait BS Confirm')];*/
            return [select id, name, location_name__c, lastmodifieddate, effective_date__c, end_date__c,  EIN_Sequence_Number__c, primary__c, change_reason__c 
                    from EIN__c where Account__c =: Accid and change_reason__c != null and (Bluestar_Transfer_Status__c = 'Transfer In Transit' or Bluestar_Transfer_Status__c = 'Seq# Requested' 
                                                                                            or Bluestar_Transfer_Status__c = 'Seq# updated' or Bluestar_Transfer_Status__c = 'Wait BS Confirm')];            
        }
        else {
            List<EIN__c> dummyrecs = new List<EIN__c>();
            return dummyrecs;
        }
    }    
    
    /******************************************************************** 
*    Method Name : transmitEIN
*   @description : This method calls the process to transmit EIN to BlueStar. 
*   @parameters  : Account ID
*   @return type :   List<EIN__c> 
*   @Author      : Bharath
***************************************************************/           
    @AuraEnabled
    public static void transmitEIN(id Accid){
        list<id> idParam = new list<id>();
        idParam.add(Accid);
        //EINCHGSEND - Use the 1st query to send ADD, CHG and END EINs.
        List<EIN__c> readEINs = [select id,name,Bluestar_Transfer_Status__c,change_reason__c from EIN__c where Account__c =: Accid and change_reason__c != null and change_reason__c != 'ENDSENT'
                                 and Bluestar_Transfer_Status__c = 'Due for Transfer'];
        if (readEINs.isEmpty()) { return; }
        List<EIN__c> updateEINs = new List<EIN__c>();
        List<Id> EINReqList = new List<Id>();
        Boolean needEINRetrieveCall = false; 
        for(EIN__c einRecord : readEINs){
            // This field update is to track the EINs which are being transmitted. This update is done to avoid duplicate transmissions by user.
            einRecord.Bluestar_Transfer_Status__c = 'Transfer In Transit';
            
            EINReqList.add(einRecord.id); // moved out of changeReasonCd check because EIN list should have all the EINs for later status update
            
            // If there is at least 1 EIN with ERR/CHG change reason code, retrieve EIN list from B*
            if (einRecord.change_reason__c != 'ADD') {
                needEINRetrieveCall = true;
            } else {
                // Table EINs with 'ADD' for transmission
                updateEINs.add(einRecord);    
            }            
        }
        
        // Request Seq# for the EINs if any CHG or END or ERR records exists for transmission.
        if (needEINRetrieveCall){
            String response = LGNA_EIN_SendStart.fetchEIN(EINReqList, Accid);
            if (response == 'Success') {
                
                
            } else {
                if(!Test.isRunningTest()){
                    throw new AuraHandledException('Communication error occured while trying to transmit EIN to BlueStar. Please try after some time. If the issue persists, please contact System Administrator.');
                }
            }
        }
        // If there are only ADDs present in EIN list, bypass Seq# request and initiate transmission of EINs to BlueStar.
        else if(!updateEINs.isEmpty() && !needEINRetrieveCall){
            upsert updateEINs;
            //Following call initiates the transmission to BlueStar.
            LGNA_EIN_SendStart.sendEINInvocable(idParam);                    
        }
        
        
    }
    
}