src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Line_of_business__c</fullName>
        <label>Line of business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ENA,</fullName>
                    <label>ENA</label>
                </value>
                <value>
                    <fullName>Major National</fullName>
                </value>
                <value>
                    <fullName>Major National GET</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Municipal</fullName>
                </value>
                <value>
                    <fullName>SCP</fullName>
                </value>
                <value>
                    <fullName>Student Health</fullName>
                </value>
                <value>
                    <fullName>ENA GET</fullName>
                </value>
                <value>
                    <fullName>Large/Mid Market</fullName>
                </value>
                <value>
                    <fullName>Municipal GET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Benefit_Agreement__c.object
<CustomObject>
    <description>Benefit Agreement information offered to the employees for the Group Account will be stored using this object</description>
    <fields>
        <fullName>Benefit_Agreement_Number__c</fullName>
        <description>This field is used to capture the number of the Benefit Agreement as listed in BlueStar</description>
        <label>Benefit Agreement Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the date the Benefit Agreement was effective as listed in BlueStar</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the financial billing arrangement that an account designates for the Benefit Agreement.</description>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>This field is used to capture the date the Benefit Agreement will renew as listed in BlueStar</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <label>Benefit Agreement</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Benefit Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Effective_Date__c</fullName>
        <label>Rate Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rate_End_Date__c</fullName>
        <description>This field is used to capture the end of the contract for the opportunity products.</description>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity_BA_GS_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Benefit_Agreement__c</fullName>
        <description>Opportunity Benefit Agreement related to the  Opportunity group section Group Section</description>
        <label>Opportunity Benefit Agreement</label>
        <referenceTo>SGR_Opportunity_Benefit_Agreement__c</referenceTo>
        <relationshipLabel>Opportunity BA GS Assignments</relationshipLabel>
        <relationshipName>Opportunity_BA_GS_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunity_Group_Section__c</fullName>
        <description>Opportunity group section related to the assignment</description>
        <label>Opportunity Group Section</label>
        <referenceTo>SGR_Opportunity_Group_Section__c</referenceTo>
        <relationshipLabel>Opportunity BA GS Assignments</relationshipLabel>
        <relationshipName>Opportunity_BA_GS_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity BA GS Assignment</label>
    <nameField>
        <label>Opportunity BA GS Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity BA GS Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Benefit_Agreement__c.object
<CustomObject>
    <description>This object is connected to Opportunity object using a look up field (Opportunity).</description>
    <fields>
        <fullName>Benefit_Agreement_Number__c</fullName>
        <label>Benefit Agreement Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Include_BA__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include BA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <description>Product Line of Business(H,D,V)</description>
        <formula>TEXT( Plan1__r.Line_Of_Business__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Line of Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_ID_13__c</fullName>
        <formula>Plan1__r.Marketing_Plan_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marketing Plan ID-13</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_ID_7__c</fullName>
        <formula>Plan1__r.Plan_Sales_ID__c</formula>
        <label>Marketing Plan ID-7</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_Name__c</fullName>
        <formula>Plan1__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marketing Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Benefit Agreements</relationshipLabel>
        <relationshipName>Opportunity_Benefit_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Effective_Date__c</fullName>
        <label>Rate Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rate_End_Date__c</fullName>
        <label>Rate End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <label>Opportunity Benefit Agreement</label>
    <nameField>
        <label>Opportunity Benefit Agreement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Benefit Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Census__c.object
<CustomObject>
    <description>This object is used  for</description>
    <fields>
        <fullName>Opportunity_Group_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Group Section</label>
        <referenceTo>SGR_Opportunity_Group_Section__c</referenceTo>
        <relationshipLabel>Opportunity Censuses</relationshipLabel>
        <relationshipName>Opportunity_Censuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is  look up  to  Opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Census</relationshipLabel>
        <relationshipName>Opportunity_Census</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Census</label>
    <nameField>
        <label>Opportunity Census Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Censuses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Group_Section__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Agreement</label>
        <referenceTo>SGR_Opportunity_Benefit_Agreement__c</referenceTo>
        <relationshipLabel>Opportunity Group Section</relationshipLabel>
        <relationshipName>Opportunity_Group_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Section_Original_Effective_Date__c</fullName>
        <label>Group Section Original Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Group Section</relationshipLabel>
        <relationshipName>Opportunity_Group_Section</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Group Section</label>
    <nameField>
        <label>Opportunity Group Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Group Section</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SGR_ViewOppBAController.cls
/**************************************************************************************
Apex Class Name     : SGR_ViewOppBAController     
Version             : 1.0
Function            : Controller class to get BA details for Opportunity
Modification Log    :
* Developer: Shankar                 Date: 11/10/2018                   Description
* ----------------------------------------------------------------------------               
* Shankar                  11/10/2018                 Initial Version
* Shankar                  22/10/2018                 1.1 Added Last Modified By in query
* Saurav                   11/1/2018                  method Added to get valodation Log List(getOppVLList)
*************************************************************************************/
public without sharing class SGR_ViewOppBAController {

    @AuraEnabled
    public static List<SGR_Opportunity_Benefit_Agreement__c> getOppBAList(Id oppId, String sortField, String sortOrder) {
        List<SGR_Opportunity_Benefit_Agreement__c> baList = new List<SGR_Opportunity_Benefit_Agreement__c>();

        String baListQuery = 'Select Id, Name, Benefit_Agreement_Number__c, Include_BA__c, Renewal_Date__c, Effective_Date__c, Rate_End_Date__c, Rate_Effective_Date__c, Funding_Type__c, LastModifiedDate, LastModifiedBy.Name, Marketing_Plan_Name__c, Marketing_Plan_ID_7__c, Marketing_Plan_ID_13__c,Line_of_Business__c from SGR_Opportunity_Benefit_Agreement__c where Opportunity__c = :oppId ORDER BY ' + sortField + ' ' + sortOrder;

        try {
            baList = (List<SGR_Opportunity_Benefit_Agreement__c>) Database.query(baListQuery);
        } catch (Exception e) {
            throw new AuraHandledException('Error while retreiving BAs. Contact System Administrator');
        }
        return baList;
    }

    @AuraEnabled
    public static Map<Id, List<SGR_Opportunity_Group_Section__c>> getOppGSList(Id oppId, String sortField, String sortOrder) {
        List<SGR_Opportunity_Benefit_Agreement__c> baList = new List<SGR_Opportunity_Benefit_Agreement__c>();
        List<SGR_Opportunity_Group_Section__c> gsAllList = new List<SGR_Opportunity_Group_Section__c>();
        Map<Id, List<SGR_Opportunity_Group_Section__c>> comMAP = new Map<Id, List<SGR_Opportunity_Group_Section__c>>();

        String baListQuery = 'Select Id, Name, Benefit_Agreement_Number__c from SGR_Opportunity_Benefit_Agreement__c where Opportunity__c = :oppId ORDER BY ' + sortField + ' ' + sortOrder;
        String grpSecQuery = 'select id from SGR_Opportunity_Group_Section__c where Opportunity__c = :oppId';
        Set<String> agreeNum = new Set<String>();
        Set<Id> GrpSet = new Set<Id>();
        Set<Id> gsNum = new Set<Id>();
        baList = Database.query(baListQuery);
        gsAllList = Database.query(grpSecQuery);
        try {
            if (baList != null && baList.size() > 0) {
                for (SGR_Opportunity_Benefit_Agreement__c agre : baList) {
                    if (agre.Benefit_Agreement_Number__c != null) {
                        agreeNum.add(agre.Benefit_Agreement_Number__c);
                    }
                }
                if (gsAllList != null && gsAllList.size() > 0) {
                    for (SGR_Opportunity_Group_Section__c agre : gsAllList) {
                        if (agre.Id != null) {
                            GrpSet.add(agre.Id);
                        }
                    }
                }
                List<Opportunity_BA_GS_Assignment__c> bagsid = [
                        SELECT Opportunity_Group_Section__c, Opportunity_Benefit_Agreement__c
                        FROM Opportunity_BA_GS_Assignment__c
                        WHERE Opportunity_Benefit_Agreement__r.Benefit_Agreement_Number__c IN :agreeNum AND Opportunity_Group_Section__c IN :GrpSet
                        LIMIT 1000
                ];
                if (bagsid != null) {
                    for (Opportunity_BA_GS_Assignment__c temp : bagsid) {
                        if (temp.Opportunity_Group_Section__c != null) {
                            gsNum.add(temp.Opportunity_Group_Section__c);
                        }
                    }
                }
                List<SGR_Opportunity_Group_Section__c> nwgslist = [
                        SELECT Group_Name__c, Group_Section_Original_Effective_Date__c, Status__c,
                                Group_Section_Cancel_Date__c, Opportunity_Group_Section_Number__c,
                                Group_Section_Cancel_Code__c
                        FROM SGR_Opportunity_Group_Section__c
                        WHERE Id IN :gsNum
                        LIMIT 1000
                ];

                for (SGR_Opportunity_Benefit_Agreement__c temp : baList) {
                    List<SGR_Opportunity_Group_Section__c> gsmaList = new List<SGR_Opportunity_Group_Section__c>();
                    for (Opportunity_BA_GS_Assignment__c mashup : bagsid) {
                        for (SGR_Opportunity_Group_Section__c agre : nwgslist) {
                            if (temp.Id == mashup.Opportunity_Benefit_Agreement__c && agre.Id == mashup.Opportunity_Group_Section__c) {
                                gsmaList.add(agre);
                            }
                        }
                        comMAP.put(temp.Id, gsmaList);
                    }
                }
            }
        }
        catch (Exception e) {
            throw new AuraHandledException('Error while retreiving BAs. Contact System Administrator');
        }
        return comMAP;
    }


    @AuraEnabled
    public static List<String> initiaterefresh(Id oppId) {
        List<String> successmsg = new List<String>();
        List<Opportunity> opps = new List<Opportunity>();
        Set<Id> ide = new Set<Id>();
        Set<Id> accids = new Set<Id>();
        Set<Id> baID = new Set<Id>();
        List<SGR_Opportunity_Benefit_Agreement__c> OlBA = new List<SGR_Opportunity_Benefit_Agreement__c>();
        List<SGR_Opportunity_Benefit_Agreement__c> obfaList = new List<SGR_Opportunity_Benefit_Agreement__c>();
        obfaList = [
                SELECT Id, Name,Opportunity__c, Benefit_Agreement_Number__c, Include_BA__c, Renewal_Date__c,
                        Effective_Date__c, Rate_End_Date__c, Rate_Effective_Date__c, Funding_Type__c, LastModifiedDate,
                        Marketing_Plan_Name__c, Marketing_Plan_ID_7__c, Marketing_Plan_ID_13__c
                FROM SGR_Opportunity_Benefit_Agreement__c
                WHERE Opportunity__c = :oppId
                LIMIT 1000
        ];
        if (!obfaList.isEmpty()) {
            OlBA = obfaList;
            for (SGR_Opportunity_Benefit_Agreement__c sg : obfaList) {
                ide.add(sg.Opportunity__c);
                baID.add(sg.Id);
            }
        }

        List<Opportunity> sgrList = [
                SELECT AccountId, Account.Name, SGR_Workflow_Status__c
                FROM Opportunity
                WHERE Id IN :ide
                LIMIT 1000
        ];

        if (!sgrList.isEmpty()) {
            for (Opportunity opp : sgrList) {
                accids.add(opp.AccountId);
            }
        }
        List<SGR_Opportunity_Group_Section__c> gaList = [
                SELECT Id, Benefit_Agreement__c
                FROM SGR_Opportunity_Group_Section__c
                WHERE Benefit_Agreement__c IN :baID
                LIMIT 1000
        ];

        try {
            delete OlBA;
            if (!gaList.isEmpty()) {
                delete gaList;
            }
        }

        catch (Exception E) {
            throw new AuraHandledException('Error while erasing Child Records. Contact System Administrator');
        }
        OlBA.clear();
        gaList.clear();

        opps = [
                SELECT Id, Name, AccountId, SGR_Workflow_Status__c, Rating_Status__c
                FROM Opportunity
                WHERE Id = :oppId
                LIMIT 1000
        ];

        if (OlBA.isEmpty() || OlBA.size() == 0 || OlBA == null) {
            SGR_AccountRenewalsHelper.insertOpportunitiesBenefitAgreement(accids, opps, null);
        }

        if (gaList.isEmpty() || gaList.size() == 0 || gaList == null) {
            SGR_AccountRenewalsHelper.insertOpportunitiesGroupSection(accids, opps, null);
        }

        SGR_AccountRenewalsHelper.insertOppBAGSAssignment(accids, opps, null);
        SGR_AccountRenewalsHelper.createEventAuditLog(opps, 'Internal Workflow', 'Refresh BA event is fired by the user ');

        String successmsg1 = 'refresh done successfully.';
        successmsg.add(successmsg1);


        for (Opportunity record : opps) {
            record.Rating_Status__c = 'Pended';
        }
        update opps;

        return successmsg;
    }

    @AuraEnabled
    public static List<SGR_Opportunity_Group_Section__c > getbaGSList(Id BAId) {
        List<SGR_Opportunity_Group_Section__c> gSLIST = new List<SGR_Opportunity_Group_Section__c>();
        String GSLISTQuery = 'Select Group_Name__c, Group_Section_Original_Effective_Date__c, Status__c, Group_Section_Cancel_Date__c, Opportunity_Group_Section_Number__c, Group_Section_Cancel_Code__c from SGR_Opportunity_Group_Section__c where Benefit_Agreement__c=:BAId ORDER BY Group_Name__c ASC';
        try {
            gSLIST = Database.query(GSLISTQuery);
        } catch (Exception e) {
            throw new AuraHandledException('Error while retreiving GAs. Contact System Administrator');
        }
        return gSLIST;
    }

    @AuraEnabled
    public static String getratingStatus(Id oppId) {
        String ratsatus = [
                SELECT Rating_Status__c
                FROM Opportunity
                WHERE Id = :oppId
                LIMIT 1
        ].Rating_Status__c;
        return ratsatus;
    }

    @AuraEnabled
    public static User getloggedinuserinfo() {
        String users = UserInfo.getUserId();
        User us = [
                SELECT Id, Name, ProfileId, Profile.Name, UserRole.Name
                FROM User
                WHERE Id = :users
                LIMIT 1
        ];
        return us;

    }

    @AuraEnabled
    public static void updateBARecord(SGR_Opportunity_Benefit_Agreement__c bARec) {
        try {
            update bARec;
            List<SGR_Opportunity_Census__c> updateCensusList = new List<SGR_Opportunity_Census__c>();
            SGR_Opportunity_Benefit_Agreement__c benAgreement = [
                    SELECT Id, Include_BA__c, Line_of_Business__c, Opportunity__c, Marketing_Plan_ID_13__c
                    FROM SGR_Opportunity_Benefit_Agreement__c
                    WHERE Id = :bARec.Id
                    LIMIT 1
            ];
            List<SGR_Opportunity_Census__c> lstOfOppCensus = [
                    SELECT Id, SGR_DentalIsChecked__c, SGR_HealthIsChecked__c, SGR_VisionIsChecked__c
                    FROM SGR_Opportunity_Census__c
                    WHERE Opportunity__c = :benAgreement.Opportunity__c AND Relationship__c = 'Subscriber' AND
                    (Health_Plan_ID__c = :benAgreement.Marketing_Plan_ID_13__c OR Dental_Plan_ID__c = :benAgreement.Marketing_Plan_ID_13__c OR Vision_Plan_ID__c = :benAgreement.Marketing_Plan_ID_13__c)
                    LIMIT 1000
            ];
            if (!lstOfOppCensus.isEmpty()) {
                for (SGR_Opportunity_Census__c census : lstOfOppCensus) {
                    if (benAgreement.Include_BA__c) {
                        census.SGR_DentalIsChecked__c = true;
                        census.SGR_HealthIsChecked__c = true;
                        census.SGR_VisionIsChecked__c = true;
                    } else {
                        if (benAgreement.Line_of_Business__c == 'H') {
                            census.SGR_DentalIsChecked__c = true;
                            census.SGR_HealthIsChecked__c = false;
                            census.SGR_VisionIsChecked__c = true;
                        } else if (benAgreement.Line_of_Business__c == 'D') {
                            census.SGR_DentalIsChecked__c = false;
                            census.SGR_HealthIsChecked__c = true;
                            census.SGR_VisionIsChecked__c = true;
                        } else if (benAgreement.Line_of_Business__c == 'V') {
                            census.SGR_DentalIsChecked__c = true;
                            census.SGR_HealthIsChecked__c = true;
                            census.SGR_VisionIsChecked__c = false;
                        }
                    }
                    updateCensusList.add(census);
                }
                if (!updateCensusList.isEmpty()) {
                    update updateCensusList;
                }
            }
        } catch (Exception e) {
        }
    }

    @AuraEnabled
    public static Opportunity getOppData(Id oppId) {
        return [
                SELECT Id, Rating_Status__c, CurrentUserProfileName__c
                FROM Opportunity
                WHERE Id = :oppId
                LIMIT 1
        ];
    }
}