src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Active_Health_Subscribers__c</fullName>
        <description>This field is used to capture the number of active health contracts for the Group Account as listed in BlueStar</description>
        <label>Active Health Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <recordTypes>
        <fullName>Competitor</fullName>
        <active>true</active>
        <description>Account record type that captures information about a competitor (carriers and vendors)</description>
        <label>Competitor</label>
    </recordTypes>

objects/Account_Products__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Product</relationshipLabel>
        <relationshipName>Account_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Product</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account Products Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Incumbent__c</fullName>
        <label>Incumbent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Carrier</fullName>
                </value>
                <value>
                    <fullName>Cigna</fullName>
                </value>
                <value>
                    <fullName>UHC</fullName>
                </value>
                <value>
                    <fullName>Aetna</fullName>
                </value>
                <value>
                    <fullName>Humana</fullName>
                </value>
                <value>
                    <fullName>PUG</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity_Product__c.object
<CustomObject>
    <description>Products related to the opportunity - acting as a junction object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Winning Carrier / Vendor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Competitor Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <formula>Opportunity_Name__r.Requested_Effective_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incumbent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incumbent</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Competitor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Products (Incumbent)</relationshipLabel>
        <relationshipName>Opportunity_Products1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Sales status of opportunity product</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>GeoAccess/Discount Analysis/Proposal Provided</fullName>
                </value>
                <value>
                    <fullName>Pricing/Presentation to Client</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Migrated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{000}</displayFormat>
        <label>OP #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LGNA_AccountProductsTest.cls
/**************************************************************************************
  Apex Class Name     : LGNA_AccountProductsTest
  Version             : 1.0
  Function            : This is a test class for LGNA_AccountProducts.
  Modification Log    :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
*  Ranjit Gandhi 		5/4/2018				Initial Version
*************************************************************************************/
@isTest
public class LGNA_AccountProductsTest {

    static testMethod void myUnitTest1() {
       
            test.StartTest();
                         Id CompetitorAccountRecordTypeId1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Competitor').getRecordTypeId();
        Account testCompetitorAccount1 = TestClassUtiltity.createAccountWithRecType('Test Account2', CompetitorAccountRecordTypeId1);

                
        Account GroupAcnt = TestClassUtiltity.CreateAccountRecord('Group Account');
                GroupAcnt.BillingStreet = '123 Main St';
                GroupAcnt.BillingCity= 'AnyCity';
                GroupAcnt.BillingState= 'IL';
                GroupAcnt.BillingPostalCode= '60053-0000';
                GroupAcnt.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
                update GroupAcnt;  		
        		
        
        		list<Product2> LstProduct =  TestClassUtiltity.createProducts();
            	insert LstProduct;
        
        		list<Opportunity> OppList =  TestClassUtiltity.CreateOpportunities(GroupAcnt.id);
        		insert OppList;
        		list<Account_Products__c> AccProduct =  TestClassUtiltity.createAccProducts(GroupAcnt.id, LstProduct[0].id);
       			insert AccProduct;
        		list<Opportunity_Product__c> OppProduct =  TestClassUtiltity.createOppProducts(OppList[0].id, LstProduct[0].id);
        		OppProduct[0].Incumbent__c = testCompetitorAccount1.Id;
        		insert OppProduct;
        		
        		Map<String, list<Object>> loadActive=LGNA_AccountProducts.loadInitialAccountProducts(GroupAcnt.id);
        		Map<String, list<Object>> loadHistorical=LGNA_AccountProducts.loadHistoricalAccountProducts(GroupAcnt.id);
        		
        		
        		Id CompetitorAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Competitor').getRecordTypeId();
        		 Account testCompetitorAccount = new Account(Name = 'Competitor', RecordTypeId = '01233000000QMOk', 
                                                  Type='Competitor Account',
                                                  Active_Health_Subscribers__c = 15000, Effective_Date__c = system.today().addyears(2));
        		
        		insert testCompetitorAccount;
        		OppProduct[0].Status__c='lost';OppProduct[0].Account__c=testCompetitorAccount.id;OppProduct[0].Incumbent__c = testCompetitorAccount1.Id;
        
        		upsert OppProduct[0];
        		Map<String, list<Object>> loadHistoricalOpp=LGNA_AccountProducts.loadHistoricalOpportunityProducts(GroupAcnt.id);
        
            	
       
    }
}