src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Forecast_Segment__c</fullName>
        <description>The forecast segment value indicator. This is based off of details on the account, such as District or Market Segment.</description>
        <label>Forecast Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENA</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment for the opportunity</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Segment__c</fullName>
        <description>The forecast segment value indicator. This is based off of details on the opportunity, such as District or Market Segment.</description>
        <label>Forecast Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENA</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <recordTypes>
        <fullName>SGR_Production_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>SGR Oppurtunity Record Type</description>
        <label>SGR Production Opportunity</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To retrieve days to submit for each division for calcuating Submit_Date__c on opportunity</description>
    <label>SGR Days to Submit</label>
</CustomObject>

objects/SGR_Renewal_Batch_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SGR_Renewal_Batch_Opptys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BatchId</label>
        <referenceTo>SGRRenewalBatch__c</referenceTo>
        <relationshipName>SGR_Renewal_Batch_Opptys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SGR_Renewal_Batch_Opptys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Intiated Rating</fullName>
                </value>
                <value>
                    <fullName>Intiated Validation</fullName>
                </value>
                <value>
                    <fullName>Opportunity created</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Renewal Document Generated</fullName>
                </value>
                <value>
                    <fullName>Send for Email Dsitrubution</fullName>
                </value>
                <value>
                    <fullName>Send for Postal Distribution</fullName>
                </value>
                <value>
                    <fullName>Send to Documnet Generaion</fullName>
                </value>
                <value>
                    <fullName>Transferred to Bluestar</fullName>
                </value>
                <value>
                    <fullName>Triggered</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Bluestar transfer initiated</fullName>
                </value>
                <value>
                    <fullName>Validation Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Renewal Batch Opportunity</label>
    <nameField>
        <label>SGR_Renewal Batch Oppty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Renewal Batch Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SGR_BSTAR_TransferSchedulerHelper.cls
/**************************************************************************************
  Apex Class Name     : SGR_BSTAR_TransferSchedulerHelper     
  Version             			: 1.0
  Function            		: This class is used to create and schedule batch jobs to perform BlueSTAR transfer
  Modification Log    	:
* Developer: Shankar  Date: 12/20/2018                   Initial version
* ----------------------------------------------------------------------------               
* Shankar                  09/05/2018                Original Version
* Shankar					 07/01/2019				Updated SOQL query and method signature to include renewal year
*************************************************************************************/
public class SGR_BSTAR_TransferSchedulerHelper {
	
	public Set<Id> oppIds;	
	
	public SGR_BSTAR_TransferSchedulerHelper() {
			this.oppIds = new Set<Id>();	
	}
	
	//public void scheduleJobs(Id batchRecId, String division, String fundingType, String marketSeg, Integer renMonth,  Integer renYear, DateTime schedDateTime) {
    public void scheduleJobs(Id batchRecId, String division, String fundingType, String marketSeg, Date renewaldate, DateTime schedDateTime) {
		Id sgrProdOppRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Production_Opportunity').getRecordTypeId();
		List<Opportunity> opps = [Select Id, AccountId, Account.AccountNumber from Opportunity 
																	WHERE 
																	HCSC_Division__c = :division AND 
																	Funding_Type__c = :fundingType AND
																	//Account_Market_Segment__c = :marketSeg AND
                                  									Renewal_Date__c >=:renewaldate AND 
                                  									Renewal_Date__c <:renewaldate.addMonths(1) AND
																	//CALENDAR_MONTH(Renewal_Date__c) = :renMonth AND
																	//CALENDAR_YEAR(Renewal_Date__c) = :renYear AND
																	Rating_Status__c = 'Sold' AND
																	RecordType.Id = :sgrProdOppRecTypeId AND
                                  									ForeCast_Segment__c='Small Group'
													];		
		
		List<SGR_Renewal_Batch_Oppty__c> rbOpptyList = new List<SGR_Renewal_Batch_Oppty__c>();
		
		if(null == opps || opps.isEmpty()) {
			SGR_Exception ex = new SGR_Exception('No opportunities found with the selected criteria');
			CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'SGR_BSTAR_TransferSchedulerHelper', null, 'SGR_BSTAR_TransferSchedulerHelper.scheduleJobs', 'High');
		}
		try {
			for (Opportunity opp: opps) {
				// Create a Bath Renewal Oppty junction record for each opportunity
				SGR_Renewal_Batch_Oppty__c rbOppty = new SGR_Renewal_Batch_Oppty__c();
				rbOppty.Account_Id__c = opp.AccountId;
				rbOppty.Account_Number__c = opp.Account.AccountNumber;
				rbOppty.BatchId__c = batchRecId;
				rbOppty.Opportunity__c = opp.Id;
				rbOppty.Processing_Status__c = 'Bluestar transfer initiated';
				rbOpptyList.add(rbOppty);
				
				oppIds.add(opp.Id);
			}
			
			if (!rbOpptyList.isEmpty()) {
				Database.SaveResult[] results = Database.insert(rbOpptyList, false);
				CreateExceptionLog.insertErrorLog(null, results, null, null, 'Apex Class', 'SGR_BSTAR_TransferSchedulerHelper', null, 'SGR_BSTAR_TransferSchedulerHelper.scheduleJobs', 'High');
			}

			String cronExpr = '';
				
			if (null != schedDateTime) {
				// Build CRON expression to run the job based on user input
				cronExpr = '0 ' + String.valueOf(schedDateTime.minute() + 1) + ' ' + String.valueOf(schedDateTime.hour()) + ' ' + String.valueOf(schedDateTime.day()) + ' ' + String.valueOf(schedDateTime.month()) + ' ? ' +  String.valueOf(schedDateTime.year());
				System.debug('cronExpr:: ' + cronExpr);
				if (!Test.isRunningTest()) {
					System.schedule('B* Transfer One time Job for ' + division + ' - ' + cronExpr , cronExpr, new SGR_BSTAR_OppValidatorBatch(oppIds, batchRecId));
				} 
			} else {
				throw new SGR_Exception('Schedule date & time is missing');
			}
		} catch (Exception ex) {
			CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'SGR_BSTAR_TransferSchedulerHelper', null, 'SGR_BSTAR_TransferSchedulerHelper.scheduleJobs', 'High');			
		}
	}
}