src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Forecast_Segment__c</fullName>
        <description>The forecast segment value indicator. This is based off of details on the account, such as District or Market Segment.</description>
        <label>Forecast Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENA</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment for the opportunity</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_UW__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned UW</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Forecast_Segment__c</fullName>
        <description>The forecast segment value indicator. This is based off of details on the opportunity, such as District or Market Segment.</description>
        <label>Forecast Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENA</fullName>
                </value>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Workflow_System_Status__c</fullName>
        <label>Workflow System Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to Fetch Mapped Plans</fullName>
                    <default>true</default>
                    <label>Ready to Fetch Mapped Plans</label>
                </value>
                <value>
                    <fullName>Ready to Validate</fullName>
                </value>
                <value>
                    <fullName>Failed Validation</fullName>
                </value>
                <value>
                    <fullName>Ready to Rate</fullName>
                </value>
                <value>
                    <fullName>Ready For Gate Processing</fullName>
                </value>
                <value>
                    <fullName>Ready to Send to B-Engaged</fullName>
                </value>
                <value>
                    <fullName>Ready to Send to BlueSTAR</fullName>
                </value>
                <value>
                    <fullName>Not Eligible to Send to BlueSTAR</fullName>
                </value>
                <value>
                    <fullName>Workflow Completed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Review Task Completion</fullName>
                </value>
                <value>
                    <fullName>Awaiting Hold Task Completion</fullName>
                </value>
                <value>
                    <fullName>Gate Processing Completed</fullName>
                </value>
                <value>
                    <fullName>Failed Rating</fullName>
                </value>
                <value>
                    <fullName>Ready for BlueSTAR Initiation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Opportunity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To retrieve days to submit for each division for calcuating Submit_Date__c on opportunity</description>
    <label>SGR Days to Submit</label>
</CustomObject>

objects/SGR_Opportunity_Plan_Rate__c.object
<CustomObject>
    <description>This object contains details about opportunity plan Rates.</description>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Plan Rates</relationshipLabel>
        <relationshipName>Opportunity_Plan_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Renewing</fullName>
                </value>
                <value>
                    <fullName>Mapped</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Alternate</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                    <isActive>false</isActive>
                    <label>Alternative</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Plan Rate</label>
    <nameField>
        <label>Opportunity Plan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SGR_BlueSTAROptysPost_Test.cls
@isTest
private class SGR_BlueSTAROptysPost_Test {
    @testSetup static void setup() {
        // Create common test Data
        
        Id sgrProdOpp = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('SGR Production Opportunity').getRecordTypeId(); 
        Account acc = Sgr_TestDataUtility.createAcc('NewAcc');
        system.debug('+++Acc.Id--'+acc.Id);
        List<Opportunity> optys = new List<Opportunity>();
        Opportunity optyIL = Sgr_TestDataUtility.createOpportunity(acc.Id, 'Marketing Release', 'Qualify');
        //opty.Account_Market_Segment__c = 'SG';
        optyIL.Funding_Type__c = 'PREM';
        optyIL.HCSC_Division__c = 'IL';
        optyIL.RecordTypeId = sgrProdOpp;
        optyIL.Renewal_Date__c = system.today().adddays(5);
        //opty.Assigned_UW__c ='';//UserInfo.getuserid();
        optyIL.Workflow_System_Status__c = 'Ready for BlueSTAR Initiation';
        optyIL.ForeCast_Segment__c='Small Group';
        optys.add(optyIL);
        Opportunity optyTX = Sgr_TestDataUtility.createOpportunity(acc.Id, 'Marketing Release', 'Qualify');
        //opty.Account_Market_Segment__c = 'SG';
        optyTX.Funding_Type__c = 'PREM';
        optyTX.HCSC_Division__c = 'TX';
        optyTX.RecordTypeId = sgrProdOpp;
        optyTX.Renewal_Date__c = system.today().adddays(30);
        //opty.Assigned_UW__c ='';//UserInfo.getuserid();
        optyTX.Workflow_System_Status__c = 'Ready for BlueSTAR Initiation';
        optyTX.ForeCast_Segment__c='Small Group';
        optys.add(optyTX);
        Insert optys;
        
        
        List<SGR_Opportunity_Plan_Rate__c> planRates = new List<SGR_Opportunity_Plan_Rate__c>();
        SGR_Opportunity_Plan_Rate__c planRateIL = new SGR_Opportunity_Plan_Rate__c(Opportunity__c = optyIL.id, Plan_Status__c = 'Renewing', Type__c='Renewal');
        planRates.add(planRateIL);
        SGR_Opportunity_Plan_Rate__c planRateTX = new SGR_Opportunity_Plan_Rate__c(Opportunity__c = optyTX.id, Plan_Status__c = 'Renewing', Type__c='Renewal');
        planRates.add(planRateTX);
        insert planRates;
    }
    @isTest
    private static void blueStarmethod(){
        Datetime myDateTime = system.now();
        Date today = system.today().adddays(5);
        String renDate = string.valueof(today);
        
        Test.startTest();
        SGR_BlueSTAROptysPost.updateBlueSTAROptys('IL', 'SG', 'PREM', renDate, myDateTime);
        SGR_BlueSTAROptysPost.updateBlueSTAROptys('TX', 'SG', 'PREM', renDate, myDateTime);
        SGR_BlueSTAROptysPost.updateBlueSTAROptys('TX', 'SG', 'PREM', 'Hi', myDateTime);
        SGR_BlueSTAROptysPost.updateBlueSTAROptys('MT', 'SG', 'PREM', renDate, myDateTime);
        Test.stopTest();
    }
    
}