src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Tax_ID__c</fullName>
        <description>Tax Identification Number used for Producer accounts</description>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
    <fields>
        <fullName>Cost_Center__c</fullName>
        <description>cost center for internal contact (HCSC employee) used on Ticket</description>
        <label>Cost Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Contact.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the unique identifier number of the contact in the source system (e.g., BlueStar, Siebel SFA)</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Identifier Number of the Contact in the Source System</inlineHelpText>
        <label>Contact Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Business_Use_of_Ticket__c</fullName>
        <label>Ticket Use Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Charities</fullName>
                </value>
                <value>
                    <fullName>Employee Incentive</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets (Client)</relationshipLabel>
        <relationshipName>Tickets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specific Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Internal Contact</value>
            </filterItems>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Charity Contact</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets (Internal Contact)</relationshipLabel>
        <relationshipName>Tickets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producer_for_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Producer for Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Producer_Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Contact</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tickets (Requestor)</relationshipLabel>
        <relationshipName>Tickets3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Event__c</fullName>
        <label>Ticket Event</label>
        <referenceTo>Ticket_Event__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ticket_Grouping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ticket Grouping</label>
        <referenceTo>Ticket_Grouping__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Price__c</fullName>
        <label>Ticket Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ticket_Type__c</fullName>
        <label>Ticket Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Box Seats</fullName>
                </value>
                <value>
                    <fullName>Terrace Seats</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Suite</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>assignToClient__c</fullName>
        <defaultValue>false</defaultValue>
        <label>assignToClient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>assignToEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>assignToEmployee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>assignToProducer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>assignToProducer</label>
        <type>Checkbox</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket_Event__c.object
<CustomObject>
    <fields>
        <fullName>Business_Use_Of_Ticket__c</fullName>
        <label>Ticket Use Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_City__c</fullName>
        <label>Event City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_State__c</fullName>
        <label>Event State</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Oklahoma</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Street_Address__c</fullName>
        <label>Event Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Venue_Name__c</fullName>
        <description>Event Venue Name dependent on State picklist</description>
        <label>Event Venue</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Event_State__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                    <default>true</default>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Alamodome</fullName>
                </value>
                <value>
                    <fullName>American Airlines Center</fullName>
                </value>
                <value>
                    <fullName>Amon G. Carter Stadium</fullName>
                </value>
                <value>
                    <fullName>AT &amp; T Center</fullName>
                </value>
                <value>
                    <fullName>AT &amp; T Stadium</fullName>
                </value>
                <value>
                    <fullName>BBVA Compass Stadium</fullName>
                </value>
                <value>
                    <fullName>Boone Pickens Stadium</fullName>
                </value>
                <value>
                    <fullName>Chesapeake Energy Arena</fullName>
                </value>
                <value>
                    <fullName>Chickasaw Bricktown Ballpark</fullName>
                </value>
                <value>
                    <fullName>Darrell K. Royal-TX Memorial Stadium</fullName>
                </value>
                <value>
                    <fullName>Dell Diamond</fullName>
                </value>
                <value>
                    <fullName>Dr. Pepper Arena</fullName>
                </value>
                <value>
                    <fullName>Gallagher Iba Arena</fullName>
                </value>
                <value>
                    <fullName>Gaylord Family-OK Memorial Stadium</fullName>
                </value>
                <value>
                    <fullName>Globe Life Park</fullName>
                </value>
                <value>
                    <fullName>Guaranteed Rate Field</fullName>
                </value>
                <value>
                    <fullName>Isotopes Park (Baseball)</fullName>
                </value>
                <value>
                    <fullName>Jones AT &amp; T Stadium</fullName>
                </value>
                <value>
                    <fullName>Kyle Field</fullName>
                </value>
                <value>
                    <fullName>Lloyd Noble Center</fullName>
                </value>
                <value>
                    <fullName>McLane Stadium</fullName>
                </value>
                <value>
                    <fullName>Minute Maid Park</fullName>
                </value>
                <value>
                    <fullName>NRG Stadium</fullName>
                </value>
                <value>
                    <fullName>ONEOK Field</fullName>
                </value>
                <value>
                    <fullName>Soldier Field - (Chicago Bears)</fullName>
                </value>
                <value>
                    <fullName>Toyota Center</fullName>
                </value>
                <value>
                    <fullName>Toyota Stadium</fullName>
                </value>
                <value>
                    <fullName>United Center</fullName>
                </value>
                <value>
                    <fullName>University Stadium (Football)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Zip_Postal_Code__c</fullName>
        <label>Event Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>incrementalNumberOfTickets__c</fullName>
        <label>incrementalNumberOfTickets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ticket Event</label>
    <nameField>
        <label>Ticket Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket_Event_Venue_Address__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds data for Ticket Event  Street and City. Referenced in Ticket Distribution class.</description>
    <fields>
        <fullName>Venue_City__c</fullName>
        <label>Venue City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue_Street__c</fullName>
        <label>Venue Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Venue_ZipCode__c</fullName>
        <label>Venue ZipCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ticket Event Venue Address</label>
</CustomObject>

objects/Ticket_Grouping__c.object
<CustomObject>
    <fields>
        <fullName>Ticket_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ticket Event</label>
        <referenceTo>Ticket_Event__c</referenceTo>
        <relationshipLabel>Ticket Groupings</relationshipLabel>
        <relationshipName>Ticket_Groupings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ticket Grouping</label>
    <nameField>
        <label>Ticket Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Groupings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <description>Cost Center the user belongs</description>
        <label>Cost Center</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TicketDistributionControllerTest.cls
/**************************************************************************************
  Apex Class Name     : TicketDistributionControllerTest
  Version             : 1.0
  Function            : This is a test class for the TicketDistributionController class
* Developer                        Date                  
* ----------------------------------------------------------------------------                 
* Nick Serafin/Slalom             10/25/2016
*************************************************************************************/
@isTest(SeeAllData=false)
private class TicketDistributionControllerTest {

    @isTest static void ticketDistributionTest() {

        Id groupAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        Id producerAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();

        List<Account> groupAccounts = new List<Account>();
        Set<Id> groupAccountIds = new Set<Id>();
        Account testGroupAccount = new Account();
        testGroupAccount.RecordTypeId = groupAccountRecordTypeId;
        testGroupAccount.External_ID__c = '1232';
        testGroupAccount.Id = fflib_IDGenerator.generate( Account.SObjectType );
        groupAccountIds.add(testGroupAccount.Id);
        groupAccounts.add(testGroupAccount);

        List<Account> producerAccounts = new List<Account>();
        Set<Id> producerAccountIds = new Set<Id>();
        Account testProducerAccount = new Account();
        testProducerAccount.RecordTypeId = producerAccountRecordTypeId;
        testProducerAccount.Tax_ID__c = '1234';
        testProducerAccount.Id = fflib_IDGenerator.generate( Account.SObjectType );
        producerAccountIds.add(testProducerAccount.Id);
        producerAccounts.add(testProducerAccount);
        
        Ticket_Event_Venue_Address__c EventVenueName = new Ticket_Event_Venue_Address__c();
        EventVenueName.Name = 'Toyota Center';  
        EventVenueName.Venue_Street__c = '1510 Polk Street';
        EventVenueName.Venue_City__c = 'Houston';
        EventVenueName.Venue_ZipCode__c = '77002';
        insert EventVenueName;
        
        Ticket_Event_Venue_Address__c EventVenueNameother = new Ticket_Event_Venue_Address__c();
        EventVenueNameother.Name = 'Other';  
        EventVenueNameother.Venue_Street__c = 'Test Street';
        EventVenueNameother.Venue_City__c = 'Test City';
        EventVenueNameother.Venue_ZipCode__c = '23234';
        insert EventVenueNameother;
        
    
        Ticket_Event__c testEvent = new Ticket_Event__c();       
        testEvent.Id = fflib_IDGenerator.generate( Ticket_Event__c.SObjectType );
        testEvent.Name = 'Hockey Game';
        testEvent.Event_Venue_Name__c = 'Toyota Center';
       
        List<Ticket_Grouping__c> ticketGroupings = new List<Ticket_Grouping__c>();
        Ticket_Grouping__c ticketGrouping = new Ticket_Grouping__c();
        ticketGrouping.Id = fflib_IDGenerator.generate( Ticket_Grouping__c.SObjectType );
        ticketGrouping.Ticket_Event__c = testEvent.Id;
        ticketGroupings.add(ticketGrouping);

        List<Ticket__c> tickets = new List<Ticket__c>();
        Ticket__c ticket = new Ticket__c();
        ticket.Ticket_Event__c = testEvent.Id;
        ticket.Ticket_Grouping__c = ticketGrouping.Id;
        ticket.Id = fflib_IDGenerator.generate( Ticket__c.SObjectType );
        tickets.add(ticket);

        //List<User> users = new List<User>();
        List<Contact>users =new List<Contact>();
        Set<Id> userIds = new Set<Id>();
        //User testUser = new User();
        Contact testUser=new Contact();
        testUser.FirstName ='Nick';
        testUser.LastName ='Serafin';
        testUser.Email = 'testing@example.com';
        testUser.Cost_Center__c = '1231252';
        testUser.Id = fflib_IDGenerator.generate( Contact.SObjectType );
        userIds.add(testUser.Id);
        users.add(testUser);

        PageReference pageRef = new PageReference('/apex/TicketDistribution');
        Test.setCurrentPage(pageRef);

        fflib_ApexMocks userMocks = new fflib_ApexMocks(); 

        UserDAO.IUserDAO userDAOInstance;
        userDAOInstance = new MockDAOs.UserDAOMock(userMocks);  

        userMocks.startStubbing();
        userMocks.when(userDAOInstance.getRequesterForTicketDistro(testUser.Id))
                    .thenReturn(testUser);
        userMocks.stopStubbing();

        userMocks.startStubbing();
        userMocks.when(userDAOInstance.getContactCostCenterForTicketDistro(userIds))
                    .thenReturn(users);
        userMocks.stopStubbing();

        fflib_ApexMocks accountMocks = new fflib_ApexMocks(); 

        AccountDAO.IAccountDAO accountDAOInstance;
        accountDAOInstance = new MockDAOs.AccountDAOMock(accountMocks);  

        accountMocks.startStubbing();
        accountMocks.when(accountDAOInstance.getProducerAccountsForTicketDistro(producerAccountIds, producerAccountRecordTypeId))
                    .thenReturn(producerAccounts);
        accountMocks.stopStubbing();

        accountMocks.startStubbing();
        accountMocks.when(accountDAOInstance.getGroupAccountsForTicketDistro(groupAccountIds, groupAccountRecordTypeId))
                    .thenReturn(groupAccounts);
        accountMocks.stopStubbing();

        fflib_ApexMocks ticketEventMocks = new fflib_ApexMocks(); 

        TicketEventDAO.ITicketEventDAO ticketEventDAOInstance;
        ticketEventDAOInstance = new MockDAOs.TicketEventDAOMock(ticketEventMocks);  

        ticketEventMocks.startStubbing();
        ticketEventMocks.when(ticketEventDAOInstance.insertTicketEvent(testEvent))
                    .thenReturn(testEvent);
        ticketEventMocks.stopStubbing();

        fflib_ApexMocks ticketGroupingMocks = new fflib_ApexMocks(); 

        TicketGroupingDAO.ITicketGroupingDAO ticketGroupingDAOInstance;
        ticketGroupingDAOInstance = new MockDAOs.TicketGroupingDAOMock(ticketGroupingMocks);  

        ticketGroupingMocks.startStubbing();
        ticketGroupingMocks.when(ticketGroupingDAOInstance.insertTicketGroupings(ticketGroupings))
                    .thenReturn(ticketGroupings);
        ticketGroupingMocks.stopStubbing();

        fflib_ApexMocks ticketMocks = new fflib_ApexMocks(); 

        TicketDAO.ITicketDAO ticketDAOInstance;
        ticketDAOInstance = new MockDAOs.TicketDAOMock(ticketMocks);  

        ticketMocks.startStubbing();
        ticketMocks.when(ticketDAOInstance.insertTickets(tickets))
                    .thenReturn(tickets);
        ticketMocks.stopStubbing();

        ApexPages.StandardController stdController = new ApexPages.StandardController(testEvent);
        TicketDistributionController ticketDistributionController = new TicketDistributionController(stdController, 
                                                                                                        ticketEventDAOInstance, 
                                                                                                            ticketDAOInstance, 
                                                                                                                ticketGroupingDAOInstance,
                                                                                                                    accountDAOInstance,
                                                                                                                        userDAOInstance);
        ticketDistributionController.ticketEventDAOInstance = ticketEventDAOInstance;
        ticketDistributionController.ticketDAOInstance = ticketDAOInstance;
        ticketDistributionController.ticketGroupingDAOInstance = ticketGroupingDAOInstance;
        ticketDistributionController.accountDAOInstance = accountDAOInstance;
        ticketDistributionController.userDAOInstance = userDAOInstance;
        
        ticketDistributionController.renderTickets();
        ticketDistributionController.ticketEvent.incrementalNumberOfTickets__c = 2;
        ticketDistributionController.singleTicket.Ticket_Price__c = 14;
        ticketDistributionController.singleTicket.Requestor_contact__c = testUser.Id;
        ticketDistributionController.singleTicket.Ticket_Type__c = 'Box';

        ticketDistributionController.generateTickets();

        System.assertEquals(ticketDistributionController.ticketGroupingWrapperList.size(), 1);

        ticketDistributionController.assignTicket.Business_Use_of_Ticket__c = 'Business';
        ticketDistributionController.assignTicket.assignToClient__c = true;
        ticketDistributionController.assignTicket.Client__c = testGroupAccount.Id;
        ticketDistributionController.ticketGroupingId = 1;
        ticketDistributionController.assignTickets();

        ticketDistributionController.ticketEvent.incrementalNumberOfTickets__c = 2;
        ticketDistributionController.singleTicket.Ticket_Price__c = 142;
        ticketDistributionController.singleTicket.Requestor_contact__c = testUser.Id;
        ticketDistributionController.singleTicket.Ticket_Type__c = 'Box';

        ticketDistributionController.generateTickets();

        ticketDistributionController.assignTicket.Business_Use_of_Ticket__c = 'Business';
        ticketDistributionController.assignTicket.assignToProducer__c = true;
        ticketDistributionController.assignTicket.Producer_For_Event__c = testProducerAccount.Id;
        ticketDistributionController.ticketGroupingId = 2;
        ticketDistributionController.assignTickets();

        ticketDistributionController.saveTickets();
        ticketDistributionController.cancel();
		ticketDistributionController.EventVenueAddress();
        ticketDistributionController.EventStateChange();
        
        System.assertEquals(ticketDistributionController.ticketGroupingWrapperList.size(), 2);

    }

    @isTest static void ticketDistributionEditTest() {

        Id groupAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        Id producerAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();

        List<Account> groupAccounts = new List<Account>();
        Set<Id> groupAccountIds = new Set<Id>();
        Account testGroupAccount = new Account();
        testGroupAccount.RecordTypeId = groupAccountRecordTypeId;
        testGroupAccount.External_ID__c = '1232';
        testGroupAccount.Id = fflib_IDGenerator.generate( Account.SObjectType );
        groupAccountIds.add(testGroupAccount.Id);
        groupAccounts.add(testGroupAccount);

        List<Account> producerAccounts = new List<Account>();
        Set<Id> producerAccountIds = new Set<Id>();
        Account testProducerAccount = new Account();
        testProducerAccount.RecordTypeId = producerAccountRecordTypeId;
        testProducerAccount.Tax_ID__c = '1234';
        testProducerAccount.Id = fflib_IDGenerator.generate( Account.SObjectType );
        producerAccountIds.add(testProducerAccount.Id);
        producerAccounts.add(testProducerAccount);

        Contact testContact = new Contact();
        testContact.Id = fflib_IDGenerator.generate(Contact.SObjectType);
    
        Ticket_Event__c testEvent = new Ticket_Event__c();
        testEvent.Id = fflib_IDGenerator.generate( Ticket_Event__c.SObjectType );
        testEvent.Name = 'Hockey Game';
       
        List<Ticket_Grouping__c> ticketGroupings = new List<Ticket_Grouping__c>();
        Ticket_Grouping__c ticketGrouping = new Ticket_Grouping__c();
        ticketGrouping.Id = fflib_IDGenerator.generate( Ticket_Grouping__c.SObjectType );
        ticketGrouping.Ticket_Event__c = testEvent.Id;
        ticketGroupings.add(ticketGrouping);

        List<Ticket__c> tickets = new List<Ticket__c>();
        Ticket__c ticket = new Ticket__c();
        ticket.Ticket_Event__c = testEvent.Id;
        ticket.Ticket_Grouping__c = ticketGrouping.Id;
        ticket.Id = fflib_IDGenerator.generate( Ticket__c.SObjectType );
        tickets.add(ticket);

        List<User> users = new List<User>();
        Set<Id> userIds = new Set<Id>();
        User testUser = new User();
        testUser.FirstName ='Nick';
        testUser.LastName ='Serafin';
        testUser.Email = 'testing@example.com';
        testUser.Cost_Center__c = '1231252';
        testUser.Id = fflib_IDGenerator.generate( User.SObjectType );
        userIds.add(testUser.Id);
        users.add(testUser);

        PageReference pageRef = new PageReference('/apex/TicketDistribution');
        pageRef.getParameters().put('ticketId', testEvent.Id);
        Test.setCurrentPage(pageRef);

        List<Ticket_Grouping__c> ticketGroupingRelationship = (List<Ticket_Grouping__c>)
        MockRelationshipHelper.makeRelationship(
            List<Ticket_Grouping__c>.class,
        new List<Ticket_Grouping__c> {ticketGrouping},
        Ticket__c.Ticket_Grouping__c,
        new List<List<Ticket__c>> {tickets});

        fflib_ApexMocks userMocks = new fflib_ApexMocks(); 

        UserDAO.IUserDAO userDAOInstance;
        userDAOInstance = new MockDAOs.UserDAOMock(userMocks);  

        userMocks.startStubbing();
        userMocks.when(userDAOInstance.getRequesterForTicketDistro(testUser.Id))
                    .thenReturn(testUser);
        userMocks.stopStubbing();

        userMocks.startStubbing();
        userMocks.when(userDAOInstance.getContactCostCenterForTicketDistro(userIds))
                    .thenReturn(users);
        userMocks.stopStubbing();

        fflib_ApexMocks accountMocks = new fflib_ApexMocks(); 

        AccountDAO.IAccountDAO accountDAOInstance;
        accountDAOInstance = new MockDAOs.AccountDAOMock(accountMocks);  

        accountMocks.startStubbing();
        accountMocks.when(accountDAOInstance.getProducerAccountsForTicketDistro(producerAccountIds, producerAccountRecordTypeId))
                    .thenReturn(producerAccounts);
        accountMocks.stopStubbing();

        accountMocks.startStubbing();
        accountMocks.when(accountDAOInstance.getGroupAccountsForTicketDistro(groupAccountIds, groupAccountRecordTypeId))
                    .thenReturn(groupAccounts);
        accountMocks.stopStubbing();

        fflib_ApexMocks ticketEventMocks = new fflib_ApexMocks(); 

        TicketEventDAO.ITicketEventDAO ticketEventDAOInstance;
        ticketEventDAOInstance = new MockDAOs.TicketEventDAOMock(ticketEventMocks);  

        ticketEventMocks.startStubbing();
        ticketEventMocks.when(ticketEventDAOInstance.grabTicketEventObj(testEvent.Id))
                    .thenReturn(testEvent);
        ticketEventMocks.stopStubbing();

        ticketEventMocks.startStubbing();
        ticketEventMocks.when(ticketEventDAOInstance.updateTicketEvent(testEvent))
                    .thenReturn(testEvent);
        ticketEventMocks.stopStubbing();

        fflib_ApexMocks ticketGroupingMocks = new fflib_ApexMocks(); 

        TicketGroupingDAO.ITicketGroupingDAO ticketGroupingDAOInstance;
        ticketGroupingDAOInstance = new MockDAOs.TicketGroupingDAOMock(ticketGroupingMocks);  

        ticketGroupingMocks.startStubbing();
        ticketGroupingMocks.when(ticketGroupingDAOInstance.grabTicketGroupings(testEvent.Id))
                    .thenReturn(ticketGroupingRelationship);
        ticketGroupingMocks.stopStubbing();

        ticketGroupingMocks.startStubbing();
        ticketGroupingMocks.when(ticketGroupingDAOInstance.upsertTicketGroupings(ticketGroupings))
                    .thenReturn(ticketGroupings);
        ticketGroupingMocks.stopStubbing();

        ticketGroupingMocks.startStubbing();
        ticketGroupingMocks.when(ticketGroupingDAOInstance.deleteTicketGrouping(ticketGrouping))
                    .thenReturn(ticketGrouping);
        ticketGroupingMocks.stopStubbing();

        fflib_ApexMocks ticketMocks = new fflib_ApexMocks(); 

        TicketDAO.ITicketDAO ticketDAOInstance;
        ticketDAOInstance = new MockDAOs.TicketDAOMock(ticketMocks);  

        ticketMocks.startStubbing();
        ticketMocks.when(ticketDAOInstance.upsertTickets(tickets))
                    .thenReturn(tickets);
        ticketMocks.stopStubbing();

        ticketMocks.startStubbing();
        ticketMocks.when(ticketDAOInstance.deleteTickets(tickets))
                    .thenReturn(tickets);
        ticketMocks.stopStubbing();

        ApexPages.StandardController stdController = new ApexPages.StandardController(testEvent);
        TicketDistributionController ticketDistributionController = new TicketDistributionController(stdController, 
                                                                                                        ticketEventDAOInstance, 
                                                                                                            ticketDAOInstance, 
                                                                                                                ticketGroupingDAOInstance,
                                                                                                                    accountDAOInstance,
                                                                                                                        userDAOInstance);
        ticketDistributionController.ticketEventDAOInstance = ticketEventDAOInstance;
        ticketDistributionController.ticketDAOInstance = ticketDAOInstance;
        ticketDistributionController.ticketGroupingDAOInstance = ticketGroupingDAOInstance;
        ticketDistributionController.accountDAOInstance = accountDAOInstance;
        ticketDistributionController.userDAOInstance = userDAOInstance;
        
        ticketDistributionController.renderTickets();
        ticketDistributionController.ticketEvent.incrementalNumberOfTickets__c = 2;
        ticketDistributionController.singleTicket.Ticket_Price__c = 14;
        ticketDistributionController.singleTicket.Requestor_contact__c = testUser.Id;
        ticketDistributionController.singleTicket.Ticket_Type__c = 'Box';

        ticketDistributionController.generateTickets();

        ticketDistributionController.assignTicket.Business_Use_of_Ticket__c = 'Business';
        ticketDistributionController.assignTicket.assignToClient__c = true;
        ticketDistributionController.assignTicket.Client__c = testGroupAccount.Id;
        ticketDistributionController.ticketGroupingId = 1;
        ticketDistributionController.assignTickets();

        ticketDistributionController.ticketEvent.incrementalNumberOfTickets__c = 2;
        ticketDistributionController.singleTicket.Ticket_Price__c = 142;
        ticketDistributionController.singleTicket.Requestor_contact__c = testUser.Id;
        ticketDistributionController.singleTicket.Ticket_Type__c = 'Box';

        ticketDistributionController.generateTickets();

        ticketDistributionController.assignTicket.Business_Use_of_Ticket__c = 'Business';
        ticketDistributionController.assignTicket.assignToProducer__c = true;
        ticketDistributionController.assignTicket.Producer_For_Event__c = testProducerAccount.Id;
        ticketDistributionController.ticketGroupingId = 2;
        ticketDistributionController.assignTickets();

        ticketDistributionController.saveTickets();
        ticketDistributionController.cancel();

        ticketDistributionController.ticketEvent.incrementalNumberOfTickets__c = 2;
        ticketDistributionController.singleTicket.Ticket_Price__c = 111;
        ticketDistributionController.singleTicket.Requestor_contact__c = testUser.Id;
        ticketDistributionController.singleTicket.Ticket_Type__c = 'Box';

        ticketDistributionController.generateTickets();

        ticketDistributionController.assignTicket.Business_Use_of_Ticket__c = 'Personal';
        ticketDistributionController.assignTicket.assignToEmployee__c = true;
        ticketDistributionController.assignTicket.Contact__c = testContact.Id;
        ticketDistributionController.ticketGroupingId = 3;
        ticketDistributionController.ticketGroupingObjId = 3;
        ticketDistributionController.assignTickets();
        ticketDistributionController.deleteTickets();

        ticketDistributionController.saveTickets();

        System.assertEquals(ticketDistributionController.ticketGroupingWrapperList.size(), 1);

    }
     @isTest static void ticketDistributionChangeRequesterTest() {

        Id groupAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId();
        Id producerAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Producer Account').getRecordTypeId();

        List<Account> groupAccounts = new List<Account>();
        Set<Id> groupAccountIds = new Set<Id>();
        Account testGroupAccount = new Account();
        testGroupAccount.RecordTypeId = groupAccountRecordTypeId;
        testGroupAccount.External_ID__c = '1232';
        testGroupAccount.Id = fflib_IDGenerator.generate( Account.SObjectType );
        groupAccountIds.add(testGroupAccount.Id);
        groupAccounts.add(testGroupAccount);

        List<Account> producerAccounts = new List<Account>();
        Set<Id> producerAccountIds = new Set<Id>();
        Account testProducerAccount = new Account();
        testProducerAccount.RecordTypeId = producerAccountRecordTypeId;
        testProducerAccount.Tax_ID__c = '1234';
        testProducerAccount.Id = fflib_IDGenerator.generate( Account.SObjectType );
        producerAccountIds.add(testProducerAccount.Id);
        producerAccounts.add(testProducerAccount);

        Contact testContact = new Contact();
        testContact.Id = fflib_IDGenerator.generate(Contact.SObjectType);
    
        Ticket_Event__c testEvent = new Ticket_Event__c();
        testEvent.Id = fflib_IDGenerator.generate( Ticket_Event__c.SObjectType );
        testEvent.Name = 'Hockey Game';       
        testEvent.Event_Venue_Name__c = 'AT & T Center';
        testEvent.Event_Street_Address__c = '14888 palm desrt ln';
        testEvent.Event_City__c = 'Frisco';
        testEvent.Event_State__c = 'TX';        
        testEvent.Event_Zip_Postal_Code__c = '75035';
        
        List<Ticket_Grouping__c> ticketGroupings = new List<Ticket_Grouping__c>();
        Ticket_Grouping__c ticketGrouping = new Ticket_Grouping__c();
        ticketGrouping.Id = fflib_IDGenerator.generate( Ticket_Grouping__c.SObjectType );
        ticketGrouping.Ticket_Event__c = testEvent.Id;
        ticketGroupings.add(ticketGrouping);

        List<Ticket__c> tickets = new List<Ticket__c>();
        Ticket__c ticket = new Ticket__c();
        ticket.Ticket_Event__c = testEvent.Id;
        ticket.Ticket_Grouping__c = ticketGrouping.Id;
        ticket.Id = fflib_IDGenerator.generate( Ticket__c.SObjectType );
        tickets.add(ticket);

        List<User> users = new List<User>();
        Set<Id> userIds = new Set<Id>();
        User testUser = new User();
        testUser.FirstName ='Nick';
        testUser.LastName ='Serafin';
        testUser.Email = 'testing@example.com';
        testUser.Cost_Center__c = '1231252';
        testUser.Id = fflib_IDGenerator.generate( User.SObjectType );
        userIds.add(testUser.Id);
        users.add(testUser);
         
         User testUser1 = new User();
        testUser1.FirstName ='Jonny';
        testUser1.LastName ='Serafin';
        testUser1.Email = 'testing@example.com';
        testUser1.Cost_Center__c = '1231252';
        testUser1.Id = fflib_IDGenerator.generate( User.SObjectType );
        userIds.add(testUser1.Id);
        users.add(testUser1);
         
        Contact testUser2 = new Contact();
        testUser2.Id=fflib_IDGenerator.generate(Contact.SObjectType);
       

        PageReference pageRef = new PageReference('/apex/TicketDistribution');
        pageRef.getParameters().put('ticketId', testEvent.Id);
        Test.setCurrentPage(pageRef);

        List<Ticket_Grouping__c> ticketGroupingRelationship = (List<Ticket_Grouping__c>)
        MockRelationshipHelper.makeRelationship(
            List<Ticket_Grouping__c>.class,
        new List<Ticket_Grouping__c> {ticketGrouping},
        Ticket__c.Ticket_Grouping__c,
        new List<List<Ticket__c>> {tickets});

        fflib_ApexMocks userMocks = new fflib_ApexMocks(); 

        UserDAO.IUserDAO userDAOInstance;
        userDAOInstance = new MockDAOs.UserDAOMock(userMocks);  

        userMocks.startStubbing();
        userMocks.when(userDAOInstance.getRequesterForTicketDistro(testUser.Id))
                    .thenReturn(testUser);
        userMocks.stopStubbing();

        userMocks.startStubbing();
        userMocks.when(userDAOInstance.getContactCostCenterForTicketDistro(userIds))
                    .thenReturn(users);
        userMocks.stopStubbing();

        fflib_ApexMocks accountMocks = new fflib_ApexMocks(); 

        AccountDAO.IAccountDAO accountDAOInstance;
        accountDAOInstance = new MockDAOs.AccountDAOMock(accountMocks);  

        accountMocks.startStubbing();
        accountMocks.when(accountDAOInstance.getProducerAccountsForTicketDistro(producerAccountIds, producerAccountRecordTypeId))
                    .thenReturn(producerAccounts);
        accountMocks.stopStubbing();

        accountMocks.startStubbing();
        accountMocks.when(accountDAOInstance.getGroupAccountsForTicketDistro(groupAccountIds, groupAccountRecordTypeId))
                    .thenReturn(groupAccounts);
        accountMocks.stopStubbing();

        fflib_ApexMocks ticketEventMocks = new fflib_ApexMocks(); 

        TicketEventDAO.ITicketEventDAO ticketEventDAOInstance;
        ticketEventDAOInstance = new MockDAOs.TicketEventDAOMock(ticketEventMocks);  

        ticketEventMocks.startStubbing();
        ticketEventMocks.when(ticketEventDAOInstance.grabTicketEventObj(testEvent.Id))
                    .thenReturn(testEvent);
        ticketEventMocks.stopStubbing();

        ticketEventMocks.startStubbing();
        ticketEventMocks.when(ticketEventDAOInstance.updateTicketEvent(testEvent))
                    .thenReturn(testEvent);
        ticketEventMocks.stopStubbing();

        fflib_ApexMocks ticketGroupingMocks = new fflib_ApexMocks(); 

        TicketGroupingDAO.ITicketGroupingDAO ticketGroupingDAOInstance;
        ticketGroupingDAOInstance = new MockDAOs.TicketGroupingDAOMock(ticketGroupingMocks);  

        ticketGroupingMocks.startStubbing();
        ticketGroupingMocks.when(ticketGroupingDAOInstance.grabTicketGroupings(testEvent.Id))
                    .thenReturn(ticketGroupingRelationship);
        ticketGroupingMocks.stopStubbing();

        ticketGroupingMocks.startStubbing();
        ticketGroupingMocks.when(ticketGroupingDAOInstance.upsertTicketGroupings(ticketGroupings))
                    .thenReturn(ticketGroupings);
        ticketGroupingMocks.stopStubbing();

        ticketGroupingMocks.startStubbing();
        ticketGroupingMocks.when(ticketGroupingDAOInstance.deleteTicketGrouping(ticketGrouping))
                    .thenReturn(ticketGrouping);
        ticketGroupingMocks.stopStubbing();

        fflib_ApexMocks ticketMocks = new fflib_ApexMocks(); 

        TicketDAO.ITicketDAO ticketDAOInstance;
        ticketDAOInstance = new MockDAOs.TicketDAOMock(ticketMocks);  

        ticketMocks.startStubbing();
        ticketMocks.when(ticketDAOInstance.upsertTickets(tickets))
                    .thenReturn(tickets);
        ticketMocks.stopStubbing();

        ticketMocks.startStubbing();
        ticketMocks.when(ticketDAOInstance.deleteTickets(tickets))
                    .thenReturn(tickets);
        ticketMocks.stopStubbing();

        ApexPages.StandardController stdController = new ApexPages.StandardController(testEvent);
        TicketDistributionController ticketDistributionController = new TicketDistributionController(stdController, 
                                                                                                        ticketEventDAOInstance, 
                                                                                                            ticketDAOInstance, 
                                                                                                                ticketGroupingDAOInstance,
                                                                                                                    accountDAOInstance,
                                                                                                                        userDAOInstance);
        ticketDistributionController.ticketEventDAOInstance = ticketEventDAOInstance;
        ticketDistributionController.ticketDAOInstance = ticketDAOInstance;
        ticketDistributionController.ticketGroupingDAOInstance = ticketGroupingDAOInstance;
        ticketDistributionController.accountDAOInstance = accountDAOInstance;
        ticketDistributionController.userDAOInstance = userDAOInstance;
        
        ticketDistributionController.renderTickets();
        ticketDistributionController.ticketEvent.incrementalNumberOfTickets__c = 2;
        ticketDistributionController.singleTicket.Ticket_Price__c = 14;
        ticketDistributionController.singleTicket.Requestor_contact__c = testUser.Id;
        ticketDistributionController.singleTicket.Ticket_Type__c = 'Box';

        ticketDistributionController.generateTickets();
         
       // ticketDistributionController.ticketEvent.incrementalNumberOfTickets__c = 2;
        ticketDistributionController.singleTicket.Ticket_Price__c = 14;
        ticketDistributionController.singleTicket.Requestor_contact__c = testUser.Id;
        ticketDistributionController.singleTicket.Ticket_Type__c = 'Box';

        ticketDistributionController.generateTickets();
		
        ticketDistributionController.assignTicket.Business_Use_of_Ticket__c = 'Business';
        ticketDistributionController.assignTicket.assignToClient__c = true;
        ticketDistributionController.assignTicket.Client__c = testGroupAccount.Id;
        ticketDistributionController.ticketGroupingId = 1;
        ticketDistributionController.assignTickets();
		ticketDistributionController.singleTicket.Requestor_contact__c = testUser1.Id;
        ticketDistributionController.changeTicketRequestor();
        //ticketEventDAOInstance.updateTicketEvent tEDAOIUp = new ticketEventDAOInstance.updateTicketEvent();
        ticketEventDAOInstance.updateTicketEvent(testEvent);
         
        ticketDistributionController.assignTicket.Business_Use_of_Ticket__c = 'Business';
        ticketDistributionController.assignTicket.assignToClient__c = true;
        ticketDistributionController.assignTicket.Client__c = testGroupAccount.Id;
        ticketDistributionController.ticketGroupingId = 1;
        ticketDistributionController.assignTickets();
		ticketDistributionController.singleTicket.Requestor_contact__c = testUser2.Id;
        ticketDistributionController.changeTicketRequestor();
         
        ticketDistributionController.ticketEvent.incrementalNumberOfTickets__c = 2;
        ticketDistributionController.singleTicket.Ticket_Price__c = 142;
        ticketDistributionController.singleTicket.Requestor_contact__c = testUser.Id;
        ticketDistributionController.singleTicket.Ticket_Type__c = 'Box';

        ticketDistributionController.generateTickets();

        ticketDistributionController.assignTicket.Business_Use_of_Ticket__c = 'Business';
        ticketDistributionController.assignTicket.assignToProducer__c = true;
        ticketDistributionController.assignTicket.Producer_For_Event__c = testProducerAccount.Id;
        ticketDistributionController.ticketGroupingId = 2;
        ticketDistributionController.assignTickets();

        ticketDistributionController.saveTickets();
         //testUser1
        ticketDistributionController.cancel();

        ticketDistributionController.ticketEvent.incrementalNumberOfTickets__c = 2;
        ticketDistributionController.singleTicket.Ticket_Price__c = 111;
        ticketDistributionController.singleTicket.Requestor_contact__c = testUser.Id;
        ticketDistributionController.singleTicket.Ticket_Type__c = 'Box';

        ticketDistributionController.generateTickets();

        ticketDistributionController.assignTicket.Business_Use_of_Ticket__c = 'Personal';
        ticketDistributionController.assignTicket.assignToEmployee__c = true;
        ticketDistributionController.assignTicket.Contact__c = testContact.Id;
        ticketDistributionController.ticketGroupingId = 3;
        ticketDistributionController.ticketGroupingObjId = 3;
        ticketDistributionController.assignTickets();
        ticketDistributionController.deleteTickets();
		
        ticketDistributionController.saveTickets();

        System.assertEquals(ticketDistributionController.ticketGroupingWrapperList.size(), 1);

    }
   
}