src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Hold_End_Date__c</fullName>
        <label>Hold End Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>renewal_duration_is_infinite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indefinite Hold</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Actuary_Gate__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Gate Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Up</fullName>
                </value>
                <value>
                    <fullName>Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Gate</label>
    <nameField>
        <displayFormat>G-{000}</displayFormat>
        <label>Gate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_Dental_Members__c</fullName>
        <description>This field is used to capture the expected number of dental members for the opportunity.</description>
        <inlineHelpText>Expected Dental Members can be managed with the opportunities products. Please manage the membership of the products associated with this opportunity to update the number of Expected Dental Members</inlineHelpText>
        <label>Expected Dental Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Health_Members__c</fullName>
        <description>This field is used to capture the expected number of health members for the opportunity.</description>
        <inlineHelpText>Expected Health Members can be managed with the opportunities products. Please manage the membership of the products associated with this opportunity to update the number of Expected Health Members</inlineHelpText>
        <label>Expected Health Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Gate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gate</label>
        <referenceTo>Actuary_Gate__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Workflow_Status__c</fullName>
        <label>Workflow Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>UW Review</fullName>
                </value>
                <value>
                    <fullName>UW Pended</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SGR_GateOptyStatusChangeController.cls
/**************************************************************************************
Apex Class Name     : SGR_GateOptyStatusChangeController  
Version             : 1.0
Function            : This is controller class for GateoptyStatusChange Component.
Modification Log    :
* Developer:                   Date  : 02/10/2018               Description
* Developer:Nidhi Reddy        Date  : 10/3/2018                  Description
* ----------------------------------------------------------------------------               
*************************************************************************************/
public class SGR_GateOptyStatusChangeController {
    @AuraEnabled Public static List<OptyWrapper> getOptyList(string GateId){
        list<OptyWrapper> RetOptyList = new list<OptyWrapper>();
        //Processing optys of current gate
        //Nidhi: replaced accountnumber with external_ID__c 
        for(Opportunity opty:[SELECT Gate__r.Status__c,Account.hold_end_date__c,Account.renewal_duration_is_infinite__c,Account.Renewal_Date__c,Account.Status__c,SGR_Workflow_Status__c,Name, Account.Name, Account.external_ID__c, RecordType.Name, Renewal_Date__c, Rating_Status__c, Expected_Health_Members__c, Expected_Dental_Members__c, LastModifiedBy.Name FROM Opportunity where Gate__c= :GateId ORDER BY Renewal_Date__c]){
            //Creating new wrapper 
            OptyWrapper ow = new OptyWrapper();
            ow.GateStatus = opty.Gate__r.Status__c;//Assign GateStatus
            ow.RenewalDurationInfinite = opty.Account.renewal_duration_is_infinite__c;//Assign 
            ow.AccountHoldDate = opty.Account.hold_end_date__c;//Assign
            ow.AccountRenewalDate = opty.Account.Renewal_Date__c;//Assign
            ow.AccountStatus = opty.Account.Status__c;//Assign
            ow.SGRWorkflowStatus = opty.SGR_Workflow_Status__c;//Assign SGR work flow status
            ow.AccountName=opty.Account.Name;//Assign Account name
            //ow.RecordTypeName=opty.RecordType.Name;
            ow.RenewalDate=opty.Renewal_Date__c;//Assign Renewal date
            //ow.external_ID__c=opty.account.external_ID__c;
            //ow.ExpectedHealthMembers=opty.Expected_Dental_Members__c;
            ow.isSelected=false;//Assign Checkbox
            ow.OptyId=opty.Id;//Assign Opty id
            ow.Name=opty.Name;//Assign Opty name
            ow.RatingStatus = opty.Rating_Status__c;//Assign Rating status
            ///ow.LastModifiedbyName=opty.LastModifiedBy.Name;
            //ow.ExpectedDentalMembers=opty.Expected_Dental_Members__c;
            RetOptyList.add(ow);//Adding wrapper to wrapper list 
        }
        //Returning Wrapper list
        return RetOptyList;
    }
    
    @AuraEnabled
    public static List<Opportunity> getSelectedOpty(List<Id> Ids){
        return [select id,Name,Rating_Status__c,Gate__r.Status__c,SGR_Workflow_Status__c,Account.Name from Opportunity
                where id=:Ids];
    }
    
    @AuraEnabled Public static List<Opportunity> processSelectedOptys(List<Opportunity> SelOptyRecords){
        list<Opportunity> OptyListToUpdate = new list<Opportunity>();
        if(!SelOptyRecords.isEmpty()){
            for(Opportunity  opp : SelOptyRecords){
                opp.Rating_Status__c='Actuarial-Released';
                OptyListToUpdate.add(opp);
            }
        }
        try{
            update OptyListToUpdate;
            return OptyListToUpdate;
        }
        catch(Exception e){
            return null;
        }
    } 
    //Wrapper class for opty list
    public class OptyWrapper{
        @AuraEnabled public String GateStatus {get;set;}
        @AuraEnabled public boolean RenewalDurationInfinite {get;set;}
        //SFDC-15482Bug-AccountHoldDate data type changed from Datetime to Date
        @AuraEnabled public Date AccountHoldDate {get;set;}
        @AuraEnabled public date AccountRenewalDate {get;set;}
        @AuraEnabled public String AccountStatus {get;set;}
        @AuraEnabled public String SGRWorkflowStatus {get;set;} 
        @AuraEnabled public String OptyId {get;set;}
        @AuraEnabled public String Name {get;set;}
        @AuraEnabled public String AccountName {get;set;}
        //@AuraEnabled public String AccountNumber {get;set;}
        //@AuraEnabled public String RecordTypeName {get;set;}
        @AuraEnabled public date RenewalDate {get;set;}
        @AuraEnabled public String RatingStatus {get;set;}
        //@AuraEnabled public double ExpectedHealthMembers {get;set;}
        //@AuraEnabled public double ExpectedDentalMembers {get;set;}
        //@auraEnabled Public string LastModifiedbyName {get;set;}
        @AuraEnabled public boolean isSelected {get;set;}
    }
}