src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>This field is used to capture the funding type(s) of a Prospect or Group Account.</description>
        <label>Funding Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>NDSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Hold_End_Date__c</fullName>
        <label>Hold End Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
                <value>
                    <fullName>SG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Business need is to show the products that were renewed for the account last year.</description>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Market_Segment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Segment Picklist values from Account</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <label>Market Segment</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PREM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HDV</fullName>
                </value>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Renewal_Account_Name__c</fullName>
        <label>Renewal Account Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Renewal</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>Opportunity record type for HCSC renewal sales</description>
        <label>Renewal</label>
    </recordTypes>
    <recordTypes>
        <fullName>SGR_Production_Opportunity</fullName>
        <active>true</active>
        <businessProcess>Renewal Sales Process</businessProcess>
        <description>SGR Oppurtunity Record Type</description>
        <label>SGR Production Opportunity</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Plan__c.object
<CustomObject>
    <description>To capture all the plans related to products - Loaded from BlueStar</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External id for integration with BlueStar.</description>
        <externalId>true</externalId>
        <inlineHelpText>REQUIRED for user to submit plan to BlueSTAR must be the corp plan ID from BlueSTAR</inlineHelpText>
        <label>Plan Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SGR_Opportunity_Plan_Rate__c.object
<CustomObject>
    <description>This object contains details about opportunity plan Rates.</description>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <label>Funding Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Alternate</fullName>
                </value>
                <value>
                    <fullName>Alternative</fullName>
                    <isActive>false</isActive>
                    <label>Alternative</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Plan Rate</label>
    <nameField>
        <label>Opportunity Plan Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Plan Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>market segment user belongs to</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Small Group</fullName>
                </value>
                <value>
                    <fullName>Mid Market</fullName>
                </value>
                <value>
                    <fullName>Large Group</fullName>
                </value>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SGR_BlueStarTransferCallout_Test.cls
@isTest(SeeAlldata = false)
public class SGR_BlueStarTransferCallout_Test {
    
    @testSetup 
    public static void setupData() {
        Profile prof = [select id from profile where name='SGR UW User'];
        
        system.debug('****'+prof);
        User u = new User(
            Alias = 'sTest', 
            Email='Tetr@testorg.com',
            EmailEncodingKey='UTF-8',
            LastName='Tering1',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = prof.Id,
            TimeZoneSidKey='America/Los_Angeles',
            UserName='Ostusu@testorg.com'
        );
        List<Account> accList = new List<Account>();
        Account a = new Account(Name = 'Test Account', hold_end_date__c = date.today().addMonths(-3), HCSC_Division__c='IL', Market_Segment__c='SG', 
                                Funding_Type__c='PREM', Renewal_Date__c = date.Today(), Product_Type__c='H', AccountNumber = '12345',
                                External_ID__c='124343');
        accList.add(a);
        Account a1 = new Account(Name = 'Test Account1', hold_end_date__c = date.today().addMonths(-3), HCSC_Division__c='IL', Market_Segment__c='SG', 
                                 Funding_Type__c='PREM', Renewal_Date__c = date.Today(), Product_Type__c='H', AccountNumber = '123456' );
        accList.add(a1);
        insert accList;
        
        Id sgrProdOppRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('SGR_Production_Opportunity').getRecordTypeId();
        List<opportunity> oplist = new List<opportunity>();
        opportunity opp = new opportunity();
        opp.Accountid = a.id;
        opp.Name = 'Sample Opp';
        opp.SGR_Renewal_Account_Name__c='STORYLINE RENOVATIONS, LLC';
        opp.HCSC_Division__c = 'IL';
        opp.Funding_Type__c = 'PREM';
        opp.Account_Market_Segment__c ='SG';
        opp.StageName = 'Triggered';
        opp.Renewal_Date__c = System.today().addDays(4);
        opp.CloseDate = System.today().addMonths(1);
        opp.RecordTypeId = sgrProdOppRecTypeId;
        opp.Rating_Status__c = 'Sold';
        opp.Assigned_UW__c = userinfo.getuserid();
        
        opportunity opp1 = new opportunity();
        opp1.Accountid = a1.id;
        opp1.Name = 'Sample Opp';
        opp1.SGR_Renewal_Account_Name__c='STORYLINE RENOVATIONS, LLC';
        opp1.HCSC_Division__c = 'IL';
        opp1.Funding_Type__c = 'PREM';
        opp1.Account_Market_Segment__c ='SG';
        opp1.StageName = 'Triggered';
        opp1.Renewal_Date__c = System.today().addDays(4);
        opp1.CloseDate = System.today().addMonths(1);
        opp1.RecordTypeId = sgrProdOppRecTypeId;
        opp1.Rating_Status__c = 'Sold';
        opp1.Assigned_UW__c = userinfo.getuserid();
        oplist.add(opp1); 
        
        insert oplist;
		
        
        List<Plan__c> plans = new List<Plan__c>();
        Plan__c PPOPlan = new Plan__c(name='Plan1',Network__c='PPO');
        plans.add(PPOPlan);
        
        Plan__c HMOPlan = new Plan__c(name='Plan1',Network__c='HMO');
        plans.add(HMOPlan);
        insert plans;
        List<SGR_Opportunity_Plan_Rate__c> planRateRecs = new List<SGR_Opportunity_Plan_Rate__c>();                                                                       
        SGR_Opportunity_Plan_Rate__c planRate1 = new SGR_Opportunity_Plan_Rate__c(Name='Plan Rate1', Opportunity__c=opp.id, Type__c='Renewal', Plan__c=PPOPlan.Id); 
        planRate1.Marketing_Plan_ID__c = 'SPSG15BCASTXO';
        planRate1.Plan_Status__c = 'Sold';
        planRateRecs.add(planRate1);
        SGR_Opportunity_Plan_Rate__c planRate2 = new SGR_Opportunity_Plan_Rate__c(Name='Plan Rate2', Opportunity__c=opp.id, Type__c='Renewal', Plan__c=HMOPlan.Id);                                                                         
        planRateRecs.add(planRate2);
        insert planRateRecs;
        
    }
    
    Public static testmethod void Validte_BlueSTARRequest(){
        try{
            Set<Id> oppIds = new Set<Id>();
            
            Opportunity o =[Select id,Account_Market_Segment__c from Opportunity Limit 1];
            oppIds.add(o.id);
            system.debug('o in Test Class method Validte_BlueSTARRequest():::::'+o);
            Test.loadData(Username_Password__c.sObjectType,'UserNamePasswordTestData');          
            Test.starttest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorSGR_blueStar()); 
            SGR_BlueStarTransferCallout.sendPlanOrRateChangeReqListToBStar(oppIds);
            SGR_BlueStarTransferCallout.isValidOpp(o); 
            SGR_BlueStarTransferCallout sgrCallout = new SGR_BlueStarTransferCallout();
            sgrCallout.createXMLDoc(o);
            Case c = SGR_BlueStarTransferCallout.getBlueStarCaseDefaultsByOpportunity(o);
            
            Test.stoptest();
        }
        catch(exception ex){
            System.debug('Exception while running test class : '+ex.getmessage());
        }
    }
    Public static testmethod void parseResponseXMLTest(){
        string responseBody=
            '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">'+
            '<soap:Body>'+
            '<ns2:executeResponse xmlns:ns2="http://accountapplication1.xplservice.commonservices.bluestar.hcsc.com/">'+
            '<AutomatedPlanChangeServiceResponse>'+  
            '<corpEntCd>TX1</corpEntCd>'+     
            '<acctNbr>219371</acctNbr>'+     
            '<opportunityId>317789</opportunityId>'+     
            '<modNbr>0</modNbr>'+    
            '<rtSzUpdateTxt>account rtSzCd not updated</rtSzUpdateTxt>'+    
            '<planResponses>'+   
            '<planResponse>' +     
            '<mktgPlnNbr>SPSG15BCASTXO</mktgPlnNbr>'+         
            '<planExecutedSuccessFully>Y</planExecutedSuccessFully>'+        
            '<grpSectTab/>'+        
            '<messagesList>' +      
            '<message>'+           
            '<msgTxt>Benefit Agreement Number 0002 has been successfully Approved.</msgTxt>'+             
            '</message>'+          
            '</messagesList>'+      
            '</planResponse>'+  
            '</planResponses>'+  
            '</AutomatedPlanChangeServiceResponse>'+ 
            '</ns2:executeResponse>'+  
            '</soap:Body>'+ 
            '</soap:Envelope>';
        Test.startTest();
        SGR_BlueStarTransferCallout.parseResponseXML(responseBody); 
        Test.stopTest();
    }
    Public static testmethod void invalidOpp(){
        List<Opportunity> o =[Select id,Account_Market_Segment__c,Renewal_Date__c,SGR_Renewal_Account_Name__c,HCSC_Division__c,
                        Assigned_UW__c from Opportunity Limit 2];
        Test.startTest();
        SGR_BlueStarTransferCallout.isValidOpp(o[0]);
        Test.stopTest();
    }
    
}