src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Cancellation_Status__c</fullName>
        <description>This field is used to capture the status of a cancellation or reinstatement request for the Account.</description>
        <label>Cancellation/Reinstatement Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Cancellation Rejected</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Requested Cancellation</fullName>
                </value>
                <value>
                    <fullName>CancelPend</fullName>
                </value>
                <value>
                    <fullName>Cancelled with Future CD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>COBRA_Administration_Type__c</fullName>
        <description>This field is used to capture the COBRA Administration type as listed in BlueStar; GRP = Group Administers; HCSC = COBRA Admin Marion; OTHR = Non HCSC Vendor administers; N/A.</description>
        <label>COBRA Administration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GRP</fullName>
                </value>
                <value>
                    <fullName>HCSC</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>OTHR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>EIN__c</fullName>
        <description>This field is used to capture the Group Tax ID Number or Employer Identification Number of the Account.</description>
        <label>EIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Multiple_EINs__c</fullName>
        <formula>IF( EIN_Count__c &gt; 1, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Multiple EINs</label>
        <type>Checkbox</type>
    </fields>

objects/EIN__c.object
<CustomObject>
    <fields>
        <fullName>Bluestar_Transfer_Status__c</fullName>
        <label>Bluestar Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Due for Transfer</fullName>
                    <default>true</default>
                    <label>Due for Transfer</label>
                </value>
                <value>
                    <fullName>Transfer In Transit</fullName>
                </value>
                <value>
                    <fullName>Transfer Complete</fullName>
                </value>
                <value>
                    <fullName>Seq# Requested</fullName>
                </value>
                <value>
                    <fullName>Seq# updated</fullName>
                </value>
                <value>
                    <fullName>Wait BS Confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Employer Identification Number</label>
    <nameField>
        <label>Employer Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employer Identification Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Market_Segment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Segment Picklist values from Account</description>
    <label>Market Segment</label>
</CustomObject>

classes/LGNA_EIN_SendStart.cls
/**************************************************************************************
* Apex Class Name     : LGNA_EIN_SendStart 
* Version             : 1.0
* Function            : This class retrieves 
* Modification Log    :
* Developer           Date                   Description
* ----------------------------------------------------------------------------                 
* Bharath            04/12/2018             Original Version
*************************************************************************************/
public class LGNA_EIN_SendStart {
    
    /******************************************************************** 
*    Method Name : sendEINInvocable
*   @description : This method submits the EIN transmission as future method.
*   @parameters  : List of Account IDs.
*   @return type :   void 
*   @Author      : Bharath
***************************************************************/           
    @InvocableMethod
    public static void sendEINInvocable(List<Id> accIds){
        system.debug('Invocable method called sendEINInvocable');
        sendEINInFuture(accIds);
    }
    
    /******************************************************************** 
*    Method Name : sendEINInFuture
*   @description : This is a future method which calls the transmission method in loop.
*   @parameters  : List of Account IDs.
*   @return type :   void 
*   @Author      : Bharath
***************************************************************/               
    @future (callout=true)
    public static void sendEINInFuture(List<Id> accIds){
        system.debug('Invocable method called sendEINInFuture');
        for(Id accId : accIds){
            String result = LGNA_EIN_TransmitServiceHelper.sendEIN(accId);
        }
    }
    
    
    
    /******************************************************************** 
*    Method Name : fetchSeqNoInFuture
*   @description : This is a future method which calls the fetchSeqNo method
*   @parameters  : List of EIN records, account id
*   @return type :   void 
*   @Author      : Bharath
***************************************************************/               
    //@future (callout=true)
    public static String fetchEIN(List<Id> einIdList, Id accId){
        system.debug('Invocable method called fetchSeqNoInFuture');
        List<EIN__c> einList = [select id,name,Bluestar_Transfer_Status__c from EIN__c where Id in :einIdList];
        
        Account acc = [select id,Name,HCSC_Division__c,External_Id__c,Market_Segment__c, 
                       Effective_Date__c, Cancellation_Status__c,COBRA_Administration_Type__c, Multiple_EINs__c
                       from Account where Id =: accId ];
        
        return LGNA_EIN_TransmitServiceHelper.retrieveEIN(einList, acc);
        
    }
    
    
}