src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>COBRA_Administration_Type__c</fullName>
        <description>This field is used to capture the COBRA Administration type as listed in BlueStar; GRP = Group Administers; HCSC = COBRA Admin Marion; OTHR = Non HCSC Vendor administers; N/A.</description>
        <label>COBRA Administration Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GRP</fullName>
                </value>
                <value>
                    <fullName>HCSC</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>OTHR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>EIN__c</fullName>
        <description>This field is used to capture the Group Tax ID Number or Employer Identification Number of the Account.</description>
        <label>EIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>This field is used to capture the list of group numbers received during the account number reservations. Will be a semicolon separated list of values.</description>
        <label>Group Number</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Market_Segment__c</fullName>
        <description>This field is used to capture the Market segment to which the Account is associated.</description>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>HCSC_Division__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>ALI</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>COMA</fullName>
                </value>
                <value>
                    <fullName>CPAA</fullName>
                </value>
                <value>
                    <fullName>EAML</fullName>
                </value>
                <value>
                    <fullName>FEP</fullName>
                </value>
                <value>
                    <fullName>HA</fullName>
                </value>
                <value>
                    <fullName>HCS2</fullName>
                </value>
                <value>
                    <fullName>HMSG</fullName>
                </value>
                <value>
                    <fullName>HSC1</fullName>
                </value>
                <value>
                    <fullName>HWB</fullName>
                </value>
                <value>
                    <fullName>IMTL</fullName>
                </value>
                <value>
                    <fullName>IMTS</fullName>
                </value>
                <value>
                    <fullName>JG</fullName>
                </value>
                <value>
                    <fullName>LAN</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>LGC</fullName>
                </value>
                <value>
                    <fullName>LGL</fullName>
                </value>
                <value>
                    <fullName>LGN</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>MARL</fullName>
                </value>
                <value>
                    <fullName>MBIL</fullName>
                </value>
                <value>
                    <fullName>MCCL</fullName>
                </value>
                <value>
                    <fullName>MCUL</fullName>
                </value>
                <value>
                    <fullName>MGC</fullName>
                </value>
                <value>
                    <fullName>MGL</fullName>
                </value>
                <value>
                    <fullName>MINAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/EIN__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>EIN</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City1__c</fullName>
        <label>City</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Name__c</fullName>
        <label>Location Name</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street11__c</fullName>
        <label>Street 1</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street21__c</fullName>
        <label>Street 2</label>
        <type>TextArea</type>
    </fields>
    <label>Employer Identification Number</label>
    <nameField>
        <label>Employer Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employer Identification Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GEMS_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street2__c</fullName>
        <label>Street2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Usage__c</fullName>
        <label>Usage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Mailing</fullName>
                </value>
                <value>
                    <fullName>BAE</fullName>
                </value>
                <value>
                    <fullName>Subsidary</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>ThirdParty</fullName>
                </value>
                <value>
                    <fullName>Stlm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GEMS Address</label>
    <nameField>
        <label>Street</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LGNA_EIN_ConfirmTest.cls
@isTest(SeeAllData=false) 
public class LGNA_EIN_ConfirmTest {

    private static testmethod void TestEINConfirmController(){
        test.startTest();
        Account accRec = new Account();
        id rec =Schema.SObjectType.Account.getRecordTypeInfosByName().get('Group Account').getRecordTypeId(); 
        accRec.RecordTypeId = rec;
        accRec.Name = 'TestAccountForEIN';
        accRec.Group_Number__c= 'B06093';
        accRec.external_id__c= 'B06093';
        accRec.BillingStreet ='Testing';
        accRec.BillingCity='Houston';
        accRec.BillingState='TX';
        accRec.BillingPostalCode='77077';
        accRec.status__c = 'Active';
        accRec.Market_Segment__c = 'Tmp';
        accRec.AccountNumber = '01245678';                
        accRec.Effective_Date__c = system.today();
        accRec.HCSC_Division__c = 'TX';
        accRec.COBRA_Administration_Type__c = 'HCSC';
        insert accRec;
        //Following can be removed if we are facing soql 101 error. This helps with coverage of very few lines.
        LGNA_EIN_ConfirmControllerApx.returnEIN(accRec.Id);
        //LGNA_EIN_TransmitServiceHelper.sendEIN(accRec.Id);

        
        /*GEMS_Address__c addrRec1 = new GEMS_Address__c();
        addrRec1.Account__c = accRec.Id;
        addrRec1.Street2__c = 'Street1';
        addrRec1.City__c = 'City1';
        addrRec1.State__c = 'TX';
        addrRec1.Zip_Code__c = '77077';
        addrRec1.Contact_Name__c = 'Test1 Name';
        addrRec1.Contact_Email__c = 'test1@gmail.com';
        addrRec1.Contact_Phone__c = '1231231234';
        addrRec1.Usage__c = 'Billing';
        insert addrRec1;
        
        GEMS_Address__c addrRec2 = new GEMS_Address__c();
        addrRec2.Account__c = accRec.Id;
        addrRec2.Street2__c = 'Street2';
        addrRec2.City__c = 'City2';
        addrRec2.State__c = 'TX';
        addrRec2.Zip_Code__c = '77077';
        addrRec2.Contact_Name__c = 'Test2 Name';
        addrRec2.Contact_Email__c = 'test2@gmail.com';
        addrRec2.Contact_Phone__c = '1231231235';
        addrRec2.Usage__c = 'Primary';
        insert addrRec2;*/
        
        EIN__c einRec1 = new EIN__C();
        einRec1.Name = '565656565';
        einRec1.Account__c = accRec.id;
        einRec1.Effective_Date__c = system.today();
        einRec1.Location_Name__c = 'Test1';
        //Bharath0626
        einRec1.Street11__c = 'Street1';
        einRec1.Street21__c = 'Street1';
        einRec1.City1__c = 'City1';
        einRec1.State1__c = 'TX';
        einRec1.Zip_Code1__c = '77077';
        einRec1.County_Code1__c = 123;
        einRec1.Country1__c = 'US';        
        insert einRec1; 
        

        
		EIN__c einRec2 = new EIN__C();
        einRec2.Name = '232323232';
        einRec2.Account__c = accRec.id;
        einRec2.Effective_Date__c = system.today();
        einRec2.Location_Name__c = 'Test2';
        einRec2.Primary__c = true;
        einRec2.Street11__c = 'Street1';
        einRec2.Street21__c = 'Street1';
        einRec2.City1__c = 'City1';
        einRec2.State1__c = 'TX';
        einRec2.Zip_Code1__c = '77077';
        einRec2.County_Code1__c = 123;
       einRec2.Country1__c = 'US';        
        insert einRec2;               
        
        LGNA_EIN_ConfirmControllerApx.returnEIN(accRec.Id);
        LGNA_EIN_ConfirmControllerApx.sentEIN(accRec.Id);
        LGNA_EIN_ConfirmControllerApx.sendProgress(accRec.Id);
        LGNA_EIN_ConfirmControllerApx.transmitEIN(accRec.Id);
        LGNA_EIN_ConfirmControllerApx.returnEIN(null);
        LGNA_EIN_ConfirmControllerApx.sentEIN(null);
        LGNA_EIN_ConfirmControllerApx.sendProgress(null);   

		EIN__c einRec3 = new EIN__C();
        einRec3.Name = '676767676';
        einRec3.Account__c = accRec.id;
        einRec3.Effective_Date__c = system.today();
        einRec3.Location_Name__c = 'Test2';
        einRec3.Street11__c = 'Street1';
        einRec3.Street21__c = 'Street1';
        einRec3.City1__c = 'City1';
        einRec3.State1__c = 'TX';
        einRec3.Zip_Code1__c = '77077';
        einRec3.County_Code1__c = 123;
        einRec3.Country1__c = 'US';        
        insert einRec3;               

        einRec3.Bluestar_Transfer_Status__c = '';
        einRec3.change_reason__c = '';
        upsert einRec3;
        einRec3.Effective_Date__c = system.today() + 1;
        einRec3.Change_Reason__c = 'CHG';        
        upsert einRec3;
        LGNA_EIN_ConfirmControllerApx.transmitEIN(accRec.Id);

        EIN__c einRec4 = new EIN__C();
        einRec4.Name = '676767678';
        einRec4.Account__c = accRec.id;
        einRec4.Effective_Date__c = system.today();
        einRec4.Location_Name__c = 'Test2';
        einRec4.Street11__c = 'Street1';
        einRec4.Street21__c = 'Street1';
        einRec4.City1__c = 'City1';
        einRec4.State1__c = 'TX';
        einRec4.Zip_Code1__c = '77077';
        einRec4.County_Code1__c = 123;
        einRec4.Country1__c = 'US';  
        einRec4.EIN_Sequence_Number__c = 123;
        insert einRec4;        
        LGNA_EIN_TransmitServiceHelper.sendNewAcctEIN(accRec.Id);
        
        List<string> einList = new List<string>();
        einList.add('565656565');
        einList.add('676767676');
        einRec2.Bluestar_Transfer_Status__c = 'Wait BS Confirm';
        upsert einRec2;
        LGNA_EIN_TransmitServiceHelper.processResponse(accRec.Id,einList);
        
        einRec4.Bluestar_Transfer_Status__c = 'Wait BS Confirm';
        einRec3.Bluestar_Transfer_Status__c = 'Wait BS Confirm';
        LGNA_EIN_TransmitServiceHelper.resetEINs(accRec.Id);
        
        GEMS_AccountStructureCreateServiceInput testInput = new GEMS_AccountStructureCreateServiceInput();
        GEMS_AccountStructureCreateServiceInput.AccountEin einInput = new GEMS_AccountStructureCreateServiceInput.AccountEin();
        List<GEMS_AccountStructureCreateServiceInput.AccountEin> einInputList = new List<GEMS_AccountStructureCreateServiceInput.AccountEin>();
        einInput.einNbr = '565656565';
        einInput.einEffDt = system.today();
        einInput.einSeqNbr = 1234;
        einInputList.add(einInput);
        einInput.einNbr = '676767678';
        einInput.einEffDt = system.today();
        einInput.einSeqNbr = 1234;
        einInputList.add(einInput);
        einInput.einNbr = '676767678';
        einInput.einEffDt = system.today() + 1;
        einInput.einSeqNbr = 1235;
        einInputList.add(einInput);        
        testInput.acctEin = einInputList;
        testInput.status = 'S';
        GEMS_AccountStructureCreateServiceOutput testOutput = LGNA_EIN_TransmitServiceHelper.updateEIN(testInput, accRec.Id);
        testInput.status = 'E';
        testOutput = LGNA_EIN_TransmitServiceHelper.updateEIN(testInput, accRec.Id);
        testInput.acctEin.clear();
        testInput.status = 'S';
        testOutput = LGNA_EIN_TransmitServiceHelper.updateEIN(testInput, accRec.Id);        

        EIN__c einRec5 = new EIN__C();
        einRec5.Name = '676767679';
        einRec5.Account__c = accRec.id;
        einRec5.Effective_Date__c = system.today();
        einRec5.Location_Name__c = 'Test2';
        einRec5.Street11__c = 'Street1';
        einRec5.City1__c = 'City1';
        einRec5.State1__c = 'TX';
        einRec5.Zip_Code1__c = '77077';
        einRec5.Country1__c = 'US';  
        einRec5.EIN_Sequence_Number__c = 123;
        insert einRec5;     
        //accRec.Market_Segment__c = null;
        //upsert accRec;
        LGNA_EIN_TransmitServiceHelper.sendNewAcctEIN(accRec.Id);
        
        //einRec2.Bluestar_Transfer_Status__c = '';
        //einRec2.change_reason__c = '';
        //upsert einRec2;        
        
        //einRec2.Bluestar_Transfer_Status__c = 'Due for Transfer';
        //einRec2.Effective_Date__c = system.today() + 1;
        //einRec2.Change_Reason__c = 'CHG';
        //einRec2.Location_Name__c = 'Test21';
        //upsert einRec2;
        //LGNA_EIN_ConfirmControllerApx.transmitEIN(accRec.Id);

        test.stopTest();
    }    
    
}