src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC state for a Prospect or Group Account.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_Decision_Date__c</fullName>
        <description>This field is used to capture the date when a decision is expected for the Opportunity.</description>
        <label>Expected Decision Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_RFP_Release_Date__c</fullName>
        <description>This field is used to capture the expected date an RFI or RFP will be received.</description>
        <label>Expected In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>This field is used to capture the HCSC State of the Account associated to the Opportunity.</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Closed_Reason__c</fullName>
        <description>This field is used to capture the primary reason why an Opportunity is won, lost or declined.</description>
        <label>Primary Closed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Absorbed by Parent Group</fullName>
                </value>
                <value>
                    <fullName>Change of Ownership</fullName>
                </value>
                <value>
                    <fullName>Consol. Covg with 1 Carrier</fullName>
                </value>
                <value>
                    <fullName>Headquarters Relocated</fullName>
                </value>
                <value>
                    <fullName>Lack of Narrow Network</fullName>
                </value>
                <value>
                    <fullName>Market Check by Group</fullName>
                </value>
                <value>
                    <fullName>Organizational Changes</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Guarantees</fullName>
                </value>
                <value>
                    <fullName>Plan Design-Other</fullName>
                </value>
                <value>
                    <fullName>Political</fullName>
                </value>
                <value>
                    <fullName>Purchase by Another Company</fullName>
                </value>
                <value>
                    <fullName>Rates-Aggregate Stop Loss-Claim/Attch Factor</fullName>
                </value>
                <value>
                    <fullName>Rates-Incumbent Reduced</fullName>
                </value>
                <value>
                    <fullName>Rates-Individual Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Rates-Insured</fullName>
                </value>
                <value>
                    <fullName>Repricing</fullName>
                </value>
                <value>
                    <fullName>Reputation of Selected Carrier</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Wellness</fullName>
                </value>
                <value>
                    <fullName>Broker Relationship</fullName>
                </value>
                <value>
                    <fullName>Changed Brokers</fullName>
                </value>
                <value>
                    <fullName>Network Discounts</fullName>
                </value>
                <value>
                    <fullName>Network Disruption</fullName>
                </value>
                <value>
                    <fullName>Product Packaging</fullName>
                </value>
                <value>
                    <fullName>Did Not Want to Disrupt Ees</fullName>
                </value>
                <value>
                    <fullName>Not Enough Diff. to Change</fullName>
                </value>
                <value>
                    <fullName>PUG Did not meet participation</fullName>
                </value>
                <value>
                    <fullName>Rates-Admin. Charge too High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFI_RFP_Received_Date__c</fullName>
        <description>This field is used to capture the date when the RFP or RFI is received.</description>
        <label>RFI/RFP Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <description>This field is used to capture the requested effective date for the opportunity.</description>
        <label>Opportunity Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Rate__c.object
<CustomObject>
    <description>Contains the rate information pertaining to BPA</description>
    <fields>
        <fullName>HCSC_Division__c</fullName>
        <description>Captures HCSC division</description>
        <label>HCSC Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secure_Information__c</fullName>
        <description>Associated benefit plan application</description>
        <label>Secure Information</label>
        <referenceTo>Secure_Information__c</referenceTo>
        <relationshipLabel>Rates</relationshipLabel>
        <relationshipName>Rates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rate</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Rates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rate_Admin_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Rate Admin Charges</relationshipLabel>
        <relationshipName>Rate_Admin_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Admin Charge</label>
    <nameField>
        <label>Rate Admin Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Admin Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Rate_Group__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate</label>
        <referenceTo>Rate__c</referenceTo>
        <relationshipLabel>Rate Groups</relationshipLabel>
        <relationshipName>Rate_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Group</label>
    <nameField>
        <label>Rate Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RatingMatrixASOControllerTest.cls
/**************************************************************************************
  Apex Class Name     : RatingMatrixASOControllerTest
  Version             : 1.0
  Function            : This is a test class for the RatingMatrixASOController class
* Developer                        Date                  
* ----------------------------------------------------------------------------                 
* Nick Serafin/Slalom             6/6/2016
*************************************************************************************/
@isTest(SeeAllData=false)
private class RatingMatrixASOControllerTest { 

	@isTest static void ratingMatrixASOTest(){
		
		Account TestAcnt = new Account();
        TestAcnt.Name = 'Test1';
        insert TestAcnt;

		Opportunity opp = new Opportunity(AccountId = TestAcnt.id, HCSC_Division__c = 'IL', Name='oppName 3',StageName = 'Expected In', CloseDate = System.Today().addYears(2), Expected_RFP_Release_Date__c = System.Today().addYears(1), Expected_Decision_Date__c = System.Today().addYears(1), RFI_RFP_Received_Date__c = System.Today().addYears(1), Primary_Closed_Reason__c = 'Savings');
        opp.Requested_Effective_Date__c = System.Today() - 1;         
        insert opp;

		Secure_Information__c testSecure = new Secure_Information__c(Opportunity_Name__c = opp.Id);
		insert testSecure;

		Rate__c testRate = new Rate__c(Secure_Information__c = testSecure.Id);
		testRate.Id = fflib_IDGenerator.generate( Rate__c.SObjectType );

		List<Rate_Group__c> rateGroupInsert = new List<Rate_Group__c>();

		Rate_Group__c testRateGroup = new Rate_Group__c(Rate__c = testRate.Id);
		testRateGroup.Id = fflib_IDGenerator.generate( Rate_Group__c.SObjectType );

		rateGroupInsert.add(testRateGroup);

		List<Rate_Admin_Charge__c> rateAdminChargeInsert = new List<Rate_Admin_Charge__c>();

		Rate_Admin_Charge__c testRateAdminCharge = new Rate_Admin_Charge__c(Rate__C = testRate.Id);
		testRateAdminCharge.Id = fflib_IDGenerator.generate( Rate_Admin_Charge__c.SObjectType );

		rateAdminChargeInsert.add(testRateAdminCharge);

		PageReference pageRef = new PageReference('/apex/RatingMatrixASO');
		pageRef.getParameters().put('state', 'IL');
		pageRef.getParameters().put('secure', testSecure.Id);
		Test.setCurrentPage(pageRef);

		fflib_ApexMocks rateMocks = new fflib_ApexMocks(); 

        RateDAO.IRateDAO rateInstance;
        rateInstance = new MockDAOs.RateDAOMock(rateMocks);  

        rateMocks.startStubbing();
        rateMocks.when(rateInstance.insertRate(testRate))
                    .thenReturn(testRate);
        rateMocks.stopStubbing();

        fflib_ApexMocks rateGroupMocks = new fflib_ApexMocks(); 

        RateGroupDAO.IRateGroupDAO rateGroupInstance;
        rateGroupInstance = new MockDAOs.RateGroupDAOMock(rateGroupMocks);  

        rateGroupMocks.startStubbing();
        rateGroupMocks.when(rateGroupInstance.insertRateGroup(rateGroupInsert))
                    .thenReturn(rateGroupInsert);
        rateGroupMocks.stopStubbing();

        fflib_ApexMocks rateAdminChargeMocks = new fflib_ApexMocks();

        RateAdminChargeDAO.IRateAdminChargeDAO rateAdminChargeInstance;
        rateAdminChargeInstance = new MockDAOs.RateAdminChargeDAOMock(rateAdminChargeMocks);  

        rateAdminChargeMocks.startStubbing();
        rateAdminChargeMocks.when(rateAdminChargeInstance.insertRateAdminCharge(rateAdminChargeInsert))
                    .thenReturn(rateAdminChargeInsert);
        rateAdminChargeMocks.stopStubbing();

        RateTermDAO.IRateTermDAO rateTermDAOInstance;

		Test.startTest();

		ApexPages.StandardController sc2 = new ApexPages.StandardController(testRate);
		RatingMatrixASOController ratingASOController = new RatingMatrixASOController(sc2, rateInstance, rateGroupInstance, rateAdminChargeInstance, rateTermDAOInstance);

		ratingASOController.rateDAOInstance = rateInstance;
		ratingASOController.rateGroupDAOInstance = rateGroupInstance;
		ratingASOController.rateAdminChargeDAOInstance = rateAdminChargeInstance;
		ratingASOController.rateTermDAOInstance = rateTermDAOInstance;

		ratingASOController.hcscDivision = 'IL';
		ratingASOController.saveRateBackground();
		ratingASOController.saveNewRateRecord();
		ratingASOController.cancel();	

		System.assertEquals(12, ratingASOController.rateGroups.size());		

		System.assertEquals(6, ratingASOController.rateAdminCharges.size());

		Test.stopTest();
	}

	@isTest static void ratingMatrixASOTestDiffState(){
		
		Account TestAcnt = new Account();
        TestAcnt.Id = fflib_IDGenerator.generate( Account.SObjectType );

		Opportunity opp = new Opportunity(AccountId = TestAcnt.id, HCSC_Division__c = 'IL', Name='oppName 3',StageName = 'Expected In', CloseDate = System.Today().addYears(2), Expected_RFP_Release_Date__c = System.Today().addYears(1), Expected_Decision_Date__c = System.Today().addYears(1), RFI_RFP_Received_Date__c = System.Today().addYears(1), Primary_Closed_Reason__c = 'Savings');
        opp.Requested_Effective_Date__c = System.Today() - 1;         
        opp.Id = fflib_IDGenerator.generate( Opportunity.SObjectType );

		Secure_Information__c testSecure = new Secure_Information__c(Opportunity_Name__c = opp.Id);
		testSecure.Id = fflib_IDGenerator.generate( Secure_Information__c.SObjectType ); 

		Rate__c testRate = new Rate__c(Secure_Information__c = testSecure.Id);
		testRate.Id = fflib_IDGenerator.generate( Rate__c.SObjectType );

		List<Rate_Group__c> rateGroupInsert = new List<Rate_Group__c>();

		Rate_Group__c testRateGroup = new Rate_Group__c(Rate__c = testRate.Id);
		testRateGroup.Id = fflib_IDGenerator.generate( Rate_Group__c.SObjectType );

		rateGroupInsert.add(testRateGroup);

		List<Rate_Admin_Charge__c> rateAdminChargeInsert = new List<Rate_Admin_Charge__c>();

		Rate_Admin_Charge__c testRateAdminCharge = new Rate_Admin_Charge__c(Rate__C = testRate.Id);
		testRateAdminCharge.Id = fflib_IDGenerator.generate( Rate_Admin_Charge__c.SObjectType );

		rateAdminChargeInsert.add(testRateAdminCharge);

		PageReference pageRef = new PageReference('/apex/RatingMatrixASO');
		pageRef.getParameters().put('state', 'TX');
		pageRef.getParameters().put('secure', testSecure.Id);
		Test.setCurrentPage(pageRef);

		fflib_ApexMocks rateMocks = new fflib_ApexMocks(); 

        RateDAO.IRateDAO rateInstance;
        rateInstance = new MockDAOs.RateDAOMock(rateMocks);  

        rateMocks.startStubbing();
        rateMocks.when(rateInstance.insertRate(testRate))
                    .thenReturn(testRate);
        rateMocks.stopStubbing();

        fflib_ApexMocks rateGroupMocks = new fflib_ApexMocks(); 

        RateGroupDAO.IRateGroupDAO rateGroupInstance;
        rateGroupInstance = new MockDAOs.RateGroupDAOMock(rateGroupMocks);  

        rateGroupMocks.startStubbing();
        rateGroupMocks.when(rateGroupInstance.insertRateGroup(rateGroupInsert))
                    .thenReturn(rateGroupInsert);
        rateGroupMocks.stopStubbing();

        fflib_ApexMocks rateAdminChargeMocks = new fflib_ApexMocks();

        RateAdminChargeDAO.IRateAdminChargeDAO rateAdminChargeInstance;
        rateAdminChargeInstance = new MockDAOs.RateAdminChargeDAOMock(rateAdminChargeMocks);  

        rateAdminChargeMocks.startStubbing();
        rateAdminChargeMocks.when(rateAdminChargeInstance.insertRateAdminCharge(rateAdminChargeInsert))
                    .thenReturn(rateAdminChargeInsert);
        rateAdminChargeMocks.stopStubbing();

        RateTermDAO.IRateTermDAO rateTermDAOInstance;

		Test.startTest();

		ApexPages.StandardController sc2 = new ApexPages.StandardController(testRate);
		RatingMatrixASOController ratingASOController = new RatingMatrixASOController(sc2, rateInstance, rateGroupInstance, rateAdminChargeInstance, rateTermDAOInstance);

		ratingASOController.rateDAOInstance = rateInstance;
		ratingASOController.rateGroupDAOInstance = rateGroupInstance;
		ratingASOController.rateAdminChargeDAOInstance = rateAdminChargeInstance;
		ratingASOController.rateTermDAOInstance = rateTermDAOInstance;

		ratingASOController.hcscDivision = 'TX';
		ratingASOController.saveRateBackground();
		ratingASOController.saveNewRateRecord();
		ratingASOController.cancel();	

		System.assertEquals(13, ratingASOController.rateGroups.size());		

		System.assertEquals(6, ratingASOController.rateAdminCharges.size());

		Test.stopTest();
	}

	@isTest static void ratingMatrixASOEditTest(){
		
		Account TestAcnt = new Account();
        TestAcnt.Name = 'Test1';
        insert TestAcnt;

		Opportunity opp = new Opportunity(AccountId = TestAcnt.id, HCSC_Division__c = 'IL', Name='oppName 3',StageName = 'Expected In', CloseDate = System.Today().addYears(2), Expected_RFP_Release_Date__c = System.Today().addYears(1), Expected_Decision_Date__c = System.Today().addYears(1), RFI_RFP_Received_Date__c = System.Today().addYears(1), Primary_Closed_Reason__c = 'Savings');
        opp.Requested_Effective_Date__c = System.Today() - 1;         
        insert opp;

		Secure_Information__c testSecure = new Secure_Information__c(Opportunity_Name__c = opp.Id);
		insert testSecure; 

		Rate__c testRate = new Rate__c(Secure_Information__c = testSecure.Id);
		testRate.Id = fflib_IDGenerator.generate( Rate__c.SObjectType );

		List<Rate_Group__c> rateGroupInsert = new List<Rate_Group__c>();

		Rate_Group__c testRateGroup = new Rate_Group__c(Rate__c = testRate.Id);
		testRateGroup.Id = fflib_IDGenerator.generate( Rate_Group__c.SObjectType );

		rateGroupInsert.add(testRateGroup);

		List<Rate_Admin_Charge__c> rateAdminChargeInsert = new List<Rate_Admin_Charge__c>();

		Rate_Admin_Charge__c testRateAdminCharge = new Rate_Admin_Charge__c(Rate__C = testRate.Id);
		testRateAdminCharge.Id = fflib_IDGenerator.generate( Rate_Admin_Charge__c.SObjectType );

		rateAdminChargeInsert.add(testRateAdminCharge);

		PageReference pageRef = new PageReference('/apex/RatingMatrixASO');
		pageRef.getParameters().put('rateId',  testRate.Id);
		Test.setCurrentPage(pageRef);

		fflib_ApexMocks rateMocks = new fflib_ApexMocks(); 

        RateDAO.IRateDAO rateInstance;
        rateInstance = new MockDAOs.RateDAOMock(rateMocks);  

        rateMocks.startStubbing();
        rateMocks.when(rateInstance.grabASORateObj(testRate.Id))
                    .thenReturn(testRate);
        rateMocks.stopStubbing();

        rateMocks.startStubbing();
        rateMocks.when(rateInstance.updateRate(testRate))
                    .thenReturn(testRate);
        rateMocks.stopStubbing();

        fflib_ApexMocks rateGroupMocks = new fflib_ApexMocks(); 

        RateGroupDAO.IRateGroupDAO rateGroupInstance;
        rateGroupInstance = new MockDAOs.RateGroupDAOMock(rateGroupMocks);  

        rateGroupMocks.startStubbing();
        rateGroupMocks.when(rateGroupInstance.grabRateGroups(testRate.Id))
                    .thenReturn(rateGroupInsert);
        rateGroupMocks.stopStubbing();
        
        rateGroupMocks.startStubbing();
        rateGroupMocks.when(rateGroupInstance.upsertRateGroup(rateGroupInsert))
                    .thenReturn(rateGroupInsert);
        rateGroupMocks.stopStubbing();

        fflib_ApexMocks rateAdminChargeMocks = new fflib_ApexMocks();

        RateAdminChargeDAO.IRateAdminChargeDAO rateAdminChargeInstance;
        rateAdminChargeInstance = new MockDAOs.RateAdminChargeDAOMock(rateAdminChargeMocks);  

        rateAdminChargeMocks.startStubbing();
        rateAdminChargeMocks.when(rateAdminChargeInstance.grabRateAdminCharges(testRate.Id))
                    .thenReturn(rateAdminChargeInsert);
        rateAdminChargeMocks.stopStubbing();

        rateAdminChargeMocks.startStubbing();
        rateAdminChargeMocks.when(rateAdminChargeInstance.upsertRateAdminCharge(rateAdminChargeInsert))
                    .thenReturn(rateAdminChargeInsert);
        rateAdminChargeMocks.stopStubbing();

        RateTermDAO.IRateTermDAO rateTermDAOInstance;

		Test.startTest();

		ApexPages.StandardController sc2 = new ApexPages.StandardController(testRate);
		RatingMatrixASOController ratingASOController = new RatingMatrixASOController(sc2, rateInstance, rateGroupInstance, rateAdminChargeInstance, rateTermDAOInstance);

		ratingASOController.rateDAOInstance = rateInstance;
		ratingASOController.rateGroupDAOInstance = rateGroupInstance;
		ratingASOController.rateAdminChargeDAOInstance = rateAdminChargeInstance;
		ratingASOController.rateTermDAOInstance = rateTermDAOInstance;

		ratingASOController.hcscDivision = 'TX';		
		ratingASOController.saveRateBackground();	
		ratingASOController.hcscDivision = 'MT';	
		ratingASOController.saveNewRateRecord();
		ratingASOController.cancel();
		
		System.assertEquals('MT', ratingASOController.hcscDivision);		

		Test.stopTest();
	}

	@isTest static void testException(){
	
	try{	

		Account TestAcnt = new Account();
        TestAcnt.Id = fflib_IDGenerator.generate( Account.SObjectType );

		Opportunity opp = new Opportunity(AccountId = TestAcnt.id, HCSC_Division__c = 'IL', Name='oppName 3',StageName = 'Expected In', CloseDate = System.Today().addYears(2), Expected_RFP_Release_Date__c = System.Today().addYears(1), Expected_Decision_Date__c = System.Today().addYears(1), RFI_RFP_Received_Date__c = System.Today().addYears(1), Primary_Closed_Reason__c = 'Savings');
        opp.Requested_Effective_Date__c = System.Today() - 1;         
        opp.Id = fflib_IDGenerator.generate( Opportunity.SObjectType );

		Secure_Information__c testSecure = new Secure_Information__c(Opportunity_Name__c = opp.Id);
		testSecure.Id = fflib_IDGenerator.generate( Secure_Information__c.SObjectType ); 

		Rate__c testRate = new Rate__c(Secure_Information__c = testSecure.Id);
		testRate.Id = fflib_IDGenerator.generate( Rate__c.SObjectType );

		PageReference pageRef = new PageReference('/apex/RatingMatrixASO');
		pageRef.getParameters().put('state', 'IL');
		pageRef.getParameters().put('secure', '');
		Test.setCurrentPage(pageRef);

		fflib_ApexMocks rateMocks = new fflib_ApexMocks(); 

        RateDAO.IRateDAO rateInstance;
        rateInstance = new MockDAOs.RateDAOMock(rateMocks);  

        fflib_ApexMocks rateGroupMocks = new fflib_ApexMocks(); 

        RateGroupDAO.IRateGroupDAO rateGroupInstance;
        rateGroupInstance = new MockDAOs.RateGroupDAOMock(rateGroupMocks);  

        fflib_ApexMocks rateAdminChargeMocks = new fflib_ApexMocks();

        RateAdminChargeDAO.IRateAdminChargeDAO rateAdminChargeInstance;
        rateAdminChargeInstance = new MockDAOs.RateAdminChargeDAOMock(rateAdminChargeMocks); 

        RateTermDAO.IRateTermDAO rateTermDAOInstance;

        Test.startTest(); 

		ApexPages.StandardController sc2 = new ApexPages.StandardController(testRate);
		RatingMatrixASOController ratingASOController = new RatingMatrixASOController(sc2, rateInstance, rateGroupInstance, rateAdminChargeInstance, rateTermDAOInstance);

		ratingASOController.rateDAOInstance = rateInstance;
		ratingASOController.rateGroupDAOInstance = rateGroupInstance;
		ratingASOController.rateAdminChargeDAOInstance = rateAdminChargeInstance;
		ratingASOController.rateTermDAOInstance = rateTermDAOInstance;

		ratingASOController.hcscDivision = 'OK';
		ratingASOController.saveRateBackground();

		}catch(Exception ex){

			System.assertEquals('System.NullPointerException: Attempt to de-reference a null object', ex.getMessage());
		}

		Test.stopTest();
	}

}