src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Encryption_Key__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Encryption key used in the environment</description>
    <fields>
        <fullName>Encryption_Key__c</fullName>
        <description>Encryption key for the BlueSTAR integration system</description>
        <label>Encryption Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Encryption Key</label>
</CustomObject>

objects/items_SharePoint__x.object
<CustomObject>
    <externalDataSource>SharePoint</externalDataSource>
    <externalName>items_SharePoint</externalName>
    <label>items_SharePoint</label>
    <pluralLabel>items_SharePoint</pluralLabel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Expected_RFP_Release_Date__c</fullName>
        <description>This field is used to capture the expected date an RFI or RFP will be received.</description>
        <label>Expected In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RFI_RFP_Received_Date__c</fullName>
        <description>This field is used to capture the date when the RFP or RFI is received.</description>
        <label>RFI/RFP Received Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/SharePointOAuthTEST__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Access_Token_1__c</fullName>
        <label>Access Token 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_2__c</fullName>
        <label>Access Token 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_3__c</fullName>
        <label>Access Token 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_4__c</fullName>
        <label>Access Token 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_5__c</fullName>
        <label>Access Token 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URI__c</fullName>
        <label>Redirect URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token_1__c</fullName>
        <label>Refresh Token 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refresh_Token_2__c</fullName>
        <label>Refresh Token 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SharePoint OAuth TEST</label>
</CustomObject>

classes/OpportunityFilesConnectControllerTest.cls
@isTest (SeeAllData=false)
private class OpportunityFilesConnectControllerTest{
    @testSetup static void setupTestData(){
        Test.startTest();
        OrganizationDAO.IOrganizationDAO organizationDAOInstance = new OrganizationDAO();
        SharePointOAuthTEST__c cs = new SharePointOAuthTEST__c();
        if (!organizationDAOInstance.isRunningInSandbox()) {
            cs.Name = System.URL.getSalesforceBaseUrl().getHost().substringbefore('.').toLowerCase();
        } else {
            cs.Name = System.URL.getSalesforceBaseUrl().getHost().substringAfterLast('--').substringbefore('.').toLowerCase();
        }
        cs.Access_Token_1__c = '00000000000000000000000000000000';
        cs.Access_Token_2__c = '00000000000000000000000000000000';
        cs.Access_Token_3__c = '00000000000000000000000000000000';
        cs.Access_Token_4__c = '00000000000000000000000000000000';
        cs.Access_Token_5__c = '00000000000000000000000000000000';
        cs.Client_ID__c = '123456789ABCDEFG';
        cs.Client_Secret__c = 'secret';
        cs.Redirect_URI__c = System.URL.getSalesforceBaseUrl().getHost().toLowerCase();
        cs.Refresh_Token_1__c = '00000000000000000000000000000000';
        cs.Refresh_Token_2__c = '00000000000000000000000000000000';
        insert cs;

        Account a = new Account(Name='Test', External_Id__c='AC102981');
        insert a;
        Opportunity o = new Opportunity(Name='Test', RFI_RFP_Received_Date__c=System.Today(), AccountId=a.Id);
        o.StageName='Expected In';
        o.probability=50;
        o.Expected_RFP_Release_Date__c=System.Today();
        o.CloseDate=System.Today();
        insert o;
        Test.stopTest();
    }

    @isTest static void basicControllerTest(){
        Test.startTest();
        ProfileDAO profileDAOInstance = new ProfileDAO();
        Profile integrationProfile = profileDAOInstance.getProfileByName(System.Label.ProfileIntegrationProfile);
        User integrationUser = TestClassUtiltity.CreateUserRecord(integrationProfile.Id, 'testUsername@intTest.com', 'test', 'testEmail@intTest.com');
        Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];
        ApexPages.CurrentPage().getParameters().put('id', o.Id);
        Encryption_Key__c testKey = new Encryption_Key__c();
        testKey.Name = 'Test Key';
        testKey.Encryption_Key__c = EncodingUtil.base64Encode(Crypto.generateAesKey(256));
        testKey.SetupOwnerId = integrationProfile.Id;
        insert testKey;
        ApexPages.StandardController std = new ApexPages.StandardController(o);
        OpportunityFilesConnectController con = new OpportunityFilesConnectController(std);
        
        try{        
            con.pageNumber = 0;
            con.pageSize = 0;
            con.totalNoOfRecs = 1;
            con.getInitialDocumentSet();
        } catch(System.MathException e) {
            System.assert(true);
        }

        con.totalNoOfRecs = 0;
        con.pageSize = 2;
        con.getInitialDocumentSet();

        con.totalNoOfRecs = 3;
        con.getInitialDocumentSet();

        try{
            con.next();
        } catch(System.NullPointerException e){
            //Requires Items_Sharepoint__x External Object to be populated, cannot do this
            System.assert(true);
        }
        System.assertEquals(1, con.pageNumber);

        try{
            con.previous();
        } catch(System.NullPointerException e){
            //Requires Items_Sharepoint__x External Object to be populated, cannot do this
            System.assert(true);
        }

        try{
            con.previous();
        } catch(System.NullPointerException e){
            //Requires Items_Sharepoint__x External Object to be populated, cannot do this
            System.assert(true);
        }

        con.fileType = 'application';
        con.fileName = 'Test file name';
        con.linkFile();
        con.fileType = 'other';
        con.fileName = 'Test file name';
        con.linkFile();
        con.verifySharePointButton();
        Test.stopTest();
    }
}