src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Hold_End_Date__c</fullName>
        <label>Hold End Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>renewal_duration_is_infinite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indefinite Hold</label>
        <type>Checkbox</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Actuary_Gate__c.object
<CustomObject>
    <fields>
        <fullName>OppCount__c</fullName>
        <label>Number of Total Opportunities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Gate Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Up</fullName>
                </value>
                <value>
                    <fullName>Down</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Gate</label>
    <nameField>
        <displayFormat>G-{000}</displayFormat>
        <label>Gate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the unique identifier number of the contact in the source system (e.g., BlueStar, Siebel SFA)</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Identifier Number of the Contact in the Source System</inlineHelpText>
        <label>Contact Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Contact.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture the HR status of the contact from PeopleSoft.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Leave</fullName>
                </value>
                <value>
                    <fullName>Probation</fullName>
                </value>
                <value>
                    <fullName>Short Term Leave</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Assigned_UW__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned UW</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dental_Count__c</fullName>
        <description># of Subscribers enrolled for Dental(does not include members count)</description>
        <label>Dental Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Gate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gate</label>
        <referenceTo>Actuary_Gate__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Health_Count__c</fullName>
        <description># of Subscribers enrolled for Health(does not include members count)</description>
        <label>Health Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rating_Status__c</fullName>
        <label>Rating Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                    <label>Actuarial Release</label>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                    <label>Underwriting Release</label>
                </value>
                <value>
                    <fullName>Finalized</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Marketing Release</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Pended</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Underwriting Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SGR_Account_Number__c</fullName>
        <formula>Account.External_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SGR_Workflow_Status__c</fullName>
        <label>Workflow Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Defined</fullName>
                </value>
                <value>
                    <fullName>UW Review</fullName>
                </value>
                <value>
                    <fullName>UW Pended</fullName>
                </value>
                <value>
                    <fullName>Actuarial-Released</fullName>
                </value>
                <value>
                    <fullName>Underwriting-Released</fullName>
                </value>
                <value>
                    <fullName>Rated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscribers_Count__c</fullName>
        <description># of Subscribers enrolled for Health and Dental(does not include members count)</description>
        <label>Subscribers Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Workflow_System_Status__c</fullName>
        <label>Workflow System Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready to Fetch Mapped Plans</fullName>
                    <default>true</default>
                    <label>Ready to Fetch Mapped Plans</label>
                </value>
                <value>
                    <fullName>Ready to Validate</fullName>
                </value>
                <value>
                    <fullName>Failed Validation</fullName>
                </value>
                <value>
                    <fullName>Ready to Rate</fullName>
                </value>
                <value>
                    <fullName>Ready For Gate Processing</fullName>
                </value>
                <value>
                    <fullName>Ready to Send to B-Engaged</fullName>
                </value>
                <value>
                    <fullName>Ready to Send to BlueSTAR</fullName>
                </value>
                <value>
                    <fullName>Not Eligible to Send to BlueSTAR</fullName>
                </value>
                <value>
                    <fullName>Workflow Completed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Review Task Completion</fullName>
                </value>
                <value>
                    <fullName>Awaiting Hold Task Completion</fullName>
                </value>
                <value>
                    <fullName>Gate Processing Completed</fullName>
                </value>
                <value>
                    <fullName>Failed Rating</fullName>
                </value>
                <value>
                    <fullName>Ready for BlueSTAR Initiation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SGR_ViewGateController.cls
/**************************************************************************************
  Apex Class Name     : SGR_ViewGateController     
  Version             : 1.0
  Function            : Controller class to get opportunities list and get total gate count
  Modification Log    :
* Developer: Shankar                 Date: 03/10/2018                   Description
* ----------------------------------------------------------------------------               
* Shankar                  03/10/2018                Original Version
  Akhil                    10/04/2018                2.0 Version
*************************************************************************************/
public class SGR_ViewGateController {
    @AuraEnabled
    public static List<Opportunity> getRelatedOpportunities(Id gateId, Integer maxRows, String sortField, String sortOrder) {
        Integer rowLimit = Integer.valueOf(maxRows);
        List<Opportunity> oppsList = new List<Opportunity>();
        
        try {
            String oppsListQuery = 'SELECT Name, Account.Name,SGR_Account_Number__c, Account.External_Id__c,Gate__c, RecordType.Name, Renewal_Date__c, Rating_Status__c, Subscribers_Count__c, Health_Count__c, Dental_Count__c, Assigned_UW__r.Name,recordtypeid FROM Opportunity where Rating_Status__c=\'Rated\' AND Gate__c =:gateId ORDER BY Renewal_Date__c ASC LIMIT ' + maxRows;           	
            
        	oppsList = Database.query(oppsListQuery); 
             
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return oppsList;
    }
    
    @AuraEnabled
    public static Integer getRelOppsCount(Id gateId) {
        try {
            AggregateResult[] result = [SELECT Count(Id) FROM Opportunity where Rating_Status__c ='Rated' AND Gate__c = :gateId];
            Integer count = 0;
                count = (Integer) result[0].get('expr0');
                List<Actuary_Gate__c> gate = [Select Id, OppCount__c from Actuary_Gate__c where Id=:gateId];
                if (!gate.isEmpty()) {
                    gate[0].OppCount__c = count;
                }
                return count;          
        } catch(Exception e) {
            throw new AuraHandledException('An error has occured while getting opportunities count. Please contact System Administrator');
        } 
    }
    

    @AuraEnabled
    public static List<Opportunity> getSelectedOpty(List<Id> ids){
        return [select id,Name,Rating_Status__c,Gate__r.Status__c,SGR_Workflow_Status__c,Account.Name,
                Account.Status__c,Account.Renewal_Date__c,Account.hold_end_date__c,
                Account.renewal_duration_is_infinite__c,Workflow_System_Status__c,recordtypeId,Renewal_Date__c,Assigned_UW__c from Opportunity
                where id=:ids];
    }
    
      @AuraEnabled
    public static Boolean getGateStatus(Id gateId){
        
        Actuary_Gate__c gate1=new Actuary_Gate__c();
        gate1=[select Status__c from Actuary_Gate__c where id=:gateId];
        if(gate1.Status__c=='Up')
                {
                    return false;
                }
                else
            	{
                return true;
            	}
    }
    
     @AuraEnabled
    public static boolean gateStatus(Id gateId){
        Actuary_Gate__c gate1=new Actuary_Gate__c();
        gate1=[select Status__c from Actuary_Gate__c where id=:gateId];
                if(gate1.Status__c=='Up')
                {
                    gate1.Status__c='Down';
                    update gate1;
                    return true;
                }
        	return false;
        
    }
    
    
    @AuraEnabled 
    Public static List<Opportunity> processSelectedOptys(List<Opportunity> selOptyRecords){
        list<Opportunity> optyListToUpdate = new list<Opportunity>();
        try{
        if(!selOptyRecords.isEmpty()){
            for(Opportunity  opp : selOptyRecords){
                opp.Rating_Status__c='Actuarial-Released';
                opp.SGR_Workflow_Activity__c = null;
                opp.Workflow_System_Status__c='Gate Processing Completed';
                optyListToUpdate.add(opp);
            }
        }
            
            update optyListToUpdate;
            SGR_ReleaseValidations.initiateValidation(optyListToUpdate);
            return optyListToUpdate;
        }
        catch(Exception e){
            return null;
        }
    } 
   
    
    @AuraEnabled
public static Boolean liftGate(Id selOptyRecords) {
    
    List<Opportunity> optyListToUpdate= new List<Opportunity>();
    List<Opportunity> optyListToUpdate1= new List<Opportunity>();
    optyListToUpdate = [select Id,status__c,HCSC_Division__c,Gate__c,Assigned_UW__c,Account.Renewal_Date__c,Account.hold_end_date__c,Account.renewal_duration_is_infinite__c,Account_Market_Segment__c,Rating_Status__c,Funding_Type__c,Renewal_Date__c,SGR_Workflow_Status__c,RecordType.Name,RecordTypeId,Workflow_System_Status__c from opportunity where Gate__c = :selOptyRecords AND Rating_Status__c='Rated'];

    set<id> sid = new set<id>();
    List<Actuary_Gate__c> gate1= new List<Actuary_Gate__c>();
     gate1=[select Id,status__c,Division__c,Effective_Date__c,Funding_Type__c,Market_Segment__c from Actuary_Gate__c where Id =:selOptyRecords];
    
      if(!optyListToUpdate.isEmpty()){
            for(Opportunity  opp : optyListToUpdate){
                
                if(opp.RecordType.Name=='SGR Production Opportunity' || opp.RecordType.Name=='SGR Analytical Opportunity'){
        
                    opp.Rating_Status__c='Actuarial-Released';
                    opp.SGR_Workflow_Activity__c = null;
                    opp.Workflow_System_Status__c='Gate Processing Completed';
      
                    sid.add(opp.Gate__c); 
            	}
                optyListToUpdate1.add(opp); 
             }
          
         
      }
        try{
             if(gate1.size()>0){
             if(gate1[0].Status__c =='Down'){
                gate1[0].Status__c ='Up';
          }  
          }
            update gate1;
            update optyListToUpdate1;
            SGR_ReleaseValidations.initiateValidation(optyListToUpdate1);
            return false;
        }
        catch(Exception e){
            return true;
        }

}
     /************Saurav End ************/
}