src/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field is used to capture the Group Account Effective Date or When the Producer was Appointed.</description>
        <label>Original Effective Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from the source system. This could be the Group Number or Producer Number based on the Account Record Type.</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>

objects/Account.object
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>This field is used to capture the list of group numbers received during the account number reservations. Will be a semicolon separated list of values.</description>
        <label>Group Number</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Producer_Number__c</fullName>
        <formula>External_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Producer Number</label>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Producer_Organization__c</fullName>
        <description>State of the Producer or Consultant Account as listed in Siebel SFA</description>
        <label>Producer Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Next Renewal Date of the Group Account</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>

objects/Account.object
    <fields>
        <fullName>Status__c</fullName>
        <description>This field is used to capture if the account is active, cancelled, or in the buying process</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>In Communication</fullName>
                </value>
                <value>
                    <fullName>Actively Engaged</fullName>
                </value>
                <value>
                    <fullName>Actively Purchasing</fullName>
                </value>
                <value>
                    <fullName>In Negotiations</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Underwriter Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

objects/FW_Service_Status_Log__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <formula>Case__r.GEMS_Effective_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ErrorCode__c</fullName>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorDescription__c</fullName>
        <label>Error Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RequestBody__c</fullName>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ResponseBody__c</fullName>
        <label>Response Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FW Service Status Log</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Status Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>This field is used to capture the External ID of the record from Source System.</description>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <description>Renewal Date for Opportunity .</description>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Upload_DateTime__c</fullName>
        <label>Renewal Upload DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Discovery</fullName>
                </value>
                <value>
                    <fullName>Finalist Named</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Onboarding Complete</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>RFP Received</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>Not Headed to RFP</fullName>
                </value>
                <value>
                    <fullName>RFP Receipt</fullName>
                </value>
                <value>
                    <fullName>In Underwriting</fullName>
                </value>
                <value>
                    <fullName>Final Presentation</fullName>
                </value>
                <value>
                    <fullName>Negotiate</fullName>
                </value>
                <value>
                    <fullName>Review with Client/Broker</fullName>
                </value>
                <value>
                    <fullName>Change Offering</fullName>
                </value>
                <value>
                    <fullName>Standard Renewal</fullName>
                </value>
                <value>
                    <fullName>Strategic Renewal</fullName>
                </value>
                <value>
                    <fullName>Network Request</fullName>
                </value>
                <value>
                    <fullName>Off-Cycle Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Producer_Group_Association__c.object
<CustomObject>
    <description>Producer and Group associations will be stored using this object</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Effective Date of the Association (Relationship between Group Account and Producer Account)</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date of the Association (Relationship between Group Account and Producer Account)</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>Stores the external ID from Source System (Concat of Group Account # and Producer Account #) for Upsert Operation</description>
        <externalId>true</externalId>
        <label>PGA External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Group_Account__c</fullName>
        <description>Stores the group account related in this association</description>
        <label>Group Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Group Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Prospect</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Prospect (Non BlueSTAR)</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Group Account (Non BlueSTAR)</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Producers Associated to Group</relationshipLabel>
        <relationshipName>Group_Associated</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Formula field to retrieve the Group Account Number for the Group Account</description>
        <formula>Group_Account__r.External_ID__c</formula>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Producer_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Producer Account related in the association</description>
        <label>Producer Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Producer_Account</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Consultant_Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups Associated to Producer</relationshipLabel>
        <relationshipName>Producer_Association</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producer_Number__c</fullName>
        <description>Formula field to retrieve the Producer Account Number for the Producer Account</description>
        <formula>Producer_Account__r.External_ID__c</formula>
        <label>Producer Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Producer_Organization__c</fullName>
        <formula>Producer_Account__r.Producer_Organization__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Producer Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Producer_Type__c</fullName>
        <description>Formula field to retrieve the Producer Type for the Producer Account</description>
        <formula>TEXT(Producer_Account__r.Type)</formula>
        <label>Producer Type</label>
        <type>Text</type>
    </fields>
    <label>Producer Group Association</label>
    <nameField>
        <displayFormat>PAG-{0000}</displayFormat>
        <label>PAG #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Producer Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SGR_BAP_GetProducerDataHelper.cls
//*************************************************************************************
// Name             : SGR_BAP_GetProducerDataHelper.cls
// Description      : This class contains the logic to process response.
// Created By       : Akbar Hussain Salisabgari 
// Created Date     : 12/28/2018
// 
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 12/28/2018       Akbar             SFDC-15963->BAP Webservice 
// ************************************************************************************
public class SGR_BAP_GetProducerDataHelper {
    
    public static SGR_BAP_GetProducerDataResponse generateBAPProducerData(SGR_BAP_GetProducerDataRequest req){
        
        Integer pageSize=2000;
        Integer pageNumber=1;
        String warnMSG=null;
            
        Set<Id> grpAccIds=new Set<Id>();
        List<Account> producerAccList = new List<Account>();
        List<Producer_Group_Association__c> producerGrpAccList = new List<Producer_Group_Association__c>();
        Map<Id, Producer_Group_Association__c> producerGrpAccMap=new Map<Id,Producer_Group_Association__c>();
        Map<Id, Opportunity> oppGrpAccMap=new Map<Id,Opportunity>();
        List<Opportunity> oppList = new List<Opportunity>();
        
        SGR_BAP_GetProducerDataResponse.ProducerData producerDataForResponse;
        List<SGR_BAP_GetProducerDataResponse.ProducerData> producerDataForResponseList=new List<SGR_BAP_GetProducerDataResponse.ProducerData>();
        
        SGR_BAP_GetProducerDataResponse res = new SGR_BAP_GetProducerDataResponse();
        
        FW_Service_Status_Log__c serLog = new FW_Service_Status_Log__c();
        serLog.Name = 'BAP Webservice';
        serLog.StartTime__c = System.now(); 
        
            serLog.RequestBody__c = String.valueOf(req);
                if(req!=null ){  
                        if(req.pageNumber>0){            
                        	pageNumber = req.pageNumber;
                       }
                		if(req.pageSize>0){
                        	pageSize = req.pageSize;
                	}   
                    Integer offSetRecs = (pageNumber-1)*pageSize;
                    res.pageNumber = pageNumber;
                    res.pageSize = pageSize;
                    
                if(String.isNotBlank(req.producerNumber)){
                    String producerNumber =req.producerNumber;
                    res.producerNumber = req.producerNumber;
                    String query = 'SELECT id, Name,Type,Producer_Number__c,RecordType.Name FROM Account WHERE RecordType.Name = \'Producer Account\' AND Type IN(\'Producer\',\'General Agent\',\'Sub Producer\') AND Producer_Number__c = :producerNumber';
                    if(String.isNotBlank(req.producerName)){
                        String producerName = '\'%'+ req.producerName +'%\'';
                        query = query +' AND Name Like'+ producerName;
                    }
                    producerAccList = Database.query(query);
                    //Akbar - 29th Jan E2E fixes - added query to get no of account recs based on producer no
                    res.totalRecords =[SELECT count() FROM Producer_Group_Association__c WHERE Producer_Number__c=:producerNumber AND ( End_Date__c=null OR End_Date__c >Today)];
                    
                    if(producerAccList!=null && producerAccList.size()>0){
                        String id = producerAccList[0].id;
                        
                        String grpAccQuery = 'SELECT Id, Name,Group_Account__c,Group_Account__r.Name, Group_Number__c, Producer_Account__c, Producer_Number__c, Producer_Organization__c, Producer_Type__c, RecordType.Name FROM Producer_Group_Association__c WHERE Producer_Account__c = :id AND Producer_Type__c IN(\'Producer\',\'General Agent\',\'Sub Producer\')';
                        //Akbar - E2E fixes start - commented below if-else condition and added new logic to compare eff date with first and last day of eff date.
                        warnMSG=null;
                        try{
                        	//MM-YYYYY
                        if(req.effectiveDate!=null){
                        	String[] effDtInput=req.effectiveDate.split('/');
                        	
                            if(effDtInput==null || effDtInput.size()==0){//mm/YYYY
                            	effDtInput=req.effectiveDate.split('-');
                            }
                        	if(effDtInput!=null && effDtInput.size()>=2){
                        	     integer mm=Integer.valueOf(effDtInput[0]);
                        	     integer yyyy=Integer.valueOf(effDtInput[1]);
                         	 	Date effectiveDate=Date.newInstance(yyyy,mm,1);
                           	
                           		Date firstDayOfMonth = effectiveDate.toStartOfMonth();//Date.valueOf(req.effectiveDate).toStartOfMonth();
                            	Date lastDayOfMonth = firstDayOfMonth.addDays(Date.daysInMonth(firstDayOfMonth.year(), firstDayOfMonth.month()) - 1);
                             
                                grpAccQuery = grpAccQuery + ' AND Effective_Date__c>=:firstDayOfMonth AND Effective_Date__c<=:lastDayOfMonth';
                       
                        	}
                        	
                         }
                        }catch(Exception e){
                            
                            warnMSG='Invalid Input Effective Date, please check date formate. Search proceeded without matching Input Effective Date.';
                        }
                        grpAccQuery = grpAccQuery + ' AND (End_Date__c = NULL OR END_Date__c>Today)';
                       //Akbar - E2E fixes end
                        if(String.isNotBlank(req.accountName)){
                            String accountName = '\'%'+ req.accountName +'%\'';
                            grpAccQuery = grpAccQuery + ' AND Group_Account__r.Name LIKE' + accountName;
                        }
                        if(String.isNotBlank(req.accountNumber)){
                            String accountNumber = '\'%'+ req.accountNumber +'%\'';
                            grpAccQuery = grpAccQuery + ' AND Group_Account__r.External_Id__c LIKE' + accountNumber;
                        }
                                           
                        producerGrpAccList = Database.query(grpAccQuery);
                        
                        if(producerGrpAccList !=null && producerGrpAccList.size()>0){
                           for(Producer_Group_Association__c producerGrpAsso: producerGrpAccList){
                                 grpAccIds.add(producerGrpAsso.Group_Account__c);
                                 producerGrpAccMap.put(producerGrpAsso.Group_Account__c, producerGrpAsso);
                           }
                           
                           oppList=[SELECT Id, Name, Renewal_Date__c,AccountId,Renewal_Upload_DateTime__c FROM Opportunity WHERE AccountId in:grpAccIds AND Renewal_Date__c >=Today LIMIT :pageSize OFFSET :offSetRecs];
                           
                           if(oppList!=null && oppList.size()>0){
                                for( Opportunity opp:oppList){
                                    oppGrpAccMap.put(opp.accountId, opp);
          
                                }
                            }
                            if(producerGrpAccMap!=null){

                               for(Id grpAccId: producerGrpAccMap.keySet()){
                                   producerDataForResponse=new SGR_BAP_GetProducerDataResponse.ProducerData();
                                   
                                   producerDataForResponse.producerType=producerAccList[0].Type;
                                   if(String.isNotBlank(producerAccList[0].Type) && producerAccList[0].Type.equalsIgnoreCase('General Agent')){
                                      producerDataForResponse.generalAgentName=producerAccList[0].Name;
                                   }
                                   else{ 
                                    producerDataForResponse.producerName=producerAccList[0].Name;
                                  } 
                                   Producer_Group_Association__c  asso=producerGrpAccMap.get(grpAccId);
                                   ProducerDataForResponse.accountNumber=asso.Group_Number__c;
                                   producerDataForResponse.accountName=asso.Group_Account__r.Name;
                             
                                  Opportunity opp=oppGrpAccMap.get(asso.Group_Account__c);

                                  if(opp!=null){
                                     producerDataForResponse.renewalDate=String.valueOf(opp.Renewal_Date__c);
                                     producerDataForResponse.postedDate=String.valueOf(opp.Renewal_Upload_DateTime__c);
                                 }
                                  
                                  producerDataForResponselist.add(producerDataForResponse);
                                      
                               }
                              
                                serLog.Status__c ='Request Process Sucessfully.';
                                serLog.ErrorCode__c = 'Success';
                                res.status = 'Success';
                                res.message = 'Request Process Sucessfully.';
                                if(warnMSG!=null){
                                    res.message=res.message+' WARNING: '+warnMSG;
                                }
                                res.producerData = producerDataForResponselist;
                                
                            }
                        }else{
                            serLog.Status__c ='Request process failed.';
                            serLog.ErrorDescription__c = 'No Group Account found with Producer Number:'+req.producerNumber;
                            serLog.ErrorCode__c = 'Failed';
                            res.status = 'Failed';
                            res.message = 'Request process failed.';
                            res.failureReason = 'No Group Account found with Producer Number:'+req.producerNumber;
                        }
                    }else{
                        serLog.Status__c ='Request process failed';
                        serLog.ErrorDescription__c = 'No Producer  found  with Producer Number :'+req.producerNumber;
                        serLog.ErrorCode__c = 'Failed';
                        res.status = 'Failed';
                        res.message = 'Request process failed';
                        res.failureReason = 'No Producer  found  with Producer Number :'+req.producerNumber;
                    }
                    
                    
                }else{
                    serLog.Status__c ='Request process failed';
                    serLog.ErrorDescription__c = 'Producer Number is not provided from  request.';
                    serLog.ErrorCode__c = 'Failed';
                    res.status = 'Failed';
                    res.message = 'Request process failed';
                    res.failureReason = 'Producer Number is not provided from  request.';
                }

                
    }else{
                serLog.Status__c ='Request process failed';
                serLog.ErrorDescription__c = 'Received request is empty.';
                serLog.ErrorCode__c = 'Failed';
                res.status = 'Failed';
                res.message = 'Request process failed';
                res.failureReason = 'Received request is empty.';
            }
    
            
        serLog.ResponseBody__c = String.valueOf(res);
        if(serLog!=null){
            insert serLog;
        }
        return res;
    }
}