src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/GEMS_Benefit_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>Plan__r.Product__r.ProductCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BA Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>GEMS Benefit Agreements</relationshipLabel>
        <relationshipName>GEMS_Benefit_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GEMS Benefit Agreement</label>
    <nameField>
        <label>BA No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GEMS Benefit Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Market_Segment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Market Segment Picklist values from Account</description>
    <label>Market Segment</label>
</CustomObject>

objects/Opportunity_Product__c.object
<CustomObject>
    <description>Products related to the opportunity - acting as a junction object</description>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <description>Funding type of the product on an opportunity</description>
        <label>Funding Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACAP</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>PREM</fullName>
                </value>
                <value>
                    <fullName>COST</fullName>
                </value>
                <value>
                    <fullName>SERV</fullName>
                </value>
                <value>
                    <fullName>PAR</fullName>
                </value>
                <value>
                    <fullName>MPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Opportunity Name related to the Product</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Name of product category</description>
        <formula>TEXT(Product__r.Product_Category__c)</formula>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>State__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>New Sale</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>Add-On Gain</fullName>
                </value>
                <value>
                    <fullName>Add-On Loss</fullName>
                </value>
                <value>
                    <fullName>Market Check</fullName>
                </value>
                <value>
                    <fullName>Upsell – IL</fullName>
                </value>
                <value>
                    <fullName>Product Term</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product related to the opportunity record</description>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Service</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projected_Members__c</fullName>
        <description>Projected number of members on the opportunity product</description>
        <label>Expected Members</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Win_Probability__c</fullName>
        <description>Probability of winning the opportunity product</description>
        <label>Win Probability %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <displayFormat>OP-{000}</displayFormat>
        <label>OP #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <description>Captures product category</description>
        <inlineHelpText>required field for plans to flow correctly on BA to BlueSTAR</inlineHelpText>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Family</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>BCC</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Disease Management</fullName>
                </value>
                <value>
                    <fullName>EPO</fullName>
                </value>
                <value>
                    <fullName>Group Govt</fullName>
                </value>
                <value>
                    <fullName>HCA</fullName>
                </value>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>IHI</fullName>
                </value>
                <value>
                    <fullName>Nurseline</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
                <value>
                    <fullName>Private Exchange</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Dearborn</fullName>
                </value>
                <value>
                    <fullName>Health Advocacy Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Health Care Management</fullName>
                </value>
                <value>
                    <fullName>Rx</fullName>
                </value>
                <value>
                    <fullName>Dearborn</fullName>
                </value>
                <value>
                    <fullName>Stop Loss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GEMS_ScreeningCase360ViewController.cls
/*
* 04/22/2018	Luke Chen	SFDC-9342 GEMS: Prod Issue - 360 view showing a different open/closed date than actual cases
*
*/
public without sharing class GEMS_ScreeningCase360ViewController
{
    public Id caseId {get; set;}
    public Double offset{get; set;}  // SFDC-9342
    public Case caseObj 
    {
        get 
        {
            if (caseObj == null)
            {
                caseObj = new Case();
                caseObj = [SELECT ID, Subject, Account_Number__c, HCSC_Division__c, Market_Segment__c, GEMS_Case_Effective_Date__c, Opportunity_Name__c FROM Case WHERE Id = :caseId];
                System.debug('case record:' +caseObj);
            }
            return caseObj;
        } 
        set;
    }
    //public Id accountId {get; set;}
    public GEMS_ScreeningCase360ViewController(){}
    
    public  Integer noOfOpportunityProducts {get; set;}
    public List<Opportunity_Product__c> listOfOpportunityProducts {get; set;}
    public List<Case> openChildCasesList{get; set;}
    public GEMS_ScreeningCase360ViewController(ApexPages.StandardController stdController) 
    {
        try
        {   
            offset = GEMS_Utility.getLocalTimeZoneOffset(); // SFDC-9342
            
            noOfOpportunityProducts = 0;
            
            caseId = stdController.getId();
            listOfOpportunityProducts = new List<Opportunity_Product__c>();
            
            listOfOpportunityProducts = [SELECT Id, Product__c, Product__r.Name,Funding_Type__c,Product_Category__c, Opportunity_Product__c.Win_Probability__c, Opportunity_Product__c.Projected_Members__c FROM Opportunity_Product__c WHERE Opportunity_Name__c =:caseObj.Opportunity_Name__c];
            openChildCasesList= [SELECT ID, casenumber, CreatedDate, ClosedDate ,Type, GEMS_Benefit_Agreement__r.Name, isclosed, Sub_Category__c, Product_Type__c, status, Days_Open__c, Owner.Name from Case WHERE GEMS_Account_Submission_Info__c =: caseId and GEMS_Benefit_Agreement__c ='' Order by CreatedDate ASC];
                System.debug('Case ID:'+caseId);
                System.debug('opp prod list:'+listOfOpportunityProducts);
    
        }catch(Exception ex){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage());
            System.debug('+myMsg++'+myMsg);
            //GEMS_CreateExceptionLog.insertErrorLog(ex, null, null, null, 'Apex Class', 'Case', null, 'GEMS_ScreeningCase360ViewController','High'); 
            ApexPages.addMessage(myMsg);
            System.debug( 'Exception : ' +ex.getMessage() );
        }
    }
}